- include/fastrtps/TopicDataType.h
- include/fastrtps/rtps/attributes/RTPSParticipantAttributes.h
- include/fastrtps/rtps/attributes/ReaderAttributes.h
> minor build fixes

- include/fastrtps/TopicDataType.h
- include/fastrtps/rtps/attributes/RTPSParticipantAttributes.h
- include/fastrtps/rtps/attributes/ReaderAttributes.h
> Revert "minor build fixes"

- cmake/dev/eprosima_libraries.cmake
This is just to make sure that any android variables passed to the FastRTPS build make their way to the FastCDR build.
> Added additional NDK variables to the Android build options

- include/fastrtps/attributes/TopicAttributes.h
- include/fastrtps/participant/Participant.h
- include/fastrtps/publisher/Publisher.h
- include/fastrtps/qos/QosPolicies.h
- include/fastrtps/qos/ReaderQos.h
- include/fastrtps/qos/WriterQos.h
- include/fastrtps/rtps/attributes/RTPSParticipantAttributes.h
- include/fastrtps/rtps/participant/RTPSParticipant.h
- include/fastrtps/subscriber/Subscriber.h
- src/cpp/participant/Participant.cpp
- src/cpp/participant/ParticipantImpl.cpp
- src/cpp/participant/ParticipantImpl.h
- src/cpp/publisher/Publisher.cpp
- src/cpp/qos/ReaderQos.cpp
- src/cpp/qos/WriterQos.cpp
- src/cpp/rtps/participant/RTPSParticipant.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/subscriber/Subscriber.cpp
- src/cpp/subscriber/SubscriberImpl.cpp
- src/cpp/subscriber/SubscriberImpl.h
- test/performance/LatencyTestTypes.h
- test/performance/ThroughputTypes.h
- utils/outdatedTests/UpdateAttributesTest/LatencyTestTypes.h
- utils/pcTests/ZMQTests/ThroughputZMQ/ZMQThroughputTypes.h
> add const where appropriate

- src/cpp/xmlparser/XMLElementParser.cpp
elem should be checked before be referenced.
> Fix potential nullptr dereferenced issue in XMLElementParser.cpp

- include/fastrtps/TopicDataType.h
- include/fastrtps/attributes/PublisherAttributes.h
- include/fastrtps/xmlparser/XMLProfileManager.h
- src/cpp/security/accesscontrol/CommonParser.cpp
- src/cpp/xmlparser/XMLParser.cpp
- src/cpp/xmlparser/XMLProfileManager.cpp
Added topic profile support for XML.
> Refs #3139. Added topic profile support.

- src/cpp/CMakeLists.txt
- src/cpp/fastrtps.rc
- src/cpp/transport/UDPv4Transport.cpp
- src/cpp/transport/UDPv6Transport.cpp
These are just a few fixes for UWP. I also renamed `interface` to avoid collisions with MSVC:
https://msdn.microsoft.com/en-us/library/737cydt1.aspx
> Fixes for UWP

- examples/C++/HelloWorldExampleTCP/HelloWorldPublisher.cpp
- include/fastrtps/xmlparser/XMLParserCommon.h
- resources/xsd/fastRTPS_profiles.xsd
- src/cpp/xmlparser/XMLElementParser.cpp
- src/cpp/xmlparser/XMLParser.cpp
- src/cpp/xmlparser/XMLParserCommon.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/XMLProfileParserTests.cpp
- test/unittest/xmlparser/test_xml_profiles.xml
[Refs #3544](https://eprosima.easyredmine.com/issues/3554) Review the XML parser to add the missing fields and update the documentation file with the last specifications
> Refs #3544 Review the XML parser

- include/fastrtps/rtps/attributes/RTPSParticipantAttributes.h
- test/blackbox/TCPReqRepHelloWorldReplier.cpp
- test/blackbox/TCPReqRepHelloWorldRequester.cpp
To avoid failing randomly some tests, I decreased the default participant announcement.
> Decreased default participant announcement

- test/performance/ThroughputPublisher.cpp
- test/performance/ThroughputSubscriber.cpp
[Refs #3670](https://eprosima.easyredmine.com/issues/3670) Fix issue on Throughput test
> Refs #3670 Fix issue on Throughput tests

- examples/C++/HelloWorldExampleTCP/HelloWorldSubscriber.cpp
- examples/C++/HelloWorldExampleTCP/HelloWorld_main.cpp
- include/fastrtps/transport/tcp/RTCPMessageManager.h
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- src/cpp/transport/TCPChannelResource.cpp
- src/cpp/transport/TCPTransportInterface.cpp
- src/cpp/transport/TCPv4Transport.cpp
- src/cpp/transport/TCPv6Transport.cpp
- src/cpp/transport/UDPv4Transport.cpp
- src/cpp/transport/UDPv6Transport.cpp
- src/cpp/transport/tcp/RTCPMessageManager.cpp
- Improved locators shrink.
- Improved mutex usage on SocketConnected method.
- TransactionId is now accessed by mutex.
> Refs #3641 Fixed localhost in TCP. 

- test/performance/ThroughputPublisher.cpp
- test/performance/ThroughputSubscriber.cpp
[Refs #3760](https://eprosima.easyredmine.com/issues/3670) Fix compilation warnings on Master branch
> Refs #3670 Fix compilation warnings on Master branch

- CMakeLists.txt
This pull request attempt to modify the examples installation in order to avoid installation in case not be necessary.
> Examples installation

- test/performance/LatencyTestPublisher.cpp
- test/performance/LatencyTestPublisher.h
- test/performance/LatencyTestSubscriber.cpp
- test/performance/LatencyTestSubscriber.h
- test/performance/ThroughputPublisher.cpp
- test/performance/ThroughputPublisher.h
- test/performance/ThroughputSubscriber.cpp
- test/performance/ThroughputSubscriber.h
- test/performance/VideoTestPublisher.cpp
- test/performance/VideoTestPublisher.h
- test/performance/VideoTestSubscriber.cpp
- test/performance/VideoTestSubscriber.h
- test/performance/main_LatencyTest.cpp
- test/performance/main_ThroughputTest.cpp
- test/performance/main_VideoTest.cpp
[Refs #3670](https://eprosima.easyredmine.com/issues/3670) Create a new input parameter on performance tests to set the domain where the participants are going to run.
> New input parameter on performance tests

- test/performance/LatencyTestTypes.h
- test/performance/ThroughputPublisher.cpp
- test/performance/ThroughputTypes.h
- test/performance/VideoTestTypes.h
[Refs #3791](https://eprosima.easyredmine.com/issues/3791) Fix compilation errors inside performance tests on Develop
> Fix compilation errors inside performance tests on Develop

- cmake/packaging/Config.cmake.in
- configure.ac
- src/cpp/CMakeLists.txt
- src/cpp/security/authentication/PKIDH.cpp
* Support of OpenSSL 1.0.2
* Fixing compilation error on ROS2
> Several fixes

- include/fastrtps/rtps/security/cryptography/CryptoTypes.h
- src/cpp/security/authentication/PKIDH.cpp
- src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.cpp
- src/cpp/security/cryptography/AESGCMGMAC_Types.h
- test/unittest/rtps/security/SecurityTests.hpp
- test/unittest/security/authentication/BuiltinPKIDHTests.cpp
* Default values on Security unit test
* Warnings on Mac
> Fixing warnings and errors on some tests

- include/fastrtps/transport/UDPTransportInterface.h
- src/cpp/transport/UDPTransportInterface.cpp
Several fixes to improve performance.
> Refs #3760. Fixing performance.

- include/fastrtps/rtps/participant/RTPSParticipantDiscoveryInfo.h
- src/cpp/rtps/builtin/discovery/participant/PDPSimpleListener.cpp
Added to participant's discovered info the remote locators. It can be useful for users.
> User case: Locator info in discovered participants

- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.cpp
- test/blackbox/BlackboxTests.cpp
Fixed segmentation fault on security.
> Fixed segmentation fault on security.

- include/fastrtps/publisher/Publisher.h
- include/fastrtps/rtps/builtin/BuiltinProtocols.h
- include/fastrtps/rtps/builtin/discovery/endpoint/EDP.h
- include/fastrtps/rtps/builtin/liveliness/WLP.h
- include/fastrtps/rtps/common/Locator.h
- include/fastrtps/rtps/participant/RTPSParticipant.h
- include/fastrtps/rtps/reader/StatefulReader.h
- include/fastrtps/rtps/writer/RTPSWriter.h
- include/fastrtps/rtps/writer/StatefulWriter.h
- include/fastrtps/rtps/writer/StatelessWriter.h
- include/fastrtps/subscriber/Subscriber.h
- src/cpp/participant/ParticipantImpl.cpp
- src/cpp/publisher/Publisher.cpp
- src/cpp/publisher/PublisherImpl.cpp
- src/cpp/publisher/PublisherImpl.h
- src/cpp/rtps/builtin/BuiltinProtocols.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/builtin/liveliness/WLP.cpp
- src/cpp/rtps/participant/RTPSParticipant.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/subscriber/Subscriber.cpp
- src/cpp/subscriber/SubscriberImpl.cpp
- src/cpp/subscriber/SubscriberImpl.h
- test/blackbox/BlackboxTests.cpp
- test/blackbox/PubSubReader.hpp
- test/blackbox/PubSubWriter.hpp
This fixes #75 exposing updateAttributes on Publisher
> Fixed mechanism to update qos

- include/fastrtps/transport/TCPChannelResource.h
- src/cpp/transport/TCPChannelResource.cpp
- src/cpp/transport/TCPTransportInterface.cpp
- test/performance/VideoTestPublisher.cpp
- test/performance/VideoTestSubscriber.cpp
> Refs #3873 Fixed tcp socket buffer sizes.

- include/fastrtps/rtps/messages/RTPSMessageGroup.h
- include/fastrtps/rtps/writer/RTPSWriter.h
- include/fastrtps/rtps/writer/StatefulWriter.h
- src/cpp/rtps/messages/RTPSMessageGroup.cpp
- src/cpp/rtps/reader/timedevent/HeartbeatResponseDelay.cpp
- src/cpp/rtps/reader/timedevent/InitialAckNack.cpp
- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/rtps/writer/RTPSWriter.cpp
- src/cpp/rtps/writer/ReaderProxy.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- src/cpp/rtps/writer/timedevent/PeriodicHeartbeat.cpp
- src/cpp/security/cryptography/AESGCMGMAC_Transform.cpp
- test/mock/rtps/RTPSWriter/fastrtps/rtps/writer/RTPSWriter.h
This will fix #250 and some other issues when there are more than two secured participants on the same domain.
> Fixing security with several participants

- src/cpp/security/cryptography/AESGCMGMAC_KeyExchange.cpp
- test/blackbox/BlackboxTests.cpp
- test/unittest/logging/LogTests.cpp
- test/unittest/rtps/flowcontrol/ThroughputControllerTests.cpp
- test/unittest/rtps/network/NetworkFactoryTests.cpp
- test/unittest/rtps/persistence/PersistenceTests.cpp
- test/unittest/rtps/reader/WriterProxyTests.cpp
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/UDPv4Tests.cpp
- test/unittest/transport/test_UDPv4Tests.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
* Detected one warning when building with security and debug on Windows.
* Also warnings on various tests under Windows 32 bits
* And one warning on UDPv4 unit tests on Mac
> Fixing some warnings [4086]

- src/cpp/transport/TCPv4Transport.cpp
- src/cpp/transport/TCPv6Transport.cpp
- src/cpp/transport/UDPv4Transport.cpp
- src/cpp/transport/UDPv6Transport.cpp
#4178 - FastRTPS linux installation failure
> Remove C++14 code from the sources which prevent linux installation [4189]

- include/fastrtps/attributes/TopicAttributes.h
- include/fastrtps/qos/ParameterTypes.h
- include/fastrtps/rtps/attributes/RTPSParticipantAttributes.h
- include/fastrtps/rtps/builtin/data/ParticipantProxyData.h
- include/fastrtps/rtps/builtin/data/ReaderProxyData.h
- include/fastrtps/rtps/builtin/data/WriterProxyData.h
- include/fastrtps/rtps/messages/CDRMessage.h
- include/fastrtps/rtps/messages/CDRMessage.hpp
- include/fastrtps/utils/fixed_size_string.hpp
- include/fastrtps/xmlparser/XMLEndpointParser.h
- src/cpp/participant/ParticipantImpl.cpp
- src/cpp/qos/ParameterList.cpp
- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
- src/cpp/rtps/builtin/data/ReaderProxyData.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/security/accesscontrol/Permissions.cpp
- src/cpp/xmlparser/XMLElementParser.cpp
- src/cpp/xmlparser/XMLEndpointParser.cpp
- test/blackbox/PubSubWriter.hpp
- test/unittest/utils/CMakeLists.txt
- test/unittest/utils/FixedSizeStringTests.cpp
A `template<size_t N> fixed_string` class containing an array of `N + 1` characters. Content is truncated when longer than N characters.
Basic operations implemented:
* Basic construction
* Construct from a `const char*` / `std::string`
* Converters to `const char*` / `std::string`
* Assignment operators from `fixed_string` / `const char*` / `std::string`
* (In)equality comparisons with `fixed_string` / `const char*` / `std::string`
Participant name, topic name and type name changed to be `fixed_string<255>`
> Fixed size strings [4216]

- resources/xsd/fastRTPS_profiles.xsd
- src/cpp/xmlparser/XMLParser.cpp
Fixed some missing and wrong documented sections.
> Feature/xml standard [#4301]

- include/fastrtps/Domain.h
- src/cpp/Domain.cpp
Create a new mutex on the Domain class to make it thread-safe
> Domain Thread Safe [4278]

- examples/C++/HelloWorldExampleTCP/HelloWorldPublisher.cpp
- examples/C++/HelloWorldExampleTCP/HelloWorldPublisher.h
- examples/C++/HelloWorldExampleTCP/HelloWorldSubscriber.cpp
- examples/C++/HelloWorldExampleTCP/HelloWorldSubscriber.h
- examples/C++/HelloWorldExampleTCP/HelloWorld_main.cpp
- include/fastrtps/transport/TCPv4Transport.h
- src/cpp/transport/TCPv4Transport.cpp
- src/cpp/utils/IPLocator.cpp
[#4279]
- Fast RTPS class TCPv4Transport modified to proper WAN operation.
- HelloWorldTCP example WAN enabled.
> Hotfix/wan issue [4322]

- test/performance/VideoTestSubscriber.cpp
- test/profiling/memory_tests.py
We have changed how some tests write their results to be used by Jenkins
> Improve reports of performance tests [4454]

- include/fastrtps/Domain.h
- include/fastrtps/publisher/PublisherHistory.h
- include/fastrtps/rtps/RTPSDomain.h
- include/fastrtps/rtps/common/Locator.h
- include/fastrtps/subscriber/SubscriberHistory.h
- src/cpp/Domain.cpp
- src/cpp/participant/ParticipantImpl.cpp
- src/cpp/participant/ParticipantImpl.h
- src/cpp/publisher/PublisherHistory.cpp
- src/cpp/publisher/PublisherImpl.cpp
- src/cpp/publisher/PublisherImpl.h
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/subscriber/SubscriberHistory.cpp
- src/cpp/subscriber/SubscriberImpl.cpp
- src/cpp/subscriber/SubscriberImpl.h
This pull request adds const qualifier for attributes in `createPublisher` and createSubscriber` functions.
> Add const qualifier [4397]

- include/fastrtps/rtps/attributes/RTPSParticipantAttributes.h
- include/fastrtps/xmlparser/XMLParserCommon.h
- resources/xsd/fastRTPS_profiles.xsd
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/xmlparser/XMLElementParser.cpp
- src/cpp/xmlparser/XMLParserCommon.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/XMLProfileParserTests.cpp
- test/unittest/xmlparser/test_xml_profiles.xml
> Refs #3998 Make mutationTries configurable [5018]

- include/fastrtps/publisher/Publisher.h
- include/fastrtps/publisher/PublisherListener.h
- include/fastrtps/qos/LivelinessChangedStatus.h
- include/fastrtps/qos/LivelinessLostStatus.h
- include/fastrtps/subscriber/Subscriber.h
- include/fastrtps/subscriber/SubscriberListener.h
- src/cpp/publisher/Publisher.cpp
- src/cpp/subscriber/Subscriber.cpp
This PR adds methods/structs at the pub/sub level related to liveliness QoS
> Liveliness QoS API [5106]

- src/cpp/types/DynamicData.cpp
> Fixed warnings on VS 2019

- include/fastrtps/transport/TCPAcceptorBasic.h
- src/cpp/transport/TCPAcceptorBasic.cpp
- src/cpp/transport/TCPAcceptorSecure.cpp
- src/cpp/transport/TCPChannelResourceBasic.cpp
- src/cpp/transport/TCPChannelResourceSecure.cpp
- src/cpp/transport/TCPTransportInterface.cpp
- test/blackbox/BlackboxTestsPersistence.cpp
- test/blackbox/BlackboxTestsRTPS.cpp
- test/blackbox/PubSubWriter.hpp
Fixes compilation issues when using asio version < 1.12.
Fixes compilation issues when not using THIRDPARTY.
> Hotfix/asio version [5088]

- src/cpp/rtps/writer/ReaderProxy.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
Follow-up of #453 that should fix #452
> ReaderProxy history reloaded incorrectly missing GAP message [4962]

- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- test/blackbox/BlackboxTestsDiscovery.cpp
- test/communication/CMakeLists.txt
- test/communication/Publisher.cpp
- test/communication/Subscriber.cpp
- test/communication/liveliness_assertion.120.xml
- test/communication/liveliness_assertion.360.xml
…cation to ease testing.
Fix #457
> Refs #4971 Fix #457. Added Blackbox for it and modified SimpleCommuni… [5205]

- README.md
- ReleaseNotes.txt
- roadmap.md
This PR adds some updates to the Fast-RTPS documentation for release 1.8.0
> Documentation updates [5372]

- include/fastrtps/rtps/history/History.h
- src/cpp/rtps/history/History.cpp
This should fix ros2/rmw_fastrtps#280 and also fix ros2/rmw_fastrtps#281
> Fix on get_change with new History ordering [5477]

- examples/C++/Keys/keys.cpp
- src/cpp/publisher/PublisherHistory.cpp
> Fix on PublisherHistory add_change function with key [5637]

- fastrtpsgen/build.gradle
- fastrtpsgen/src/main/java/com/eprosima/fastrtps/fastrtpsgen.java
- fastrtpsgen/src/main/java/com/eprosima/fastrtps/idl/grammar/Context.java
- fastrtpsgen/src/main/java/com/eprosima/fastrtps/solution/Project.java
This PR:
* Updates submodules related with fastrtpsgen
* Sets compatibility with java 1.8
* Fixes warnings
> Using java 1.8 [5705]

- .gitmodules
> Fix #583 by updating fastcdr and idl submodules. [5887]

- include/fastrtps/rtps/builtin/discovery/endpoint/EDPClient.h
- include/fastrtps/rtps/builtin/discovery/endpoint/EDPServer.h
- include/fastrtps/rtps/builtin/discovery/participant/PDP.h
- include/fastrtps/rtps/builtin/discovery/participant/PDPClient.h
- include/fastrtps/rtps/builtin/discovery/participant/PDPServer.h
- include/fastrtps/rtps/builtin/discovery/participant/PDPSimple.h
- include/fastrtps/rtps/builtin/discovery/participant/timedevent/RemoteParticipantLeaseDuration.h
- include/fastrtps/rtps/resources/TimedEvent.h
- include/fastrtps/types/AnnotationParameterValue.h
- include/fastrtps/types/TypeIdentifier.h
- include/fastrtps/types/TypeIdentifierTypes.h
- include/fastrtps/types/TypeObject.h
- include/fastrtps/types/TypeObjectHashId.h
Solved doxygen compilation issues
> Refs 5997: Bugfix/doxygen issues

- doxyfile.in
- include/fastrtps/rtps/builtin/discovery/participant/PDPServer.h
- include/fastrtps/rtps/common/LocatorSelectorEntry.hpp
minor issues introduced within last commits.
> Solved doxygen issues

- include/fastrtps/rtps/messages/RTPSMessageGroup.h
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/messages/RTPSMessageGroup.cpp
> Fixing builds without security

- include/fastrtps/rtps/builtin/data/ReaderProxyData.h
- include/fastrtps/rtps/builtin/data/WriterProxyData.h
- src/cpp/rtps/builtin/data/ReaderProxyData.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPStatic.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/builtin/liveliness/WLP.cpp
- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/transport/TCPTransportInterface.cpp
- src/cpp/transport/UDPTransportInterface.cpp
- test/mock/rtps/ReaderProxyData/fastrtps/rtps/builtin/data/ReaderProxyData.h
- test/mock/rtps/WriterProxyData/fastrtps/rtps/builtin/data/WriterProxyData.h
> Fixing local/remote locators management [6081]

- include/fastrtps/rtps/messages/CDRMessage.hpp
- src/cpp/qos/ParameterList.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
- src/cpp/rtps/reader/FragmentedChangePitStop.cpp
- src/cpp/utils/IPFinder.cpp
This should fix #627, fix #628, fix #629, fix #630 and fix #631
> Fixing coverity report issues [6100]

- test/blackbox/PubSubParticipant.hpp
- test/blackbox/PubSubWriter.hpp
- test/blackbox/PubSubWriterReader.hpp
- test/blackbox/ReqRepAsReliableHelloWorldReplier.hpp
- test/blackbox/ReqRepAsReliableHelloWorldRequester.hpp
- test/blackbox/TCPReqRepHelloWorldReplier.hpp
- test/blackbox/TCPReqRepHelloWorldRequester.hpp
Should make some tests less flaky
> Increasing default max_blocking_time on tests [6015]

- examples/C++/RTPSTest_as_socket/TestReaderSocket.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/reader/RTPSReader.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
- test/blackbox/RTPSAsSocketReader.hpp
This should fix #638 by changing the default value of m_acceptMessagesFromUnkownWriters on RTPSReader.
> Change unknown writers default behaviour [6121]

- include/fastrtps/utils/fixed_size_bitmap.hpp
- test/unittest/utils/BitmapRangeTests.cpp
This is part of the fragmentation API refactor.
> Adding sliding window to BitmapRange [6043]

- examples/C++/RTPSTest_as_socket/TestReaderSocket.cpp
- include/fastrtps/rtps/reader/RTPSReader.h
- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/reader/RTPSReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- test/blackbox/RTPSAsSocketReader.hpp
> Change unknown writers default behaviour [6125]

- include/fastrtps/utils/fixed_size_bitmap.hpp
- test/unittest/utils/BitmapRangeTests.cpp
New `add_range` and `is_set` methods, along with code style and unit tests.
> Bitmap range improvements [6167]

- include/fastrtps/rtps/builtin/discovery/participant/PDP.h
* Removes non-existent parameter in PDP.h
> Fix for doxygen [6185]

- include/fastrtps/qos/ParameterTypes.h
> Refs #6216 Export addToCDRMessage function in DLL. [6230]

- src/cpp/transport/UDPTransportInterface.cpp
This should fix ros2/rmw_fastrtps#297
> Sending multicast through localhost [6289]

- examples/C++/XMLProfiles/XMLProfilesExamplePublisher.cxx
Allow continuous sending on the publisher, so this example can be used to reproduce communication issues easily.
> Improving XMLProfiles example [6288]

- src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.cpp
> Mutex baptism [6293]

- include/fastrtps/rtps/common/Guid.h
- include/fastrtps/rtps/messages/MessageReceiver.h
- include/fastrtps/rtps/reader/RTPSReader.h
- include/fastrtps/rtps/reader/StatefulReader.h
- include/fastrtps/rtps/reader/StatelessReader.h
- src/cpp/rtps/messages/MessageReceiver.cpp
- src/cpp/rtps/reader/RTPSReader.cpp
> Bugfix/clearpath issue 647 [6277]

- test/performance/LatencyTestPublisher.cpp
- test/performance/ThroughputPublisher.cpp
Code changes: 
* Divides by two the roundtrip time in the latency test
* Accounts for the wait time in the throughput test
> Fixes to performance tests

- include/fastrtps/rtps/common/SequenceNumber.h
This PR improves SequenceNumber.h
* Applies coding style 
* Removes LLONG_MAX
* Improves performance on some operators
> SequenceNumber_t improvements [6359]

- include/fastrtps/rtps/builtin/discovery/participant/PDPSimple.h
- include/fastrtps/rtps/builtin/discovery/participant/timedevent/RemoteParticipantLeaseDuration.h
- include/fastrtps/transport/test_UDPv4Transport.h
- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/builtin/discovery/participant/timedevent/RemoteParticipantLeaseDuration.cpp
- src/cpp/rtps/messages/MessageReceiver.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- src/cpp/transport/test_UDPv4Transport.cpp
- test/blackbox/BlackboxTestsDiscovery.cpp
- test/blackbox/PubSubReader.hpp
- test/blackbox/PubSubWriter.hpp
This PR changes the behavior of asserting the participant liveliness. With these changes, the assertion occurs each time we received an RTPS message from the remote participant.
> Assertion of participant liveliness receiving any RTPS message [6386]

- include/fastrtps/rtps/builtin/data/ParticipantProxyData.h
- include/fastrtps/rtps/builtin/discovery/participant/PDP.h
- include/fastrtps/transport/test_UDPv4Transport.h
- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/messages/MessageReceiver.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- src/cpp/transport/test_UDPv4Transport.cpp
- test/blackbox/BlackboxTestsDiscovery.cpp
- test/blackbox/PubSubReader.hpp
- test/blackbox/PubSubWriter.hpp
This PR changes the behavior of asserting the participant's liveliness. With these changes, the assertion occurs each time we received an RTPS message from the remote participant.
> Assertion of participant liveliness receiving any RTPS message [6401]

- test/performance/ThroughputPublisher.cpp
> Refs #6045 - Fix depth and allocated samples issues throughput [6433]

- include/fastrtps/utils/collections/ResourceLimitedVector.hpp
> Added copy constructor to ResourceLimitedVector. [6411]

- include/fastrtps/config.h.in
- src/cpp/CMakeLists.txt
- src/cpp/publisher/PublisherImpl.cpp
- test/CMakeLists.txt
> Added STRICT_REALTIME option

- include/fastrtps/subscriber/SubscriberHistory.h
- src/cpp/subscriber/SubscriberHistory.cpp
- test/blackbox/BlackboxTestsPubSubHistory.cpp
> SubscriberHistory improvements [6412]

- include/fastrtps/rtps/common/Guid.h
- include/fastrtps/rtps/messages/MessageReceiver.h
- include/fastrtps/rtps/reader/RTPSReader.h
- include/fastrtps/rtps/reader/StatefulReader.h
- include/fastrtps/rtps/reader/StatelessReader.h
- src/cpp/rtps/messages/MessageReceiver.cpp
- src/cpp/rtps/reader/RTPSReader.cpp
This PR backports #705 to 1.8.x
> Backport of #705 [6454]

- src/cpp/subscriber/SubscriberHistory.cpp
Fixes valgrind unitialized errors.
> Refs #6451 Fix valgrind unitilized error. [6456]

- test/performance/LatencyTestPublisher.cpp
- test/performance/ThroughputPublisher.cpp
- test/performance/ThroughputSubscriber.cpp
Backport of #711 + #713 + #719 + #735
> Performance tests improvements [6415]

- include/fastrtps/rtps/attributes/WriterAttributes.h
- include/fastrtps/rtps/builtin/discovery/participant/PDPSimple.h
- include/fastrtps/rtps/writer/RTPSWriter.h
- src/cpp/participant/ParticipantImpl.cpp
- src/cpp/qos/ReaderQos.cpp
- src/cpp/qos/WriterQos.cpp
- src/cpp/rtps/builtin/BuiltinProtocols.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/builtin/liveliness/WLP.cpp
- src/cpp/rtps/builtin/liveliness/WLPListener.cpp
- src/cpp/rtps/builtin/liveliness/timedevent/WLivelinessPeriodicAssertion.cpp
- src/cpp/rtps/writer/LivelinessManager.cpp
- src/cpp/rtps/writer/RTPSWriter.cpp
- test/blackbox/BlackboxTestsLivelinessQos.cpp
- test/blackbox/PubSubParticipant.hpp
- test/blackbox/PubSubReader.hpp
- test/blackbox/PubSubWriter.hpp
> WLP improvements (#650) [6455]

- CMakeLists.txt
> Refs #6500 BUILD_DOCUMENTATION now gets the current version being gen… [6500]

- src/cpp/fastrtps_deprecated/transport/TCPTransportInterface.cpp
- src/cpp/fastrtps_deprecated/transport/TCPv4Transport.cpp
don't transform remote locator to localhost if it's in the whitelist
> Don't transform whitelist remote locators [6543]

- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
> Fixing compilation error without security.

- include/fastdds/rtps/builtin/discovery/participant/PDPClient.h
- include/fastdds/rtps/builtin/discovery/participant/PDPServer.h
- include/fastdds/rtps/common/CDRMessage_t.h
- include/fastdds/rtps/messages/RTPSMessageGroup.h
- include/fastdds/rtps/reader/StatefulReader.h
- include/fastdds/rtps/writer/RTPSWriter.h
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/messages/RTPSMessageGroup.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/writer/RTPSWriter.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
This will fix #684 using thread-local storage for RTPSMessageGroup_t instances.
> Using thread local storage for RTPSMessageGroup_t [6547]

- include/fastrtps/qos/QosPolicies.h
- src/cpp/qos/ParameterList.cpp
- src/cpp/qos/QosPolicies.cpp
TypeConsistencyEnforcementQosPolicy was being serialized incorrectly.
> Fixed wrong serialization of TypeConsistencyEnforcementQosPolicy. [6589]

- include/fastrtps/qos/QosPolicies.h
- src/cpp/qos/ParameterList.cpp
- src/cpp/qos/QosPolicies.cpp
TypeConsistencyEnforcementQosPolicy was being serialized incorrectly.
> Fixed wrong serialization of TypeConsistencyEnforcementQosPolicy. [6590]

- test/profiling/allocations/AllocTestCommon.cpp
- test/profiling/allocations/test_with_memory_tool.sh
Improving consistency of allocation profiler results
> Allocation profiler improvements

- include/fastdds/dds/core/policy/WriterDataLifecycleQosPolicy.hpp
- include/fastdds/dds/topic/qos/DataWriterQos.hpp
- src/cpp/CMakeLists.txt
- src/cpp/dds/topic/qos/DataWriterQos.cpp
- Created DataWriterQos
- Created WriterDataLifecycleQosPolicy
> DataWriterQos [6563]

- include/fastrtps/qos/ReaderQos.h
- include/fastrtps/qos/WriterQos.h
> Recover enums from QosPolices

- include/fastdds/dds/core/policy/ReaderDataLifecycleQosPolicy.hpp
- include/fastdds/dds/topic/qos/DataReaderQos.hpp
- src/cpp/CMakeLists.txt
- src/cpp/dds/topic/qos/DataReaderQos.cpp
- Created DataReaderQos class
- Created ReaderDataLifecycleQosPolicy
> DataReaderQos [6561]

- include/dds/topic/BuiltinTopic.hpp
- include/dds/topic/BuiltinTopicKey.hpp
- include/dds/topic/detail/BuiltinTopic.hpp
- include/dds/topic/detail/BuiltinTopicKey.hpp
- include/fastdds/dds/topic/BuiltinTopicKey.hpp
- include/fastdds/dds/topic/ParticipantBuiltinTopicData.hpp
- include/fastdds/dds/topic/PublicationBuiltinTopicData.hpp
- include/fastdds/dds/topic/SubscriptionBuiltinTopicData.hpp
- include/fastdds/dds/topic/TopicBuiltinTopicData.hpp
The pull request adds:
* BuiltinTopicKey
* BUILTIN_TOPIC_KEY_TYPE_NATIVE
* ParticipantBuiltinTopicData
* TopicBuiltinTopicData
* SubscriptionBuiltinTopicData
* PublicationBuiltinTopicData
> BuiltinTopicData classes

- include/dds/core/status/State.hpp
- include/dds/core/status/Status.hpp
- include/dds/core/status/detail/Status.hpp
- include/dds/topic/TopicListener.hpp
- include/dds/topic/detail/AnyTopic.hpp
- include/dds/topic/detail/TAnyTopicImpl.hpp
- include/fastdds/dds/topic/Topic.hpp
- include/fastdds/dds/topic/TopicDescription.hpp
- include/fastdds/dds/topic/TopicListener.hpp
- include/fastrtps/types/TypesBase.h
- src/cpp/CMakeLists.txt
- src/cpp/dds/topic/Topic.cpp
* Adds Topic class.
* Adds TopicListener.
* PSM updates:
* Implements `AnyTopic.hpp`.
* Adds correct implementations to `detail/Status.hpp`.
* Other minor style fixes.
> Refs #5824 Topic Implementation. Minor updates to PSM API. [6613]

- include/fastdds/dds/topic/DataWriterListener.hpp
Added new method to the DataWriterListener class:
* on_offered_incompatible_qos
> DataWriterListener [6640]

- examples/C++/Keys/keys.cpp
> Fix keys example in master [6591]

- include/fastdds/rtps/builtin/data/ParticipantProxyData.h
- include/fastdds/rtps/builtin/discovery/endpoint/EDPServer.h
- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
- src/cpp/rtps/builtin/data/ProxyHashTables.hpp
- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- test/unittest/security/authentication/CMakeLists.txt
This pull request meets the Github issue #636 and the pull request #637.
The main goal is speed up the PDP database queries by replacing actual vector collections with hash tables keeping our current allocation-free philosophy intact.
> User endpoint discovery database speed up queries [6588]

- include/fastrtps/rtps/builtin/discovery/participant/PDPClient.h
- include/fastrtps/rtps/builtin/discovery/participant/PDPServer.h
- include/fastrtps/rtps/common/CDRMessage_t.h
- include/fastrtps/rtps/messages/RTPSMessageGroup.h
- include/fastrtps/rtps/reader/StatefulReader.h
- include/fastrtps/rtps/writer/RTPSWriter.h
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/messages/RTPSMessageGroup.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/writer/RTPSWriter.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
> [1.9.x] Using thread local storage for RTPSMessageGroup_t [6728]

- src/cpp/rtps/writer/StatefulWriter.cpp
> [1.9.x] Improvements on check_acked_status [6729]

- test/profiling/allocations/AllocTestCommon.cpp
- test/profiling/allocations/test_with_memory_tool.sh
> [1.9.x] Allocation profiler improvements [6732]

- examples/C++/Keys/keys.cpp
> Fix Keys example in 1.8.x

- src/cpp/qos/ParameterList.cpp
> [1.8.x] Fix reception of ParameterList [6725]

- examples/C++/UserDefinedTransportExample/UserDefinedTransportExampleReader.cpp
- examples/C++/UserDefinedTransportExample/UserDefinedTransportExampleWriter.cpp
This is a backport from part of #734.
> Fixed failing example.

- README.md
> Fixed installation from sources on README.

- include/dds/core/xtypes/DynamicData.hpp
- include/dds/core/xtypes/SequenceType.hpp
Remove warning when compiling in release mode.
> Removed warning at release mode.

- include/fastrtps/rtps/RTPSDomain.h
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/RTPSDomainImpl.hpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
Functions for finding local readers / writers from its GUID have been added to RTPSDomain
> Internal methods to find endpoints on the local process [6791]

- include/fastrtps/qos/QosPolicies.h
- include/fastrtps/rtps/attributes/ReaderAttributes.h
- include/fastrtps/rtps/attributes/WriterAttributes.h
- include/fastrtps/rtps/common/Time_t.h
- include/fastrtps/rtps/writer/LivelinessData.h
- test/mock/rtps/QosPolicies/fastrtps/qos/QosPolicies.h
This is a backport of the commit 5d0b5e80d0dae08452a19d721e892bb0837ed925
> Fixes static initialization order fiasco.

- CMakeLists.txt
- doxyfile.in
- include/fastrtps/types/AnnotationParameterValue.h
- include/fastrtps/types/TypeIdentifier.h
- include/fastrtps/types/TypeIdentifierTypes.h
- include/fastrtps/types/TypeObject.h
- include/fastrtps/types/TypeObjectHashId.h
> [master] Build option to check documentation [6877]

- test/profiling/allocations/test_xml_profiles.xml
> [master] Improved allocation profiler settings. [6892]

- src/cpp/rtps/writer/LivelinessManager.cpp
> [master] Removing a logError in favor of a logInfo. [6904]

- doc/design/intra-process.md
> [master] Intra process design [6917]

- src/cpp/dds/core/policy/ParameterList.cpp
- src/cpp/dds/core/policy/QosPolicies.cpp
> [master] Fix reception of ParameterList [6872]

- cmake/modules/FindTinyXML2.cmake
> [master] Only call find_package for TinyXML2 if thirdparty options are off [6889]

- src/cpp/publisher/PublisherImpl.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- test/blackbox/BlackboxTestsPubSubFragments.cpp
This PR will allow sending fragmented changes on synchronous mode
> Sending fragments on sync writers [6830]

- src/cpp/rtps/writer/ReaderProxy.cpp
> [1.9.x] clean ReaderProxy cache on acked_changes_set [6959]

- include/fastrtps/rtps/builtin/data/ReaderProxyData.h
- include/fastrtps/rtps/builtin/data/WriterProxyData.h
- src/cpp/rtps/builtin/data/ReaderProxyData.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
This PR reduces the size of `WriterProxyData` and `ReaderProxyData` by dynamically allocating X-Types related information only when necessary.
> [1.9.x] Reducing size of proxy data structures [7010]

- include/fastrtps/utils/TimedMutex.hpp
> Removes internal windows header [1.9.x]

- include/fastrtps/rtps/resources/ResourceEvent.h
- src/cpp/rtps/resources/ResourceEvent.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- test/blackbox/BlackboxTestsLivelinessQos.cpp
- test/blackbox/PubSubParticipant.hpp
- test/blackbox/PubSubReader.hpp
- test/blackbox/PubSubWriter.hpp
This PR builds on top of #942 and should fix [this problem](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1119/valgrindResult/pid=18098/)
If this one is merged, it closes #942
> Fixing liveliness with intra-process <1.9.x> [7220]

- include/fastrtps/utils/TimedMutex.hpp
> [master] Removes internal windows header [7226]

- test/performance/latency/CMakeLists.txt
- test/performance/throughput/CMakeLists.txt
- test/performance/video/CMakeLists.txt
Properly sets the environment with CMake for running performce tests with c-test in windows
> [1.9.x] Correct environment for running performance test in windows with c-test [7232]

- test/performance/latency/CMakeLists.txt
- test/performance/throughput/CMakeLists.txt
- test/performance/video/CMakeLists.txt
> [master] Correct environment for running performance test in windows with c-test [7235] 

- include/fastdds/rtps/writer/StatefulWriter.h
- src/cpp/rtps/writer/StatefulWriter.cpp
Improvement sending only GAP for sequence number greater/equal than history minimum sequence number. In other case, force to send a piggyback heartbeat.
> Improve sending GAP [master]

- include/fastdds/rtps/history/History.h
- include/fastdds/rtps/history/ReaderHistory.h
- include/fastdds/rtps/reader/RTPSReader.h
- src/cpp/rtps/history/History.cpp
- src/cpp/rtps/history/ReaderHistory.cpp
- src/cpp/rtps/reader/RTPSReader.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
Added a mechanism to improve the performance with consecutive calls to `History::get_change()`.
> Improvement in consecutives History::get_change [master]

- include/fastdds/rtps/history/CacheChangePool.h
- include/fastdds/rtps/resources/ResourceManagement.h
- include/fastrtps/xmlparser/XMLParserCommon.h
- resources/xsd/fastRTPS_profiles.xsd
- src/cpp/rtps/history/CacheChangePool.cpp
- src/cpp/rtps/writer/RTPSWriter.cpp
- src/cpp/rtps/xmlparser/XMLElementParser.cpp
- src/cpp/rtps/xmlparser/XMLParserCommon.cpp
- test/unittest/rtps/history/CacheChangePoolTests.cpp
> [master] Use cache change pool when DYNAMIC_RESERVE [7021]

- configure.ac
- fastrtps.repos
Updating versions for next release.
> 1.9.4 [7303]

- test/performance/throughput/ThroughputPublisher.cpp
> Solve throughput test compiler warning in Windows <1.9.x>

- test/performance/throughput/throughput_tests.py
> Name CSVs with delivery <1.9.x> [7426]

- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
> Avoid data races between ReceiverResource and Participant initialization [7490]

- src/cpp/rtps/reader/StatelessReader.cpp
- src/cpp/rtps/transport/test_UDPv4Transport.cpp
- test/blackbox/BlackboxTests.hpp
- test/blackbox/BlackboxTestsPubSubFragments.cpp
- test/blackbox/PubSubReader.hpp
- test/blackbox/utils/data_generators.cpp
This is a port of #1013 from 1.9.x
> Do not reuse cache change if sample does not fit <master> [7726]

- test/blackbox/BlackboxTestsLivelinessQos.cpp
- test/blackbox/PubSubParticipant.hpp
This is a port of #982 + #983 + #985 from 1.9.x
> Improve liveliness tests <master> [7703]

- src/cpp/fastrtps_deprecated/publisher/PublisherImpl.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- test/blackbox/BlackboxTestsPubSubFragments.cpp
- test/blackbox/PubSubReader.hpp
- test/blackbox/PubSubWriter.hpp
This is a port of #898 and #902 from 1.9.x
> Sending fragments on sync writers <master> [6955]

- src/cpp/dds/topic/DataReaderImpl.cpp
- src/cpp/dds/topic/DataWriterImpl.cpp
- src/cpp/fastrtps_deprecated/publisher/PublisherHistory.cpp
> Fix handling of STRICT_REALTIME <master> [7373]

- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
This is a port of #915 from 1.9.x
> Correctly checking EDP kind selection <master> [7736]

- include/fastdds/rtps/common/CacheChange.h
- include/fastrtps/utils/fixed_size_bitmap.hpp
- test/blackbox/BlackboxTestsPubSubFragments.cpp
This is a port of #926 from 1.9.x
> Not using std::set on ChangeForReader_t <master> [7094]

- include/fastdds/rtps/builtin/data/ReaderProxyData.h
- include/fastdds/rtps/builtin/data/WriterProxyData.h
- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- src/cpp/rtps/builtin/data/ReaderProxyData.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
> Improve proxy data memory usage <master> [7011]

- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
> Protect add_participant_proxy_data on initPDP <master> [7707]

- src/cpp/rtps/messages/submessages/DataMsg.hpp
This is a port of #999 from 1.9.x
> Fixed submessage_size calculation on last data_frag <master> [7608]

- include/fastdds/rtps/writer/ReaderProxy.h
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/WriterProxy.cpp
- src/cpp/rtps/reader/WriterProxy.h
- src/cpp/rtps/writer/ReaderProxy.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- test/mock/rtps/ReaderLocator/fastdds/rtps/writer/ReaderLocator.h
- test/mock/rtps/ReaderProxyData/fastdds/rtps/builtin/data/ReaderProxyData.h
- test/mock/rtps/WriterProxyData/fastdds/rtps/builtin/data/WriterProxyData.h
This is a port of #916 from 1.9.x
> Reduce proxies memory consumption <master> [7039]

- include/fastdds/rtps/writer/ReaderProxy.h
- include/fastdds/rtps/writer/StatefulWriter.h
- include/fastdds/rtps/writer/StatelessWriter.h
- src/cpp/rtps/flowcontrol/ThroughputController.cpp
- src/cpp/rtps/flowcontrol/ThroughputController.h
- src/cpp/rtps/writer/ReaderProxy.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
> Avoid temporary allocations when not using flow controllers <master> [7275]

- include/fastdds/dds/core/policy/ParameterTypes.hpp
- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
- include/fastdds/rtps/builtin/data/ParticipantProxyData.h
- include/fastdds/rtps/builtin/data/ReaderProxyData.h
- include/fastdds/rtps/builtin/data/WriterProxyData.h
- include/fastdds/rtps/builtin/discovery/endpoint/EDPClient.h
- include/fastdds/rtps/builtin/discovery/endpoint/EDPServer.h
- include/fastdds/rtps/builtin/discovery/endpoint/EDPSimple.h
- include/fastdds/rtps/messages/CDRMessage.h
- include/fastdds/rtps/messages/CDRMessage.hpp
- src/cpp/dds/core/policy/ParameterTypes.cpp
- src/cpp/dds/core/policy/QosPolicies.cpp
- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
- src/cpp/rtps/builtin/data/ReaderProxyData.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPClient.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.h
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
- src/cpp/rtps/builtin/liveliness/WLP.cpp
- test/mock/dds/QosPolicies/fastdds/dds/core/policy/QosPolicies.hpp
This is a port of #918 and #1009 from 1.9.x
> Reduce builtin endpoints memory consumption <master> [7036]

- include/fastrtps/qos/QosPolicies.h
This PR will fix #1053 as well as introduce some improvements on the whole `QosPolicies.h` file
> Improvements on QosPolicies.h [7892]

- src/cpp/rtps/writer/ReaderProxy.cpp
- test/mock/rtps/StatefulWriter/fastrtps/rtps/writer/StatefulWriter.h
- test/mock/rtps/WriterHistory/fastrtps/rtps/history/WriterHistory.h
> Simulate initial acknack on ReaderProxy::start() <1.8.x> [7973]

- thirdparty/boost/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp
This PR solves the github issue #1076.
> CMake Error: compiling thirdparty/boost in Ubuntu16 <master> [8000]

- include/fastrtps/attributes/ReplierAttributes.hpp
- include/fastrtps/attributes/RequesterAttributes.hpp
- include/fastrtps/attributes/all_attributes.h
- include/fastrtps/xmlparser/XMLParser.h
- include/fastrtps/xmlparser/XMLParserCommon.h
- include/fastrtps/xmlparser/XMLProfileManager.h
- include/fastrtps/xmlparser/XMLTree.h
- resources/xsd/fastRTPS_profiles.xsd
- src/cpp/rtps/xmlparser/XMLElementParser.cpp
- src/cpp/rtps/xmlparser/XMLParser.cpp
- src/cpp/rtps/xmlparser/XMLParserCommon.cpp
- src/cpp/rtps/xmlparser/XMLProfileManager.cpp
- test/unittest/xmlparser/XMLProfileParserTests.cpp
- test/unittest/xmlparser/test_xml_profiles.xml
This pull request Implements XML parsing for Requester and Replier entities.
> XML services entities

- include/fastdds/dds/subscriber/DataReader.hpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReader.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
This PR bring changes done to `fastrtps::Subscriber` and `fastrtps::Publisher` into `fastdds::DataReader` and `fastdds::DataWriter`.
Changes are from PRs #968, #1029, #1097 and #1104
> Bring missing changes to DataReader and DataWriter

- include/dds/core/refmacros.hpp
This PR implements the explicit/implicit conversion macros for REFERENCE types on PSM
> DDS conversion between REFERENCE objects

- include/dds/domain/DomainParticipant.hpp
- include/fastdds/dds/domain/DomainParticipant.hpp
- src/cpp/dds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- test/unittest/dds/participant/ParticipantTests.cpp
* Change delete_participant to follow the DDS standard
* New test to check its functionality
NOTE: This PR must be merged after #1073
> DDS standard delete participant

- examples/C++/DDS/DynamicHelloWorldExample/HelloWorldPublisher.cpp
- examples/C++/DDS/HelloWorldExample/HelloWorldPublisher.cpp
- examples/C++/DDS/TypeLookupService/TypeLookupPublisher.cpp
- include/dds/domain/DomainParticipant.hpp
- include/dds/pub/Publisher.hpp
- include/dds/pub/PublisherListener.hpp
- include/dds/pub/detail/Publisher.hpp
- include/dds/pub/qos/PublisherQos.hpp
- include/dds/pub/qos/detail/PublisherQos.hpp
- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/dds/publisher/Publisher.hpp
- include/fastdds/dds/publisher/qos/PublisherQos.hpp
- src/cpp/CMakeLists.txt
- src/cpp/dds/domain/DomainParticipant.cpp
- src/cpp/dds/pub/Publisher.cpp
- src/cpp/fastdds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastdds/publisher/Publisher.cpp
- src/cpp/fastdds/publisher/PublisherImpl.cpp
- src/cpp/fastdds/publisher/PublisherImpl.hpp
- src/cpp/fastdds/publisher/qos/PublisherQos.cpp
- test/dds/communication/Publisher.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
- test/xtypes/TestPublisher.cpp
* Add new create_publisher method following DDS standard
* New unit test to check PIM create_publisher functionality
* Implementation of PSM Publisher constructor
* New unit test for PSM constructor
NOTE: This PR must be merged after #1073
> DomainParticipant create_publisher

- test/unittest/dds/participant/ParticipantTests.cpp
* Add unit test for delete_publisher functionality
NOTE: This PR must be merged after #1089
> DomainParticipant delete_publisher

- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/dds/domain/DomainParticipantFactory.hpp
- src/cpp/dds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastdds/subscriber/qos/SubscriberQos.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
* set_qos and get_qos implementation
* Add unit test for check PIM functionality
* PSM qos methods implementation
* Add unit test for check PSM functionality
NOTE: This PR must be merged after #1073
> DomainParticipant qos methods

- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastdds/dds/domain/DomainParticipantFactory.hpp
- include/fastdds/dds/domain/qos/DomainParticipantFactoryQos.hpp
- src/cpp/CMakeLists.txt
- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- src/cpp/fastdds/domain/qos/DomainParticipantFactoryQos.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
* Implementation of get_qos
* Implementation of set_qos
* Add new unit test for checking its functionality
> DomainParticipantFactory qos methods

- include/fastdds/dds/domain/DomainParticipant.hpp
- src/cpp/fastdds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastdds/topic/TopicImpl.cpp
- src/cpp/fastdds/topic/TopicImpl.hpp
- test/unittest/dds/participant/ParticipantTests.cpp
This PR includes:
* Reference counting methods on TopicImpl
* Implementation and unit test for delete_topic API
> DDS delete_topic [8180]

- include/fastdds/dds/topic/Topic.hpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/topic/Topic.cpp
Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>
> Topic constructor needs the type_name to store it

- include/dds/pub/Publisher.hpp
- src/cpp/dds/pub/Publisher.cpp
- test/unittest/dds/publisher/PublisherTests.cpp
* PSM participant method implementation
* Add unit tests for PIM and PSM methods
> DDS Publisher get_participant

- src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
> Avoid DATA(p) to multicast on first participant discovery <master> [8216]

- include/fastdds/dds/subscriber/qos/SubscriberQos.hpp
- src/cpp/dds/domain/DomainParticipant.cpp
- src/cpp/dds/sub/Subscriber.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastdds/subscriber/SubscriberImpl.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.hpp
- src/cpp/fastdds/subscriber/qos/SubscriberQos.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/subscriber/SubscriberTests.cpp
- Correct get_qos on PIM
- Unit test for PIM Subscriber get/set_qos
- Link PSM qos getter/setter to PIM implementation
- Unit test for PSM Subscriber qos getter/setter
> DDS Subscriber get/set qos

- examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.cpp
- examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.h
- examples/C++/DDS/HelloWorldExample/HelloWorldSubscriber.cpp
- examples/C++/DDS/HelloWorldExample/HelloWorldSubscriber.h
- examples/C++/DDS/TypeLookupService/TypeLookupSubscriber.cpp
- examples/C++/DDS/TypeLookupService/TypeLookupSubscriber.h
- include/fastdds/dds/subscriber/DataReader.hpp
- include/fastdds/dds/subscriber/DataReaderListener.hpp
- include/fastdds/dds/subscriber/SampleInfo.hpp
- src/cpp/fastdds/subscriber/DataReader.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
- test/dds/communication/Subscriber.cpp
- test/unittest/dds/subscriber/SubscriberTests.cpp
- test/xtypes/TestSubscriber.cpp
- test/xtypes/TestSubscriber.h
- Adapt the PIM implementation
- Unit test to check preconditions
> DDS DataReader read/take_next_sample

- src/cpp/fastrtps_deprecated/security/OpenSSLInit.cpp
- src/cpp/fastrtps_deprecated/security/authentication/PKIDH.cpp
- src/cpp/fastrtps_deprecated/security/authentication/PKIIdentityHandle.h
- src/cpp/fastrtps_deprecated/security/cryptography/AESGCMGMAC_KeyExchange.cpp
- src/cpp/fastrtps_deprecated/security/cryptography/AESGCMGMAC_KeyFactory.cpp
- src/cpp/fastrtps_deprecated/security/cryptography/AESGCMGMAC_Transform.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
- test/unittest/security/authentication/CMakeLists.txt
- test/unittest/security/cryptography/CMakeLists.txt
- test/unittest/security/cryptography/CryptographyPluginTests.hpp
This PR adds support for OpenSSL 1.1.1d. It should fix part of #1087.
> Support for OpenSSL 1.1.1d <master>

- src/cpp/fastrtps_deprecated/security/cryptography/AESGCMGMAC_Transform.cpp
- src/cpp/fastrtps_deprecated/security/cryptography/AESGCMGMAC_Transform.h
- src/cpp/fastrtps_deprecated/security/cryptography/AESGCMGMAC_Types.h
- test/unittest/security/cryptography/CryptographyPluginTests.hpp
Cherry-pick of last commit in 0.10.X
> Fixing AES-128 use cases. <master>

- CMakeLists.txt
- cmake/modules/FindThirdpartyBoost.cmake
- src/cpp/rtps/transport/shared_mem/RobustInterprocessCondition.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemSegment.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
- test/communication/liveliness_assertion.360.xml
- test/communication/liveliness_assertion.xml
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/publisher/PublisherTests.cpp
- test/unittest/dds/subscriber/SubscriberTests.cpp
- test/unittest/transport/SharedMemTests.cpp
- thirdparty/boost/include/boost/interprocess/sync/interprocess_semaphore.hpp
- thirdparty/boost/include/boost/interprocess/sync/posix/semaphore.hpp
- thirdparty/boost/include/boost/interprocess/sync/spin/semaphore.hpp
- thirdparty/boost/test/ThirdpartyBoostCompile_test.cpp
Bring #1147 and #1159 to master.
Also making Shared memory active by default
> Shared Memory fixes and improvements

- test/dds/communication/Subscriber.cpp
Not a complete correction of the issue, but the existence of the Topic should be checked before creation
> bugfix on DDS Communication test

- include/fastdds/rtps/writer/StatelessWriter.h
- src/cpp/rtps/writer/RTPSWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
> Improved best-effort late-joiners

- include/fastdds/dds/domain/DomainParticipantFactory.hpp
- include/fastdds/dds/publisher/Publisher.hpp
- src/cpp/dds/domain/DomainParticipant.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/publisher/PublisherTests.cpp
- test/unittest/dds/subscriber/SubscriberTests.cpp
Signed-off-by: Iker Luengo <ikerluengo@eprosima.com>
> remove default QoS parameter from entity creation methods [8364]

- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
> Fixed DomainParticipantFactory::participant_has_been_deleted <2.0.x>

- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
- test/performance/throughput/ThroughputPublisher.cpp
This issue was causing throughput tests failures in MAC platform. Possibly, errors in other tests could also be caused by this issue.
> Fix SHM Watchdog race condition <2.0.x> [8449]

- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
This PR eliminates the fictitious matching of PDPSimple endpoints between themselves.
> Improved PDPSimple memory usage <2.0.x> [8491]

- cmake/modules/FindThirdpartyBoost.cmake
> link atomic under clang

- fastrtps.repos
> 2.0.0 [8544]

- CMakeLists.txt
> Disable default SHM on Windows installers [8605]

- examples/C++/DDS/HistoryKind/README.txt
Signed-off-by: Johnny Willemsen <jwillemsen@remedy.nl>
> Fixed typo in readme

- README.md
> Fixed documentation links in README.md

- examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.cpp
Signed-off-by: LuisGasco <luisgasco@eprosima.com>
> Fixes topic name

- src/cpp/fastdds/topic/TypeSupport.cpp
Signed-off-by: Johnny Willemsen <jwillemsen@remedy.nl>
> Check for an empty string using empty()

- include/fastdds/rtps/writer/ReaderProxy.h
- include/fastdds/rtps/writer/StatefulWriter.h
- src/cpp/rtps/writer/ReaderProxy.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- test/blackbox/common/RTPSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSWithRegistrationWriter.hpp
- test/mock/rtps/RTPSGapBuilder/rtps/messages/RTPSGapBuilder.hpp
- test/unittest/rtps/writer/CMakeLists.txt
This is a forward port of #1295
> Fix sending GAPs to late joiners <master> [8894]

- include/fastdds/dds/domain/DomainParticipantFactory.hpp
- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- src/cpp/rtps/xmlparser/XMLProfileManager.cpp
- Load domain id from XML. 
- Apply default profile from XML using DDS API.
> Refs #8925 & #8926 DDS API XML fixes [8928]

- README.md
- fastrtps.repos
Create a `fastdds_ws` root directory for the colcon workspace
> Update colcon installations instructions

- examples/C++/DDS/LifespanQoSExample/LifespanSubscriber.cpp
> Only read on_data_available [8899]

- examples/C++/Configurability/README.txt
- examples/C++/DDS/Configurability/README.txt
- examples/C++/DDS/HistoryKind/README.txt
- examples/C++/DDS/Keys/README.txt
- examples/C++/DDS/LateJoiners/README.txt
- examples/C++/DDS/SampleConfig_Controller/README.txt
- examples/C++/DDS/SampleConfig_Events/README.txt
- examples/C++/DDS/SampleConfig_Multimedia/README.txt
- examples/C++/HistoryKind/README.txt
- examples/C++/Keys/README.txt
- examples/C++/LateJoiners/README.txt
- examples/C++/SampleConfig_Controller/README.txt
- examples/C++/SampleConfig_Events/README.txt
- examples/C++/SampleConfig_Multimedia/README.txt
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.h
- src/cpp/rtps/reader/WriterProxy.h
- src/cpp/security/cryptography/AESGCMGMAC_Transform.cpp
- src/cpp/utils/collections/concurrent_queue.h
Signed-off-by: Johnny Willemsen <jwillemsen@remedy.nl>
> Fixed docu typos

- src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
- test/unittest/transport/SharedMemTests.cpp
- thirdparty/boost/include/boost/interprocess/shared_memory_object.hpp
- thirdparty/boost/include/boostconfig.hpp
> SIGBUS in boost::interprocess when /dev/shm is full (#1248) > 2.0.x [9028]

- examples/C++/DDS/CustomListenerExample/CustomListenerPublisher.cpp
- examples/C++/DDS/CustomListenerExample/CustomListenerPublisher.h
- examples/C++/DDS/CustomListenerExample/CustomListenerSubscriber.cpp
- examples/C++/DDS/CustomListenerExample/CustomListenerSubscriber.h
- examples/C++/DDS/CustomListenerExample/CustomListeners.cpp
- examples/C++/DDS/CustomListenerExample/CustomListeners.h
- examples/C++/DDS/CustomListenerExample/Topic.h
- examples/C++/DDS/CustomListenerExample/TopicTypes.h
> Fix uncrustify issues CustomListeners

- test/CMakeLists.txt
- test/system/tools/fastdds/CMakeLists.txt
- test/system/tools/fastdds/tests.py
- tools/CMakeLists.txt
- tools/fastdds/CMakeLists.txt
- tools/fastdds/discovery/parser.py
- tools/fastdds/fastdds
- tools/fastdds/fastdds.bat
- tools/fastdds/fastdds.py
- tools/fastdds/ros-discovery
- tools/fastdds/ros-discovery.bat
- tools/fastdds/shm/clean.py
- tools/fastdds/shm/parser.py
> fastdds Python tool (#1252) > 2.0.x [9025]

- include/fastrtps/utils/TimedConditionVariable.hpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastrtps_deprecated/publisher/PublisherHistory.cpp
- src/cpp/fastrtps_deprecated/publisher/PublisherImpl.cpp
- src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.cpp
> [8968] Added missing includes preventing correct realtime build.

- src/cpp/rtps/writer/StatefulWriter.cpp
- test/blackbox/common/BlackboxTestsPubSubHistory.cpp
* Add Blackbox test 
* Fix bug [8945]
> Fix Writer history behavior when there are no matched readers [9030]

- src/cpp/fastdds/publisher/qos/WriterQos.cpp
This, along with #1382, should fix #1380 
> Leave correct default values on WriterQos::clear [9298]

- src/cpp/fastdds/publisher/qos/WriterQos.cpp
- src/cpp/rtps/builtin/data/ReaderProxyData.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
This is a port of #1382 and #1384 to master
> Fixes for #1380 <master> [9302]

- include/fastdds/rtps/builtin/discovery/participant/PDPServer.h
- src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
- src/cpp/rtps/writer/ReaderProxy.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
This PR adds the creation of PDP and EDP discovery endpoints. Merge after #1391
> Create server discovery endpoints

- examples/C++/Keys/keys.cpp
Fix warnings introduced by #1365
> Fix warnings

- package.xml
> Add file package.xml with repo info to rosdistro display

- examples/C++/DDS/Configurability/UseCasePublisher.cpp
- examples/C++/DDS/Configurability/UseCaseSubscriber.cpp
- include/fastrtps/utils/fixed_size_bitmap.hpp
- test/unittest/transport/SharedMemTests.cpp
This PR fixes build errors and warnings under VS 2019 (see [here](http://jenkins.eprosima.com:8080/view/Nightly/job/nightly_fastdds_sec_master_windows/463/msbuild/))
> Fixed warnings on VS 2019 [9375]

- README.md
> Update README: add Linux aarch64 support and badges [9400]

- include/fastdds/rtps/writer/StatefulWriter.h
- src/cpp/rtps/builtin/BuiltinProtocols.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
- src/cpp/rtps/writer/StatefulWriter.cpp
This PR adds "process writers acknowledgements" sub-routine to discovery server.
> Server routine: Process writers acknowledgements sub-routine

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
> Server routine: Process disposals sub-routine

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataQueueInfo.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataQueueInfo.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
Merge after https://github.com/eProsima/Fast-DDS/pull/1407
> Server routine: Process data queue sub-routine

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
> Server routine: Process dirty topics sub-routine

- src/cpp/rtps/builtin/discovery/participant/DServerEvent2.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
> Server routine: Server thread

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
> Server routine: Database server prefix

- Quality_Declaration_foonathan_memory.md
For more information about Foonathan API used by *eprosima Fast DDS*, please refer to #1403
> Add Quality Declaration for foonathan_memory external dependency [9398]

- QUALITY.md
- README.md
For more info about the code style, please refer to eProsima/cpp-style#3
For more info about CONTRIBUTING and VULNERABILITY policies, please refer to https://github.com/eProsima/policies
For more information about Fast CDR Quality Declaration, please refer to https://github.com/eProsima/Fast-CDR/blob/master/QUALITY.md
For more information about `foonathan_memory` Quality Declaration, please refer to https://github.com/eProsima/Fast-DDS/blob/master/Quality_Declaration_foonathan_memory.md
> Add Quality Declaration and update README [9371]

- include/fastdds/dds/core/policy/ParameterTypes.hpp
- include/fastdds/rtps/security/cryptography/CryptoTypes.h
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/security/authentication/PKIDH.cpp
- src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.cpp
- src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.h
- src/cpp/security/cryptography/AESGCMGMAC_Types.h
Fixes some issues on security code found by Static Analysis Tools.
> Fixed SAT issues on security code <2.0.x> [9374]

- test/unittest/security/cryptography/CryptographyPluginTests.hpp
Fix test factory_CreateLocalParticipantHandle to prevent previous flaky behavior.
Uncrustify file.
> Fix bug CryptographyPluginTest [9438]

- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
Merge after `feature/discovery-server/testing` branch.
> Clear changes to release [9483]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryEndpointInfo.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
Merge after merging branch feature/discovery-server/testing
> Server is acked by default in DDB [9470]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
Merge after
https://github.com/eProsima/Fast-DDS/pull/1431
> Server DATA(p) acked just checked when necessary [9472]

- include/fastdds/rtps/writer/StatefulWriter.h
- include/fastrtps/publisher/PublisherHistory.h
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastrtps_deprecated/participant/ParticipantImpl.cpp
- src/cpp/fastrtps_deprecated/publisher/PublisherHistory.cpp
- src/cpp/rtps/reader/StatefulPersistentReader.cpp
- src/cpp/rtps/reader/StatelessPersistentReader.cpp
- src/cpp/rtps/writer/PersistentWriter.cpp
- src/cpp/rtps/writer/ReaderProxy.cpp
- src/cpp/rtps/writer/StatefulPersistentWriter.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessPersistentWriter.cpp
This is a rework of #1272 on the `master` branch.
> Fixed crash after recovery with persistence [9497]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners2.cpp
- src/cpp/rtps/builtin/discovery/participant/DServerEvent2.cpp
- src/cpp/rtps/builtin/discovery/participant/DServerEvent2.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
Rebase `feature/discovery-server/prototype` after https://github.com/eProsima/Fast-DDS/pull/1439 is merged.
> Server dedicated thread for routine processing [9488]

- src/cpp/subscriber/SubscriberHistory.cpp
- test/blackbox/BlackboxTestsPubSubFragments.cpp
- test/blackbox/BlackboxTestsPubSubHistory.cpp
- test/blackbox/PubSubReader.hpp
- test/mock/rtps/ReaderHistory/fastrtps/rtps/history/ReaderHistory.h
This is a backport of #1314 to 1.8.x
> Fix for late-joiners KEEP_LAST, RELIABLE, TRANSIENT_LOCAL <1.8.x> [9026]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> Quick fix in is_writer and is_reader in DDB

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataQueueInfo.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryEndpointInfo.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantChangeData.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners2.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
Merge after #1439 . I'm disabling tests now not to choke CI until #1439 is merged and this PR is rebased.
> Server periodic announcements [9490]

- thirdparty/boost/include/boost/interprocess/shared_memory_object.hpp
> Use posix_fallocate

- thirdparty/boost/include/boost/interprocess/shared_memory_object.hpp
> Use posix_fallocate <2.0.x>

- test/blackbox/RTPSWithRegistrationReader.hpp
This is a backport of #1441 to 2.0.x
> Fixed RTPSWithRegistrationReader <2.0.x> [9538]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryEndpointInfo.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
The changes are most of them in DiscoveryDataBase.cpp
However, there are many changes in new functions, change some methods visibility and encapsulate functionality
Merge after https://github.com/eProsima/Fast-DDS/pull/1432
> Discovery Server: New design for process disposals [9499]

- include/fastrtps/xmlparser/XMLProfileManager.h
> Added mising cleanup in XMLProfileParser [9572]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
> [Discovery Server] Identify writers and readers only with values valid in RTPS specification

- include/fastrtps/utils/collections/foonathan_memory_helpers.hpp
- src/cpp/rtps/builtin/data/ProxyHashTables.hpp
This is a rework of #1457 on `2.0.x`
Backport support for new [foonathan_memory](https://github.com/foonathan/memory) API.
> Account for new API on foonathan_memory [9545]

- include/fastdds/rtps/writer/StatefulPersistentWriter.h
- include/fastdds/rtps/writer/StatefulWriter.h
- src/cpp/rtps/writer/StatefulPersistentWriter.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- test/blackbox/common/RTPSBlackboxTestsPersistence.cpp
- test/blackbox/common/RTPSBlackboxTestsPersistenceNonIntraprocess.cpp
- test/blackbox/common/RTPSWithRegistrationReader.hpp
- test/blackbox/common/RTPSWithRegistrationWriter.hpp
- test/blackbox/common/mock/BlackboxMockConsumer.h
* Warning Log when an inconsistent acknack is received
* Error Log in case of persistent writer (database corruption)
* Blackbox test
> Warning Log when an inconsistent acknack is received [9579]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners2.cpp
- src/cpp/rtps/builtin/discovery/participant/DServerEvent2.cpp
- src/cpp/rtps/builtin/discovery/participant/DServerEvent2.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
Connect remote servers by pinging.
> [Discovery Server] Connect remote servers [9596]

- src/cpp/fastdds/publisher/PublisherImpl.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
> Fixed interlocking on endpoint deletion <master> [9612]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
> [Discovery Server] Cleanup mutex

- include/fastdds/rtps/common/EntityId_t.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryEndpointInfo.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantChangeData.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
> [Discovery Server] Propagation to other servers using virtual topics [9582]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
Fix a bug that the new updates weren't sent before when arriving.
Also fix repetition of set dirty topics.
> [Discovery Server] Send new updates

- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
For example, a user setting the UserData QoS, it is not be sent in the discovery.
I've added a regression test.
> Fix in EDP because wasn't setting first QoS correctly [8703]

- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/rtps/security/SecurityManager.h
- test/blackbox/api/dds-pim/PubSubParticipant.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp
- test/blackbox/common/BlackboxTestsSecurity.cpp
This is a port of #1490 into master
> Keep pending security messages directed for each local endpoint <master> [9627]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
Fix error in server endopoints. Routine must restarte till the own server is acked by al clients.
Fix set virtual topic to dirty in virtual endpoints creation.
> Routine is restarted till server is acked by all

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
- src/cpp/rtps/history/WriterHistory.cpp
Correct destruction race condition and other things
> [Discovery Server] Destruction

- src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
> Keep PDP lock when calling EDP::assignRemoteEndpoints

- include/fastdds/rtps/writer/StatefulWriter.h
Signed-off-by: Ignacio Montesino <ignaciomontesino@eprosima.com>
> Fix compile error on mac [9737]

- configure.ac
- include/fastdds/dds/topic/TopicDataType.hpp
- Add virtual method `is_bounded` returning `false` by default
- Add virtual method `is_plain` returning `false` by default
> Refs #9037 Extend TopicDataType API [9041]

- include/fastdds/rtps/history/ReaderHistory.h
- include/fastdds/rtps/history/WriterHistory.h
Correct Doxygen spelling errors
> Correct Doxygen typos

- test/unittest/security/accesscontrol/CMakeLists.txt
> Fix undefined OStreamConsumer reference error

- test/unittest/logging/LogTests.cpp
New `consumer_stream` tests introduced with #1340 have been seen to be flaky (for example #1525 [Linux CI](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3026/)). This pull request fixes the flaky behavior.
> Fix flaky Log Tests [9789]

- include/fastdds/dds/core/policy/ParameterTypes.hpp
- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastdds/rtps/common/CacheChange.h
- include/fastdds/rtps/common/SequenceNumber.h
- include/fastdds/rtps/messages/CDRMessage.hpp
- include/fastrtps/types/AnnotationParameterValue.h
- include/fastrtps/utils/collections/ResourceLimitedVector.hpp
- include/fastrtps/utils/fixed_size_bitmap.hpp
- src/cpp/dynamic-types/DynamicTypeBuilderFactory.cpp
- src/cpp/fastdds/core/policy/ParameterSerializer.hpp
- src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
- test/mock/dds/QosPolicies/fastdds/dds/core/policy/QosPolicies.hpp
Port of #1290 
* fixed warnings
Signed-off-by: ahcorde <ahcorde@gmail.com>
* Added cosmetic suggestions
Signed-off-by: ahcorde <ahcorde@gmail.com>
> fixed warnings [9193]

- include/fastdds/dds/core/policy/ParameterTypes.hpp
- include/fastdds/rtps/security/cryptography/CryptoTypes.h
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/security/authentication/PKIDH.cpp
- src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.cpp
- src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.h
- src/cpp/security/cryptography/AESGCMGMAC_Types.h
This is a port of #1398 into master branch
> Fixed SAT issues on security code <master> [9482]

- CMakeLists.txt
> Include SHM in the default transports. <master> [9727]

- src/cpp/rtps/persistence/PersistenceFactory.cpp
- src/cpp/rtps/persistence/SQLite3PersistenceService.cpp
- src/cpp/rtps/persistence/SQLite3PersistenceService.h
- src/cpp/rtps/persistence/SQLite3PersistenceServiceStatements.h
- test/blackbox/common/DDSBlackboxTestsPersistenceGuid.cpp
- test/blackbox/common/RTPSBlackboxTestsPersistenceGuid.cpp
- test/unittest/rtps/persistence/PersistenceTests.cpp
Implementation and testing of the new persistence schema to store last sequence number as described in https://gitlab.intranet.eprosima.com/eProsima/fastrtps-internal-docs/blob/feature/dds-layer-persistence/design/persistence_schema_v2.0.md
> Bug/persistence schema [9021]

- include/fastdds/rtps/transport/UDPTransportInterface.h
- include/fastdds/rtps/transport/UDPv4Transport.h
- include/fastdds/rtps/transport/UDPv6Transport.h
- include/fastdds/rtps/transport/test_UDPv4Transport.h
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/transport/UDPTransportInterface.cpp
- src/cpp/rtps/transport/UDPv4Transport.cpp
- src/cpp/rtps/transport/UDPv6Transport.cpp
- src/cpp/rtps/transport/test_UDPv4Transport.cpp
- test/blackbox/api/dds-pim/PubSubWriterReader.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubWriterReader.hpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
This is a port of #1520 to the master branch
> Fix communications with localhost only <master> [9757]

- package.xml
> Fixed package.xml [9832]

- package.xml
This PR adds a `package.xml` file to ease the integration with ROS 2.
> Added package.xml <2.0.x> [9836]

- package.xml
> Removing some dependencies from package.xml <2.0.x>

- package.xml
> Removing some dependencies from package.xml <master> [9858]

- src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPUtils.hpp
> Null check in EDPSimple destructor [9891]

- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/rtps/security/SecurityManager.h
This is a port of PR #1532 from master to 2.0.x
> bugfix for security handshake race condition <2.0.x> [9793]

- include/fastdds/rtps/builtin/discovery/endpoint/EDPSimple.h
- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- include/fastdds/rtps/builtin/liveliness/WLP.h
> Avoid using private header on public ones

- README.md
This PR adds a line coverage report shield linked to the Jenkins job running the coverage analysis.
> Add coverage shield to README.md [9998]

- src/cpp/rtps/xmlparser/XMLElementParser.cpp
- test/unittest/xmlparser/XMLElementParserTests.cpp
- test/unittest/xmlparser/wrapper/XMLParserTest.hpp
1 fix in `XMLElementParser::getXMLPropertiesPolicy`
> Negative clauses Coverage for XMLElementParser methods

- test/unittest/xmlparser/XMLElementParserTests.cpp
- test/unittest/xmlparser/wrapper/XMLParserTest.hpp
Signed-off-by: Ignacio Montesino <ignaciomontesino@eprosima.com>
> XMLElementParser add methods nacho

- src/cpp/rtps/xmlparser/XMLElementParser.cpp
- test/unittest/xmlparser/XMLElementParserTests.cpp
- test/unittest/xmlparser/mock/XMLMockConsumer.h
> Share mutex in MockLockConsumer condition variable

- test/unittest/xmlparser/XMLElementParserTests.cpp
> Added positive tests for the durability qos policy kind

- src/cpp/rtps/transport/UDPv6Transport.cpp
> Fix UDPv6 assert [10013]

- src/cpp/rtps/xmlparser/XMLElementParser.cpp
- test/unittest/xmlparser/CMakeLists.txt
- test/unittest/xmlparser/XMLElementParserTests.cpp
- test/unittest/xmlparser/mock/XMLMockConsumer.h
- test/unittest/xmlparser/wrapper/XMLParserTest.hpp
This PR adds all the remaining unit tests to cover all the source code lines in file `src/cpp/rtps/xmlparser/XMLElementParser.cpp`. The `XMLElementParser` code lines coverage has been increased to 100%
> Added remaining test cases for XMLElementParser.cpp [10011]

- include/fastdds/rtps/writer/RTPSWriter.h
- include/fastdds/rtps/writer/StatefulWriter.h
- include/fastdds/rtps/writer/StatelessWriter.h
- src/cpp/fastrtps_deprecated/attributes/TopicAttributes.cpp
- src/cpp/fastrtps_deprecated/publisher/PublisherHistory.cpp
- src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- test/blackbox/common/BlackboxTestsPubSubHistory.cpp
- test/mock/rtps/RTPSWriter/fastdds/rtps/writer/RTPSWriter.h
This PR fixes RTPS writers and so they correctly handle infinite resource limits
> Fixed resource limits on keyed topics [9787]

- QUALITY.md
- Quality_Declaration_foonathan_memory.md
- README.md
- versions.md
> Upgrade to QL1

- src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.cpp
- src/cpp/security/cryptography/AESGCMGMAC_Transform.cpp
- src/cpp/security/cryptography/AESGCMGMAC_Types.h
Some static analysis warnings were found while investigating [this](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3217/valgrindResult/pid=34826/)
This PR fixes them, and also adds some tidiness to the code of `AESGCMGMAC`
> Fixes and cleanup on AESGCMGMAC [10096]

- src/cpp/security/authentication/PKIDH.cpp
This is a trivial PR to fix a typo.
> Fix spelling errors

- include/fastrtps/attributes/ParticipantAttributes.h
Check also domainId in equality between participant attributes
> Update participant attributes equality comparison

- test/unittest/transport/UDPv4Tests.cpp
The now guarded code assumes that the interface list is never empty, and will throw an exception on `interfaces.at(0).name` otherwise.
I used `interfaces.size() > 0` for consistency with `open_and_close_two_multicast_transports_with_whitelist`. `!interfaces.empty()` would probably be more efficient, although I doubt that it makes a noticeable difference here.
Also, starting with GTest 1.10, you could call `GTEST_SKIP()` to make it explicit that the test is not actually run.
> Only run tests with non-local interfaces if such an interface exists

- src/cpp/fastdds/publisher/qos/WriterQos.cpp
> Correct default reliability on WriterQos::clear <2.0.x>

- include/fastdds/dds/core/LoanableArray.hpp
- include/fastdds/dds/core/StackAllocatedSequence.hpp
- test/unittest/dds/collections/LoanableSequenceTests.cpp
Implementation of an `std::array`-based `LoanableCollection`
> LoanableArray and StackAllocatedSequence [10142]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
Error fixed in #1620 backport to 2.0.x in order to fix future timing errors that arrive with ResourceTimeEvent.
> Backport 2.0.x - Fix DS with Timing errors in acks [10133]

- include/fastdds/rtps/common/Types.h
- include/fastdds/rtps/common/VendorId_t.hpp
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/common/GuidUtils.hpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/shared_mem/SHMLocator.hpp
- src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
- src/cpp/utils/Host.hpp
- src/cpp/utils/System.cpp
- src/cpp/utils/SystemInfo.hpp
- test/mock/rtps/MessageReceiver/fastdds/rtps/messages/MessageReceiver.h
- test/unittest/rtps/common/CMakeLists.txt
- test/unittest/rtps/common/GuidUtilsTests.cpp
Backport of #1637 into `2.1.x`
> Increasing GUID prefix uniqueness <2.1.x>

- include/fastdds/rtps/common/Types.h
- include/fastdds/rtps/common/VendorId_t.hpp
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/common/GuidUtils.hpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/shared_mem/SHMLocator.hpp
- src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
- src/cpp/utils/Host.hpp
- src/cpp/utils/System.cpp
- src/cpp/utils/SystemInfo.hpp
- test/mock/rtps/MessageReceiver/fastdds/rtps/messages/MessageReceiver.h
- test/unittest/rtps/common/CMakeLists.txt
- test/unittest/rtps/common/GuidUtilsTests.cpp
Backport of #1637 into `2.0.x`
> Increasing GUID prefix uniqueness <2.0.x>

- src/cpp/rtps/resources/ResourceEvent.cpp
- test/unittest/rtps/resources/timedevent/TimedEventTests.cpp
Remove unnecessary waiting in ResourceEvent loop
Do not wait on active timers in ResourceEvent loop if there are pending
timers.
Cherry-pick direct backport.
Test with Discovery-Server and works (except backup: not working in 2.0.x and fastdds discovery server tool test: not backport of correct closure)
> Backport remove waiting resource event <2.0.x> [10179]

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
DDB counts new entities since last consulted.
> Count new entities [10133]

- test/system/tools/fds/tests.py
> Improve verbosity in failure of test_fast_discovery_closure

- examples/C++/DDS/HelloWorldExampleSharedMem/HelloWorld_main.cpp
- examples/C++/DDS/SecureHelloWorldExample/HelloWorld_main.cpp
- examples/C++/DynamicHelloWorldExample/HelloWorld_main.cpp
- examples/C++/HelloWorldExampleSharedMem/HelloWorld_main.cpp
- examples/C++/SecureHelloWorldExample/HelloWorld_main.cpp
This PR sets log level to Error in all examples
> Set all log levels to Error in examples

- include/fastdds/dds/log/Log.hpp
> Revert API break on forcing ; after log* macros

- include/fastrtps/xmlparser/XMLProfileManager.h
- include/fastrtps/xmlparser/XMLTree.h
- src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
- src/cpp/rtps/xmlparser/XMLParser.cpp
- src/cpp/rtps/xmlparser/XMLProfileManager.cpp
- test/unittest/xmlparser/XMLProfileParserTests.cpp
- test/unittest/xmlparser/test_xml_root_library_settings.xml
Merge after #1612
Added unit tests for the `XMLProfileManager` classes' public methods
> Added tests for XMLProfileManager [10089]

- test/performance/throughput/ThroughputPublisher.cpp
- test/performance/throughput/ThroughputSubscriber.cpp
Change unlock order in code to try to fix unknown failure in ThroughputTest.
Log added to keep tracking in next failure.
> Throughput test late unlock [10237]

- include/fastrtps/utils/IPLocator.h
- src/cpp/utils/IPLocator.cpp
- test/unittest/utils/LocatorTests.cpp
RFC recommendation: https://tools.ietf.org/html/rfc5952
Related to #1653
> Apply RFC to IPv6 to string [10252]

- include/fastrtps/subscriber/SubscriberHistory.h
- src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
- src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
- test/unittest/dds/subscriber/FooBoundedType.hpp
- test/unittest/dds/subscriber/FooBoundedTypeSupport.hpp
- test/unittest/dds/subscriber/FooType.hpp
This builds on top of #1662 and adds a test and fixes for filtering on read / not_read sample states
> Additional DataReader tests [10200]

- include/fastdds/dds/subscriber/DataReader.hpp
> Fix Doxygen typo in DataReader.hpp [10318]

- README.md
DO NOT DELETE, please!
More changes planned
> share project section README.md <master>

- include/fastdds/dds/core/status/StatusMask.hpp
- src/cpp/CMakeLists.txt
This pull request must be merged before #1705
> [10341] Library changes required for PR #1705

- fastrtps.repos
> Set Fast DDS version in repos

- thirdparty/boost/include/boost/config/platform/qnxnto.hpp
Fixes issue #1631 in branch 2.1.x
> add boost platform config for qnx

- doc/README.html.in
- utils/doxygen/pages/mainpage.dox
There is still some files with the old name.
> Update some files to new product name [10454]

- src/cpp/utils/string_convert.cpp
> Change ifdef to include any libc++ LLVM implementaion <2.1.x>

- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- src/cpp/rtps/history/TopicPayloadPoolRegistry.cpp
- src/cpp/rtps/history/TopicPayloadPoolRegistry.hpp
- src/cpp/rtps/history/TopicPayloadPoolRegistry_impl/TopicPayloadPoolRegistry.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemWatchdog.hpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
This is a port of #1748 into 2.1.x
> Fix singleton destruction order <2.1.x> [10583]

- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- include/fastdds/rtps/builtin/discovery/participant/timedevent/DSClientEvent.h
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.cpp
> Client match EDP with the servers individually <2.1.x> [10604]

- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- include/fastdds/rtps/builtin/discovery/participant/timedevent/DSClientEvent.h
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.cpp
> Client match EDP with the servers individually <2.0.x> [10604]

- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemWatchdog.hpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/subscriber/CMakeLists.txt
- test/unittest/dds/subscriber/DataReaderTests.cpp
This is a port of #1748 into 2.0.x
> Fix singleton destruction order <2.0.x> [10584]

- thirdparty/boost/include/boost/interprocess/shared_memory_object.hpp
> Use ftruncate on QNX <master>

- include/fastdds/rtps/common/CacheChange.h
- include/fastdds/rtps/common/LocatorSelectorEntry.hpp
> Fixed with and easily typos

- src/cpp/rtps/DataSharing/DataSharingPayloadPool.hpp
- src/cpp/utils/shared_memory/RobustExclusiveLock.hpp
- src/cpp/utils/shared_memory/RobustSharedLock.hpp
- src/cpp/utils/shared_memory/SharedDir.hpp
This is a port of #1766 to master
> [10647] Provide an alternative path for robustlock files under QNX <master>

- tools/fds/server.cpp
With this PR, `fastdds discovery` lists all the locators specified for the server.
> List all server locators [10725]

- src/cpp/rtps/resources/ResourceEvent.cpp
- test/unittest/rtps/resources/timedevent/TimedEventTests.cpp
> <2.1.x> Remove unnecessary waiting in ResourceEvent loop [10723]

- include/fastdds/dds/subscriber/SampleInfo.hpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
- versions.md
> Add reception timestamp to fastdds SampleInfo [10492]

- test/performance/latency/CMakeLists.txt
- test/performance/latency/latency_tests.py
- test/performance/throughput/CMakeLists.txt
- test/performance/throughput/throughput_tests.py
> Explicitly set reliability

- src/cpp/utils/Host.hpp
- src/cpp/utils/IPFinder.cpp
> Add QNX to the MAC retrieving platforms

- src/cpp/rtps/transport/shared_mem/MultiProducerConsumerRingBuffer.hpp
Running [MSAN](https://github.com/google/sanitizers/wiki/MemorySanitizer) on a trivial example results in an instant crash and cryptic stack trace from a debugger:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000020aa99f in select_compare_exchange_16 () at third-party/gcc/src/libatomic/cas_n16.c:124
124	third-party/gcc/src/libatomic/cas_n16.c: No such file or directory.
(gdb) bt
#0  0x00000000020aa99f in select_compare_exchange_16 () at third-party/gcc/src/libatomic/cas_n16.c:124
#1  0x00007ffff7de04a8 in _dl_relocate_object () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7dd8208 in dl_main () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7dee14f in _dl_sysdep_start () from /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff7dd6136 in _dl_start () from …
```
> Avoid using a custom atomic type for shared pointer data.

- include/fastdds/rtps/common/GuidPrefix_t.hpp
> [10790] Hotfix GuidPrefix serialization

- include/fastdds/rtps/common/GuidPrefix_t.hpp
> [10790] Fix GuidPrefix serialization <2.1.x>

- include/fastdds/rtps/common/GuidPrefix_t.hpp
> [10790] Fix GuidPrefix serialization <2.0.x>

- src/cpp/utils/SystemInfo.hpp
- test/unittest/utils/CMakeLists.txt
- test/unittest/utils/SystemInfoTests.cpp
> [10922] Extend SystemInfo class to provide a method to get environment variables

- .github/workflows/mirror.yml
Add a github workflow so pushes on master branch make branch 2.3.x follow along.
> Mirror master branch onto 2.3.x

- include/fastdds/dds/domain/DomainParticipant.hpp
- src/cpp/fastdds/domain/DomainParticipant.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
> DDS API fix

- include/fastdds/rtps/common/Time_t.h
- src/cpp/rtps/common/Time_t.cpp
- src/cpp/rtps/persistence/SQLite3PersistenceService.cpp
- src/cpp/rtps/persistence/SQLite3PersistenceServiceStatements.h
- test/unittest/rtps/persistence/CMakeLists.txt
- test/unittest/rtps/persistence/PersistenceTests.cpp
The new database schema solves LivesSpam and RPC issues.
The Upgrading procedure is updated.
New tests are added to check database migration.
> [10500] Upgrade persistence database to v3.0

- include/fastdds/rtps/common/Time_t.h
> Fix doxygen documentation

- include/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.h
- src/cpp/rtps/network/ReceiverResource.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
- test/blackbox/common/BlackboxTestsPubSubBasic.cpp
> Fix heartbeat and ACKs issues <2.2.x> [11004]

- include/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.h
- src/cpp/rtps/network/ReceiverResource.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
- test/blackbox/common/BlackboxTestsPubSubBasic.cpp
> Fix heartbeat and ACKs issues <2.1.x> [11005]

- include/fastrtps/types/TypesBase.h
> Fix C++ 20 issue with explicit use of operator

- .github/actions/fetch-fastdds-repos/action.yml
- .github/actions/install-apt-packages/action.yml
- .github/actions/install-gtest/action.yml
- .github/actions/install-python-packages/action.yml
- .github/workflows/colcon.meta
- .github/workflows/test.yml
- codecov.yml
> Action for coverage [11098]

- .github/workflows/colcon.meta
> Enable statistics tests [11098]

- include/fastdds/rtps/Endpoint.h
- include/fastdds/rtps/reader/RTPSReader.h
- include/fastdds/rtps/writer/RTPSWriter.h
- include/fastdds/statistics/rtps/StatisticsCommon.hpp
- include/fastdds/statistics/rtps/StatisticsCommonEmpty.hpp
- src/cpp/CMakeLists.txt
- src/cpp/rtps/messages/RTPSMessageGroup.cpp
- src/cpp/rtps/participant/RTPSParticipant.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/rtps/reader/RTPSReader.cpp
- src/cpp/rtps/writer/RTPSWriter.cpp
- src/cpp/statistics/rtps/StatisticsBase.cpp
- src/cpp/statistics/rtps/StatisticsBase.hpp
- src/cpp/statistics/rtps/reader/StatisticsReaderImpl.cpp
- src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
- src/cpp/statistics/types/types.cxx
- test/unittest/statistics/rtps/CMakeLists.txt
- test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
Listener management implementation on the rtps layer 
References [10809], [10810], [10811] and [10812].
> Statistics module rtps listener management

- include/fastrtps/utils/IPFinder.h
> Correct comparison of MAC addresses <2.2.x>

- src/cpp/rtps/transport/shared_mem/SharedMemChannelResource.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
- test/communication/CMakeLists.txt
- test/communication/PubSubMain.cpp
- test/communication/Subscriber.cpp
- test/communication/Subscriber.hpp
- test/communication/SubscriberMain.cpp
- test/communication/shm_communication_subscriber_dies_while_processing_message.py
- test/communication/shm_communication_subscriber_dies_while_processing_message.xml
This is port of #1856 from <master> to <2.2.x>
> Free used buffers in SHM on zombie ports <2.2.x> [11127]

- src/cpp/rtps/transport/shared_mem/SharedMemChannelResource.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
- test/communication/CMakeLists.txt
- test/communication/PubSubMain.cpp
- test/communication/Subscriber.cpp
- test/communication/Subscriber.hpp
- test/communication/SubscriberMain.cpp
- test/communication/shm_communication_subscriber_dies_while_processing_message.py
- test/communication/shm_communication_subscriber_dies_while_processing_message.xml
This is a port of #1856 from <master> to <2.0.x>
> Free used buffers in SHM on zombie ports <2.0.x> [11125]

- src/cpp/rtps/writer/LivelinessManager.cpp
> Avoid using reference after removing item on LivelinessManager <2.0.x> [11018]

- src/cpp/rtps/writer/LivelinessManager.cpp
> Avoid using reference after removing item on LivelinessManager [11019]

- src/cpp/rtps/writer/LivelinessManager.cpp
> Avoid using reference after removing item on LivelinessManager <2.2.x> [11020]

- src/cpp/rtps/writer/LivelinessManager.cpp
> Avoid using reference after removing item on LivelinessManager <2.1.x> [11021]

- .github/workflows/colcon.meta
- .github/workflows/test.yml
- include/fastdds/statistics/rtps/StatisticsCommon.hpp
- include/fastdds/statistics/rtps/StatisticsCommonEmpty.hpp
- src/cpp/rtps/messages/RTPSMessageGroup.cpp
- src/cpp/statistics/rtps/StatisticsBase.cpp
- src/cpp/statistics/rtps/StatisticsBase.hpp
- src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
- test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
Updated besides: testing & workflow
This pull request must be merged after https://github.com/eProsima/Fast-DDS/pull/1915
> [10800] - Collection of data and notification to listeners GAP_COUNT

- configure.ac
- package.xml
> Bump version to 2.3.1

- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/statistics/rtps/StatisticsBase.cpp
- src/cpp/statistics/rtps/StatisticsBase.hpp
- src/cpp/statistics/types/typesPubSubTypes.cxx
- test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
There is a little piggyback preventing the dds layer statistics endpoints from been instrumented from the rtps layer.
> [10802] Collection of data and notification to listeners PDP_PACKETS

- src/cpp/CMakeLists.txt
- src/cpp/rtps/messages/MessageReceiver.cpp
- src/cpp/rtps/messages/fuzz_processCDRMsg.cpp
cc @MiguelCompany 
Oss-fuzz build is failing because the signature of `processCDRMsg` changed recently
cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34310
This should fix it
> oss-fuzz integration

- README.md
> [11596] Update to ROS 2 Galactic

- include/fastdds/rtps/network/NetworkFactory.h
- src/cpp/rtps/network/NetworkFactory.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
Backport bugfix to foxy(2.0.x)
> Fix wrong calculation of user multicast port <2.0.x> (#1479)

- README.md
Co-Authored by: Roman Sokolkov @r7vme
Signed-off-by: Dani-Cabezas <DanielCabezas@eprosima.com>
This is a rework of #725
> Extend README.md quick demo with real example

- include/fastrtps/types/DynamicData.h
- src/cpp/dynamic-types/DynamicData.cpp
Signed-off-by: Jose Antonio Moral <joseantoniomoralparras@gmail.com>
> Add DynamicData::get_union_id() method

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
This PR should solve the `logError` described by @rsanchez15 in https://github.com/eProsima/Fast-DDS-statistics-backend/pull/103#pullrequestreview-706074761
> Accept Statistics DataWriters in Discovery Server [12139]

- src/cpp/rtps/RTPSDomain.cpp
> Remove unused variable

- tools/fds/server.cpp
> Fix Fast DDS CLI server name

- examples/C++/DDS/LateJoiners/latejoiners.cpp
Improve waiting logic on Late Joiners example
> Fix LateJoiners example

- configure.ac
- fastrtps.repos
- package.xml
> Bump version to 2.3.4

- src/cpp/fastdds/publisher/DataWriter.cpp
- test/unittest/dds/publisher/DataWriterTests.cpp
> Implementation of DataWriter::get_type() [12286]

- configure.ac
- package.xml
> Bump version to 2.4.0

- include/fastdds/rtps/builtin/discovery/endpoint/EDPStatic.h
- src/cpp/rtps/builtin/discovery/endpoint/EDPStatic.cpp
- test/blackbox/CMakeLists.txt
- test/blackbox/PubSubReaderPersistence.xml.in
- test/blackbox/PubSubWriterPersistence.xml.in
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
- test/blackbox/common/DDSBlackboxTestsPersistence.cpp
Feature for distributing persistence guid through participant user_data when EDP static is used
> Add load persistence_guid from UserData [11689]

- CMakeLists.txt
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/utils/SystemInfo.cpp
- src/cpp/utils/SystemInfo.hpp
- test/unittest/utils/SystemInfoTests.cpp
- thirdparty/filewatch/FileWatch.hpp
- thirdparty/filewatch/LICENSE
This PR is built over #2159.
* Adds FileWatch to the thirdparties
* Creates a wrapper API for FileWatch on SystemInfo
* Unit testing for the new API
> [12199] filewatch integration

- include/fastdds/rtps/builtin/discovery/endpoint/EDPStatic.h
> Hotfix: fix doxydoc

- include/fastdds/dds/domain/qos/DomainParticipantQos.hpp
- include/fastrtps/types/TypesBase.h
Fixes needed for the Python bindings to work
> python bindings fixes [11914]

- include/fastdds/rtps/common/InstanceHandle.h
- include/fastdds/rtps/history/ReaderHistory.h
- include/fastdds/rtps/reader/StatefulReader.h
- include/fastdds/rtps/writer/ReaderProxy.h
> [13179] Fix doxygen documentation

- versions.md
Only last commit is relevant. Merge after #2245.
> [12821] Hotfix: add xml string feature to versions

- include/fastdds/rtps/transport/ChainingTransport.h
> [13291] Hotfix: doxygen documentation

- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/rtps/transport/test_UDPv4Transport.cpp
- src/cpp/rtps/transport/test_UDPv4Transport.h
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
- test/blackbox/common/RTPSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSWithRegistrationReader.hpp
- test/blackbox/common/RTPSWithRegistrationWriter.hpp
> Add participant locators if new network interfaces are found

- src/cpp/rtps/RTPSDomain.cpp
> Change log verbosity in error mutation_took_place_on_meta [13422]

- test/blackbox/CMakeLists.txt
Temporarily disabled due to Windows CI issues
> Restore PKCS#11 Windows testing [12823]

- README.md
Add a twitter shield to README
> Twitter shield [13539]

- RELEASE_SUPPORT.md
- RELEASE_SUPPORT.rst
> [13563] Release lifecycle

- src/cpp/security/artifact_providers/FileProvider.cpp
- test/unittest/security/authentication/BuiltinPKIDHTests.cpp
> [12974] Fix segmentation fault when loading private key with wrong password

- src/cpp/security/authentication/PKIDH.cpp
> [13365] Fix memory leak in DH key generation

- test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp
- test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestType.h
- test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestType.idl
- test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypeTypeObject.cxx
This PR adds tests for DDSSQLFilter module. Still pending:
> DDSSQLFilter Behavioral tests [13789]

- include/fastdds/rtps/participant/RTPSParticipant.h
Signed-off-by: Ines Luño <inesluno@eprosima.com>
> Fix Doxygen Warnings

- thirdparty/optionparser/optionparser.hpp
> Always include local optionparser.h [13785]

- fastrtps.repos
Correctly point `fastrtps.repos` to branch 2.5.x
> Fixup #2529

- .github/workflows/mirror.yml
- CMakeLists.txt
- package.xml
This PR bumps the version to 2.6.0, and also changes the mirroring workflow to branch 2.6.x
> [13785] Bump version to 2.6.0

- .github/workflows/mirror.yml
Use a generic name on the mirroring workflow, so it does not include a specific branch name.
> Rename mirror workflow

- configure.ac
> [13784] Bump to version 1.7.3

- configure.ac
- fastrtps.repos
I have not modified the dependencies versions. I am not sure if it is advisable.
> [13784] Bump version to 1.8.5

- configure.ac
- fastrtps.repos
- package.xml
I have not modified the dependencies versions. I am not sure if it is advisable.
> [13784] Bump to version 2.2.1

- include/fastdds/rtps/network/NetworkFactory.h
- include/fastdds/rtps/transport/ChainingTransport.h
- include/fastdds/rtps/transport/TransportInterface.h
- src/cpp/rtps/network/NetworkFactory.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/TCPTransportInterface.h
- src/cpp/rtps/transport/UDPTransportInterface.h
- src/cpp/rtps/transport/UDPv4Transport.h
- src/cpp/rtps/transport/UDPv6Transport.cpp
- src/cpp/rtps/transport/UDPv6Transport.h
- src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
- src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
- test/unittest/rtps/network/mock/MockTransport.h
- versions.md
This PR refactors the dynamic network interface extending the API to support more transport layers (not only UDPv4).
Task 13909 includes the design of test cases for this feature. The changes introduced should not break anything.
I will leave the CI to ensure this point.
Currently documentation is up-to-date. There has been no change in the behavior introduced by this PR.
> [14046] Dynamic network empty interfaces refactor

- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- test/dds/discovery/client_server_dynamic_discovery.py
- versions.md
This PR allows users to modify the remote servers locators at runtime in the environment file besides simply adding new remote servers to the list.
Test should be added in the [Discovery-Server](https://github.com/eProsima/Discovery-Server) repository.
Internal comments in the code have been modified accordingly.
Related documentation PR: eProsima/Fast-DDS-docs#349
> [13944] Feature: modify remote servers locators

- include/fastdds/dds/subscriber/DataReader.hpp
eprosima::fastdds::dds::DataReader::type() is not exported on Windows. This PR fixes this.
> Fix not exported function on DataReader [14077]

- roadmap.md
This PR updates Fast DDS roadmap.
> [14094] Update roadmap

- include/fastdds/rtps/builtin/discovery/endpoint/EDPStatic.h
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/builtin/BuiltinProtocols.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPStatic.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/blackbox/common/BlackboxTestsDiscovery.cpp
This PR adds a new exchange format of Static Discovery's information which reduces the network bandwidth usage.
Documentation: eProsima/Fast-DDS-docs#358
> Add new exchange format to Static Discovery [13266]

- Quality_Declaration_foonathan_memory.md
- README.md
Update README and ROS 2 references.
Fixes #1993
> [14124] Update README and ROS 2 references

- include/fastdds/dds/subscriber/DataReader.hpp
- include/fastdds/dds/topic/ContentFilteredTopic.hpp
- include/fastdds/dds/topic/IContentFilterFactory.hpp
- include/fastdds/dds/topic/Topic.hpp
- include/fastdds/dds/topic/TopicDescription.hpp
- include/fastdds/rtps/reader/RTPSReader.h
Adding missing doxydoc on ContentFilteredTopic methods.
Also removing some doc, as we don't need destructor or get_impl to be shown.
Closes #2609
> [13791] Several doxydoc improvements

- src/cpp/rtps/security/SecurityManager.cpp
> Authentication exponential backoff [12682]

- .github/workflows/thread-sanitizer.yaml
The sanitizer fixes go into the intermediate branch `features/tsan/fixes`. The github action must run whenever a *push* or *pull request* is performed against this intermediate branch.
Note that once the  `features/tsan/fixes` branch is merge into master the workflow must be modified to reference `master` changes as trigger.
The action will run on the Ubuntu host using the *apt* provided g++ (thread sanitizer is not yet available on other platforms).
The action's workflow:
- build from sources Fast-DDS and all the dependencies setting the sanitizer flags. 
- run the testing specifying a per-test sanitizer log.
- parsing the result log in order to: identify the issues, sort them by frequency, and filter out duplicates.
- generate a …
> [14285] Add sanitizer workflow

- test/unittest/logging/log_macros/LogMacrosDefaultTests.cpp
Fast DDS `LogMacrosDefaultTests.cpp` does not compile setting  the folllowing CMake options: `LOG_NO_INFO=OFF` and    `FASTDDS_ENFORCE_LOG_INFO=ON`
> Fix Log Macros test compilation error [14263]

- CMakeLists.txt
- fastrtps.repos
- package.xml
Just what the title says.
Bump version on `2.4.x` so we can do the EOL release.
> [14351] Bump version to 2.4.2

- .github/workflows/thread-sanitizer.yaml
https://github.com/eProsima/Fast-DDS/pull/2622 merged a new Sanitizer workflow to automatically run on certain triggers for the feature/tsan/fixes branch. As it is now, the branch being tested is master. This PR fixes that via the use of the checkout Github Action. 
- [N/A] Fast DDS test suite has been run locally. 
- [N/A] New feature has been documented/Current behavior is …
> [14354] Fixed sanitizers workflow to use current branch

- .github/workflows/thread-sanitizer.yaml
https://github.com/eProsima/Fast-DDS/pull/2633 attempted to fix an issue regarding the branch to use when running sanitizer tests. As it turns out, it was failing one of the steps but not failing the workflow run as a result. This PR fixes the cause of the error. 
- NA Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- NA Any new/modified methods have been properly documented using Doxygen. 
- NA Fast DDS test suite has been run locally. 
- NA Changes are ABI compatible. 
- NA Changes are API compatible. 
- NA Documentation builds and tests pass locally. 
- NA New feature has been added to the `versions.md` file (if applicable).
- NA New feature has been documented/Current behavior is correctly described in the …
> [14354] Fixed failure of sanitizer workflow

- .github/workflows/thread-sanitizer.yaml
See title. Also fixes a typo. Disables standard output for merge command to reduce confusion.
- NA Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- NA Any new/modified methods have been properly documented using Doxygen. 
- NA Fast DDS test suite has been run locally. 
- NA Changes are ABI compatible. 
- NA Changes are API compatible. 
- NA Documentation builds and tests pass locally. 
- NA New feature has been added to the `versions.md` file (if applicable).
- NA New feature has been documented/Current behavior is correctly described in the documentation.
> [14285] Alligned working path with master branch

- include/fastdds/dds/publisher/DataWriter.hpp
- src/cpp/fastdds/publisher/DataWriter.cpp
- src/cpp/fastdds/publisher/DataWriterHistory.cpp
- src/cpp/fastdds/publisher/DataWriterHistory.hpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.hpp
- src/cpp/fastdds/publisher/history/DataWriterInstance.hpp
- src/cpp/utils/constructor_macros.hpp
- test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
- test/mock/rtps/PublisherHistory/fastdds/publisher/DataWriterHistory.hpp
- test/unittest/dds/publisher/DataWriterTests.cpp
This PR provides tests and implementation for `DataWriter::get_key_value`
> [13151] DataWriter::get key value implementation

- test/blackbox/common/DDSBlackboxTestsFindTopic.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
Following TDD, this PR adds tests for `DomainParticipant::find_topic` before implementing it
Checked that the new tests fail.
> [14615] Add tests for DomainParticipant::find_topic

- README.md
Currently, the Jenkins cobertura plugin is broken in the sense that it does not return the actual coverage data.
For this reason, we have decided to morph the badge into a pass/no-pass one that links to the coverage report in Jenkins, which does work.
- *N/A*: Fast DDS test suite has been run locally. 
- *N/A*: New feature has been …
> Migrate coverage badge to pass/no-pass [14702]

- src/cpp/rtps/builtin/liveliness/WLP.cpp
Function WLP::remove_local_writer() returned false in some cases/situations that were actual succesful.
> Fix missing return in WLP::remove_local_writer() [14751]

- include/fastdds/rtps/writer/ReaderProxy.h
- src/cpp/rtps/writer/ReaderProxy.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
Signed-off-by: Aleksandr Rozhdestvenskii <hexonxons@gmail.com>
> [galactic] Fix: gap not being sent with heartbeat [14676]

- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- src/cpp/rtps/transport/UDPTransportInterface.cpp
- src/cpp/rtps/transport/UDPTransportInterface.h
- src/cpp/rtps/transport/UDPv4Transport.cpp
- src/cpp/rtps/transport/UDPv6Transport.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
> Fix WLP deadlock and EDP discovery performance improvement [14450][14457]

- CMakeLists.txt
- package.xml
- versions.md
> [14579] Bump version to 2.6.1

- include/fastdds/dds/publisher/DataWriter.hpp
- include/fastdds/rtps/common/WriteParams.h
- src/cpp/fastdds/publisher/DataWriter.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.hpp
- src/cpp/rtps/history/WriterHistory.cpp
- test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- versions.md
This PR provides tests and implementation of the following DataWriter methods:
* `write_w_timestamp`
* `register_instance_w_timestamp`
* `unregister_instance_w_timestamp`
* `dispose_w_timestamp`
> [13150] Implementation of DataWriter `_w timestamp` methods

- fastrtps.repos
Just what the title says. Set the version of dependencies to the ones in the v2.6.1 tag, and 2.6.x for this repo.
> [14579] Update repos file to 2.6.x.

- README.md
Signed-off-by: Ricardo González Moreno <ricardo@richiware.dev>
> Recover old coverage badge [14854]

- test/dds/communication/SubscriberDynamic.cpp
The test DDSSimpleCommunicationTypeDiscovery is ill-formed using one of the framework callbacks to create an endpoint. This may deadlock the transport thread used in the callback.
The test has been refactored using a future/promise C++11 strategy that allows generating all endpoints from the main thread.
> [14834] Fixing tsan issue 4192 (DDSSimpleCommunicationTypeDiscovery refactor) <feature/tsan/fixes>

- tools/fds/CMakeLists.txt
> fix c++11 support for fast discovery server tool

- include/fastdds/rtps/reader/ReaderListener.h
- **N/A** Fast DDS test suite has been run locally.
> [15024 ] Added bulk notification interface to RTPS reader listener

- include/fastdds/dds/subscriber/DataReaderListener.hpp
follow-up for https://github.com/eProsima/Fast-DDS/issues/2760
Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>
> multiple messages could be delivered via on_data_available.

- src/cpp/security/OpenSSLInit.hpp
Only use deprecated `ENGINE_cleanup()` function with OpenSSL versions 1.1.0 and lower.
> Move deprecated openssl cleanup function to match the right version [14967]

- test/blackbox/common/BlackboxTestsLogConsumer.cpp
> Fix regex in LogConsumer blackbox test

- RELEASE_SUPPORT.md
- roadmap.md
- versions.md
This PR updates:
- the release lifecycle support adding the new minor release.
- Fast DDS roadmap.
- Versions file with the new features, ABI breaks and new API extensions.
> [14910] Update release related information

- .github/workflows/thread-sanitizer.yaml
Update the current one in the intermediate branch `feature/tsan/fixes` to run in every master pull request or commit.
Make sure it fails in the presence of new deadlocks.
Show a summary of the sanitizer results on termination using Github action environment variable mechanism.
> [15025] Update thread sanitizer workflow.

- .github/workflows/thread-sanitizer.yaml
Prevent workflow run on:
- `no-test` flag selected
- non-sources (including cmake) changes
- [] NA Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added.
> [15025] Improvements thread sanitizer workflow

- .github/workflows/thread-sanitizer.yaml
Specify a fix version of gtest for the thread sanitizer job
> Set ThreadSanitizer workflow gtest version to 1.11

- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
This PR adds a check to prevent dereferencing the data_available_instances_ collection's end iterator.
> [15192] Added check to prevent dereferencing end() iterator

- CMakeLists.txt
- package.xml
This PR bumps version to 2.5.2. This is the final patch release for Fast DDS 2.5.x.
> [15161] Bump version to 2.5.2 (EOL)

- src/cpp/CMakeLists.txt
- src/cpp/rtps/network/ExternalLocatorsProcessor.cpp
- src/cpp/rtps/network/ExternalLocatorsProcessor.hpp
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/statistics/dds/CMakeLists.txt
This PR adds an empty implementation for `ExternalLocatorsProcessor`, so we can add unit tests for it and, in parallel, prepare the implementation
> [15017] Adding empty implementation for ExternalLocatorsProcessor

- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
Signed-off-by: Ricardo González Moreno <ricardo@richiware.dev>
> Store EDP listener pointers before being used [15216]

- configure.ac
- fastrtps.repos
- package.xml
> [15163] Bump to version 2.1.2

- fastrtps.repos
> [15163] Fix fastrtps version

- configure.ac
- package.xml
> [15160] Bump version to 2.3.5

- CMakeLists.txt
- package.xml
* **N/A** New feature has been added to the `versions.md` file (if applicable).
> [15162] Bump version to 2.6.2

- CMakeLists.txt
- package.xml
> [15159] Bump to version 2.7.1

- include/fastdds/dds/domain/DomainParticipantFactory.hpp
- include/fastdds/dds/publisher/DataWriter.hpp
> [15159] Remove unsupported note from supported methods

- fastrtps.repos
- **N/A**Documentation builds and tests pass locally. 
> Set fixed versions on fastrtps.repos <2.7.x>

- utils/scripts/update_generated_code_from_idl.sh
This PR adds an script for regenerating source code from all idl files included in this repository.
> Add script to generate idl files [15348]

- examples/cpp/dds/BasicConfigurationExample/BasicConfigurationPublisher.cpp
- examples/cpp/dds/BasicConfigurationExample/BasicConfigurationPublisher.h
- examples/cpp/dds/BasicConfigurationExample/BasicConfigurationSubscriber.cpp
- examples/cpp/dds/BasicConfigurationExample/BasicConfigurationSubscriber.h
- examples/cpp/dds/BasicConfigurationExample/BasicConfiguration_main.cpp
- examples/cpp/dds/BasicConfigurationExample/CMakeLists.txt
- examples/cpp/dds/BasicConfigurationExample/README.md
- examples/cpp/dds/BasicConfigurationExample/arg_configuration.h
Command line processing now relies entirely on *optionparser.h* capabilities.
A new `--ttl` option has been added that specifies how many hops must multicast specify. It doesn't affect unicast TTL.
If no transport is specified but ttl is then the example will try to mimick builtin transport with the specified hops.
- [] NA Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added.
> [15477] Update BasicConfigurationExample to allow set up TTL

- test/unittest/xmlparser/XMLProfileParserTests.cpp
- test/unittest/xmlparser/test_xml_profiles.xml
This PR adds tests related with the XML parsing of the external locators configuration.
> [14631] External locators XML parsing tests

- test/unittest/dynamic_types/DynamicComplexTypesTests.cpp
- utils/scripts/update_generated_code_from_idl.sh
> Update script for generating idl files [15483]

- .github/workflows/thread-sanitizer.yaml
- test/blackbox/CMakeLists.txt
> Default test switch

- package.xml
Signed-off-by: Giuseppe Barbieri  <giuse.barbieri@gmail.com>
A few test and tools depend on python3 interpreter. This is only installed in the [github action yml](https://github.com/eProsima/Fast-DDS/blob/32f0eabb3f9fbc1da8d9ccd4e3465d4a37f56001/.github/actions/install-apt-packages/action.yml#L9), but it is currently missing from the package.xml.
This issue was spotted in the 2.1.x branch (ROS foxy distribution), hence it will require backporting.
> add missing dep python3 to package.xml

- examples/cpp/dds/BasicConfigurationExample/BasicConfigurationPublisher.cpp
- examples/cpp/dds/BasicConfigurationExample/BasicConfigurationSubscriber.cpp
Add Guid info to BasicConfiguration Example in printed information by `cout`.
> Add Guid info to BasicConfiguration Example cout [15244] 

- include/fastrtps/xmlparser/XMLParser.h
- include/fastrtps/xmlparser/XMLParserCommon.h
- resources/xsd/fastRTPS_profiles.xsd
- src/cpp/fastdds/builtin/typelookup/TypeLookupManager.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/utils/QosConverters.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/builtin/liveliness/WLP.cpp
- src/cpp/rtps/network/ExternalLocatorsProcessor.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/reader/WriterProxy.cpp
- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- src/cpp/rtps/xmlparser/XMLElementParser.cpp
- src/cpp/rtps/xmlparser/XMLParser.cpp
- src/cpp/rtps/xmlparser/XMLParserCommon.cpp
- test/mock/rtps/ExternalLocatorsProcessor/rtps/network/ExternalLocatorsProcessor.hpp
- test/unittest/rtps/discovery/CMakeLists.txt
- test/unittest/rtps/reader/CMakeLists.txt
Adds implementation for the external locators feature.
- ❌ Changes are ABI compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable). <-- Will be done on the PR to master
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation.   <-- Will be done on the PR to master
> [15017] External locators implementation

- roadmap.md
This PRs updates the short-term roadmap
> [15600] Update roadmap

- src/cpp/statistics/fastdds/publisher/qos/DataWriterQos.cpp
> Increase statistics DataWriters history

- src/cpp/rtps/flowcontrol/FlowControllerFactory.cpp
Fix build on old compilers when FASTDDS_STATISTICS is define same as #2220
> Fix build on old compilers when FASTDDS_STATISTICS is define

- include/fastdds/rtps/transport/test_UDPv4TransportDescriptor.h
- include/fastdds/rtps/writer/StatefulWriter.h
- src/cpp/rtps/messages/RTPSMessageGroup.cpp
- src/cpp/rtps/transport/test_UDPv4Transport.cpp
- src/cpp/rtps/transport/test_UDPv4Transport.h
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
> [15896] Fix selection of output locators

- RELEASE_SUPPORT.md
> Add 2.8.x to RELEASE_SUPPORT

- src/cpp/CMakeLists.txt
Install public statistics .idl
Added public statistics .idl installation in CMakeLists.txt
@Mergifyio backport 2.7.x 2.6.x 2.3.x
**N/A**  Any new/modified methods have been properly documented using Doxygen. 
**N/A**  Fast DDS test suite has been run locally. 
**N/A** New feature has been documented/Current behavior is correctly described in the documentation.
> [16002] Install public statistics .idl

- src/cpp/rtps/persistence/SQLite3PersistenceService.cpp
A variable was being created under an scope and its reference used out from that scope in Persistence Service.
> Fix out of scope variable call in Persistence service [15995]

- CMakeLists.txt
> Avoid sanitizer warning message if option not set

- .github/workflows/asan.yml
Do not run ASAN CI job if `skip-ci` and/or `no-test` labels are set.
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- N/A Fast DDS test suite has been run locally. 
- N/A Documentation builds and tests pass locally. 
> [15964] Skip ASAN job if skip-ci or no-test label is set

- CMakeLists.txt
- package.xml
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- N/A Fast DDS test suite has been run locally. 
- N/A Documentation builds and tests pass locally. 
> [16076] Bump version to 2.8.1

- .github/workflows/mirror.yml
This PRs mirrors `master` both onto `2.8.x` and `2.9.x`.
It does so by adding a `matrix` strategy to the `mirror_job` job in the `mirror` workflow.
Prior to merging any PR with ABI and/or API break, the mirror to `2.8.x` should be disabled.
- *N/A*: Fast DDS test suite has been run locally. 
- *N/A*: New feature has been added to the …
> [16076] Mirror master onto both 2.8.x & 2.9.x

- .github/workflows/mirror.yml
- CMakeLists.txt
- package.xml
- versions.md
Bump version to  2.9.0:
Merge after:
* #3099 
- *N/A*: Fast DDS test suite has been run locally. 
- *N/A* Check CI results: changes do not issue any …
> [16076] Bump version to  2.9.0

- CMakeLists.txt
- package.xml
Signed-off-by: Audrow Nash <audrow@openrobotics.org>
> Bump to 2.6.3

- include/fastdds/rtps/attributes/ServerAttributes.h
List being written to the output stream was the one for unicast locators twice.
> Fixed list to read from

- .github/workflows/thread-sanitizer.yaml
TSAN Github workflow has started using Ubuntu 22.04. For some reason this is making the workflow fail consistently, maybe due to a higher CPU or disk load from the number of reports generated by a newer compiler.
This PR forces the usage of Ubuntu Focal for the Thread sanitizer workflow until a deeper investigation can be done on the issue.
- [NA] The code follows the style guidelines of this project. 
- [NA] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [NA] Fast DDS test suite has been run locally. 
- …
> [16488] Reverted OS version from ubuntu-latest to Ubuntu Focal

- examples/cpp/dds/ContentFilteredTopicExample/HelloWorld.cxx
- examples/cpp/dds/ContentFilteredTopicExample/HelloWorldTypeObject.h
- utils/scripts/update_generated_code_from_idl.sh
#3140 updated TypeSupports using the most recent Fast DDS-Gen release (v2.3.0).
This [script](https://github.com/eProsima/Fast-DDS/blob/master/utils/scripts/update_generated_code_from_idl.sh) automatically regenerates the TypeSupports and TypeObjects (if required).
ContentFilteredTopicExample IDL is not among the ones required to regenerate its TypeObject when it should not be so.
This PR updates the script and the TypeSupport and TypeObject.
- …
> [16440] Update ContentFilteredTopicExample TypeObject

- PLATFORM_SUPPORT.md
- RELEASE_SUPPORT.md
- roadmap.md
> [16440] Update Fast DDS roadmap, and release and platform support

- src/cpp/CMakeLists.txt
https://github.com/eProsima/Fast-DDS/pull/3136 introduced this bug by changing the generated manifest file location.
- NA Fast DDS test suite has been run locally.
> [16430] Manifest installation fix.

- src/cpp/fastdds/core/condition/WaitSetImpl.cpp
- test/unittest/dds/core/condition/WaitSetImplTests.cpp
This is a backport of #3194 to 2.6.x.
The backport cannot be performed automatically since the original PR has modifications on ReadConditionImpl, which was introduced on 2.7.1
> [16192] Fix notification lost <2.6.x>

- .github/pull_request_template.md
This PR adds a check to ensure the applicable backports are included in the PR description. trying to improve the code maintenance of supported releases.
**N/A** The code follows the style guidelines of this project. 
**N/A** New feature has been documented/Current …
> [16522] Add backports to PR checklist

- versions.md
Fast DDS v2.9.0 did not update correctly versions.md file.
**N/A** Commit messages follow the project guidelines. 
**N/A** The code follows the style guidelines of this project. 
**N/A** New feature has been documented/Current behavior is correctly described in the …
> Fix versions.md

- .github/workflows/sanitizer-tests.yaml
- [ N/A] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ N/A] Any new/modified methods have been properly documented using Doxygen. 
- [ N/A] Fast DDS test suite has been run locally. 
- [ N/A] Changes are ABI compatible. 
- [N/A ] Changes are API compatible. 
- [ N/A] Documentation builds and tests pass locally. 
- [ N/A] New feature has been added to the `versions.md` file (if applicable).
- [ N/A] New feature has been documented/Current behavior is correctly described in the documentation. 
- [N/A ] Applicable backports have been included in the description.
> Select Discovery Server branch on sanitizers action

- CMakeLists.txt
- package.xml
- [NA] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [NA] Fast DDS test suite has been run locally. 
- [NA] Documentation builds and tests pass locally. 
> [16801] Bump version to 2.6.4

- src/cpp/rtps/messages/MessageReceiver.cpp
This PR prevents using the `participant_` member of `MessageReceiver` when `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` is defined, since in that case the `MessageReceiver` is instantiated with `nullptr` for the participant.
- **N/A** Applicable backports have been included in the …
> [16810] Avoid null dereference on fuzzer

- CMakeLists.txt
- package.xml
Signed-off-by: Mikel Rico <mikelrico@eprosima.com>
- [N/A] Fast DDS test suite has been run locally. 
> [16802] Bump version to 2.9.1

- fastrtps.repos
- *N/A* Check CI results: failing …
> [16802] Fix versions in fastrtps.repos

- include/fastdds/dds/topic/Topic.hpp
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
In order to be able to call `get_inconsistent_topic_status` on Windows, it needs to have the `dllexport`/`dllimport` defined correctly.  In Fast-RTPS, this is done through the `RTPS_DllAPI` macro, which is added in this PR.
> Add Windows linkage to get_inconsistent_topic_status.

- configure.ac
- package.xml
Bump version to Fast DDS v2.1.3 in `2.1.x` branch.
**N/A** The code follows the style guidelines of this project. 
**N/A** Applicable backports have been included …
> [16904] Bump version to v2.1.3

- CMakeLists.txt
- package.xml
Bump Fast DDS version to v2.7.2
**N/A** The code follows the style guidelines of this project. 
**N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
> [16905] Bump version to v2.7.2

- Quality_Declaration_foonathan_memory.md
This PR updates Quality_Declaration_foonathan_memory.md updating the links to the currently used upstream release.
> [17123] Update foonathan_memory quality declaration

- src/cpp/rtps/writer/StatefulWriter.cpp
This PR improves compiler optimizations and dynamic memory usage by using functors instead of `std::function` for the parameter of `for_matched_readers`
> [17274] Using functors in StatefulWriter.cpp for_matched_readers

- .github/pull_request_template.md
Remove 2.7.x branch from Mergifyio suggestions on the PR template
- [NA] New feature has been documented/Current behavior is correctly described in the documentation. 
- [NA] Applicable backports have been included in the description.
> [17351] Remove 2.7.x branch from Mergifyio suggestions

- RELEASE_SUPPORT.md
Updating the release support document with the planned dates for the next release.
> Update RELEASE_SUPPORT with dates for 2.10.x

- .github/workflows/documentation-tests.yaml
> [17290] Fix Fast DDS docs CI when workflow dispatch event

- src/cpp/rtps/writer/StatefulWriter.cpp
- test/blackbox/common/BlackboxTestsAcknackQos.cpp
Moved block of code before calling flowcontroller::add_new_sample() avoiding the usage of a removed CacheChange_t pointer.
Fixes #3323.
> Fix crash when disable_positive_acks is enable and the remote reader is best-effort [17338]

- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
This test makes sure that the remote builtin endpoint configuration is honored, reducing the number of HEARTBEAT/ACKNACK messages being sent depending on the configuration.
@Mergifyio backport 2.9.x
> [17291] Add tests to check that remote builtin endpoints are honored

- PLATFORM_SUPPORT.md
- RELEASE_SUPPORT.md
- roadmap.md
- versions.md
This PR:
* Updates Fast CDR dependency to the latest release v1.0.27
* Updates Fast DDS roadmap
* Update Platform and Release support
- [N/A] Check CI results: changes do …
> [17830] Prepare for release v2.10.0

- examples/cpp/dds/DeadlineQoSExample/CMakeLists.txt
- examples/cpp/dds/DeadlineQoSExample/deadlinepayloadPubSubMain.cxx
@Mergifyio backport 2.9.x 2.8.x 2.6.x 2.1.x 
- **N/A**  New feature has been documented/Current behavior is correctly described in the documentation. 
> Fix asio dependency

- .github/workflows/thread-sanitizer.yaml
- PLATFORM_SUPPORT.md
Currently, the configured runner OS for the Thread Sanitizer Github Action is Ubuntu 20.04. This PR updates it to 22.04 and update GCC to version 12.1 (from the 11.3 default) to prevent several false positives triggered by the old version.
- [N/A] Applicable backports have been included in the …
> [17839] Update runner and GCC version for Thread Sanitizer job

- CMakeLists.txt
- RELEASE_SUPPORT.md
- package.xml
- versions.md
- [ N/A ] Check CI results: changes do not issue any warning.
- [ N/A ] Check CI results: failing tests are unrelated with the changes.
> [17983] Bump to version 2.10.1

- CMakeLists.txt
- package.xml
> [17831] Bump to 2.8.2

- fastrtps.repos
Versions in this branch are incorrectly pointing to master instead to the relevant versions for this branch's lifecycle.
> [17831] Fix 2.8.x branch fastrtps.repos versions

- .github/pull_request_template.md
- RELEASE_SUPPORT.md
This PR removes version 2.8.x from the supported branches.
> [17831] Removed 2.8.x from the supported platforms

- resources/xsd/fastRTPS_profiles.xsd
- test/system/tools/xmlvalidation/all_profile.xml
- test/system/tools/xmlvalidation/dataReader_profile.xml
Previous configuration would allow to include data writer QoS in data reader QoS XML configuration files. Those QoS from writer do not exist in the reader configuration.
The implemented solution is based on duplicating the QoS schema, keeping the complete one for the data writer entity, and the  new one (without `disable_heartbeat_piggyback` and `publishMode` QoS) has been assigned to the data reader.
XML test configuration files has been updated and test has passed locally.
> [18186] Update endpoint qos XML schema

- configure.ac
- package.xml
Version bump to 2.1.4
- [NA] The code follows the style guidelines of this project. 
- [NA] New feature has been documented/Current behavior is correctly described in the documentation. 
> [18438] Bump version to 2.1.4

- resources/xsd/fastRTPS_profiles.xsd
- test/system/tools/xmlvalidation/dataReader_profile.xml
- test/system/tools/xmlvalidation/dataWriter_profile.xml
There are four tags supported by XMLParser but not by XSD file. This PR fixes it. The tags are:
- TimeBasedFilterQos
- PreserntationQos
- DestinationOrderQos
- DurabilityServiceQos
> Support missing tags in XSD [17823]

- RELEASE_SUPPORT.md
2.1.x has reached EOL. This PR removes the **bold** font style that marked it as a supported branch.
- [NA] The code follows the style guidelines of this project. 
- [NA] New feature has been documented/Current behavior is correctly described in the documentation. 
- [NA] Applicable backports have been included in the description.
> [18436] Remove 2.1.x from the supported branches

- include/fastrtps/types/DynamicDataHelper.hpp
- src/cpp/dynamic-types/DynamicDataHelper.cpp
> Print output Dynamic Types inline

- src/cpp/dynamic-types/DynamicPubSubType.cpp
- src/cpp/fastdds/builtin/typelookup/common/TypeLookupTypes.cpp
- src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp
- src/cpp/rtps/transport/tcp/TCPControlMessage.cpp
- src/cpp/security/cryptography/AESGCMGMAC_Transform.cpp
This should fix #3422 by capturing all possible exceptions from Fast CDR in the places where Fast DDS is using it for (de)serialization.
> [18632] Capture all fastcdr exceptions

- examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationSubscriber.cpp
- examples/cpp/dds/BasicConfigurationExample/BasicConfigurationSubscriber.cpp
This PR solves an error affecting two examples, where topics are deleted before endpoints (using those topics). This issue has no further consequences in this particular case, but it is a malpractice that would lead to segfaults in other scenarios (e.g. intraprocess).
@Mergifyio backport 2.10.x 2.9.x 2.6.x 
> Examples fix: delete topic after endpoint

- test/performance/latency/LatencyTestPublisher.cpp
- [N/A] Commit messages follow the project guidelines. 
> Mod: correct the overhead time unit

- CMakeLists.txt
- package.xml
> [18917] Bump to version v2.6.5

- RELEASE_SUPPORT.md
- roadmap.md
- versions.md
This PR:
* Updates Fast CDR dependency to the latest release v1.1.0
* Updates Fast DDS roadmap.
* Updates Release support.
- [N/A] Check CI results: changes do not issue …
> [18911] Prepare for release v2.11.0

- examples/cpp/dds/AdvancedConfigurationExample/arg_configuration.h
Fix `--xml-profile` argument in `AdvancedConfigurationExample`.
> Fix AdvancedConfigurationExample --xml-profile option

- include/fastdds/dds/domain/DomainParticipantListener.hpp
> Add unsupported note to new ignore DomainPartListener callbacks

- versions.md
> [18910] Update versions.md

- src/cpp/utils/shared_memory/RobustInterprocessCondition.hpp
> Fix bug with SHM interoperability with previous versions

- roadmap.md
#3582 updated the roadmap but overlooked to update the date.
> [18910] Update roadmap date

- examples/cpp/dds/RequestReplyExample/Calculator.h
- examples/cpp/dds/RequestReplyExample/Calculator.idl
- examples/cpp/dds/RequestReplyExample/CalculatorClient.cpp
- examples/cpp/dds/RequestReplyExample/CalculatorServer.cpp
- *N/A*: Commit messages follow the project guidelines. 
> Fix spelling mistake: SUBSTRACTION to SUBTRACTION

- src/cpp/fastdds/core/policy/ParameterSerializer.hpp
Fix out-of-bounds access during deserialization of PID_PROPERTY_LIST.
- [NO] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- Has been confirmed to fix the issue in the security advisories
> [19116] Improve validation on PID_PROPERTY_LIST deserialization

- include/fastdds/statistics/rtps/monitor_service/interfaces/IConnectionsQueryable.hpp
- **N/A**  New feature has been documented/Current behavior is correctly described in the documentation. 
- **N/A**  Applicable backports have been included in the description.
> [18074] Bugfix/connection namespace

- CONTRIBUTING.md
corresponging -> corresponding
> [19089] Correct CONTRIBUTING.md typo

- include/fastdds/dds/core/status/StatusMask.hpp
Statistics Backend compilation with GCC13 fails due to missing includes. This PR adds the missing directive.
> [19171] Added missing cstdint include

- .github/pull_request_template.md
- .github/workflows/mirror.yml
- CMakeLists.txt
- RELEASE_SUPPORT.md
- package.xml
This PR makes master the develop branch for next minor release (2.12.0)
- **N/A** The PR has a milestone assigned.
- **N/A** Check CI results: failing tests are unrelated …
> Prepare branch out for 2.12.x

- CMakeLists.txt
- package.xml
- [N/A] The PR has a milestone assigned.
> [19217] Bump to version v2.9.2

- versions.md
> Remove merging conflicts tag from versions.md

- CMakeLists.txt
- RELEASE_SUPPORT.md
- package.xml
- versions.md
Related documentation PR: eProsima/Fast-DDS-docs#539
> [19324] Bump version to v2.6.6

- CMakeLists.txt
- package.xml
- versions.md
Related documentation PR: eProsima/Fast-DDS-docs#544
> [19325] Bump version to v2.11.2

- test/blackbox/common/BlackboxTestsDiscovery.cpp
Making RemoteBuiltinEndpointHonoring less flakey by explicitly checking the entity id of the heartbeats and acknacks sent.
> [19358] Fix RemoteBuiltinEndpointHonoring blackbox test

- CMakeLists.txt
- package.xml
- versions.md
Related documentation PR: eProsima/Fast-DDS-docs#547
> [19360] Bump version 2.10.2

- fastrtps.repos
> [19360] Fix versions on .repos

- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- include/fastdds/rtps/participant/RTPSParticipant.h
- include/fastdds/statistics/rtps/monitor_service/interfaces/IStatusQueryable.hpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
- test/mock/dds/Publisher/fastdds/dds/publisher/Publisher.hpp
- test/mock/rtps/BuiltinProtocols/fastdds/rtps/builtin/BuiltinProtocols.h
- test/mock/rtps/EDP/fastdds/rtps/builtin/discovery/endpoint/EDP.h
- test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
- test/mock/rtps/ReaderProxyData/fastdds/rtps/builtin/data/ReaderProxyData.h
- test/mock/rtps/SecurityManager/rtps/security/SecurityManager.h
- test/mock/rtps/TypeLookupManager/fastdds/dds/builtin/typelookup/TypeLookupManager.hpp
- test/mock/rtps/WLP/fastdds/rtps/builtin/liveliness/WLP.h
- test/mock/rtps/WriterHistory/fastdds/rtps/history/WriterHistory.h
- test/mock/rtps/WriterProxyData/fastdds/rtps/builtin/data/WriterProxyData.h
- test/unittest/rtps/discovery/CMakeLists.txt
- test/unittest/rtps/discovery/PDPTests.cpp
- test/unittest/statistics/dds/StatisticsDomainParticipantMockTests.cpp
- test/unittest/statistics/dds/StatisticsDomainParticipantMockTests/mock/statistics/fastdds/publisher/PublisherImpl.hpp
- test/unittest/statistics/rtps/CMakeLists.txt
- test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
> [18071] Update classes to implement interfaces

- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- include/fastdds/rtps/participant/RTPSParticipant.h
- include/fastdds/statistics/dds/domain/DomainParticipant.hpp
- include/fastdds/statistics/rtps/monitor_service/Interfaces.hpp
- include/fastdds/statistics/rtps/monitor_service/interfaces/IConnectionsObserver.hpp
- include/fastdds/statistics/rtps/monitor_service/interfaces/IProxyObserver.hpp
- include/fastdds/statistics/rtps/monitor_service/interfaces/IStatusObserver.hpp
- src/cpp/fastdds/core/policy/ParameterList.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/participant/RTPSParticipant.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/statistics/fastdds/domain/DomainParticipant.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.hpp
- test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
- test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
- test/unittest/rtps/discovery/PDPTests.cpp
This PR prepares the branch for the feature implementation. It introduces a refactor in the Monitor Service Interfaces and several fixes in the tests and deserialization methods.
As a follow up branch, it may not be compiling, but it is skipped 
- **N/A** Applicable backports have been …
> [19402] Prepare for the monitor service implementation

- .github/workflows/config/coverage.repos
- .github/workflows/config/default_ci.repos
- .github/workflows/config/nightly.repos
- .github/workflows/sanitizer-tests.yaml
- .github/workflows/statistics_coverage.yml
- .github/workflows/thread-sanitizer.yaml
- fastrtps.repos
After merging eProsima/Fast-CDR#156 which includes an API break upgrading Fast CDR to v2.0.0, Fast DDS nightly workflows are failing. Until #3828 is merged, this is going to keep happening. This PR modifies the Fast CDR dependency fixing it to 1.1.x branch instead of master.
- [N/A] New feature has been documented/Current behavior is …
> [19461] Fix Fast DDS nightly jobs

- .github/workflows/sanitizer-tests.yaml
- *N/A*: The PR has a milestone assigned.
- *N/A*: Check CI results: changes do not issue any warning.
- *N/A*: Check CI results: failing tests are unrelated with …
> [19461] Fix ASAN nightly jobs

- fastrtps.repos
- [N/A] Commit messages follow the project guidelines. 
> Fix .repos branches

- .github/workflows/mirror.yml
This PR depends on eProsima/eProsima-CI#25. Once this PR is merged and released, the branch of the create PR action must be updated previous to merging.
> [18503] Use eProsima-CI external actions for mirror workflow [WIP]

- include/fastdds/dds/core/policy/ParameterTypes.hpp
- test/unittest/dds/core/CMakeLists.txt
- test/unittest/dds/core/policy/CMakeLists.txt
- test/unittest/dds/core/policy/ParameterPropertyList.cpp
This PR fixes #1530. It also includes a regression test.
> [19208] Fix ParameterPropertyList increment operators

- tools/fds/CMakeLists.txt
We are already doing the check on the main CMakeLists.txt, and the removed code is making the OSS fuzz build fail
> Not checking for C++11 on fast-discovery-server CMakeLists.txt

- examples/cpp/dds/ContentFilteredTopicExample/HelloWorldTypeObject.cxx
- src/cpp/dynamic-types/AnnotationParameterValue.cpp
- src/cpp/dynamic-types/BuiltinAnnotationsTypeObject.cpp
- src/cpp/dynamic-types/DynamicTypeBuilderFactory.cpp
- src/cpp/dynamic-types/TypeIdentifier.cpp
- src/cpp/dynamic-types/TypeIdentifierTypes.cpp
- src/cpp/dynamic-types/TypeObject.cpp
- src/cpp/dynamic-types/TypeObjectFactory.cpp
- src/cpp/fastdds/builtin/common/RPCHeadersImpl.cpp
- src/cpp/fastdds/builtin/typelookup/TypeLookupManager.cpp
- src/cpp/fastdds/builtin/typelookup/common/TypeLookupTypes.cpp
- src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
- test/blackbox/types/HelloWorldTypeObject.cxx
- test/blackbox/types/TestIncludeRegression3361TypeObject.cxx
- test/blackbox/types/TestRegression3361TypeObject.cxx
- test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestTypeTypeObject.cxx
- test/unittest/dynamic_types/DynamicComplexTypesTests.cpp
- test/unittest/dynamic_types/idl/BasicTypeObject.cxx
- test/unittest/dynamic_types/idl/TestTypeObject.cxx
- test/unittest/dynamic_types/idl/new_features_4_2TypeObject.cxx
- test/unittest/xtypes/idl/TypesTypeObject.cxx
- test/unittest/xtypes/idl/WideEnumTypeObject.cxx
- test/xtypes/idl/TypesTypeObject.cxx
> Maintain xtypes serialization to previous encoding version to maintain interop [19625]

- RELEASE_SUPPORT.md
> Mark LTS releases on RELEASE_SUPPORT.md

- README.md
Including the `lastCompletedBuild/` statement in the badge, the README displays  the jenkins last completed build and avoid the `running` badge.
> [19728] Update README CI badges with last completed build (avoid 'running' case)

- include/fastdds/rtps/transport/PortBasedTransportDescriptor.hpp
> [19645] Fix doxygen

- CMakeLists.txt
- package.xml
This PR:
* Bumps the library version to v2.12.1
* Upgrades the Fast CDR submodule to v2.1.0
> [19860] Bump version to 2.12.1

- .github/workflows/documentation-tests.yaml
The doc CI trigger was wrongly set to push and PR events to 2.6.x branch
> [20023] Fix documentation CI branch

- .github/workflows/documentation-tests.yaml
Improve handling of events on Github docs CI
> [20022] Better handling of trigger events in docs CI

- .github/workflows/documentation-tests.yaml
- .github/workflows/reusable-windows-ci.yml
This PR:
1. Fixes the fallback branch for the gh docs CI
2. Fixes the selected .repos file for windows gh CI on push events to 2.12.x
> [20025] Fix branch selection on Github CI

- .github/workflows/documentation-tests.yaml
- .github/workflows/reusable-windows-ci.yml
- .github/workflows/sanitizer-tests.yaml
- .github/workflows/thread-sanitizer.yaml
This PR adds CCache to all CI jobs to speed up builds.
> [20055] Add CCache to all CI jobs

- include/fastdds/dds/xtypes/dynamic_types/AnnotationDescriptor.hpp
- src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
> New AnnotationDescriptor API [20115]

- src/cpp/utils/threading/threading_pthread.ipp
This little PR fixes the `set_affinity` call  when compiling for Android since `pthread_setaffinity_np()` is not exposed.
> [20117] Fix setaffinity directive for Android

- include/fastdds/dds/xtypes/dynamic_types/DynamicTypeMember.hpp
- include/fastdds/dds/xtypes/dynamic_types/MemberDescriptor.hpp
- include/fastdds/dds/xtypes/dynamic_types/VerbatimTextDescriptor.hpp
- include/fastdds/dds/xtypes/dynamic_types/detail/type_traits.hpp
- include/fastdds/dds/xtypes/dynamic_types/type_traits.hpp
- src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeMemberImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/MemberDescriptorImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/TypeDescriptorImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/VerbatimTextDescriptorImpl.hpp
> New DynamicTypeMember API [20136]

- include/fastdds/dds/xtypes/dynamic_types/DynamicType.hpp
- include/fastdds/dds/xtypes/dynamic_types/DynamicTypeMember.hpp
- include/fastdds/dds/xtypes/dynamic_types/Types.hpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeImpl.hpp
> New DynamicType API [20139]

- include/fastdds/dds/topic/TopicDataType.hpp
#4131 broke the compilation of Fast DDS Python tests. It seems on that project we have a problem when Fast DDS marks a method with `FASTDDS_TODO_BEFORE` an exported method with `RTPS_DllAPI`. This change must be included in:
* #4154
> [20055] Fix compilation of Fast DDS Python tests

- include/fastdds/dds/xtypes/dynamic_types/DynamicType.hpp
- include/fastdds/dds/xtypes/dynamic_types/DynamicTypeBuilder.hpp
- include/fastdds/dds/xtypes/dynamic_types/DynamicTypeMember.hpp
- include/fastdds/dds/xtypes/dynamic_types/Types.hpp
- src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeMemberImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/MemberDescriptorImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/TypeDescriptorImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/VerbatimTextDescriptorImpl.hpp
> New DynamicTypeBuilder API [20153]

- include/fastdds/dds/xtypes/dynamic_types/DynamicTypeBuilder.hpp
- include/fastdds/dds/xtypes/dynamic_types/DynamicTypeBuilderFactory.hpp
- include/fastdds/dds/xtypes/dynamic_types/Types.hpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/TypeDescriptorImpl.hpp
> New DynamicTypeBuilderFactory API [20158]

- include/fastdds/dds/core/Types.hpp
- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastrtps/types/TypesBase.h
> Move DDS types [20161]

- src/cpp/rtps/builtin/discovery/participant/simple/SimplePDPEndpointsSecure.hpp
This fixes a potential deadlock introduced by f2e5ceae8fbea0a6c9445a366faaca0b98a8ef86
Built on top of 
@Mergifyio backport 2.12.x 2.11.x 2.10.x
> [19770] Fix comparison in remove_from_pdp_reader_history

- CMakeLists.txt
- package.xml
This PR Bumps the Fast DDS version to `v2.13.1`
- **N/A**Any new/modified methods have been properly documented using Doxygen. 
- *N/A* Check CI results: failing tests are …
> [20176] Bump version to 2.13.1

- .github/pull_request_template.md
This PR updates the PR's contribution template
*  To check for PR's title and description correctness.
*  Update the backports list.
> [20215] Update PR checklist template. Backports and Description

- versions.md
Versions.md update was missing in previous Fast DDS v2.13.0 release. This PR includes those changes in the file, among with the incoming for v2.13.1
Related documentation PR: eProsima/Fast-DDS-docs#634
> [20176] Update versions.md

- include/fastdds/rtps/builtin/BuiltinProtocols.h
- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.hpp
- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.hpp
- src/cpp/fastdds/xtypes/type_representation/TypeIdentifierWithSizeHashSpecialization.h
- src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
- src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
- src/cpp/rtps/builtin/BuiltinProtocols.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/mock/rtps/BuiltinProtocols/fastdds/rtps/builtin/BuiltinProtocols.h
- test/mock/rtps/TypeLookupManager/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
- test/unittest/dds/status/ListenerTests.cpp
- test/unittest/rtps/discovery/PDPTests.cpp
> [20130] Implement TypeLookupManager async_get_type

- include/fastdds/dds/xtypes/dynamic_types/DynamicData.hpp
- include/fastdds/dds/xtypes/dynamic_types/DynamicDataFactory.hpp
- src/cpp/fastdds/xtypes/dynamic_types/DynamicDataFactoryImpl.hpp
- src/cpp/fastdds/xtypes/dynamic_types/DynamicDataImpl.hpp
> New DynamicData API [20168]

- CMakeLists.txt
- package.xml
- versions.md
This PR updates the required files to bump Fast DDS version to v2.10.3.
It also includes the forthcoming features as part of the version.
> [20023] Bump version to v2.10.3

- .github/workflows/nightly-windows-ci.yml
- .github/workflows/rebase-3.0.x-devel.yaml
This PR includes two CI jobs:
* Rebase nightly against master to ensure latest changes are included
* Windows nightly job ensuring that the branch keeps building with the latest changes
- [N/A] Applicable backports have been included in the …
> [19452] Include CI workflows for 3.0.x-devel branch

- .github/workflows/nightly-windows-ci.yml
- .github/workflows/rebase-3.0.x-devel.yaml
#4294 introduced 2 workflows to manage the transition to 3.0, one of them was not according to Github rules, and the other one was not fully correct; This PR fixes both of them.
- _N/A_: Applicable backports have been included in the …
> [19452] Fix 3.0.x workflows

- .github/workflows/rebase-3.0.x-devel.yaml
This PR fixes the 3.0.x rebase workflow adding the missing config required to push the changes after rebasing.
- _N/A_: Check CI results: changes do not issue any warning. …
> [19452] Fix 3.0.x rebase workflow

- .github/workflows/config/nightly.meta
- .github/workflows/reusable-windows-ci.yml
This PR prevents the Github actions windows CI from attempting to create a test report if the label `no-test` is set
> [20400] Test report action does not run when no-test label is set

- .github/workflows/config/nightly.meta
Quick fix for something that was overlooked in #4361 
- _N/A_ Check CI results: changes do not issue any warning.
- _N/A_ Check CI results: failing tests are …
> [20318] Add GTEST_INDIVIDUAL=ON to nightly meta 

- include/fastdds/rtps/attributes/ServerAttributes.h
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
> [19696] Fix data race on PDP

- .github/workflows/reusable-windows-ci.yml
Quick fix for something that was overlooked in #4361 
- _N/A_ Check CI results: changes do not issue any warning.
- _N/A_ Check CI results: failing tests are …
> [20318] Select correct repos for nightly build

- .github/workflows/reusable-windows-ci.yml
This PR adds a test summary to Github Windows CI
> [20442] Add test summary to Github Windows CI

- CMakeLists.txt
- package.xml
This PR Bumps the Fast DDS version to `v2.13.2`
> [20346] Bump version to v2.13.2

- CMakeLists.txt
- package.xml
- versions.md
This PR bumps Fast DDS version to v2.11.3 and updates `versions.md` with the introduced features.
> [20024] Bump to version v2.11.3

- test/blackbox/CMakeLists.txt
- test/blackbox/xfail_tests.cmake
#3971 introduced a new way of discovering the individual tests, which had the downside of loosing the `Blackbox*` prefix names; this PR restores those prefixes
> [20234] Restore Blackbox tests names

- fastrtps.repos
During 2.12.x branchout it seems that the `fastrtps.repos` file versions were not changed to the proper versions. Instead, they are all `master`
This PR updates those versions to the corresponding ones.
- **N/A** Applicable …
> [20485] Fix .repos versions

- CMakeLists.txt
- package.xml
- versions.md
This PR bumps the Fast DDS version to v2.13.3
> [20505] Bump version to v2.13.3

- .github/pull_request_template.md
- .github/workflows/config/default_ci_2.13.x.repos
- .github/workflows/config/nightly_2.13.x.repos
- .github/workflows/mac-ci.yml
- .github/workflows/mirror.yml
- .github/workflows/windows-ci.yml
- CMakeLists.txt
- package.xml
This PR bumps Fast DDS version to 2.14.0:
**IMPORTANT**: This PR needs to be rebased after merging:
* eProsima/Fast-DDS#4417
* eProsima/Fast-DDS#4442
> [20414] Bump version to 2.14.0

- .github/workflows/sanitizer-tests.yaml
…action
This pr remove `head_ref branch` for discovery-server in sanitizer-tests Github action.
> Remove head_ref branch for discovery_sevrer in Github action 

- fastrtps.repos
This PR set fixed versions in fastrpts.repos
> [20494] Set fixed versions in fastrpts.repos

- src/cpp/statistics/rtps/StatisticsBase.hpp
This PR is a partial backport of #4448 to add a missing virtual destructor.
> [20511] Add missing virtual destructor for StatisticsAncillary

- test/performance/video/CMakeLists.txt
- test/performance/video/VideoTestPublisher.cpp
- test/performance/video/VideoTestPublisher.hpp
- test/performance/video/VideoTestSubscriber.cpp
- test/performance/video/VideoTestSubscriber.hpp
- test/performance/video/VideoTestTypes.cpp
- test/performance/video/VideoTestTypes.hpp
- test/performance/video/main_VideoTest.cpp
This PR substitutes the old APIs with new ones in supports files for video performance tests.
> [20415] Update APIs in video performance tests 

- .github/workflows/nightly-mac-ci.yml
- .github/workflows/nightly-windows-ci.yml
In the PR improving the CI...
- #4480
... a matrix of Fast DDS branches (supported versions) was introduced in the nightly jobs.
That introduced the `fail-fast` strategy [default value](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures) (`true`) which makes nightly jobs fail if any of then fails.
This PR modifies that behaviour in favor of the intended behavior: run ALL nightlys independently.
- **N/A** …
> [20553] Fix nightly jobs

- fastrtps.repos
This PR changes dependency version to last patch in .repos file
> [20603] Upgrade dependency version to last patch version in .repos file

- fastrtps.repos
This PR removes idl parser from .repos file,  since it's downloaded when gradle fastddsgen.
- N/A Applicable backports have been included in the …
> [20603] Remove idl parser from .repos file

- RELEASE_SUPPORT.md
- roadmap.md
- versions.md
This PR updates both the roadmap and the release support in-repo documentation in preparation for v2.14.0
* Related docs PR: eProsima/Fast-DDS-docs#731
> [20644] Update roadmap and release support

- src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
- src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
This PR adds the Annotations when solving dependencies.
> [20565] Added Annotation dependencies

- fastdds.repos
This pr updates FastDDS and FastDDS-Gen versions in the .repos file  
- _N/A_: Check CI results: changes do not issue any warning.
- _N/A_: Check CI results: failing tests are unrelated …
> Update versions in fastdds.repos file

- .github/workflows/documentation-tests.yaml
This PR extends the `ubuntu-build-and-test-documentation` Github CI job to include Fast DDS Python in the build.
It also uses a new action from eProsima-CI to deduce which branch to use:
* eProsima/eProsima-CI#82
TODO:
> [20694] Build Fast DDS Python bindings in Fast DDS Docs Github CI job

- CMakeLists.txt
- package.xml
- versions.md
This PR bumps Fast DDS version to v2.13.4, and removes already implemented feature from versions.md
> [20723] Bump version to v2.13.4

- .github/workflows/nightly-sanitizers-ci.yml
This PR correctly sets branches for reusable-sanitizers-ci. Depends on:
* #4675 
* #4676 
* #4677
- _N/A_: Applicable backports have …
> [20848] Correctly set branches for reusable-sanitizers-ci

- CMakeLists.txt
- package.xml
- versions.md
This PR updates the required files to bump Fast DDS version to v2.6.8.
It also updates `versions.md`.
- _N/A_ Changes are ABI compatible. 
- _N/A_Applicable backports have been included in the description.
> [20824] Bump version to v2.6.8

- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/dds/publisher/DataWriter.hpp
- include/fastdds/dds/publisher/Publisher.hpp
- include/fastdds/dds/subscriber/DataReader.hpp
- include/fastdds/dds/subscriber/Subscriber.hpp
Changes in doxygen to fix warnings on documentation
> Changes in doxygen to fix warnings on documentation [20850]

- CMakeLists.txt
- package.xml
This PR bumps Fast DDS version to 2.14.1
> [20963] Bump version to 2.14.1

- fastrtps.repos
This pr updates .repos file for version 2.14.x
-_N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
- _N/A_ Applicable backports …
> [19452] Update repos file

- .github/workflows/reusable-mac-ci.yml
- .github/workflows/reusable-sanitizers-ci.yml
- .github/workflows/reusable-ubuntu-ci.yml
Windows github workflow is writing the hosts file so the tests using DNS can be run.
This PR writes the `/etc/hosts` file using `sudo tee -a ` on Ubuntu, Sanitizers, and Mac workflows.
> [20652] Add DNS entries to hosts files on github workflows

- CMakeLists.txt
- package.xml
- versions.md
Preparing for releasing v2.10.4, this PR bumps the version correspondingly.
> [20995] Bump version to 2.10.4

- .github/workflows/reusable-ubuntu-ci.yml
Fix for Shapes Demo fallback branch to 2.6.x, quick fix for #4847
- __NO__ Commit messages follow the project guidelines. 
- __NO__ The code follows the style guidelines of this project. 
- __NO__ New feature has been documented/Current …
> Set Fallback branch to 2.6.x

- CMakeLists.txt
- package.xml
- versions.md
This PR bumps the Fast DDS 2.13.x latest version to v2.13.5
**NOTE**: This PR must be merged right after:
- #4882
- **N/A** Applicable …
> [21100] Bump to v2.13.5

- src/cpp/rtps/messages/RTPSMessageGroup.cpp
This PR fix a warning introduced in the PR #4537 
- N/A Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
> Fix compilation warning

- README.md
This PR updates de Ubuntu CI nightly badge with the lately improved Github actions Ubuntu CI.
- **N/A** New feature …
> [21158] Update README.md with GitHub actions Ubuntu CI nightly

- src/cpp/utils/UnitsParser.hpp
A Ubuntu 24 issue in FastDDS compilation. This Pull Request fix the issue described.
- N/A Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
> Fix compilation in Ubuntu 24.04 platforms

- .github/pull_request_template.md
- README.md
- RELEASE_SUPPORT.md
This PR is a manual backport of the changes introduced in 
- #4990 
@Mergifyio backport 2.13.x 2.10.x 
- **N/A** New feature has been documented/Current behavior is …
> [21224] Update version support documentation (backport #4990)

- include/fastrtps/types/DynamicLoanableSequence.hpp
This PR updates a comment section that makes build fail in documentation jobs.
Note that the name of the PR branch is the same as the one failing in documentation:
- eProsima/Fast-DDS-Docs/pull/835 …
> [21256] Manual fix for documentation generation

- RELEASE_SUPPORT.md
> [21244] Update RELEASE_SUPPORT for `v2.6.9` release

- RELEASE_SUPPORT.md
This PR updates the 2.14 latest release in RELEASE_SUPPORT.md
- …
> [21311] Update 2.14 latest release in RELEASE_SUPPORT.md

- examples/cpp/custom_payload_pool/CMakeLists.txt
- examples/cpp/delivery_mechanisms/CMakeLists.txt
- examples/cpp/security/CMakeLists.txt
- examples/cpp/security/README.md
This PR fixes the installation the 3 examples that were not correctly installed:
* Security
* Custom payload pool
* Delivery mechanisims
At the end of the day, all examples should be installed under `<install_dir>/share/fastdds/examples/cpp`
- _N/A_: New feature has been added to the `versions.md` file (if …
> [21364] Fix installation of some examples

- examples/cpp/discovery_server/README.md
- examples/cpp/xtypes/README.md
hello world example section links (waitset subscriber and xml profile manager) section links was kept in some other examples README (which don't have those sections).
This PR removes those links
- **N/A** New feature has been added to the `versions.md` …
> [21495] Remove unexisting links in example READMEs

- RELEASE_SUPPORT.md
Update `RELEASE_SUPPORT.md` after 2.10.5 release
- _N/A_: …
> [21557] Update latest 2.10.x to 2.10.5

- UPGRADING.md
This PR restructures the migration changes from Fast DDS v2 to v3 into a comprehensive step-by-step guide to help users in updating their projects.
- N/A: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- N/A: Any new/modified methods have been properly documented using Doxygen. 
- N/A: Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- N/A: New feature has been added to the `versions.md` file (if applicable).
- N/A: New feature has been documented/Current behavior is correctly described in the documentation. 
- N/A: Applicable backports have been included in the description.
- **N/A** If this is a critical bug fix, backports to the …
> [21471] Convert Fast DDS v2 to v3 Migration Changes into a Step-by-Step User Guide

- .github/pull_request_template.md
- .github/workflows/mirror.yml
- .github/workflows/nightly-mac-ci.yml
- .github/workflows/nightly-sanitizers-ci.yml
- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/nightly-windows-ci.yml
- CMakeLists.txt
- package.xml
- src/cpp/rtps/messages/MessageReceiver.cpp
This PR bumps Fast DDS version to 3.1.0:
- _N/A_ If this is a critical bug fix, backports to the …
> Bump version to 3.1.0

- README.md
This PR adds references to new nightly jobs per supported branch in README
This PR is on top of (and should be merge after):
- #5292
@Mergifyio backport 3.0.x 2.14.x 2.10.x 2.6.x
**NOTE**: references to master should be updated in the backports to the corresponding branch name
- **N/A** New feature has been …
> [21790] Add references to new nightly jobs per supported branch in README

- RELEASE_SUPPORT.md
- roadmap.md
- versions.md
This PR updates the roadmap, release support and versions.md for preparing for `v3.1.0` release.
- **N/A** New feature has been documented/Current behavior is …
> [21783] Update roadmap, release support and versions for `v3.1.0` release

- README.md
This PR updates the Fast DDS README's commercial support section
@Mergifyio backport 3.0.x 2.14.x 2.10.x
- **N/A** New feature has been documented/Current behavior …
> [21890] Update commercial support section in readme

- .github/pull_request_template.md
- .github/workflows/mirror.yml
- .github/workflows/nightly-mac-3.1.x.yml
- .github/workflows/nightly-sanitizers-3.1.x.yml
- .github/workflows/nightly-ubuntu-3.1.x.yml
- .github/workflows/nightly-windows-3.1.x.yml
- CMakeLists.txt
- package.xml
This PR performs the branch out procedure from 3.1.x (current master) to 3.2.x (new master):
- Bump version
- Update mirror workflow to 3.2.x
- Include 3.1.x as supported branch for backporting improvements and fixes
- Add 3.1.x nightly workflows
- **N/A** Changes are API …
> [21882] Branch out 3.2.x

- RELEASE_SUPPORT.md
Update `RELEASE_SUPPORT.md` after 2.10.5 release
- _N/A_ Applicable …
> [21755] Update latest 2.10.x to 2.10.6

- README.md
Delate benchmark example from the README until it get completed. 
Also I updated the command to execute "hello_world" in the README to use the new version.
-  _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
-  _N/A_ Any new/modified methods have been properly documented using Doxygen. 
-  _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
-  _N/A_ New feature has been added to the `versions.md` file (if applicable).
> [21891] Correct examples on README

- RELEASE_SUPPORT.md
This PR updates the `RELEASE_SUPPORT.md` of `master` to `2.14.4`.
*Note: IDK if we should include backports we I have seen that we are not doing that for other releases.*
- **N/A** New feature has been added to the `versions.md` file (if …
> Refs #21560: Update `RELEASE_SUPPORT` ref to 2.14.4

- package.xml
This adds the [replace tag](https://www.ros.org/reps/rep-0149.html#replace-multiple) to the `package.xml` file so `fastrtps` package would be uninstalled when installing `fastdds`. …
> [22713] Add `replace` tag to `package.xml`

- CMakeLists.txt
- package.xml
- versions.md
Bumps Fast DDS's version to `v3.0.2`.
- __NO__ The code follows the style guidelines of this project. 
- __NO__ New feature has been documented/Current behavior is correctly described in the documentation. 
- __NO__ Applicable backports …
> [21627] Bump version to v3.0.2

- RELEASE_SUPPORT.md
This PR updates the `RELEASE_SUPPORT.md` of `master` to `3.0.2`.
- __N/A__ The code follows the style guidelines of this project. 
- __N/A__ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- __N/A__ Changes are API compatible. 
- __N/A__ New feature has been added to the `versions.md` file (if applicable).
- __N/A__ New feature has been documented/Current behavior is correctly described in the …
> [21627] Update `RELEASE_SUPPORT` ref to 3.0.2

- src/cpp/rtps/transport/TCPTransportInterface.cpp
@Mergifyio backport 3.1.x 2.14.x 
> Remove repeated header include & Fix log

- .github/workflows/weekly-ubuntu-2.6.x.yml
Ubuntu 20.04 image was removed since 15/04/2025, so 2.6.x weekly is failing …
> [21559] Upgrade 2.6.x weekly Ubuntu image to 22.04

- .github/workflows/nightly-windows-master.yml
This moves `SimpleCommunication` and `system` tests from unit to black-box tests in Windows nightly.
- __NO__: Commit messages follow the project guidelines. 
- _N/A_: Applicable backports have been included …
> Move `SimpleCommunication` and `system` tests in Windows nightly

- .github/pull_request_template.md
Now that we froze [2.10.7](https://github.com/eProsima/Fast-DDS/milestone/82), which will mark the EOL of 2.10.x, this removes it from the PR template comment regarding backports.
- _N/A_: New feature has been added to the `versions.md` file (if …
> [22188] Remove 2.10.x from PR template

- .github/pull_request_template.md
- .github/workflows/mirror.yml
- .github/workflows/nightly-mac-3.2.x.yml
- .github/workflows/nightly-sanitizers-3.2.x.yml
- .github/workflows/nightly-ubuntu-3.2.x.yml
- .github/workflows/nightly-windows-3.2.x.yml
This PR brings the branch out for 3.3.x including:
* Update mirror workflow to 3.3.x
* Include 3.2.x as supported branch for backporting improvements and fixes
* Add 3.2.x nightly workflows
*Note: Bumping project's version is left for the corresponding bump to 3.3.0*
- **N/A** …
> [23269] Branch out 3.3.x

- test/examples/windows/Dockerfile
This PR fixes the OpenSSL version in the windows docker image for example testing in `3.1.1`
@Mergifyio backport 3.2.x
> [23444] Install Fix OpenSSL version in windows example testing

- .github/pull_request_template.md
- .github/workflows/mirror.yml
- .github/workflows/nightly-mac-3.3.x.yml
- .github/workflows/nightly-sanitizers-3.3.x .yml
- .github/workflows/nightly-ubuntu-3.3.x.yml
- .github/workflows/nightly-windows-3.2.x copy.yml
- .github/workflows/nightly-windows-3.3.x.yml
- RELEASE_SUPPORT.md
Branchout 3.4.x
* Updated mergify backport versions to include 3.3.x
* Added nightly tasks for v 3.3.x to CI
* Mirrored main to 3.4.x
* Changed EOL for 2.16 to May 2027 in order to match ROS Humble 
- [ _N/A_] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ _N/A_] Any new/modified methods have been properly documented using Doxygen. 
- [ _N/A_] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [ _N/A_] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [ _N/A_] Changes are API compatible. 
- [ _N/A_] New feature has been added to the `versions.md` file (if applicable).
- [ _N/A_] New feature …
> [23515] Branch out 3.4.x

- test/blackbox/common/BlackboxTestsLivelinessQos.cpp
This PR increase the announcement period in liveliness QoS test. 
Failing test output: 
```
2025-07-22T12:12:18.4389161Z             Start   702: BlackboxTests_DDS_PIM.LivelinessQos/LivelinessQos.IndependentTopics_reliable/Transport
2025-07-22T12:12:18.4389564Z 
2025-07-22T12:12:18.4391059Z 702: Test command: D:\a\Fast-DDS\Fast-DDS\build\fastrtps\test\blackbox\RelWithDebInfo\BlackboxTests_DDS_PIM.exe "--gtest_filter=LivelinessQos/LivelinessQos.IndependentTopics_reliable/Transport" "--gtest_also_run_disabled_tests"
2025-07-22T12:12:18.4392445Z 702: Environment variables: 
2025-07-22T12:12:18.4392881Z 702:  CERTS_PATH=D:/a/Fast-DDS/Fast-DDS/src/fastrtps/test/certs
2025-07-22T12:12:18.4394248Z 702:  TOPIC_RANDOM_NUMBER=4096
2025-07-22T12:12:18.4395676Z 702:  W_UNICAST_PORT_RANDOM_NUMBER=5755 …
```
> Increase the announcement period in liveliness test

- test/blackbox/utils/filter_helpers.hpp
This PR fixes compatibility with Fasts CDRv1 after breaking it with #5764.
- _N/A_ Applicable backports have been included in the …
> [22814] Fix compatibility with Fast CDR v1

- PLATFORM_SUPPORT.md
- RELEASE_SUPPORT.md
- roadmap.md
- versions.md
Update documents related to version management.
- Related documentation PR: eProsima/Fast-DDS-docs#1143
- …
> [23520] Documentation updates for v3.4.0
