eProsima/Fast-DDS

- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- src/cpp/rtps/reader/WriterProxy.cpp
- src/cpp/rtps/reader/WriterProxy.h
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
- test/unittest/rtps/reader/WriterProxyTests.cpp
Because of #2282, several test started to fail in ROS2 CI. This is caused by a design decision: historical data is considered lost and therefore the user is warning. We decided to change this decision and start not considering historical data as lost. This PR performs the changes for that.
> Behaviour change: historical data is not considered lost

- CMakeLists.txt
Windows installer CI fails because **cURL** cannot be invoke from **CMake** (no current explanation for this because it works fine locally ... note curl is distributed as an os tool from windows 10 henceforth).
The installer CI is running CMake 17 thus we can use the **CMake** `file(DOWNLOAD )` command instead of calling **cURL**.
> [14849] Fixing CMakeLists.txt to avoid using curl (fails on windows installer ci

- src/cpp/security/cryptography/AESGCMGMAC_KeyExchange.cpp
This PR adds a missing header include for the `memcpy` function. Without that include, the build fails with GCC 12.
Unchecked items above are not applicable.
> Fix build failure with GCC 12 [14891]

- include/dds/topic/Topic.hpp
- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/dds/topic/Topic.hpp
- src/cpp/CMakeLists.txt
- src/cpp/fastdds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastdds/publisher/filtering/ReaderFilterCollection.hpp
- src/cpp/fastdds/topic/ContentFilteredTopicImpl.cpp
- src/cpp/fastdds/topic/ContentFilteredTopicImpl.hpp
- src/cpp/fastdds/topic/Topic.cpp
- src/cpp/fastdds/topic/TopicImpl.cpp
- src/cpp/fastdds/topic/TopicImpl.hpp
- src/cpp/fastdds/topic/TopicProxy.hpp
- src/cpp/fastdds/topic/TopicProxyFactory.cpp
- src/cpp/fastdds/topic/TopicProxyFactory.hpp
- test/blackbox/common/DDSBlackboxTestsFindTopic.cpp
- test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/dds/status/CMakeLists.txt
- test/unittest/statistics/dds/CMakeLists.txt
> [14615] Add implementation of DomainParticipant::find_topic

- include/dds/topic/Topic.hpp
- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/dds/topic/Topic.hpp
- src/cpp/CMakeLists.txt
- src/cpp/fastdds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastdds/publisher/filtering/ReaderFilterCollection.hpp
- src/cpp/fastdds/topic/ContentFilteredTopicImpl.cpp
- src/cpp/fastdds/topic/ContentFilteredTopicImpl.hpp
- src/cpp/fastdds/topic/Topic.cpp
- src/cpp/fastdds/topic/TopicImpl.cpp
- src/cpp/fastdds/topic/TopicImpl.hpp
- src/cpp/fastdds/topic/TopicProxy.hpp
- src/cpp/fastdds/topic/TopicProxyFactory.cpp
- src/cpp/fastdds/topic/TopicProxyFactory.hpp
- test/blackbox/common/DDSBlackboxTestsFindTopic.cpp
- test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/dds/status/CMakeLists.txt
- test/unittest/statistics/dds/CMakeLists.txt
This PR adds tests and implementation for DomainParticipant::find_topic.
> Add implementation of DomainParticipant::find_topic

- include/fastdds/rtps/transport/TCPTransportDescriptor.h
This PR adds the required API for later implementation of Server Name Indication (SNI).
> [15013] Add SNI API

- include/fastrtps/types/DynamicTypeMember.h
- include/fastrtps/types/TypeDescriptor.h
- src/cpp/dynamic-types/DynamicDataHelper.cpp
When used in plotjuggler fastdds plugin : https://github.com/eProsima/plotjuggler-fastdds-plugins
there has been a problem while using the Dynamic Types API in Windows because some methods does not have the dll support.
> [15007] Add dll support to Dynamic Types API

- include/fastdds/rtps/attributes/ServerAttributes.h
- include/fastdds/rtps/builtin/BuiltinProtocols.h
- src/cpp/CMakeLists.txt
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/builtin/BuiltinProtocols.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/ServerAttributes.cpp
- src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/utils/SystemInfo.cpp
- src/cpp/utils/SystemInfo.hpp
- test/blackbox/CMakeLists.txt
- test/dds/discovery/CMakeLists.txt
- test/unittest/dds/participant/CMakeLists.txt
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/statistics/dds/CMakeLists.txt
- test/unittest/statistics/rtps/CMakeLists.txt
- test/unittest/utils/SystemInfoTests.cpp
- thirdparty/filewatch/FileWatch.hpp
This PR must be merged after #2730.
This PR fixes Thread Sanitizer issues 4135 and its equivalents.
This deadlock is caused by having the PDP lock taken when iterating over the DiscoveryServer list calling `match_pdp_reader_nts_`, which in turn calls `matched_reader_add_`, locking the Writer lock.
As seen in previous Sanitizer issues, these two locks should be taken in reverse order: Writer first then PDP. When a participant is enabled, it takes the mutexes in the proper order, leading to a deadlock.
The deadlock occurs as follows:
`PDPServer::createPDPEndpoints` (A) -> `StatefulWriter::matched_reader_add` (B)
`PDPServer::announceParticipantState` (B) -> `PDPServer::announceParticipantState` (A)
Since the second pair of locks cannot be reversed due to the previous rule. to prevent this …
> [14833] DiscoveryServer list access deadlock fix <feature/tsan/fixes>

- fastrtps.repos
- include/fastdds/dds/core/status/SampleRejectedStatus.hpp
Signed-off-by: Ricardo González Moreno <ricardo@richiware.dev>
> Fix doxygen for SampleRejectedStatus

- src/cpp/utils/shared_memory/SharedMemWatchdog.hpp
`SharedMemWatchdog::exit_thread_` has a data race on destruction because it's accessed from the main thread. as easy as
promote it to atomic_bool.
> Fix SharedMemWatchdog datarace (issue 1049) [14916] <feature/tsan/fixes>

- include/fastdds/dds/subscriber/DataReader.hpp
- include/fastdds/dds/subscriber/ReadCondition.hpp
- src/cpp/CMakeLists.txt
- src/cpp/fastdds/subscriber/DataReader.cpp
- src/cpp/fastdds/subscriber/ReadCondition.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
- test/unittest/dds/subscriber/SubscriberTests.cpp
This PR adds the necessary changes to the public API in order to support ReadCondition.
> [14925] Add interfaces for ReadCondition

- src/cpp/utils/shared_memory/SharedMemWatchdog.hpp
`SharedMemWatchdog::exit_thread_` has a data race on destruction because it's accessed from the main thread. as easy as
promote it to atomic_bool.
Review and testing on: https://github.com/eProsima/Fast-DDS/pull/2761
> Fix SharedMemWatchdog datarace (issue 1049) [14916] <master>

- include/fastrtps/utils/DBQueue.h
- src/cpp/fastdds/log/Log.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/transport/shared_mem/SharedMemLog.hpp
Implement new methods in DBQueue class so it allows to move elements TO the queue and FROM the queue, avoiding copy of big objects.
Methods implemented:
- Push(T&&) move an element to the queue
- FrontAndPop() get the first element from the queue by moving it and remove it from the queue
> DBQueue move Push and Pop methods [14537]

- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastdds/rtps/attributes/EndpointAttributes.h
- include/fastdds/rtps/attributes/ExternalLocators.hpp
- include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
- include/fastdds/rtps/common/LocatorWithMask.hpp
- include/fastrtps/attributes/PublisherAttributes.h
- include/fastrtps/attributes/SubscriberAttributes.h
This PR adds `metatraffic_external_unicast_locators`, `default_external_unicast_locators`, and `ignore_non_matching_locators` to the participant configuration structures.
> [14630] Adding configuration data for external locators feature

- include/fastdds/dds/log/Log.hpp
- test/blackbox/common/BlackboxTestsLogConsumer.cpp
Current version of Shapes Demo does not compile on Windows due to un-exported Fast DDS LogConsomer functions. 
See the error below:
```
mainwindow.obj : error LNK2019: unresolved external symbol "protected: void __cdecl eprosima::fastdds::dds::LogConsumer::print_header(class std::basic_ostream<char,struct std::char_traits<char> > &,struct eprosima::fastdds::dds::Log::Entry const &,bool)const " (?print_header@LogConsumer@dds@fastdds@eprosima@@IEBAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEBUEntry@Log@234@_N@Z) referenced in function "public: virtual void __cdecl ShapesDemoLogConsumer::Consume(struct eprosima::fastdds::dds::Log::Entry const &)" (?Consume@ShapesDemoLogConsumer@@UEAAXAEBUEntry@Log@dds@fastdds@eprosima@@@Z) [C:\Users\eProsima\eProsima\shapesdemo\build\ShapesDemo\Shapes …
```
> Export required LogConsumer API on Windows platforms

- thirdparty/filewatch/FileWatch.hpp
> [15049] Fix duration cast on FileWatch

- src/cpp/rtps/writer/LivelinessManager.cpp
Conversation is located here: https://github.com/eProsima/Fast-DDS/pull/2794
Added missing protection during liveliness assertion. This may cause erroneous memory access in some cases.
> Added missing protection during liveliness assertion <master>

- src/cpp/rtps/builtin/data/WriterProxyData.cpp
The use of common proxy pools in the EDP management was generating issues due to the improper clean up of the proxies.
> [14681] Fixing WriterProxyData clear() method

- test/blackbox/CMakeLists.txt
CMake policies change no longer support the test command line including filters. Upgrade to the new syntax.
> Fix windows build with GTEST_INDIVIDUAL unset

- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.hpp
RTPS layer always reset `LivelinessLostStatus::total_changes` after calling the `on_liveliness_lost()` listener callback.
This PR fixes this adding its own `LivelinessLostStatus` to `DataWriterImpl`.
@Mergifyio backport 2.5.x
> Fix resetting of `LivelinessLostStatus::total_changes` [14984]

- CMakeLists.txt
- src/cpp/rtps/writer/LivelinessManager.cpp
fix:  liveliness core dump caused by omit mutex lock
> fix:  liveliness core dump caused by omit mutex lock

- include/fastdds/dds/subscriber/DataReader.hpp
- include/fastdds/rtps/reader/RTPSReader.h
- src/cpp/fastdds/subscriber/DataReader.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp
- src/cpp/rtps/reader/RTPSReader.cpp
- test/mock/rtps/RTPSReader/fastdds/rtps/reader/RTPSReader.h
- test/unittest/dds/subscriber/DataReaderTests.cpp
This PR adds an overload of `DataReader::get_unread_count` that receives a boolean indicating whether the unread changes should be marked as read.
This allows the application to implement a pattern where the number of newly available samples is obtained inside `on_data_available()`.
> [15118] Adding DataReader::get_unread_count (bool mark_as_read)

- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp
This PR highly improves the performance of read / take methods when the number of instances on a keyed topic is high.
The main ideas behind it are:
* Using iterators on ReadTakeCommand
* Using a specific collection for instances with available data on DataReaderHistory
This should fix #2779.
@mergifyio backport 2.6.x
> [15015] Improve read/take performance

- src/cpp/fastdds/core/policy/ParameterSerializer.hpp
- test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
- test/unittest/rtps/builtin/CMakeLists.txt
A parameter on a parameter list should not be considered invalid if its length is greater than expected.
This should fix interoperability issues like [this one](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1328)
Draft till we add a test
@Mergifyio backport 2.6.x
> [15155] Fixed validation on ParameterPropertyList_t

- src/cpp/rtps/reader/WriterProxy.cpp
- src/cpp/rtps/reader/WriterProxy.h
- src/cpp/rtps/writer/StatefulWriter.cpp
In lossy environments one participant can drop another one due to exceed the lease duration. We found that in the
process of rediscovering the dropped participant, the PDP works but the EDP could fail. The corner cases where this
could happen are:
1. First initial ACKNACK (preemptive ACKNACK) is lost and the remote EDP builtin datawriter not reload the information.
2. Initial ACKNACK is received, the remote EDP builtin datawriter answer with a HEARTBEAT, and this message is answered
with a normal ACKNACK which is lost. Never again a HEARTBEAT is sent.
To fix these corner cases this PR adds:
1. Send recursively the preemptive ACKNACK until a HEARTBEAT is received.
2. The reception of a preemptive ACKNACK causes sending a HEARTBEAT message but also restart the periodic heartbeat
event.
> Improve rediscovery on lossy environments [15165]

- src/cpp/rtps/reader/StatefulReader.cpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsDataSharing.cpp
Implementing Ownership it was detected this bug. A change removed by history (and not read yet by user) is not being
acked correctly.
This PR fixes this.
> Fix acknowledge in Datasharing

- include/fastdds/rtps/history/ReaderHistory.h
- src/cpp/rtps/history/CacheChangePool.cpp
Function `ReaderHistory::remove_changes_with_pred()` is using `std::remove_if` in a wrong way. According to the
standard `std::remove_if` uses moveable assigments and the returned iterators contains unexpected data.
But this function is used the returned iterators to release CacheChanges and it is releasing wrong ones.
This PR fixes this.
This PR also fixes issue #2533.
> Fix wrong usage of std::remove_if [15204]

- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
Accessing Topic pointer after deleting TopicProxy.
> Fix wrong pointer access [15227]

- test/unittest/security/authentication/BuiltinPKIDHTests.cpp
Fixes deprecation warnings on tests
> Quick fix warnings against openssl 3.0 [15225]

- include/fastrtps/xmlparser/XMLEndpointParser.h
- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- src/cpp/rtps/xmlparser/XMLEndpointParser.cpp
- test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
- test/mock/rtps/XMLEndPointParser/fastrtps/xmlparser/XMLEndpointParser.h
- test/unittest/dds/status/CMakeLists.txt
Adding tests to check_xml_static_discovery() and funtionality to loadXMLFile()
This PR adds a negative tets for each field in the XML files to be checked by DomainParticipantFactory::check_xml_static_discovery().
Also adds the posibility of using "flags" for XMLEndpointParser::loadXMLFile(std::string& filename). The string  could contain a filename (file://) or the XML content directly (data://), filename assumed if neither.
> [13824] Feature/check xml static discovery testing

- CMakeLists.txt
Quick hotfix for cmake versions under 3.17 (like focal and bionic provided ones).
`file(DOWNLOAD` is not able (on unix base platforms) to default to working dir if only a filename is provided.
> [14849] Fix file(DOWNLOAD) by providing a relative path

- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
- src/cpp/rtps/common/ChangeComparison.hpp
- src/cpp/rtps/history/ReaderHistory.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- test/unittest/rtps/history/ReaderHistoryTests.cpp
This PR implements calls to the new `on_data_available` callback of `rtps::ReaderListener`
> [15168] Notify changes in bulk on RTPS readers

- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
Currently, a trace with Error severity is shown during a change reception when trying to reserve a CacheChange but being unable to due so during to QoS constraints. This log trace should be a Warning instead, since there's no actual error, just expected behaviour. Also, modify the message shown so it better shows the actual issue.
@Mergifyio backport 2.6.x
> [15119] Clarified CacheChange reservation failure message

- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/dds/domain/DomainParticipantFactory.hpp
- include/fastdds/dds/publisher/DataWriter.hpp
- include/fastdds/dds/publisher/Publisher.hpp
- include/fastdds/dds/subscriber/DataReader.hpp
- include/fastdds/dds/subscriber/Subscriber.hpp
- include/fastdds/dds/topic/Topic.hpp
Addition of 'warning' indications in doxygen documentation in order to indicate which APIs are not implemented yet.
Edit: In order to merge with  [15158] ReadConditions Implementation #2872, some not-supporting warnings are removed in those methods that are implemented.
> [14686] Fix doxygen documentation to clearly state which API is unsupported

- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
This PR applies a fix detected in backport #2845.
> Fix datasharing ack when proxy is known

- include/fastdds/rtps/writer/ReaderLocator.h
- include/fastdds/rtps/writer/ReaderProxy.h
- src/cpp/rtps/writer/ReaderLocator.cpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- test/mock/rtps/ReaderLocator/fastdds/rtps/writer/ReaderLocator.h
> Fix datarace using writer's locator selectors [15289]

- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
This fix solves multiple dataraces in SharedMemGlobal.
> Add lock guard at changing SHM port listener status members [15261] 

- src/cpp/rtps/reader/WriterProxy.h
This fix solve the following issue: 
- Reading a private member of WriterProxy (last_heartbeat_count_) in perform_initial_ack_nack() while changing its value in process_heartbeat(....) function
> Set last_heartbeat_count_ private member of WriterProxy as atomic [15295]

- src/cpp/rtps/RTPSDomain.cpp
There was a datarace caused by deleting the builtinprotocols of the RTPSParticipant when it was being disabled while the same builtinprotocols were being updated by the file watcher. This fix prevents the file watcher from iterating over the participant being deleted by first removing it from the RTPSDomain participant list and subsequently disabling it.
> Disable RTPSParticipantImpl after removing it from RTPSDomain participants list [15313]

- src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/regressions/14456.xml
> [15315] Fix null dereference on eprosima::fastrtps::xmlparser::XMLParser::parseXMLBitsetDynamicType

- include/fastdds/rtps/RTPSDomain.h
- src/cpp/rtps/RTPSDomain.cpp
Some API is missing in order to create a RTPSWriter with a custom ChangePool
> Add API to createRTPSWriter with a custom change pool [14951]

- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
Fix spelling mistakes.
_I have no permission to add `skip-ci` label._
- *N/A*: Fast DDS test suite has been run locally. 
> Fix spelling mistakes.

- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/rtps/network/ReceiverResource.h
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastdds/publisher/PublisherImpl.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.cpp
- src/cpp/rtps/network/ReceiverResource.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
- test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
- test/unittest/dds/participant/ParticipantTests.cpp
Avoid data races on listener callbacks by:
- protecting DomainParticipantImpl getters and setters
- protecting RTPSParticipantImpl getters and setters
- Force ReceiverResource disable() method to wait for all concurrent callbacks.
> [15250] Fixing datarace on listener callbacks

- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
This should fix dataraces involving access to the listener on `RTPSReader` and `DataReaderImpl`.
> [15341] Protect access to reader listeners

- include/fastrtps/utils/fixed_size_string.hpp
- test/unittest/utils/FixedSizeStringTests.cpp
Updating generated code from IDL files with last fastddsgen version breaks the compilation of several tests because
`fixed_string` doesn't implement `std::string::compare`. This PR implements this function.
> Add std::string::compare API to fixed_string [15351]

- src/cpp/fastdds/subscriber/history/DataReaderInstance.hpp
- test/blackbox/common/BlackboxTestsPubSubHistory.cpp
This PR fixes a regression introduced in #2872 by avoiding the instance state to change when a writer is unmatched for an instance that has never been updated.
@Mergifyio backport 2.7.x
Fixes #2904
- Only `BlackboxTests_DDS_PIM.PubSubHistory` and `BlackboxTests_DDS_PIM.PubSubBasic` were checked on Windows
> [15375] Skip writer_removed processing for unaccounted instances

- include/fastdds/rtps/transport/TCPv4TransportDescriptor.h
- test/blackbox/common/BlackboxTestsTransportTCP.cpp
- versions.md
Add function to `TCPv4TransportDescriptor` to get the WAN address. 
- ❌ Fast DDS test suite has been run locally. 
> Get WAN address API in TCPv4 transport descriptors

- CMakeLists.txt
There is being used `target_link_options` in our CMakeLists.txt files which was incorporated in CMake 3.13. This PR
fixes the `cmake_minimum_required`.
> Fix cmake_minimum_required due to target_link_options [15378]

- include/fastdds/dds/core/policy/QosPolicies.hpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.hpp
- src/cpp/fastdds/publisher/PublisherImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/fastdds/subscriber/SubscriberImpl.cpp
- src/cpp/fastdds/topic/TopicImpl.cpp
- src/cpp/fastdds/topic/TopicImpl.hpp
- test/blackbox/common/BlackboxTestsPubSubHistory.cpp
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
- test/unittest/dds/topic/TopicTests.cpp
It is needed to verify the consistency of certain configurations of Resource Limits QoS policy when creating `dataReaders`, `dataWriters` and `Topics`. 
Those certain configurations are, when using instances, with parameters set as `max_samples < ( max_instances * max_samples_per_instance )`, in which case the creator should return `nullptr`.
Two unit tests has been created per each object creator, one for not keyed topic, and other for keyed topic. Then, new check rules have been added to each `check_qos()` method, in form of another method that extends it: `check_qos_including_resource_limits()`.
The two new rules cover, using instances, when `max_instances` or `max_samples_per_instance` are set to `inf` (`<= 0`), and max_samples not (`> 0`); and when `max_samples < ( max_instances * …
> [14958] Instance allocation consistency

- src/cpp/CMakeLists.txt
- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/publisher/PublisherImpl.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.cpp
- src/cpp/fastdds/utils/QosConverters.cpp
- src/cpp/fastdds/utils/QosConverters.hpp
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/dds/status/CMakeLists.txt
- test/unittest/statistics/dds/CMakeLists.txt
set_qos_from_attributes() are defined as static free functions. And there is the need to access them from outside the .cpp where they are defined.
This PR should satisfy the following:
- Provide a header and a source 
- Put the new files in src/cpp/fastdds/utils
- Add the free functions into the eprosima::fastdds::dds::utils namespace.
- The new functions cannot be static. We won't inline them either.
- Refactor usage of the functions.
- [N/A] New feature has been documented/Current behavior is correctly described in the …
> [15417] Group set_qos_from_attributes free functions into a separate file

- src/cpp/utils/IPFinder.cpp
Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>
Syscall param ioctl(SIOCGIFHWADDR) points to uninitialised byte(s): (valgrind)
```bash
root@tomoyafujita:~/ros2_ws/colcon_ws# valgrind --leak-check=full ./build/demo_nodes_cpp/talker
==207805== Memcheck, a memory error detector
==207805== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==207805== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==207805== Command: ./build/demo_nodes_cpp/talker
==207805==
==207805== Syscall param ioctl(SIOCGIFHWADDR) points to uninitialised byte(s)
==207805==    at 0x4F21AFF: ioctl (ioctl.c:36)
==207805==    by 0x5F984EE: eprosima::fastrtps::rtps::IPFinder::getAllMACAddress(std::vector<eprosima::fastrtps::rtps::IPFinder::info_MAC, …
```
> Syscall param ioctl(SIOCGIFHWADDR) points to uninitialised byte(s)

- cmake/common/gtest.cmake
- include/fastdds/rtps/attributes/ServerAttributes.h
- include/fastdds/rtps/common/LocatorList.hpp
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- test/CMakeLists.txt
- test/blackbox/CMakeLists.txt
- test/blackbox/common/BlackboxTestsDiscovery.cpp
- test/system/tools/fds/CMakeLists.txt
- test/system/tools/fds/tests.py
- test/unittest/dds/participant/CMakeLists.txt
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/utils/CMakeLists.txt
- thirdparty/optionparser/optionparser.hpp
- thirdparty/optionparser/optionparser/optionparser.h
- tools/fds/CMakeLists.txt
- tools/fds/server.cpp
- tools/fds/server.h
+ Now supports IPv6 addresses for UDP.
+ The DNS names can be decorated to specify which address family to use if IPv4 and IPv6 addresses are available.
+ Now IPv6 addresses can be specified at the cli.
+ DNS resolution supports IPv6 but available IPv4 addresses will take precedence for backward compatibility.
Testing has been updated to take into account IPv6 addresses.
Documentation https://github.com/eProsima/Fast-DDS-docs/pull/401
> [15482] UDPv6 support for fast-discovery-server tool and ROS_DISCOVERY_SERVER

- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
Signed-off-by: Mikel Rico <mikelrico@eprosima.com>
Fix for not getting logError in `filPublisherAttributes` call, when using statistics with EV or property policy `fastdds.statistics`
`logErrors` were printed when using EV for Statistics topics.
This comes from the PR https://github.com/eProsima/Fast-DDS/pull/2927/files#
The solution is to write the parameter for not printing those messages in those calls.
- [N/A] New feature has been …
> [15014] Fix for not logError in filPublisherAttributes call

- include/fastdds/rtps/common/EntityId_t.hpp
- include/fastdds/rtps/common/Guid.h
- include/fastdds/rtps/common/GuidPrefix_t.hpp
- test/unittest/rtps/common/CMakeLists.txt
- test/unittest/rtps/common/EntityIdTests.cpp
- test/unittest/rtps/common/GuidPrefixTests.cpp
- test/unittest/rtps/common/GuidTests.cpp
This PR improves the performance of `GUID_t::operator<`.
`GUID_t::operator<` is an operation highly used in Fast-DDS because of maps where GUID is key.
Changing the for comparison loop for `std::memcmp` (used from underly clases).
Some tests have been run manually* and the result is that `memcmp` tends** to be x10 faster.
\* using char[16] and checking time elapsed in 1000000 iterations
\** the time changes a lot if the different byte is the first or the last one, or one in the middle.
- Added methods `cmp` to GuidPrefix and EntityId, and used in `Guid::operator<`.
- Added tests for `cmp` methods and `operator<` methods that did not exist.
-
> [15611] Improve GUID_t operator< performance

- examples/cpp/dds/BasicConfigurationExample/BasicConfigurationPublisher.cpp
- examples/cpp/dds/BasicConfigurationExample/BasicConfigurationSubscriber.cpp
- examples/cpp/dds/BasicConfigurationExample/BasicConfiguration_main.cpp
- examples/cpp/dds/BasicConfigurationExample/arg_configuration.h
- examples/cpp/dds/HelloWorldExample/HelloWorld_main.cpp
Fixing the specific use case where the first argument is a flag (like `--transient`).
In that case, the mechanism that checks if the first argument is `publisher\subscriber` failed.
The changes are piggybacked to `DDSHelloWorldExample` that uses the same parsing strategy.
> [15212] hotfix of BasicConfigurationExample cli

- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
- test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
This PR adds protection to the `id_counter` access and modification inside the `preprocess_endpoint_attributes` function.
> [15652] Adding protection to id_counter access

- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- include/fastdds/rtps/common/Property.h
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- test/blackbox/common/DDSBlackboxTestsPropertyQos.cpp
- versions.md
PropertyQoS can be propagated with DATA(P) (as some of them already do) but it was not implemented.
With this new PR the Properties that are set as `propagate` will be added to the DATA(P) and sent through the network.
*NOTE:* This could be generalized for Participant Type and/or physical data, that would make more sense than adding them ad hoc. I wait for Fast DDS team feedback to do it. 
Related documentation PR: eProsima/Fast-DDS-docs#405
> Propagate PropertyQoS if it set in property

- include/fastdds/dds/publisher/qos/WriterQos.hpp
- include/fastdds/dds/subscriber/qos/ReaderQos.hpp
- src/cpp/rtps/xmlparser/XMLElementParser.cpp
- test/unittest/xmlparser/XMLElementParserTests.cpp
- test/unittest/xmlparser/wrapper/XMLParserTest.hpp
- versions.md
This PR Adds the possibility to configure Ownership and Ownership Strength QoS from XML.
This PR covers the following tasks:
- Creation of two new tests, to check the configuration of Ownership and Ownership Strength QoS in XML profile.
- Uncomment the already developed functions `getXMLOwnershipQos()` and `getXMLOwnershipStrengthQos()`.
- Arrange the correct call to those two methods from `getXMLWriterQosPolicies()`.
- Erase previous logs and comments that stated ownership was not supported.
Related documentation PR: eProsima/Fast-DDS-docs#403 (PR)
> [15628] XML configuration for Ownership QoS

- include/fastdds/dds/domain/DomainParticipantFactory.hpp
- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
This PR addresses #2537 by adding a new API on `DomainParticipantFactory` that returns a shared pointer, and making the old API call the new one and return the raw pointer inside the shared one.
> [15321] Adding DomainParticipantFactory::get_shared_instance() API

- test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
This PRs corrects an initialization order warning in DomainParticipantImpl
> [15600] Correct initialization order warning in DomainParticipantImpl mock

- include/fastdds/dds/subscriber/DataReader.hpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
The `DataReader` header only includes a forward declaration of `ReadCondition`.
The following code:
```c++
// create condition
auto cond = reader->create_readcondition(ANY_SAMPLE_STATE, ANY_VIEW_STATE, ALIVE_INSTANCE_STATE);
// attach to the corresponding wait set
wait_set.attach_condition(*cond);
```
will fail with the message:
+ GCC `error: cannot convert 'ReadCondition*' to 'Condition*' in initialization`
+ MSVC `error C2440: 'initializing': cannot convert from 'ReadCondition *' to 'Condition *`
The `DataReader` header must include the definition of `ReadCondition`.
The `ReadCondition` blackbox testing works now without including the `ReadCondition` header.
> Refs 15852: Fixing ReadConditions missing header on DataReader header

- test/unittest/statistics/dds/StatisticsQosTests.cpp
- test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
This PR fixes a regression in `StatisticsQosTests.StatisticsDataWriterQosTest` introduced by #2998 , and also a linking problem in `RTPSStatisticsTests` on Windows 
> [15897] Fix StatisticsQosTests & RTPSStatisticsTests fixture linking

- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/rtps/flowcontrol/FlowControllerImpl.hpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSBlackboxTestsBasic.cpp
This PR fixes a segmentation fault that may arise when calling `RTPSParticipantImpl::createWriter` on the same participants in parallel from different threads.
@Mergifyio backport 2.7.x 2.6.x 2.3.x 2.1.x
> [15905] Fix dataraces when creating DataWriters

- src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/regressions/15344.xml
bugfix Null Dereference in parseXMLEnumDynamicType. Added corresponding test.
@Mergifyio backport 2.7.x 2.6.x 2.3.x 2.1.x
**N/A** New feature has been documented/Current behavior is correctly described in the documentation.
> [15970] Fix null Dereference Parse XML Enum Dynamic Type

- include/fastdds/rtps/writer/StatefulWriter.h
- src/cpp/rtps/writer/StatefulWriter.cpp
- test/blackbox/common/RTPSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSWithRegistrationReader.hpp
- test/blackbox/common/RTPSWithRegistrationWriter.hpp
When using separate sending, in the event of a change with a sequence number lower than the last one being no longer available in the Writer History a GAP was not being properly sent. This leads to the Reader and Writer being stuck on a cycle of HEARTBEATs and ACKNACKs that request the missing change.
> [15915] Send GAPs correctly when using separate sending

- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
- test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
- test/mock/dds/Publisher/fastdds/dds/publisher/Publisher.hpp
> Add fixes to tests for ASAN

- examples/cpp/dds/BasicConfigurationExample/BasicConfigurationPublisher.cpp
- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
- test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
- test/unittest/statistics/dds/StatisticsDomainParticipantTests.cpp
If compiled with statistics, when a participant calls delete_contained_entities() followed by a call to Factory::delete_participant(), a SegFault was produced.
Proposed solution changes:
Making ParticipantImpl delete_contained_entities() virtual so that the statistics participant can set the builtin_publishers to nullptr. 
@Mergifyio backport 2.7.x 2.6.x 2.3.x
> [16038] Fix SegFault in delete_contained_entities() when compiled with statistics

- test/blackbox/common/RTPSBlackboxTestsBasic.cpp
- test/dds/communication/PublisherModule.cpp
Small PR that fixes a memory leak of an object created in test and never destroyed.
> Fix memory leak in tests [15996]

- test/mock/rtps/StatefulReader/fastdds/rtps/reader/StatefulReader.h
> Remove getGuid implementation in StatefulReader mock

- src/cpp/rtps/flowcontrol/FlowControllerFactory.cpp
This should fix building with old compilers that cannot deduce they should use the move constructor of unique_ptr.
@Mergifyio backport 2.7.x 2.6.x
> [15997] Construct with decltype when inserting to map on FlowControllerFactory

- .github/workflows/asan.yml
- include/fastdds/rtps/participant/ParticipantDiscoveryInfo.h
- include/fastdds/rtps/transport/ChainingTransport.h
- src/cpp/rtps/transport/ChainingTransport.cpp
- test/blackbox/common/BlackboxTests.cpp
- test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
- test/unittest/dds/participant/CMakeLists.txt
- test/unittest/dds/participant/ParticipantTests.cpp
> Fix ASAN errors in API tests [15965]

- include/fastdds/dds/subscriber/DataReader.hpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
DataReader APIs rely on `DataReaderImpl::read_or_take()'  method:
```
ReturnCode_t read( LoanableCollection& data_values, SampleInfoSeq& sample_infos,...)
return read_or_take(data_values, sample_infos, max_samples, HANDLE_NIL,
sample_states, view_states, instance_states, false, false, false);
ReturnCode_t read_instance( LoanableCollection& data_values, SampleInfoSeq& sample_infos, ...)
return read_or_take(data_values, sample_infos, max_samples, a_handle,
sample_states, view_states, instance_states, true, true, false);
ReturnCode_t read_next_instance( LoanableCollection& data_values, SampleInfoSeq& sample_infos, ...)
return read_or_take(data_values, sample_infos, max_samples, previous_handle,
sample_states, view_states, …
```
> [16042] Fixing read/take_next_instance

- include/fastdds/rtps/resources/TimedEvent.h
- src/cpp/rtps/reader/WriterProxy.cpp
- src/cpp/rtps/reader/WriterProxy.h
- src/cpp/rtps/resources/TimedEvent.cpp
- test/mock/rtps/TimedEvent/fastdds/rtps/resources/TimedEvent.h
- test/unittest/rtps/resources/timedevent/TimedEventTests.cpp
- test/unittest/rtps/resources/timedevent/mock/MockEvent.cpp
- test/unittest/rtps/resources/timedevent/mock/MockEvent.h
This reverts commit 3e0d1d6f5e0200ef66228d0adec97d0c1d1117bc because it has introduced the possibility of a deadlock.
We should reintroduce the changes in the near future with an additional test that reliably reproduces the original issue.
> Revert changes from #3046

- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
- src/cpp/rtps/builtin/data/ProxyDataFilters.hpp
- src/cpp/rtps/builtin/data/ReaderProxyData.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
- src/cpp/rtps/network/ExternalLocatorsProcessor.cpp
- src/cpp/rtps/network/ExternalLocatorsProcessor.hpp
- src/cpp/utils/Host.hpp
- test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
This PR fixes some corner cases for the communication between containers on different hosts when discovered using the external locators feature.
> [16133] Fix corner cases on external locators selection

- CMakeLists.txt
- cmake/common/gtest.cmake
- cmake/modules/check_shared_mutex_priority.cpp
- include/fastrtps/utils/ProxyPool.hpp
- include/fastrtps/utils/shared_mutex.hpp
- src/cpp/CMakeLists.txt
- src/cpp/rtps/history/TopicPayloadPool.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/unittest/utils/CMakeLists.txt
- test/unittest/utils/shared_mutex_tests.cpp
The C++ standard requirements for `shared_mutex` do not specify if exclusive lock operation should preempt the shared lock one. Posix allows both behaviors but defaults to not preempting shared locks. STL implementations are split on this subject:
- Windows, boost ->  preemption (`PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP`)
- Linux, Mac -> not preemption (` PTHREAD_RWLOCK_PREFER_READER_NP`)
In order to prevent deadlock scenarios:
- out third party implementation avoids preemption.
- if the framework's defaults to preemption the third party is forced.
- code checks used to avoid deadlock on the preemption scenario have been removed.
Documentation: https://github.com/eProsima/Fast-DDS-docs/pull/413
- [] NA New feature has been added to the `versions.md` file (if applicable).
> [15766] Update shared_mutex thirdparty to don't prioritize writers

- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/topic/TopicProxyFactory.cpp
- src/cpp/fastdds/topic/TopicProxyFactory.hpp
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/publisher/PublisherTests.cpp
When registering a Type and when creating a Topic, a type name is requested.
However, this type name is not used in Topic creation because it uses internally the type name of the type support, that can actually not be the same as the type name that was registered.
Simple regression test has been uploaded in commit a393cf71424e57a076ccab8931703b1afdac022a that fails before the fix, and passes afterwards.
- NA New feature has been added to the `versions.md` file (if applicable).
- NA New feature has been documented/Current behavior is correctly described in the documentation.
> Fix bug in Topic creation with differfent Type Name [16242]

- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
Configuring a participant with `ignoreParticipantFlags = FILTER_DIFFERENT_HOST | FILTER_DIFFERENT_PROCESS`, and another one with the default configuration `ignoreParticipantFlags = FILTER_NONE` results in HEARTBEAT and ACKNACK messages sent to the multicast address and port for the builtin endpoints.
This PR fixes that situation by:
1. Make participants that only want intraprocess communications to not announce locators
2. Always ignore participants without locators when they are not on the same process.
As a bonus, participants that only want intraprocess communications set multicast TTL to 0 (so their announcements do not leave the host) and avoids creating the SHM transport.
@Mergifyio backport 2.7.x 2.6.x 2.1.x
- *N/A* Any new/modified methods have been properly documented using …
> [16277] Fix communication with asymmetric ignoreParticipantFlags

- test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
It seems #3105 made the black-box tests for the old API fail to build.
- Just checked locally that it builds
> Added ignore_participant_flags() to Blackbox_FastRTPS PubSubReader.

- include/fastdds/rtps/resources/ResourceEvent.h
- src/cpp/rtps/resources/ResourceEvent.cpp
- test/blackbox/common/BlackboxTestsSecurity.cpp
- test/certs/governance_helloworld_disable_liveliness.smime
- test/certs/governance_helloworld_disable_liveliness.xml
- test/unittest/rtps/resources/timedevent/TimedEventTests.cpp
When a participant compiled WITH_SECURITY checks for the liveliness of a matched remote participant (served in the event_service() of Resource Manager), and this one has expired, security_manager tries to remove the remote participant proxy data, which, in turn, destroys AuthInfo; within its destructor, the destruction of timedEvent is performed with the subsequent unregister_timer() call into ResourceManager. At this point there is a deadlock when evaluating the condition variable for accessing the collection as it is the same execution thread.
Proposed solution changes:
Grant timer collections access to the execution thread within unregister_events(). Prevent  active_timers collection from iterator invalidation.
@Mergifyio …
> [16271] Fix Deadlock in remove_participant (ResourceEvent thread) when compiled WITH_SECURITY

- src/cpp/rtps/transport/UDPTransportInterface.h
- test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
- test/blackbox/common/BlackboxTestsPubSubBasic.cpp
- test/unittest/transport/UDPv4Tests.cpp
- test/unittest/transport/UDPv6Tests.cpp
This PR covers the fix of the following tests:
- BlackboxTests_DDS_PIM.PubSubBasic.ReceivedPropertiesDataWithinSizeLimit.Transport (Failed)
- BlackboxTests_DDS_PIM.PubSubBasic.ReceivedPropertiesDataWithinSizeLimit.Intraprocess (Failed)
- BlackboxTests_DDS_PIM.PubSubBasic.ReceivedPropertiesDataWithinSizeLimit.Datasharing (Failed)
- UDPv4Tests.send_to_wrong_interface (Subprocess aborted)
- UDPv6Tests.send_to_wrong_interface (Subprocess aborted)
> Fix failed tests when compiling with statistics enabled

- include/fastdds/rtps/participant/RTPSParticipant.h
- include/fastdds/rtps/reader/RTPSReader.h
- include/fastdds/rtps/writer/RTPSWriter.h
- include/fastdds/statistics/rtps/StatisticsCommon.hpp
- src/cpp/rtps/participant/RTPSParticipant.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/rtps/reader/RTPSReader.cpp
- src/cpp/rtps/writer/RTPSWriter.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantStatisticsListener.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantStatisticsListener.hpp
- src/cpp/statistics/rtps/StatisticsBase.cpp
- src/cpp/statistics/rtps/StatisticsBase.hpp
- src/cpp/statistics/rtps/reader/StatisticsReaderImpl.cpp
- src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
- test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
- test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
- versions.md
This PR prevents the calculation of any statistics measurements if the corresponding DataWriter is not enabled.
> [16284] Avoid statistics calculations for not enabled statistics DataWriters

- test/unittest/statistics/dds/StatisticsQosTests.cpp
This PR intends to fix the StatisticsQosTests windows linkage issue. In addition, it fixes a test that tried to read a second xml profiles file with some profiles names shared with the first one, consequently, it was being ignored because of the bool flag default_xml_profiles_loaded in DomainParticipantFactory.
Proposed solution: Change the usage of ParticipantImpl to Participant (user api) to prevent linkage problems and unify all xml profiles from both files into a single one.
**N/A** New feature has been added to the …
> [16362] Fix Windows StatistisQosTests.cpp linkage and Failed test

- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
When calling `DomainParticipantFactory::get_participant_qos_from_profile`, if the profile is not found, `XMLProfileManager` outputs an error log. However, the function already returns a `RETCODE_BAD_PARAMETER` so the log is not really required.
-  **N/A** Any new/modified methods have been properly documented using Doxygen. 
-  **N/A** New feature has been added to the `versions.md` file (if applicable).
-  **N/A** New feature has been documented/Current behavior is correctly described in the documentation.
> [14758] Disable XMLProfileManager error when Participant profile is not found

- src/cpp/CMakeLists.txt
Addresses issue: https://github.com/eProsima/Fast-DDS/issues/3131
- NA Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- NA Any new/modified methods have been properly documented using Doxygen.
> [16430] Fixing CMake for Fast-DDS use as submodule

- CMakeLists.txt
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/statistics/rtps/StatisticsBase.cpp
- src/cpp/statistics/rtps/reader/StatisticsReaderImpl.cpp
- src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
- test/blackbox/api/dds-pim/PubSubParticipant.hpp
- test/unittest/statistics/dds/StatisticsQosTests.cpp
- versions.md
Signed-off-by: Mikel Rico <mikelrico@eprosima.com>
Set FASTDDS_STATISTICS CMake option to ON
- [N/A] Fast DDS test suite has been run locally. 
Related documentation PR: [eProsima/Fast-DDS-docs# (PR) ](https://github.com/eProsima/Fast-DDS-docs/pull/430)
> [16328] Set FASTDDS_STATISTICS CMake option to ON

- include/fastdds/rtps/common/Time_t.h
- src/cpp/rtps/common/Time_t.cpp
- test/unittest/rtps/common/CMakeLists.txt
- test/unittest/rtps/common/TimeTests.cpp
There is an error in Time_t operator >> when there are not 9 digits in the nanoseconds value (after `.`).
Also Time_t operators raised warnings when compiled in APEX performance test repository (basically, when used).
After merged, backport to 2.0.x
> Time t operators [10652]

- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/statistics/rtps/StatisticsBase.cpp
- src/cpp/statistics/rtps/StatisticsBase.hpp
- test/unittest/statistics/rtps/RTPSStatisticsTests.cpp
This PR fixes a behaviour in which endpoints created after setting the enabled_writers_mask where not receiving such mask and so they were not publishing statistical data.
> [16440] Set enabled statistics writers mask on new endpoints

- include/fastdds/dds/domain/DomainParticipant.hpp
- src/cpp/fastdds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
- test/unittest/dds/participant/ParticipantTests.cpp
Related to #3040 
This PR modifies the current behaviour of `DomainParitcipant::set_listener`, so that for it to proceed no callbacks should be on execution at that moment. This would prevent the following situation: user sets participant's listener to `nullptr` and destroys the object (listener), while `DomainParticipantImpl::MyRTPSParticipantListener` is about to invoke participant's listener callback (obtained reference was still not `nullptr`), hence resulting in undefined behaviour.
> Protect DomainParticipant set_listener [16040]

- include/fastdds/rtps/reader/StatefulReader.h
- include/fastdds/rtps/resources/TimedEvent.h
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/WriterProxy.cpp
- src/cpp/rtps/reader/WriterProxy.h
- src/cpp/rtps/resources/TimedEvent.cpp
- test/mock/rtps/StatefulReader/fastdds/rtps/reader/StatefulReader.h
- test/mock/rtps/TimedEvent/fastdds/rtps/resources/TimedEvent.h
- test/unittest/rtps/history/CMakeLists.txt
- test/unittest/rtps/reader/CMakeLists.txt
- test/unittest/rtps/reader/WriterProxyStopTest.cpp
- test/unittest/rtps/reader/WriterProxyTests.cpp
- test/unittest/rtps/resources/timedevent/TimedEventTests.cpp
- test/unittest/rtps/resources/timedevent/mock/MockEvent.cpp
- test/unittest/rtps/resources/timedevent/mock/MockEvent.h
This PR is a revision of #3046, in which the data race between `WriterProxy::stop` and `perform_initial_acknack` was addressed by forcing the thread invoking the former to wait for the completion of the latter. However, a deadlock may occur as the reader waiting for the event to end does so with `Endpoint::mp_mutex` locked, which is also locked when sending an acknack at `perform_initial_acknack`.
Two different solutions are suggested:
- Introducing a new mutex in `StatefulReader` which is taken before reader's, and released after modifying the writer proxy's state and before waiting for the executing event to finish.
- Releasing reader's mutex before stopping a `WriterProxy`, and locking it again after doing so. This solution implies that `StatefulReader::matched_writer_add` and …
> Fix datarace on WriterProxy stop while TimedEvent being triggered [16341]

- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemLog.hpp
- src/cpp/utils/shared_memory/SharedMemSegment.hpp
- test/unittest/transport/SharedMemTests.cpp
- test/unittest/transport/mock/SharedMemGlobalMock.hpp
Thread sanitizer reports a data race when attempting to create a boost's named_mutex for the same port from different threads (in the same process). This situation occurs, for example, when a two participants in the same process discover another one from a different process at the same time. Both attempt to create and lock a named_mutex corresponding to the same port (remote participant's) through boost library, which seems not to be thread safe according to thread sanitizer. Likewise, opening and creating a named_mutex for the same port from different threads results in a data race being reported. Same goes for destroying and opening/creating a named_mutex.
This PR attempts to solve this data race by protecting the creation/destruction of a named_mutex with a static mutex in …
> Protect creation/destruction of boost's named_mutex [16273]

- src/cpp/rtps/builtin/liveliness/WLP.cpp
- test/blackbox/api/dds-pim/PubSubWriterReader.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubWriterReader.hpp
- test/blackbox/common/BlackboxTestsLivelinessQos.cpp
There is a classic ABBA lock between the two participants' PDP mutexes due to the intraprocess scenario.
The threads deadlock are the participants' event threads (in this trace 49 and 42). The event that triggers the deadlock
is WLP announcement.
The deadlock in the main thread takes place on participants' writer destruction. The writer's destructor must unregister
it's timers and that can only take place once the writer's participant event thread is idle (been deadlock never gets
idle).
A new test able to reproduce this situation was introduced.
> [16166] Fixing deadlock in WLP

- test/communication/CMakeLists.txt
- test/communication/secure_ds_pubsub_secure_crypto_communication.py
- test/communication/secure_ds_simple_secure_msg_crypto_pub.xml
- test/communication/secure_ds_simple_secure_msg_crypto_sub.xml
- test/communication/secure_simple_ds_server.xml
Adds a (failing) system test with three (secure) participants:
* A discovery server started with the CLI tool
* A client with a DataWriter
* A client with a DataReader
The test expects the DataReader should receive samples from the DataWriter.
- Only the added test have been checked to fail
> [16499] Adding system test for secure discovery server

- CMakeLists.txt
Since CCache 4.6.1, Visual Studio is supported. But for Debug and RelWithDebugInfo build types, `ccache` needs the compilation option `Z7` instead of `Zi`. This PR adds the CMake feature of detecting the usage of `ccache` and changing the compilation option.
> Support ccache on windows

- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
> [16597] Fix assertion when built with statistics

- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- include/fastdds/rtps/common/EntityId_t.hpp
- src/cpp/CMakeLists.txt
- src/cpp/rtps/builtin/discovery/participant/DS/DiscoveryServerPDPEndpointsSecure.hpp
- src/cpp/rtps/builtin/discovery/participant/DS/FakeWriter.hpp
- src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.cpp
- src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.h
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
- src/cpp/rtps/messages/RTPSMessageGroup.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/rtps/security/SecurityManager.cpp
- test/mock/rtps/PDP/fastdds/rtps/builtin/discovery/participant/PDP.h
- test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/rtps/security/CMakeLists.txt
- test/unittest/statistics/dds/CMakeLists.txt
> [16501] PKI exchange finished 

- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- src/cpp/rtps/builtin/discovery/endpoint/EDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.h
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- test/communication/secure_ds_simple_secure_msg_crypto_pub.xml
- test/communication/secure_ds_simple_secure_msg_crypto_sub.xml
> [16603] Secure PDP exchange

- src/cpp/rtps/builtin/discovery/endpoint/EDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
This PR aims to complete EDP exchange with a secure discovery server. Secure Endpoints creation is left to SimpleEDP so it is needed to mark those endpoints as available.
> [16622] secure discovery server EDP exchange

- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
This PR fixes a corner case missed in #3089, where a data race might occur when a listener is being set while a `MyRTPSParticipantListener::Sentry` is being created (where the value of this listener was being checked without protection).
Additionally, an overflow issue affecting the timeout in `set_listener` is also addressed.
> Fine-tune DomainParticipant's blocking set_listener

- src/cpp/fastdds/core/condition/WaitSetImpl.cpp
- src/cpp/fastdds/core/condition/WaitSetImpl.hpp
- test/unittest/dds/core/condition/WaitSetImplTests.cpp
Signed-off-by: Chen Lihui <lihui.chen@sony.com>
Please refer to https://github.com/ros2/rclcpp/issues/2039#issuecomment-1310024990.
> [16192] fix notification lost

- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- test/communication/CMakeLists.txt
- test/unittest/rtps/security/SecurityHandshakeProcessTests.cpp
- test/unittest/rtps/security/SecurityTests.cpp
- test/unittest/rtps/security/SecurityTests.hpp
- test/unittest/rtps/security/SecurityValidationRemoteTests.cpp
This PR revisits the initial system test and fixes a minor argument that causes liveliness assertion to expire.
> [16498] Secure DS POC

- include/fastdds/dds/publisher/DataWriterListener.hpp
- versions.md
This PR includes a new non-standard callback to DataWriterListener.
Only the extended public API is included in order to implement the feature test suite before the feature implementation.
This PR also updates the notation using the DDS compliant one and substituting the C-style castings for a C++-style ones.
Related documentation PR: eProsima/Fast-DDS-docs#439
> [16736] Add DataWriterListener on_unacknowledged_sample_removed callback

- include/fastdds/rtps/writer/RTPSWriter.h
- versions.md
This PR adds the empty implementation for the `RTPSWriter::has_been_delivered` public virtual method required for the implementation of the new `DataWriterListener::on_unacknowledged_sample_removed`.
**ABI break** Changes are ABI compatible. 
> Public RTPS API: RTPSWriter::has_been_delivered()

- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/blackbox/common/DDSBlackboxTestsDataReader.cpp
`mp_reader->nextUntakenCache()` in `get_first_untaken_info()` is removing the change (`it->remove_change()`) if `matched_writer_lookup()` returns false. This, in turn calls `change_removed_by_history()` but `get_last_notified()` returns always false in that case because no writerGUID is found, hence a sequence number of 0.0 is returned. 
This situation causes that `total_unread_` is not decremented despite removing the change, so the history size and `total_unread_` variable are inconsistent and the issue arises. 
When user calls `take_next_sample()`,  `Ret::NO_DATA` is returned despite `reader->get_unread_count()` is different from 0.
`get_first_untaken_info()` should be a read-only API and `mp_reader->nextUntakenCache()` should not be called from inside because it modifies the history …
> [16608] Fix total_unread_ consistent with reader's history upon get_first_untaken_info()

- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastdds/dds/publisher/qos/DataWriterQos.hpp
- include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
- include/fastdds/rtps/attributes/WriterAttributes.h
- include/fastdds/rtps/flowcontrol/ThroughputControllerDescriptor.h
Since Fast DDS v2.4.0, flow controllers have substituted the previous throughput controllers.
This PR fixes the Doxygen documentation so the methods and structures superseded are shown as deprecated.
**N/A** New feature has been documented/Current behavior is correctly described in the documentation.
> [16315] Doxygen documentation: add deprecation notice to ThroughputControllerDescriptor

- include/fastdds/rtps/writer/RTPSWriter.h
After test plan review, the RTPS API method name was agreed to be changed from `RTPSWriter::has_been_delivered` to `RTPSWriter::has_been_fully_delivered`.
> [16736] Hotfix: change API name according to test plan review suggestion

- src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
- src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
- test/blackbox/common/BlackboxTestsTransportTCP.cpp
Sporadically, the Blackbox TCP_TLS tests stops on an ABBA deadlock. perform_listen_operation is called while another thread is processing a send operation on a TCP Transport.
After further analysis, the root of the problem seems to be the occasional miss of callback execution in `asio::async_write`. As a consequence, a waited-for promise is never set, hence getting stuck at the future get with several locked mutexes required in other threads.  This event seems not to be random; it could only be observed after the communication channel is closed/broken (ec=broken_pipe).
Proposed solution:
After testing several versions of asio library and looking for related issues without success, `asio::async_write` is replaced for its synchronous counterpart. Note that there should be no difference in …
> Fix deadlock on TLS closure [16288]

- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/blackbox/common/DDSBlackboxTestsDataReader.cpp
This is a rework of #3203 that avoids the segfault reported on https://github.com/ros2/rmw_fastrtps/issues/659
**Backports:** We will update the currently created PRs (#3217, #3218, #3219) accordingly
> Fix total_unread_ consistent with reader's history after get_first_untaken_info

- .github/workflows/mirror.yml
- CMakeLists.txt
- package.xml
- *N/A* Check CI results: failing …
> [16802] Branch out 2.10.x

- include/fastdds/rtps/builtin/discovery/endpoint/EDPSimple.h
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServer.hpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
- src/cpp/rtps/security/SecurityManager.cpp
This PR intends to add necessary fixes to have a successful Secure DIscovery Server - Secure DIscovery Server interaction. Punctual changes on PDP Clients are also considered.
The example scenario in which fixes have been tested has been:
SimpleSecurePublisher - SDS1 - SDS2 - SImpleSecureSubscriber
Update 18/01/2022:
- In `EDPServer::process_and_release_change`, I still leave the call to `remove_change_from_writer_history()` (from PDPServer) since PDPServer makes use of it when checking if the change comes from a participant.
- I applied the shortcut to accept a writer entity id on `get_builtin_reader_history_pair_by_entity()`.
- Tested case Pub-DS1-DS2-Sub With and Without security.
**N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and …
> [16739] Operative SecureDS-SecureDS 

- src/cpp/rtps/writer/StatelessWriter.cpp
`StatelessWriter::is_acked_by_all` checks that the sample has been delivered but instead of checking that the sequence number is lower than the last sent, the contrary is checked. This PR fixes this and other places where this same issue is happening.
@Mergifyio backport 2.9.x 2.8.x 2.7.x 2.6.x
**N/A** New feature has been documented/Current behavior is correctly described in the …
> [16737] Fix StatelessWriter ACK check

- include/fastdds/rtps/attributes/ServerAttributes.h
- test/blackbox/CMakeLists.txt
- test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
- test/unittest/dds/participant/CMakeLists.txt
> Remove odr-violation ASAN warning

- test/certs/governance_disable_discovery_disable_rtps_helloworld_all_enable.smime
- test/certs/governance_disable_discovery_disable_rtps_helloworld_all_enable.xml
- test/certs/governance_disable_discovery_helloworld_all_enable.smime
- test/certs/governance_disable_discovery_helloworld_all_enable.xml
- test/certs/governance_disable_rtps_helloworld_all_enable.smime
- test/certs/governance_disable_rtps_helloworld_all_enable.xml
- test/communication/CMakeLists.txt
- test/communication/secure_ds_simple_secure_no_discovery_no_rtps_protection_pub.xml
- test/communication/secure_ds_simple_secure_no_discovery_no_rtps_protection_sub.xml
- test/communication/secure_ds_simple_secure_no_discovery_protection_pub.xml
- test/communication/secure_ds_simple_secure_no_discovery_protection_sub.xml
- test/communication/secure_ds_simple_secure_no_rtps_protection_pub.xml
- test/communication/secure_ds_simple_secure_no_rtps_protection_sub.xml
- test/communication/secure_simple_ds_server_no_discovery_no_rtps_protection.xml
- test/communication/secure_simple_ds_server_no_discovery_protection.xml
- test/communication/secure_simple_ds_server_no_rtps_protection.xml
This PR intends to extend the simple secure DS system tests by including no discovery no RTPS protection cases.
> [16740] Simple secure scenario additional tests

- include/fastdds/rtps/common/Time_t.h
- src/cpp/rtps/common/Time_t.cpp
- src/cpp/statistics/rtps/messages/RTPSStatisticsMessages.hpp
UBSan (Undefined Behavior Sanitizer) produced the following warning:
```
third-party/eprosima/Fast-DDS/Fast-DDS-2.9.0/src/cpp/statistics/rtps/messages/RTPSStatisticsMessages.hpp:200:21: runtime error: member access within misaligned address 0x7f81715df7d4 for type 'eprosima::fastdds::statistics::rtps::StatisticsSubmessageData', which requires 8 byte alignment
```
This is triggered by casting an octet* to a StatisticsSubmessageData* and accessing one of StatisticsSubmessageData members . Since both of them have different alignment that operation is undefined behavior.
The workaround for this issue is using memcpy and offsetof to copy directly to the octet buffer reconstructing the StatisticsSubmessageData manually.
- [NA] Tests …
> [16671] Fixed StatisticsSubmessageData unaligned access

- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.h
- test/communication/CMakeLists.txt
…kelists spaces corrected
This PR intends to add the necessary fixes to get the 3 simple test scenarios working. 
When discovery is not protected, let pdp matching to be done later but accept messages from unknown, but trusted, reliable writers. When discovery is not protected, discoveryservers participantproxydata is not filled within `assignremoteEndpoints()` because discovering a participant happens before authentication, so security secrets are not known at that moment. On disposal, try again to find the correct participantproxydata.
- …
> [16880] Fix simple test scenarios

- .github/pull_request_template.md
This PR updates the PR template so that the only test that are required for the contributor to have been run locally are those added in the PR.
- *N/A* Applicable …
> [16909] Update pull request template

- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
This PR adds the tests for the new `DataWriterListener::on_unacknowledged_sample_removed`.
> [16736] On unacknowledged sample removed tests

- test/system/tools/fds/CMakeLists.txt
- test/system/tools/fds/test_xml_secure_discovery_server.xml
- test/system/tools/fds/tests.py
- tools/fds/server.cpp
This little PR adds Security Message print as specified in eProsima/Fast-DDS-docs#437 
-  [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
-  **N/A** Any new/modified methods have been properly documented using Doxygen. 
-  **N/A** New feature has been added to the `versions.md` file (if applicable).
-  **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
-  **N/A** Applicable backports have been included in the description.
> [17090] Added Security print to fast-discovery-server executable

- src/cpp/fastdds/builtin/typelookup/TypeLookupManager.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
- src/cpp/rtps/builtin/liveliness/WLP.cpp
This PR fixes the way the builtin endpoints mask from the DATA(p) is processed, so communication is not enforced on certain builtin endpoints when they are not present on the mask.
Regression tests will be added on a follow-up, since we have other changes depending on this.
@Mergifyio backport 2.9.x 2.8.x 2.6.x 2.1.x
- Tests that thoroughly check the regression **will be added on a follow-up PR**
> [16119] Correctly handle builtin endpoints mask

- include/fastrtps/utils/TimedMutex.hpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/rtps/reader/RTPSReader.cpp
- src/cpp/rtps/resources/ResourceEvent.cpp
This PR avoids using `try_lock_until` when `HAVE_STRICT_REALTIME` has not been set (in which case it was using a 24 hours timeout).
It also fixes a bug in the custom TimedMutex, which was always using `steady_clock::now` for calculating the required timeout.
@Mergifyio backport 2.9.x 2.8.x 2.6.x 2.1.x
> [17148] Improve behavior when HAVE_STRICT_REALTIME is not set.

- src/cpp/rtps/RTPSDomainImpl.hpp
- src/cpp/utils/shared_memory/RobustInterprocessCondition.hpp
- src/cpp/utils/shared_memory/SharedMemSegment.hpp
#3185 introduced shared pointers to keep track of Boost objects usage and optimize destruction order. This had the side effect of preventing SHM communication with earlier versions of Fast DDS. This PR restores the compatibility.
@Mergifyio backport 2.9.x
> [16979] Moved boost at_exit registration to RTPSDomainImpl

- .github/pull_request_template.md
> [17125] Add milestone check to PR template.

- test/unittest/dds/topic/DDSSQLFilter/CMakeLists.txt
DDSSQLFilterValueTests.test_filtered_value does not exist unless GTEST_INDIVIDUAL CMake option is used
- [NA] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
> Compilation error due to test [16371]

- resources/xsd/fastRTPS_profiles.xsd
- test/system/tools/xmlvalidation/XMLTesterExample.xml
- test/system/tools/xmlvalidation/profileAll.xml
- test/system/tools/xmlvalidation/profileDomainParticipant.xml
- tools/fastdds/fastdds.py
Rebased #3224 
**This pull request should be merged right after #3224 gets merged**
- Restore  `<domainId>` tag in XSD schema
- Restore tag in ALL test XMLs (only new files from #3224 )
Documentation Pull Request: eProsima/Fast-DDS-docs#464
- **N/A**  Any new/modified methods have been properly documented using Doxygen. 
Related documentation PR: eProsima/Fast-DDS-docs#464
> [17206] Restore participant domainID tag in XML profile

- test/performance/throughput/ThroughputPublisher.cpp
- test/performance/throughput/ThroughputSubscriber.cpp
- test/performance/throughput/ThroughputSubscriber.hpp
- test/performance/throughput/ThroughputTypes.cpp
- test/performance/throughput/ThroughputTypes.hpp
Samples sent and throughput value numbers suffer overflow.
Run colcon test for any of the following tests:
- interprocess_reliable_shm
- interprocess_reliable_udp
For payloads;demand:
- 16;100
- 8388608;100
And recoveries:
- 0;10;20;30;40;50;60;70;80;90;100;
- Fix overflow by counting received sampler directly instead of doing the following calculation, which is how it was done: counting lost samples comparing the sequence number of each received sample and the sequence number of the previous one, and then calculating received samples from last sequence number minus the count of lost samples.
- Then, lost samples calculation is also done now from the calculation of sent samples minus the received samples, instead of the mentioned calculation in receiver.
- [N/A] Tests that thoroughly …
> [17004] Fix performance tests - Overflow in received samples

- examples/cpp/dds/DynamicHelloWorldExample/HelloWorldSubscriber.cpp
- examples/cpp/dds/DynamicHelloWorldExample/HelloWorldSubscriber.h
Modified DynamicData example to be in line with eProsima's recommendations on entity creation inside callbacks (which we discourage).
> [17297] Avoid creation of DynamicTypes on example

- src/cpp/rtps/transport/ChainingTransport.cpp
This PR fixes compilation error in Ubuntu Xenial which uses old compiler gcc 5.4.
@mergifyio backport 2.9.x 2.8.x 2.6.x
> Fix compilation on old compilers [16901]

- test/blackbox/common/DDSBlackboxTestsListeners.cpp
This PR aims to fix multiple memory leaks detected by the ASAN workflow on some tests.
@Mergifyio backport 2.9.x
> [17514] Fixed ASAN detected leaks

- test/mock/rtps/SharedMemSegment/utils/shared_memory/SharedMemSegment.hpp
Merging #3293 added an ASAN heap-buffer-overflow since Boost singleton references were removed from SharedMemSegment on #3298 but those changes were not propagated to the mock used in the test. This PR fixes that issue.
> [17350] Removed Boost singleton references from mock

- src/cpp/rtps/builtin/liveliness/WLP.cpp
WLP::add_local_reader takes the PDP mutex to protect the reader collection. WLP::remove_local_reader should take the same mutex to prevent simultaneous addition/removal from the same container.
@Mergifyio backport 2.9.x 2.8.x
Fixes #3304 
> [17267] Added missing mutex to WLP::remove_local_reader

- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/rtps/security/SecurityManager.h
The use of temporary ProxyData objects in the SecurityManager was causing some data races when PKI exchanges where happening with several participants at once, leading to incomplete DH negotiations in the worst cases.
This PR replaces these temporary objects with two preallocated pools that will prevent concurrent access to resources.
> [17617] Replaced SecurityManager temporary ProxyDatas with ProxyPools

- include/fastdds/dds/core/policy/QosPolicies.hpp
This PR specifies the meaning of value 0 in `ResourceLimitsQos` attributes.
> Improve doxygen documentation for ResourceLimitsQos [16814]

- resources/xsd/fastRTPS_profiles.xsd
- test/communication/liveliness_assertion.120.xml
- test/communication/liveliness_assertion.360.xml
- test/communication/liveliness_assertion.xml
- test/communication/shm_communication_subscriber_dies_while_processing_message.xml
- test/communication/simple_besteffort.xml
- test/communication/simple_reliable.xml
- test/communication/simple_reliable_besteffort.xml
- test/communication/simple_secure_besteffort_pub.xml
- test/communication/simple_secure_besteffort_sub.xml
- test/dds/communication/simple_besteffort.xml
- test/dds/communication/simple_besteffort_zerocopy.xml
- test/dds/communication/simple_reliable.xml
- test/dds/communication/simple_reliable_zerocopy.xml
- test/performance/latency/xml/intraprocess_best_effort.xml
- test/performance/latency/xml/intraprocess_reliable.xml
- test/performance/throughput/xml/interprocess_best_effort_shm.xml
- test/performance/throughput/xml/interprocess_reliable_shm.xml
- test/performance/throughput/xml/intraprocess_best_effort.xml
- test/performance/throughput/xml/intraprocess_reliable.xml
- test/system/tools/xmlvalidation/XMLTesterExample.xml
- test/system/tools/xmlvalidation/librarySettings_profile.xml
- test/system/tools/xmlvalidation/profileAll.xml
- test/system/tools/xmlvalidation/profileDomainParticipant.xml
- test/system/tools/xmlvalidation/topic_profile.xml
- test/unittest/dds/profiles/test_xml_profiles.xml
- test/unittest/dds/profiles/test_xml_profiles_for_string.xml
- test/unittest/xmlparser/test_xml_profiles.xml
- test/unittest/xmlparser/test_xml_root_library_settings_profile.xml
Validation test has passed locally.
The XML schema has been updated to meet the following requirements:
- `topic` was already supported as profile in Fast DDS, so it is also supported in the schema as a profile (with `profile_name` and `is_default_profile` attributes) 
- `library_settings` is not supported as profile. Move it as dds child.
- `participant` > `rtps` > `allocation` > `send_buffers` is supported but was not included in the schema.
Also, missing elements has been added in the XML profile testing files. 
Related documentation PR: …
> [17559] Update Fast DDS profiles schema with troubleshooting errors

- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/dds/domain/DomainParticipantListener.hpp
- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- include/fastdds/rtps/participant/ParticipantDiscoveryInfo.h
- include/fastdds/rtps/participant/RTPSParticipant.h
- include/fastdds/rtps/participant/RTPSParticipantListener.h
- include/fastdds/rtps/reader/ReaderDiscoveryInfo.h
- include/fastdds/rtps/writer/WriterDiscoveryInfo.h
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/participant/RTPSParticipant.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
- versions.md
This PR introduces the required API to implement the ignore DDS entity feature.
- [NO] Changes are ABI compatible. 
- [NO] Changes are API compatible. 
As this feature is not yet implemented, it will be documented in a follow-up PR when the implementation is made.
> [17509] Feature: Ignore empty API

- src/cpp/utils/IPFinder.cpp
Signed-off-by: Lightech <lightech@outlook.com>
> Include the right header when building for iOS

- include/fastdds/dds/core/policy/ParameterTypes.hpp
- src/cpp/fastdds/core/policy/ParameterList.cpp
- src/cpp/fastdds/core/policy/ParameterSerializer.hpp
- src/cpp/rtps/history/CacheChangePool.cpp
- src/cpp/rtps/history/WriterHistory.cpp
- src/cpp/rtps/messages/submessages/DataMsg.hpp
- src/cpp/rtps/transport/test_UDPv4Transport.cpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
The value for PID_RELATED_SAMPLE_IDENTITY enum definition is changed to (`0x0083`) the one defined in the document `Remote Procedure Call over DDS`, document reference `ptc/2016-03-19`, V1.0.
The legacy value used is now defined under PID_CUSTOM_RELATED_SAMPLE_IDENTITY.
The definitions for the values `0x0080` to `0x0082` have been added as well.
> [17515] Use standard value for PID_RELATED_SAMPLE_IDENTITY

- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
- No need to backport since regression is only in master
> [17941] Fix regression introduced by #3396

- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/dds/domain/DomainParticipantListener.hpp
- include/fastdds/rtps/messages/MessageReceiver.h
- include/fastdds/rtps/participant/RTPSParticipantListener.h
- src/cpp/fastdds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
- src/cpp/rtps/messages/MessageReceiver.cpp
- src/cpp/rtps/participant/RTPSParticipant.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
- test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
- test/unittest/dds/participant/ParticipantTests.cpp
- versions.md
This PR provides the implementation and test for the ignore_participant API call.
- Related documentation PR: eProsima/Fast-DDS-docs#475
> [17873] DomainParticipant::ignore_participant implementation

- src/cpp/rtps/reader/WriterProxy.cpp
- test/mock/rtps/TimedEvent/fastdds/rtps/resources/TimedEvent.h
- test/unittest/rtps/reader/CMakeLists.txt
- test/unittest/rtps/reader/WriterProxyAcknackTests.cpp
- test/unittest/rtps/reader/WriterProxyTests.cpp
This PR introduces an exponential backoff for the periodic sending of the initial acknack. 
> [17832] Initial acknack backoff

- src/cpp/rtps/transport/UDPTransportInterface.cpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
This PR fixes a wrong behavior where a multicast address on an initial peer locator is being incorrectly treated as unicast.
@Mergifyio backport 2.9.x 2.6.x 2.1.x
> [17976] Correctly assign multicast port to multicast initial peers

- src/cpp/rtps/messages/MessageReceiver.cpp
This fixes a regression on the fuzzer introduced by #3412 
> Fix null dereference when fuzzing

- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/RTPSDomainImpl.hpp
Picks the smallest available participant ID.
This picks the smallest available participant ID when creating new participants.
This is necessary for the out of box discovery improvements in ROS 2: https://github.com/ros2/rmw_fastrtps/pull/653
The issue with picking one greater than the maximum participant ID  is that it's possible for the ID to increase well beyond the number of alive participants. For example, Participant A is created with 0, and B is created with 1. A is destroyed, and C is created. C takes ID 2 even though 0 is available and there are only two participants. When using unicast discovery this can cause participants to no longer be discoverable after the maximum ID climbs past `maxInititialPeersRange`. This is currently causing the `test_launch_ros` tests to fail with the …
> Pick smallest available participant ID for new paricipants

- .github/workflows/thread-sanitizer.yaml
Since the upgrade to Ubuntu 22.04, TSan Github Workflows are being prematurely canceled due to resource starvation. This PR limits memory usage, history size and disables some unit tests while the stability of Ubuntu Jammy runners improves. …
> [18054] Cap Thread Sanitizer memory usage to prevent runner shutdown

- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/RTPSDomainImpl.hpp
- test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
- test/mock/rtps/RTPSDomainImpl/rtps/RTPSDomainImpl.hpp
- test/unittest/dds/participant/ParticipantTests.cpp
"
Second participant creation fails, but when its `DomainParticipantImpl` will be removed from the factory, the code remove the one of the first participant. This is because they share the same GUID.
"
> Fix segfault when creating two participant with same fixed id [18051]

- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
This PR fixes a SEGFAULT which occurred when doing the following sequence:
1. Creating a a DomainParticipant with a listener which captures the offered_deadline_missed events.
2. Creating a DataWriter without any listener that was not used to write data within the deadline period, thus triggering the offered deadline missed event.
@Mergifyio backport 2.9.x 2.6.x 2.1.x
> [17961] Select correct listener for on_requested_deadline_missed

- include/fastrtps/utils/TimedMutex.hpp
This should fix #3451 by adding an alias for `xtime` on newer versions of MSVC.
@Mergifyio backport 2.9.x 2.6.x 2.1.x
> [18149] Fix build on msvc 19.36.32528

- resources/xsd/fastRTPS_profiles.xsd
As long as the schema cannot recognize the `kind` value to create restrictions related to the transport descriptor elements that are associated to a kind of transport, it makes no sense to keep the `kind` element as mandatory in the schema. …
> [18123] Update XML schema to set Transport descriptor kind as NOT mandatory

- cmake/packaging/Config.cmake.in
- src/cpp/CMakeLists.txt
Improve loading `fastrtps` through its cmake config file. This PR includes these features:
1. Select library type using `find_package()` components.
```cmake
find_package(fastrtps shared) # Load shared library
find_package(fastrtps static) # Load static library
```
2. Select library type using variable `fastrtps_SHARED_LIBS`
```cmake
fastrtps_SHARED_LIBS=ON # Load shared library
ffastrtps_SHARED_LIBS=OFF # Load static library
```
3. Select library type using the variable `BUILD_SHARED_LIBS`
```cmake
BUILD_SHARED_LIBS=ON # Load shared library
BUILD_SHARED_LIBS=OFF # Load static library
```
4. If non-previous scenarios were used, the static library tried to be loaded and if it fails, dynamic library is loaded.
- *N/A* Tests that thoroughly check the new feature have been added/Regression …
> Improve target loading [16416]

- test/blackbox/api/dds-pim/PubSubWriterReader.hpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSWithRegistrationReader.hpp
- test/blackbox/common/RTPSWithRegistrationWriter.hpp
This PR provides tests for the participant ignore local endpoints tests
The following changes are expected to fail:
* BlackboxTests_RTPS.RTPS.participant_ignore_local_endpoints
* BlackboxTests_DDS_PIM.DDSBasic.participant_ignore_local_endpoints
> [18155] Participant ignore local enpoints tests

- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/blackbox/api/dds-pim/PubSubWriterReader.hpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSWithRegistrationReader.hpp
- test/blackbox/common/RTPSWithRegistrationWriter.hpp
- test/mock/rtps/PDP/fastdds/rtps/builtin/discovery/participant/PDP.h
- test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
This PR provides the implementation for the participant ignore local endpoints tests.
Depends on:
* #3476
* Related documentation PR: eProsima/Fast-DDS-docs#485
> [18156] Participant ignore local enpoints implementation

- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/blackbox/api/dds-pim/PubSubWriterReader.hpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSWithRegistrationReader.hpp
- test/blackbox/common/RTPSWithRegistrationWriter.hpp
- test/mock/rtps/PDP/fastdds/rtps/builtin/discovery/participant/PDP.h
- test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
- versions.md
This PR adds functionality for instructing a DomainParticipant/RTPSParticipant to not match their compatible local endpoints.
* Related documentation PR: eProsima/Fast-DDS-docs#485
> [18151] Participant ignore local endpoints

- src/cpp/utils/shared_memory/RobustInterprocessCondition.hpp
Since `boost/interprocess` v1.74+ removed direct dependency on `boost/datetime`. Fast-DDS won't compile:
```
boost/interprocess/sync/posix/semaphore_wrapper.hpp:226:21: error: no matching function for call to 'timepoint_to_timespec'
timespec tspec = timepoint_to_timespec(abs_time);
^~~~~~~~~~~~~~~~~~~~~
boost/interprocess/sync/posix/semaphore.hpp:55:14: note: in instantiation of function template specialization 'boost::interprocess::ipcdetail::semaphore_timed_wait<boost::date_time::special_values>' requested here
{  return semaphore_timed_wait(&m_sem, abs_time); }
^
boost/interprocess/sync/interprocess_semaphore.hpp:133:16: note: in instantiation of function template specialization 'boost::interprocess::ipcdetail::posix_semaphore::timed_wait<boost::date_time::special_values>' requested …
```
> Forward compatibility with boost interprocess 1.74+

- include/fastdds/rtps/transport/TransportDescriptorInterface.h
- include/fastrtps/types/TypeNamesGenerator.h
@Mergifyio backport 2.9.x 2.6.x 2.1.x
Fixes #3494
> [18431] Fix missing includes

- cmake/packaging/Config.cmake.in
- src/cpp/CMakeLists.txt
According to [Fast DDS versioning policy](https://github.com/eProsima/Fast-DDS/blob/master/VERSIONING.md), patch releases should not introduce ABI breaks or behavioral changes. #3134 introduced a change in the packaging that should not be released in a patch release because it removes a CMake option that any user can be using: `FASTDDS_STATIC`. This PR reverts those changes in 2.10.x branch. This PR **must** be merged after merging #3500 (mirror workflow updated to not mirror into 2.10.x).
- [N/A] Any new/modified methods have been properly documented using Doxygen. …
> [18449] Revert #3134 in 2.10.x

- resources/xsd/fastRTPS_profiles.xsd
- test/system/tools/xmlvalidation/all_profile.xml
- test/system/tools/xmlvalidation/dataReader_profile.xml
Recent change in the endpoint QoS XML schema (#3492) was not considered while merging new XML schema supported tags (#3399).
This hotfix would include the new definition in both endpoint QoS XML schema. 
It also removes ownership strength from DataReadeQoS
@Mergifyio backport 2.10.x 
Related documentation PR: eProsima/Fast-DDS-docs#495
Backport 2.10.x
> [18674] Fixes on XML schema

- CMakeLists.txt
Currently, documentation builds fail if the current version of Fast DDS does not have a matching tag in ReadTheDocs. This complicated the process of generating testing. 
This PR adds a mechanism to get the current `master` branch from ReadTheDocs should the current version download fail. 
- [NA] The code follows the style guidelines of this project. 
- [NA] New feature has been documented/Current behavior is …
> [18725] Added documentation version fallback

- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
Use unrestricted permissions when creating mutexes, locks and shared memory segments to allow applications started by different users to communicate.
> [18765] Use unrestricted permissions when creating shared memory segments

- include/fastdds/dds/topic/ContentFilteredTopic.hpp
- versions.md
This PR fixes the exported symbols on ContentFilteredTopic
- Changes are **NOT** ABI compatible.
> [14260] Fixed exported symbols on ContentFilteredTopic

- src/cpp/fastdds/core/policy/ParameterSerializer.hpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/topic/ContentFilteredTopicImpl.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
This PR adds an additional check to verify that the expression_parameters vector provided when creating a ContentFilteredTopic math with the limits established in the DomainParticipantQoS. It also fixes a wrong length comparison when deserializing that same vector.
Related documentation PR: eProsima/Fast-DDS-Docs#510
> [18763] Improve content filter expression parameters checks and verbosity.

- src/cpp/fastdds/log/Log.cpp
Signed-off-by: Irene Bandera <irenebandera@eprosima.com>
https://github.com/eProsima/Fast-DDS/tree/bug/logError
> Fix tests with Log: wait for Log background thread initialization on the first queued entry [16948]

- src/cpp/rtps/security/SecurityManager.cpp
- test/blackbox/common/BlackboxTestsSecurity.cpp
- versions.md
This PR deprecates the following properties:
* `rtps.participant.rtps_protection_kind`
* `rtps.endpoint.submessage_protection_kind`
* `rtps.endpoint.payload_protection_kind`
https://github.com/eProsima/Fast-DDS-docs/pull/512
> [13521] Deprecate rtps security properties

- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/TCPTransportInterface.h
- src/cpp/rtps/transport/tcp/RTCPHeader.h
- src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
- src/cpp/rtps/transport/tcp/RTCPMessageManager.h
- test/unittest/transport/TCPv4Tests.cpp
TCPControlMsgHeader deserialize  in TCPTRansportInterface.cpp : "TCPControlMsgHeader controlHeader = *(reinterpret_cast<TCPControlMsgHeader*>(receive_buffer));" ,  function receive_header() not process endianness also. however, TCPHeader and TCPControlMsgHeader has member of type uint16_t or uint32_t
> check endianness of TCPControlMsgHeader&TCPHeader

- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- include/fastdds/rtps/builtin/discovery/participant/PDPSimple.h
- include/fastdds/rtps/common/WriteParams.h
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.h
- src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
There is a static (global) variable that is supposed to contain default values, but it does not.
This variable is sent to multiple functions by default by reference, where it is modified (it is not default anymore) without guards (TSAN issues).
> Fix static variable data race access [17163]

- src/cpp/fastdds/publisher/qos/WriterQos.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
This PR fixes a bug where a QoS is copied from one ReaderProxyData to another but partition names are not copied if the list is empty. 
Specifically, this code path: 
```
/// src/cpp/rtps/builtin/discovery/participant/PDP.cpp   
else
{
// Pool is not empty, use entry from pool
ret_val = reader_proxies_pool_.back();
reader_proxies_pool_.pop_back();
}
// Add to ParticipantProxyData
(*pit->m_readers)[reader_guid.entityId] = ret_val;
```
> Fix partition copy in QoS [11451]

- test/unittest/utils/BitmapRangeTests.cpp
Signed-off-by: David Coello Pulido <davidcoello@eprosima.com>
> Add BitmapRange UT

- src/cpp/rtps/writer/StatelessWriter.cpp
Signed-off-by: Irene Bandera <irenebandera@eprosima.com>
> Fix data_count = 0 when using datasharing [16060]

- include/fastdds/dds/domain/DomainParticipantListener.hpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- versions.md
This should fix #3460 by calling the old overload whenever the new one does not ignore the participant.
Please note that a test that mixes two versions of the product would be difficult to implement, so this fix should be manually checked.
The black-box tests currently use the old overload of the listener, so passing them is enough to check that the old overload is called when the new one has not been overridden.
No need to backport since it only affects 2.10.1.
Related …
> [18259] Calling old `on_participant_discovery` overload

- src/cpp/CMakeLists.txt
- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/security/accesscontrol/DistinguishedName.cpp
- src/cpp/security/accesscontrol/DistinguishedName.h
- src/cpp/security/accesscontrol/Permissions.cpp
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/security/accesscontrol/CMakeLists.txt
- test/unittest/security/accesscontrol/DistinguishedNameTests.cpp
- test/unittest/statistics/dds/CMakeLists.txt
Reimplement Distinguished names comparator function `rfc2253_string_compare`.
There was an incorrect behavior in the comparison of Distinguished Names in security accesscontrol module.
Main problem is that RFC 2253 was not correctly followed, and some Distinguished Names that should be accepted were not (mainly because disorder of value-types attributes was not contemplated).
This PR have the following features in respective commits:
1. Extend a function that made security fail without log information (35cd6225ae72188100bc04edf9cc06e674053776)
2. Implement new `rfc2253_string_compare` function (c80227739b7842dbc7428da9e73b338881989cb7)
3. Add tests for such function (270c155eca0fdbb2c003a1ea5d8be459d79cfccf)
> **NOTE**: The implementation of this function is highly non trivial as many …
> Distinguished names comparator [18789]

- CMakeLists.txt
- examples/cpp/dds/StaticHelloWorldExample/HelloWorldPublisher_static_disc.xml
- examples/cpp/dds/StaticHelloWorldExample/HelloWorldSubscriber_static_disc.xml
- resources/xsd/fastdds_static_discovery.xsd
- test/blackbox/PubSubReaderPersistence_static_disc.xml.in
- test/blackbox/PubSubReader_static_disc.xml.in
- test/blackbox/PubSubWriterPersistence_static_disc.xml.in
- test/blackbox/PubSubWriter_static_disc.xml.in
- test/system/tools/fastdds/CMakeLists.txt
- test/system/tools/xmlvalidation/discovery_static_disc.xml
- versions.md
This PR adds a new resources: an XSD file to validates static discovery XML files.
> Add XSD for static discovery [17842]

- include/fastdds/dds/domain/DomainParticipantFactory.hpp
- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
load_profiles() method is called in a singleton without guards, and this could lead to multiple threads loading files at the same time.
TSAN fails in most tests for this (every time a DomainParticipant is created).
- ¿? Changes are ABI compatible. 
> Fix load profiles TSAN issue [17162]

- include/fastdds/rtps/messages/CDRMessage.hpp
- test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
UBSan (Undefined behavior sanitizer) reports nullptr memcpy calls when memcpy arguments should be guaranteed as not null. Checks have been added to prevent this.
> [18004] Added length checks to prevent nullptr memcpy calls

- cmake/common/test_wrapper.cmake
- cmake/common/test_wrapper.cmake.in
- test/communication/CMakeLists.txt
- tools/fastdds/CMakeLists.txt
The #2886 pull request introduced a change in testing that made communication tests fail quietly, shown as passed.
This PR update the dependency included and introduces the fast dds cli tool in the build env (only if compiling tests) to proceed as expected in the previous PR.
> [19054] Fix communication tests not runned

- .github/workflows/config/default_ci.meta
- .github/workflows/reusable-windows-ci.yml
- test/communication/multiple_secure_ds_pubsub_secure_crypto_communication.py
- test/communication/secure_ds_pubsub_secure_crypto_communication.py
This PR:
1. Fixes an `AttributeError` exception in Windows DS secure tests
2. Adds security to github windows CI runs
> [19014] Fix Github Windows CI

- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/rtps/participant/RTPSParticipant.h
- include/fastdds/statistics/dds/domain/DomainParticipant.hpp
- src/cpp/fastdds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/rtps/participant/RTPSParticipant.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/statistics/fastdds/domain/DomainParticipant.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
This PR moves the Monitor Service high level api to the statistics DDS DomainParticipant API and in the RTPS layer under the `FASTDDS_STATISTICS` compilation macro . It also completes the RTPS API by including the last changes of the `update 2` on the design
Related documentation PR: eProsima/Fast-DDS-docs#506
- **N/A**  Applicable backports have been included in the description.
> [19071] Move and complete the Monitor Service High level API to statistics

- include/fastdds/rtps/history/IPayloadPool.h
- src/cpp/rtps/history/TopicPayloadPool.hpp
- src/cpp/rtps/history/TopicPayloadPool_impl/Dynamic.hpp
- src/cpp/rtps/history/TopicPayloadPool_impl/DynamicReusable.hpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
- test/unittest/rtps/history/TopicPayloadPoolTests.cpp
As a regression of #1929, this PR introduces a couple of unit tests, the regression BB test and proposes a fix for accepting zero sized payload allocations in the topic pool. 
In particular, this is interesting to properly add to the history the disposals of any endpoints in a remote Participant configured with DYNAMIC_*_MEMORY modes, as the payload size in that case is 0. Otherwise, the disposal CacheChanges are always discarded by remote participants and are not added to the history.
*Note: this PR should not be merged until 2.11 freeze is finished*
@Mergifyio backport 2.11.x 2.10.x 2.9.x 2.6.x
Fixes #1929
> [13608] Dynamic memory topic payload pool properly handle Zero sized payloads

- examples/cpp/dds/ContentFilteredTopicExample/ContentFilteredTopicExamplePublisher.cpp
- examples/cpp/dds/ContentFilteredTopicExample/ContentFilteredTopicExampleSubscriber.cpp
Improve user experience by explicitly registering the TypeObject and referencing the documentation.
> [18825] Explicitly register type object in ContentFilteredTopicExample

- include/fastrtps/config.h.in
Some log tests define `FASTDDS_ENFORCE_LOG_INFO` before including config.h (through other includes). This results in a double definition of `FASTDDS_ENFORCE_LOG_INFO` when compiling the CMake option `-DFASTDDS_ENFORCE_LOG_INFO=ON`.
The afected tests `LogMacrosTests` have all been run locally on a build using the the CMake option.
> [19139] Avoid double definition of FASTDDS_ENFORCE_LOG_INFO

- include/fastdds/statistics/rtps/monitor_service/Interfaces.hpp
- include/fastdds/statistics/rtps/monitor_service/interfaces/IConnectionsObserver.hpp
- include/fastdds/statistics/rtps/monitor_service/interfaces/IConnectionsQueryable.hpp
- include/fastdds/statistics/rtps/monitor_service/interfaces/IEDPObserver.hpp
- include/fastdds/statistics/rtps/monitor_service/interfaces/IProxyQueryable.hpp
- include/fastdds/statistics/rtps/monitor_service/interfaces/IStatusListerner.hpp
- include/fastdds/statistics/rtps/monitor_service/interfaces/IStatusQueryable.hpp
This PR adds the needed interfaces for the Monitor Service in the RTPS Layer according to the design. 
_Note: A little mistake was found in the design. The `IStatusQueryable` methods not returning the statuses_
- **N/A**  New feature has been documented/Current behavior is correctly described in the documentation. 
- **N/A**  Applicable backports have been included in the description.
> [18069] Add monitor service RTPS interfaces

- src/cpp/utils/shared_memory/RobustInterprocessCondition.hpp
> [19127] Revert parallel testing SemaphoreNode changes

- src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
Small refactor to the way SHM ports are regenerated preventing extra shared pointers from being created.
> [18966] Refactor of regenerate_port.

- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
This PR improves the detection of ports that may have been left in an inconsistent state, adding checks to detect if a port owner has died, leaving the port in a perpetually processing state.
> [18966] Improved shm listener status update mechanism

- test/unittest/statistics/rtps/CMakeLists.txt
- test/unittest/statistics/rtps/MonitorServiceTests.cpp
This PR introduces the unittests for the MonitorService class. A series of triggers are fired on the listener so that the Monitor service performs the corresponding calls (timed) to the query interfaces is asserted.
> [18074] Unit tests for the Monitor Service main class

- include/fastdds/rtps/builtin/data/ParticipantProxyData.h
- include/fastdds/rtps/builtin/data/ReaderProxyData.h
- include/fastdds/rtps/builtin/data/WriterProxyData.h
- include/fastdds/rtps/participant/RTPSParticipant.h
- include/fastdds/statistics/dds/domain/DomainParticipant.hpp
- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
- src/cpp/rtps/builtin/data/ReaderProxyData.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
- src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
- src/cpp/rtps/participant/RTPSParticipant.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- src/cpp/statistics/fastdds/domain/DomainParticipant.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
- test/blackbox/CMakeLists.txt
- test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/dds/status/CMakeLists.txt
- test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
- test/unittest/statistics/dds/CMakeLists.txt
This PR adds methos for proxy deserialization at DDS level
- **N/A** ? Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
-**N/A** Applicable backports have been included in the description.
> [19166] Deserialization methods for Monitor Service

- src/cpp/CMakeLists.txt
This completes the work on https://github.com/eProsima/Fast-DDS/pull/3653
OpenSSL only should be a mandatory dependence on static linking. CMake shouldn't search for it for dynamic ones.
> Refs 19117. Refixing OpenSSL search on installer

- include/fastrtps/utils/fixed_size_string.hpp
- test/unittest/utils/FixedSizeStringTests.cpp
> Added < and > operators to fixed_string.

- include/fastdds/dds/publisher/Publisher.hpp
- include/fastdds/dds/subscriber/Subscriber.hpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.hpp
- src/cpp/fastdds/publisher/Publisher.cpp
- src/cpp/fastdds/publisher/PublisherImpl.cpp
- src/cpp/fastdds/publisher/PublisherImpl.hpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/fastdds/subscriber/Subscriber.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.hpp
- src/cpp/statistics/fastdds/publisher/DataWriterImpl.hpp
- src/cpp/statistics/fastdds/publisher/PublisherImpl.hpp
- src/cpp/statistics/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/statistics/fastdds/subscriber/SubscriberImpl.hpp
- test/blackbox/api/dds-pim/CustomPayloadPool.hpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/unittest/common/CustomPayloadPool.hpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
- test/unittest/statistics/dds/StatisticsDomainParticipantMockTests/mock/statistics/fastdds/publisher/PublisherImpl.hpp
- versions.md
> [19023] Custom Payload pools test implementation

- include/fastdds/rtps/builtin/discovery/participant/PDP.h
> Fix PDP Doxygen comments typos

- src/cpp/rtps/resources/TimedEventImpl.cpp
- src/cpp/rtps/resources/TimedEventImpl.h
Eliminates the overhead of mutex locking in a method in TimeEventImpl that is frequently called. 
While investigating scalability of discovery service on a large distributed system, hotspot analysis using Intel vtune showed that most time is spent with mutexes. Further analysis identifies a particular culprit whose removal increases the performance by 2x.
The following is from a machine with Haswell CPU running a SERVER participant. Evidently, 50% of the compute is spent locking and unlocking a mutex. The CPU consumption measured by top is of the order of 37%.
The performance analysis with vtune allows the construction of a so-called flamegraph that makes it very easy to understand the caller-callee relationship. The graph makes it very clear that the vast majority of the mutex locks and …
> [19256] Remove mutex from TimedEventImpl

- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
This pull request aim to expose the usage of a custom payload pool implementation on the DDS layer, and implements the functionality
Test are implemented in this PR: #3719 
Related documentation PR: eProsima/Fast-DDS-docs#514  
> [19024] Expose Payload Pool on DDS layer: Implementation

- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- test/blackbox/common/DDSBlackboxTestsDataSharing.cpp
This PR enables datasharing processing on readers which are directly notified by a datasharing writer in the same process.
- Some of the existing datasharing blackbox tests have been updated to run both with intraprocess on and off, so we can check for TSan report on possible deadlocks.
> [19247] Improve performance on intraprocess + data-sharing

- src/cpp/rtps/resources/TimedEventImpl.cpp
Adds explicit initialization of the atomic time_point added in #3745.
> [19266] Added atomic time_point initialization

- src/cpp/rtps/DataSharing/DataSharingListener.cpp
- src/cpp/rtps/DataSharing/DataSharingNotification.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
This, along with #3753, highly improves the situation described in ros2/rmw_fastrtps#699.
I'm still not sure whether it is completely fixed, but the changes here fix two obvious bugs.
1. When a participant crashes just after pushing a descriptor into the listening port of another participant, the descriptor should be popped from the port even if it points to a non-existent / corrupted segment. Otherwise the listener enters in an infinite loop.
2. Some mutex locks could throw an unhandled timeout exception, making participant crashes more probable.
- I consider the testcase in …
> Improve SHM resilience to crashing participants

- src/cpp/rtps/DataSharing/DataSharingNotification.hpp
- src/cpp/rtps/DataSharing/DataSharingPayloadPool.hpp
Some android build targets cannot translate from `alignas(uint64_t)` to `alignas(8)`.
> [19268] Replace uint64_t by 8 in alignas specifier

- src/cpp/rtps/xmlparser/XMLParser.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/regressions/18395_profile_bin.xml
Fixes a `nullptr` access when attempting to get the text of no initialized `use_default` tag within a `log` tag in an XML configuration file, e.g.:
```xml
<log>
</use_default/>
</log>
```
> [18395] Fix XMLParser null-derefence in parseLogConfig

- src/cpp/rtps/network/NetworkFactory.cpp
- src/cpp/rtps/network/NetworkFactory.h
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsTransportSHMUDP.cpp
- test/unittest/rtps/network/CMakeLists.txt
- test/unittest/rtps/network/NetworkFactoryTests.cpp
- test/unittest/transport/CMakeLists.txt
- test/unittest/transport/TCPv6Tests.cpp
- versions.md
This is a rework of #3641.
In order to improve resilience when a participant dies unexpectedly, forcing discovery to use UDP by default.
The behavior can be configured using a new property `fastdds.shm.enforce_metatraffic`, which can take values `none` (default), `unicast` (default behavior before this PR), or `all` (would allow communication with a SHM only participant)
This PR changes the default behavior, but since it improves Fast DDS stability, and it has no ABI breaks, we will backport it to the supported branches.
Related documentation PR: eProsima/Fast-DDS-docs#535
> [19263 ] User configuration for SHM metatraffic

- src/cpp/rtps/xmlparser/XMLParser.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/regressions/simple_participant_profiles_nok.xml
- test/unittest/xmlparser/regressions/simple_participant_profiles_ok.xml
According to the XSD schema, an XML configuration file can include an empty DomainParticipant profile, meaning without any `domainId` or `rtps` tags.
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
<profiles>
<participant profile_name="empty_participant">
</participant>
</profiles>
</dds>
```
However, the XMLParser was expecting a minimum occurrences of 1 for the `rtps` tag, so the above XML passes the validation, but fails to load.
This PR fixes that inconsistency by allowing an empty participant profile.
> [19315] Allow participant profiles with no rtps tag

- include/fastdds/dds/publisher/Publisher.hpp
- include/fastdds/dds/subscriber/Subscriber.hpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.hpp
- src/cpp/fastdds/publisher/Publisher.cpp
- src/cpp/fastdds/publisher/PublisherImpl.cpp
- src/cpp/fastdds/publisher/PublisherImpl.hpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/fastdds/subscriber/Subscriber.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.hpp
- src/cpp/statistics/fastdds/publisher/DataWriterImpl.hpp
- src/cpp/statistics/fastdds/publisher/PublisherImpl.hpp
- src/cpp/statistics/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/statistics/fastdds/subscriber/SubscriberImpl.hpp
- test/blackbox/api/dds-pim/CustomPayloadPool.hpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/unittest/common/CustomPayloadPool.hpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
- test/unittest/statistics/dds/StatisticsDomainParticipantMockTests/mock/statistics/fastdds/publisher/PublisherImpl.hpp
- versions.md
This pull request aims to expose the usage of a custom payload pool implementation on the DDS layer
Related documentation PR: eProsima/Fast-DDS-docs#514
> [19265] Custom pools on DDS layer feature

- include/fastdds/dds/domain/DomainParticipant.hpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
According to the [documentation](https://fast-dds.docs.eprosima.com/en/latest/fastdds/api_reference/dds_pim/domain/domainparticipant.html"), register_remote_type returns true if type is already available to indicate its intention of not calling the callback.
However, the function returns RETCODE_OK regardless.
This PR fixes this by:
* Returning NO_DATA when using type lookup service
* Improving the API reference
> [19359] Fix DomainParticipant::register_remote_type return when negotiating type

- src/cpp/utils/SystemInfo.cpp
- src/cpp/utils/threading.hpp
- src/cpp/utils/threading/threading_osx.ipp
- src/cpp/utils/threading/threading_pthread.ipp
- src/cpp/utils/threading/threading_win32.ipp
This provides implementation of the methods for setting the thread name added in #3821 
> [17492] Platform implementations for set_name_to_current_thread

- test/blackbox/api/dds-pim/PubSubReader.hpp
> Remove warning on Win32 architecture

- test/profiling/allocations/test.sh
- test/profiling/allocations/test_with_memory_tool.sh
- tools/fastdds/fastdds
- tools/fastdds/ros-discovery
- utils/scripts/update_generated_code_from_idl.sh
In order to improve script portability, instead of setting the absolute path to the interpreter, this PR modifies the shebang to make use of `/usr/bin/env` program. This can have its own portability issues, though it seems that most systems agrees with this convention.
This PR fixes #3734.
- [N/A] New …
> [19208] Improve script portability

- .github/workflows/sanitizer-tests.yaml
- src/cpp/rtps/xmlparser/XMLElementParser.cpp
This fixes an error on #3841 detected by the asan job, due to a submatch being used after modifying the original input string.
> Fix heap-use-after-free on XMLElementParser.cpp

- include/fastdds/rtps/history/History.h
- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- src/cpp/rtps/history/History.cpp
- src/cpp/rtps/history/ReaderHistory.cpp
- src/cpp/rtps/history/WriterHistory.cpp
- test/blackbox/common/BlackboxTestsPubSubHistory.cpp
- test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
`History::remove_change` return statement was based on the fact that `remove_change_nts` return a `History::iterator` different than `end` iteration. However, `remove_change_nts` was also calling `erase` method and this will return the iterator pointing to the next element of the collection or `end` if that was the last element. Therefore, `remove_change_nts` could return `end` iterator and still be the expected result. 
This PR updates two main functions:
- `remove_change_nts`. This function will return the same iterator in case it could not remove the change.
- `History::remove_change`. This function will check if the change pointed by the iterator returned by `remove_change_nts` is the expected one (next iterator in the History colection) or not (same iterator).
This PR also expects to …
> [19590] Change history remove change return statement

- .github/workflows/reusable-windows-ci.yml
- .github/workflows/windows-ci.yml
> [19578] Fix OpenSSL path on Windows CI

- examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorld.cxx
- examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorld.h
- examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorld.idl
- examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorldCdrAux.hpp
- examples/cpp/dds/HelloWorldExampleDataSharing/HelloWorldPubSubTypes.h
One of the Data-sharing constraints is that the types must be bounded. In the Data-sharing helloworld example, it is forced to use datasharing but the IDL types do not use bounded strings. 
This Pull Request updates IDL to use bounded string, and regenerates the types with the bounded string.
@Mergifyio backport 2.11.x 2.10.x 2.6.x 
Fixes #3710 
- **N/A** New feature has been documented/Current …
> [19089] Fix HelloWorld DataSharing example idl

- include/fastrtps/utils/TimedMutex.hpp
This PR changes to the the STL implementation the Timed/RecursiveTimedMutex in MSVC >= 19.36.
_Note: Tested compilation against 19.37.32824.0_
Fixes #3783 
Fixes #3829
**N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
**N/A**  New feature has been added to the `versions.md` file (if applicable).
**N/A**  New feature has been documented/Current behavior is correctly described in the documentation.
> [19642] Use STL implementation of Timed/RecursiveTimedMutex when MSVC >= 19.36

- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.hpp
- test/unittest/dds/publisher/DataWriterTests.cpp
This PR fixes a regression introduced in #3879.
It adds a regression test and also refactors the method performing the DataWriterQos assignment.
This regression was discovered while reviewing the backports, so it does not need to be automatically backported.
Its merge commit should be cherry-picked in the backports for #3879 instead.
Related documentation PR: eProsima/Fast-DDS-docs#575
- **N/A (see description)** Applicable backports have been included in the description.
> [19687] Fix updatability of immutable DataWriterQos

- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
This PR introduces a `LOG_ERROR` message to indicate that it was not possible to build a receiver resource. This can be useful in case of using SHM transport and being unable to open or regenerate a port file even after trying with all mutation tries.
_Note: It can be argued if we should print the particular locator in the error message. I left it as it is in order not to expose more information than adequate_
@Mergifyio backport 2.11.x 2.10.x 2.6.x 
Fixes #3535, #3536
- …
> [19638] Log error message upon receiver resource creation failure

- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
This reworks what was done on #3924, so
1. The log is a warning instead of an error
2. The log is not always shown, since there are places (unique network flows, for instance) where several calls to `createReceiverResources` are done, and an error log is shown when all of them fail.
> [19773] Rework log upon receiver resource creation failure

- include/fastrtps/utils/IPLocator.h
- src/cpp/rtps/transport/ChainingSenderResource.hpp
- src/cpp/rtps/transport/TCPSenderResource.hpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/UDPSenderResource.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemSenderResource.hpp
- src/cpp/utils/IPLocator.cpp
- test/blackbox/common/BlackboxTestsTransportCustom.cpp
This PR fixes an incorrect behavior when a `TCP client` receives the discovery information from a `TCP server` with a WAN configured in the locator. It creates more sender resources than needed as it fails to recognize that the ones already created were matching the target ones.
@Mergifyio backport 2.11.x 2.10.x 2.6.x 
> [19665] Hotfix TCP sender resources creation

- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
- test/blackbox/common/BlackboxTestsPubSubBasic.cpp
- test/blackbox/common/BlackboxTestsSecurity.cpp
This PR adds two blackbox tests to check that a participant with a fixed GUID prefix is re-discovered when it is re-created, both with and without security.
> [19769] Add tests for reconnection with same GUID

- test/unittest/rtps/flowcontrol/CMakeLists.txt
The Flow controllers unit test end up including `<fastcdr/cdr/fixed_size_string.hpp>` through the internal header `src/cpp/statistics/types/types.h`, but they do not link with Fast CDR. In a colcon context this is OK as Fast CDR will always be compiled and installed before compiling Fast DDS, so its header are in the include path when compiling the unit tests. However, when using the Fast CDR submodule, CMake may start by compiling the unit tests prior to Fast CDR and Fast DDS, and in that case the Fast CDR headers are not in the include path. This PR fixes this by explicitly linking with Fast CDR in those tests.
- *N/A*: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the …
> [19839] Fix flow controllers utests compilation when using Fast CDR from thirdparty

- src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/regressions/19354_2_profile_bin.xml
- test/unittest/xmlparser/regressions/19354_profile_bin.xml
Bit mask's bit bound attribute can be set to values out of expected bounds (0 < bit_bound < 65) through XML configuration. This PR add a check in XML parser to avoid it.
- **N/A**  New feature has been documented/Current behavior is correctly described in the documentation.
> [19354] Add XML parser bit_bound bounds check

- include/fastdds/rtps/messages/CDRMessage.h
- include/fastdds/rtps/messages/CDRMessage.hpp
> Simplify code in CDRMessage

- src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/regressions/19851_profile_bin.xml
Struct's name attribute is mandatory to be set while configuring types through XML configuration. This PR add a check in XML parser to fail if no name was defined.
> [19851] Fix missing mandatory attribute check in XML parser struct type

- include/fastdds/rtps/transport/test_UDPv4TransportDescriptor.h
- src/cpp/rtps/transport/test_UDPv4Transport.cpp
- src/cpp/rtps/transport/test_UDPv4Transport.h
- test/blackbox/common/BlackboxTestsPubSubHistory.cpp
The `PubSubHistory/PubSubHistory.PubSubAsReliableKeepLastWithKeyUnorderedReception` consistently fails if it is launched with `taskset -c 2 [command]` (which makes the test to run in one core). The reason is that the `drop data percentage` deterministically drop every 1 out of 5 DATA packages sent (User endpoints only, discovery traffic endpoints are not considered, so any change in the discovery settings results in no effect).
The changes let the `test_UDPTransportDescriptor` percentages to be dynamically updated, and proposes a fix for the test which consists in varying the drop percentage after having received some packets.
Note: The complete launch command is `taskset -c 2 ./BlackboxTests_DDS_PIM --gtest_filter=PubSubHistory/PubSubHistory.PubSubAsReliableKeepLastWithKeyUnorderedRecepti …
> [19870] PubSubAsReliable test fix 

- src/cpp/rtps/transport/shared_mem/SharedMemChannelResource.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
- test/blackbox/common/BlackboxTestsTransportSHM.cpp
This PR avoids an ` Error receiving data: No such file or directory` warning when processing a descriptor for which the segment does not exist anymore.
-  Not sure if we can backport this completely, since I have changed the category of some warnings, which can be considered a behavior change
> [19869] SHM transport: ignore non-existing segment on pop

- src/cpp/utils/IPFinder.cpp
This pull request fixed #3982: Mac address overflow in `IPFinder::getAllMACAddress()` on Windows.
`IP_ADAPTER_ADDRESSES::PhysicalAddressLength` will get max up to 8 bytes, but we have only 6 bytes for mac address.
In some case, `GetAdaptersAddresses()` will report address with `PhysicalAddressLength=8`, e.g. "Microsoft Teredo Tunneling Adapter", which will cause crash at `DomainParticipantFactory::create_participant()`. All 8 bytes of `IP_ADAPTER_ADDRESSES::PhysicalAddress` here are `0` in this situation, so use minimal length 6 does not affect the result.
This bug fix could be backported to older versions.
This fix is valid for all versions since `v2.6.6` up to `master`, older versions not checked yet. It should be merged to all branches having `IPFinder::getAllMACAddress()`.
- No new …
> Fix: mac address overflow on windows

- test/unittest/utils/SystemInfoTests.cpp
This PR introduces a fix for the `SystemInfoTests.FileWatchTest`. Under some circumstances, specially when the test is executed in a low resources context (1~2 cores) and a windows machine, the first `write` operation in the file can be performed before the `watch_thread` reaches the `WaitForMultipleObjects()` call. Hence, the event of changing the file is lost and the test fails with timeout.
The fix simply introduces an initial waiting time before performing the first write operation, giving enough time for the `watch_thread()` to be correctly scoping for directory changes. 
- **N/A** …
> [19889] FileWatchTest fix for github windows ci

- include/fastdds/rtps/transport/test_UDPv4TransportDescriptor.h
PR #3994 was merged with warnings in Mac. This PR fixes those warnings by deleting the copy/move constructor/assignment from `test_UDPv4TransportDescriptor`.
**Note:** Since backports of #3994 have not yet been merged, it would be a good idea to cherry pick the only commit in this PR to those backports.
- **NO** Changes are API compatible. 
- Though changes are not API compatible, the transport descriptor is only used for testing purposes, and it is always constructed with `std::make_shared`, so nothing should break
- *N/A* New feature has been …
> [19913] Make `test_UDPv4TransportDescriptor` non-copyable and non-moveable

- .github/workflows/mirror.yml
- CMakeLists.txt
- RELEASE_SUPPORT.md
- package.xml
This PR:
* Changes the master branch mirror to 2.13.x to prepare for the branch out
* Bumps Fast DDS version to 2.13.0, as the subsequent PRs will already break ABI or add new features
**IMPORTANT**: This PR should be merged right after #3970.
**IMPORTANT**: Remember to create a `2.13.x` branch spawning from master right after merging #3970.
- *N/A*: New feature has been documented/Current behavior …
> [19860] Bump version to 2.13.0

- include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
Fixes ununitialized error reported by valgrind. Kudos @pablogs9 
@Mergifyio backport master
> Fix uninitialized member

- test/unittest/xmlparser/XMLProfileParserTests.cpp
Fixes compilation of XMLProfileParserTests when building w/o security
> [19887] Fix compilation of XMLProfileParserTests

- test/blackbox/common/BlackboxTestsTransportSHM.cpp
Makes the behavior of `SHM.IgnoreNonExistentSegment` black-box test specific on each platform.
@Mergifyio backport 2.12.x
> [19887] Improve IgnoreNonExistentSegment test

- test/blackbox/common/BlackboxTestsTransportSHM.cpp
This PR fixes a warning introduced by #4036.
**Backport note:** Since #4036 has not yet been backported (to 2.12.x), it would be a nice idea to backport it along with this one.
> [20017] Fix warning in Mac rewarding unnecessary lambda capture

- src/cpp/statistics/fastdds/domain/DomainParticipant.cpp
ReturnCode_t compilation error when compiling with FASTDDS_STATISTICS=OFF
> [20049] Bug ReturnCode_t FASTDDS_STATISTICS=OFF

- src/cpp/rtps/transport/UDPv4Transport.cpp
- src/cpp/rtps/transport/UDPv6Transport.cpp
- test/blackbox/common/BlackboxTestsNetworkConf.cpp
- test/unittest/transport/UDPv4Tests.cpp
- test/unittest/transport/UDPv6Tests.cpp
- test/unittest/transport/mock/MockReceiverResource.h
Fixes a bug in Windows where a participant without whitelist ends up listening on the same unicast ports as a participant with whitelist. This made the whitelist participant get the incoming traffic to that port, making the non-whitelist one deaf to it.
> [19587] Use `SO_EXCLUSIVEADDRUSE` for Win32 unicast listening sockets

- include/fastdds/dds/xtypes/common.hpp
- include/fastdds/dds/xtypes/type_representation/TypeObjectRegistry.hpp
- include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
- src/cpp/CMakeLists.txt
- src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
- src/cpp/fastdds/xtypes/type_representation/TypeObjectUtils.cpp
- src/cpp/fastdds/xtypes/type_representation/dds_xtypes_typeobjectCdrAux.ipp
- src/cpp/fastdds/xtypes/type_representation/dds_xtypes_typeobjectPubSubTypes.cxx
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/dds/status/CMakeLists.txt
- test/unittest/dds/xtypes/type_representation/CMakeLists.txt
- test/unittest/dds/xtypes/type_representation/TypeObjectRegistryTests.cpp
- test/unittest/dds/xtypes/type_representation/TypeObjectUtilsTests.cpp
- test/unittest/statistics/dds/CMakeLists.txt
- utils/scripts/update_generated_code_from_idl.sh
This PR depends on #3974.
This PR implements:
* TypeObjectRegistry API with exception to `TypeObjectRegistry::are_types_compatible`.
* Public API unit tests.
- [N/A] The PR has a milestone assigned.
> [19837] TypeObjectRegistry implementation

- .github/workflows/reusable-windows-ci.yml
This PR changes the way in which failed tests are re-run up to 3 tries from the colcon option to the ctest's one
> [20035] Rerun failed tests with ctest option instead of colcon's

- .github/workflows/reusable-windows-ci.yml
Github Windows CI on pushes to 2.6.x is failing because the push event passes branch `refs/head/2.6.x`, and since there is not .repos file for such branch (there is one for 2.6.x), the CI was defaulting to looking for a `default_ci_master.repos` file, which in 2.6.x does not exist. This PR fixes this quirk.
- See #4087
- *N/A*: New …
> [20022] Select correct .repos file on push events

- .github/workflows/reusable-windows-ci.yml
Github Windows CI on pushes to 2.10.x is failing because the push event passes branch `refs/head/2.10.x`, and since there is not .repos file for such branch (there is one for 2.10.x), the CI was defaulting to looking for a `default_ci_master.repos` file, which in 2.10.x does not exist. This PR fixes this quirk.
- *N/A*: New feature has …
> [20023] Select correct .repos file on push events

- .github/workflows/documentation-tests.yaml
Improve handling of events on Github docs CI
- *N/A* Check CI results: failing tests are unrelated with …
> [20024] Better handling of trigger events in docs CI

- src/cpp/rtps/transport/TCPAcceptor.cpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/TCPTransportInterface.h
- src/cpp/rtps/transport/TCPv4Transport.cpp
- src/cpp/rtps/transport/TCPv6Transport.cpp
- test/blackbox/CMakeLists.txt
- test/blackbox/common/BlackboxTestsTransportTCP.cpp
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
Related documentation PR: https://github.com/eProsima/Fast-DDS-docs/pull/598 (PR) 
> [20019] Add Autofill port to TCP Transport

- .github/workflows/documentation-tests.yaml
Improve handling of events on Github docs CI
> [20035] Better handling of trigger events in docs CI

- include/fastdds/dds/domain/DomainParticipantListener.hpp
Mark the old overload of `on_participant_discovery` to be removed in v3.0.
Addresses #4043.
> [20068] Mark on_participant_discovery overload removal

- test/blackbox/common/BlackboxTestsTransportSHM.cpp
This is a backport of #4036 along with #4052 into 2.12.x
> Improve IgnoreNonExistentSegment test (backport #4036)

- include/fastdds/dds/log/Log.hpp
- include/fastdds/rtps/attributes/ServerAttributes.h
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
Define a super client setting a new environment variable ROS_SUPER_CLIENT
Related documentation PR: eProsima/Fast-DDS-docs#596
> [19967] Define a super client by environment variable 

- src/cpp/rtps/transport/TCPTransportInterface.cpp
- test/blackbox/common/BlackboxTestsTransportTCP.cpp
- test/blackbox/common/TCPReqRepHelloWorldReplier.cpp
- test/blackbox/common/TCPReqRepHelloWorldReplier.hpp
TCP channel reuse required joining the thread in charge of the previous channel. However, this call to `join()` involved taking some mutex that prevented the old thread from finishing its tasks, leading to a deadlock.
The disabling of the old channel has been relocated as well as the protection of some other channel resources.
Fixes #4026 
-  *N/A* New feature has been added to the `versions.md` file (if applicable).
> [19939] TCP deadlock on channel reuse

- examples/cpp/dds/DiscoveryServerExample/DiscoveryServerPublisher.cpp
- examples/cpp/dds/DiscoveryServerExample/DiscoveryServerServer.cpp
- examples/cpp/dds/DiscoveryServerExample/DiscoveryServerSubscriber.cpp
- examples/cpp/dds/DiscoveryServerExample/DiscoveryServer_main.cpp
- examples/cpp/dds/DiscoveryServerExample/README.md
- examples/cpp/dds/DiscoveryServerExample/arg_configuration.h
- examples/cpp/dds/DiscoveryServerExample/common.h
- include/fastdds/rtps/attributes/ServerAttributes.h
- include/fastdds/rtps/common/Locator.h
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
- test/unittest/utils/LocatorTests.cpp
- tools/fds/server.cpp
- tools/fds/server.h
- versions.md
This PR adds TCPv4/6 support for both the Fast DDS CLI and the ROS_DISCOVERY_SERVER environment variable. 
Related tests: https://github.com/eProsima/Discovery-Server/pull/66 (PR)
Related documentation PR: https://github.com/eProsima/Fast-DDS-docs/pull/599 (PR)
> [20021] TCP support for Discovery server CLI and env. var.

- test/unittest/dds/participant/CMakeLists.txt
Fix dns filter of tests in CMakeLists file 
@Mergifyio backport 2.12.x 2.11.x 2.10.x
> Fix dns filter in CMakeLists file

- src/cpp/rtps/messages/RTPSMessageGroup.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/blackbox/common/BlackboxTests.hpp
- test/blackbox/common/BlackboxTestsSecurity.cpp
- test/blackbox/common/BlackboxTestsTransportTCP.cpp
- test/blackbox/common/DDSBlackboxTestsSecurity.cpp
- test/blackbox/common/TCPReqRepHelloWorldReplier.cpp
- test/blackbox/common/TCPReqRepHelloWorldReplier.hpp
- test/blackbox/common/TCPReqRepHelloWorldRequester.cpp
- test/blackbox/common/TCPReqRepHelloWorldRequester.hpp
> [13364] Fix memory problem when ciphering payload

- include/fastdds/dds/topic/TopicDataType.hpp
- src/cpp/CMakeLists.txt
- src/cpp/fastdds/topic/TopicDataType.cpp
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/dds/status/CMakeLists.txt
- test/unittest/dds/subscriber/CMakeLists.txt
- test/unittest/dds/topic/DDSSQLFilter/CMakeLists.txt
- test/unittest/dynamic_types/CMakeLists.txt
- test/unittest/rtps/builtin/CMakeLists.txt
- test/unittest/rtps/discovery/CMakeLists.txt
- test/unittest/rtps/network/CMakeLists.txt
- test/unittest/statistics/dds/CMakeLists.txt
- test/unittest/statistics/rtps/CMakeLists.txt
- test/unittest/xmlparser/CMakeLists.txt
- test/unittest/xtypes/CMakeLists.txt
The write operation in latest versions of Fast DDS calls the new serialize method in which the topic data representation is needed (`serialize(void* data, SerializedPayload_t* payload, DataRepresentationId_t data_representation)`). If the data type was generated with old versions of Fast DDS Gen, this function is not implemented in the type support so the write operation will fail. This PR updates the default behaviour of this function so it will call the old serialize method in case this one is not overridden. 
@Mergifyio backport 2.12.x
- *N/A*: New …
> [20134] Change serialize function default behaviour to omit the data representation

- test/blackbox/common/BlackboxTests.cpp
- test/blackbox/common/BlackboxTests.hpp
- test/blackbox/common/BlackboxTestsSecurity.cpp
This fixes a build regression introduced by #2485 when `SECURITY=OFF` and `NO_TLS=OFF`.
> [20055] Fix build with TLS, but not security.

- src/cpp/rtps/writer/RTPSWriter.cpp
- test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
There is a data race on the access to StatefulWriter's history between the events thread (sending heartbeat), and the main thread (or the one from where the writer is deleted), which results in a deadlock.
More specifically, the thread sending heartbeat gets stuck in an infinite loop (while within StatefulWriter's add_gaps_for_holes_in_history_ ) since the cache change involved had been released (hence its sequence number set to 0) from the thread destroying the writer (RTPSWriter::deinit) without protection. A priori, the solution would be to protect the destruction to avoid the data race.
This could be replicated often with BasicConfigurationExample, by increasing the heartbeat sending period to raise the probability of occurrence: …
> [20060] Fix data race on writer destruction while sending hearbeat

- src/cpp/rtps/attributes/RTPSParticipantAttributes.cpp
This PR apply a bugfix removing the SHM locators of the metatrafficUnicastLocator in the LARGE_DATA mode.
@Merfigyio backport 2.6.x 2.10.x 2.11.x 2.12.x
- _N/A_ Changes are ABI compatible. 
- _N/A_ Check CI results: changes do not issue any warning.
- _N/A_ Check CI results: failing tests are unrelated with the changes.
> [20020] Remove SHM locator from metatrafficUnicastLocList in LARGE_DATA

- src/cpp/rtps/transport/TCPTransportInterface.cpp
- test/blackbox/common/BlackboxTestsTransportCustom.cpp
- test/blackbox/common/BlackboxTestsTransportTCP.cpp
- test/blackbox/common/TCPReqRepHelloWorldReplier.cpp
- test/blackbox/common/TCPReqRepHelloWorldReplier.hpp
- test/blackbox/xfail_tests.cmake
This reverts #4099 since it has introduced deadlocks in TCP.
@Mergifyio backport 2.12.x 2.11.x 2.10.x
- _N/A_ The PR has a milestone assigned.
> Revert "TCP deadlock on channel reuse (#4099)"

- CMakeLists.txt
- RELEASE_SUPPORT.md
- package.xml
- versions.md
This PR bumps 2.6.x version to 2.6.7, and syncs `RELEASE_SUPPORT.md` with master
> [20022] Bump version to 2.6.7

- src/cpp/rtps/builtin/discovery/participant/DS/PDPSecurityInitiatorListener.cpp
- src/cpp/rtps/security/SecurityManager.cpp
- test/blackbox/common/BlackboxTestsSecurity.cpp
This PR fixes a data race occurring in `PDPListenerSecurityInitiator`  affecting `SecurityManager`. The `temp_participant_data_` was being overwritten as `discovered_participant()` was being called without the `PDP` mutex taken. This causes a corruption when the secure participant was in the middle of matching to a previous secure participant.
This PR also ensures that the `discovered_participant()` method is using the `ParticipantProxyData` from the `discovered_participants` collection.
_Note: openning as draft as proper test needs to be added_
@Mergifyio backport 2.12.x 2.11.x 2.10.x
> [20166] Fix data race in PDPListener and SecurityManager

- thirdparty/filewatch/FileWatch.hpp
When compiling Fast-DDS with clang, it shows a warning that the use of std::move in FileWatch.hpp is pessimizing. Remove the unnecessary std::move here, which fixes the warning.
Note that this is against the 2.11.x branch, which is what we are using in ROS 2.  But I can retarget it to `master` if that is preferred.
- [??] Changes are ABI compatible. 
> Remove a pessimizing move.

- test/communication/multiple_secure_ds_pubsub_secure_crypto_communication.py
- test/communication/secure_ds_pubsub_secure_crypto_communication.py
PR #3616 was not backported into 2.6.x because secure discovery server feature had not been backported.
Now that it has (commit 4f53410273e6a9d11ba83a9ee77c306d94c809c9), the Windows github action is failing with a python exception that was fixed by #3616.
This PR backports that fix by cherry-picking 802f224a9f4b2af6bb2500d7d689a4870e440581
- **N/A** Commit messages follow the project guidelines. 
- **N/A** New feature has been documented/Current behavior is correctly …
> [20022] Fix Github Windows CI (backport #3616)

- src/cpp/rtps/attributes/RTPSParticipantAttributes.cpp
This PR includes a static cast to void of the `RTPSParticipantAttributes` argument when `FASTDDS_SHM_TRANSPORT_DISABLED` is set. This caused build issues in windows in some github runners that were disabling SHM transport for some reason.
The static cast solves those build issues
**N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
**N/A** New feature has been documented/Current behavior is correctly described in the documentation.
> Add static cast to unused variable in RTPSParticipantAttributes

- .github/workflows/reusable-windows-ci.yml
- include/fastdds/rtps/messages/CDRMessage.hpp
- include/fastdds/rtps/security/logging/Logging.h
- include/fastrtps/utils/fixed_size_bitmap.hpp
- src/cpp/fastdds/subscriber/history/DataReaderInstance.hpp
- src/cpp/rtps/DataSharing/WriterPool.hpp
- src/cpp/rtps/builtin/liveliness/WLP.cpp
- src/cpp/rtps/flowcontrol/FlowControllerImpl.hpp
- src/cpp/rtps/history/CacheChangePool.cpp
- src/cpp/rtps/history/TopicPayloadPool.cpp
- src/cpp/rtps/network/NetworkFactory.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- src/cpp/rtps/security/logging/Logging.cpp
- src/cpp/rtps/transport/shared_mem/test_SharedMemTransport.cpp
- src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.cpp
- src/cpp/security/cryptography/AESGCMGMAC_Types.h
- test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp
- test/unittest/utils/BitmapRangeTests.cpp
- test/unittest/xmlparser/XMLProfileParserTests.cpp
Several Github Windows CI have started to fail for the same reason, even though the base branches are different:
* https://github.com/eProsima/Fast-DDS/actions/runs/7538695931/job/20519719577#step:18:501
* https://github.com/eProsima/Fast-DDS/actions/runs/7537913605/job/20517574924?pr=4246
* https://github.com/eProsima/Fast-DDS/actions/runs/7537990202/job/20517771780?pr=4247
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x 
- _N/A_: New feature has been documented/Current …
> [20255] Fix max clash with Windows CI

- include/fastdds/dds/publisher/Publisher.hpp
- include/fastdds/dds/subscriber/Subscriber.hpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.hpp
- src/cpp/fastdds/publisher/Publisher.cpp
- src/cpp/fastdds/publisher/PublisherImpl.cpp
- src/cpp/fastdds/publisher/PublisherImpl.hpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/fastdds/subscriber/Subscriber.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.hpp
- src/cpp/statistics/fastdds/publisher/DataWriterImpl.hpp
- src/cpp/statistics/fastdds/publisher/PublisherImpl.hpp
- src/cpp/statistics/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/statistics/fastdds/subscriber/SubscriberImpl.hpp
- test/blackbox/api/dds-pim/CustomPayloadPool.hpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/unittest/common/CustomPayloadPool.hpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
- test/unittest/statistics/dds/StatisticsDomainParticipantMockTests/mock/statistics/fastdds/publisher/PublisherImpl.hpp
This pull request aims to expose the usage of a custom payload pool implementation on the DDS layer
> [20243] Custom pools on DDS layer feature (backport #3755)

- src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
This fix already exists on master, so this is a backport of just this fix onto 2.11.x.  This gets rid of a possible use of an uninitialized value warning when building with gcc 13.2.0
Partial backport of #3828 
> Fix an uninitialized value when building with gcc 13.2.0

- src/cpp/rtps/transport/TCPTransportInterface.cpp
When sending TCP messages, the locator selector from the publisher includes the locators to which messages will be sent. These locators are compared with the send_resource_list_. If there are more than two endpoints available (locators A and B), the following checks are made: A==A, A==B, B==A, B==B.
Successful checks end in trying to send data to the correspondent locator.
Mismatching checks produce a warning, though it is actually correct behavior.
- N/A New feature has been added to the `versions.md` file (if …
> [20121] Remove unnecessary TCP warning

- include/fastdds/rtps/builtin/data/ParticipantProxyData.h
- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
This PR fixes a datarace in `PDPListener` that was causing assertions on Windows Debug. Prior to this PR, if a DATA(P) of an already discovered participant was received through multicast (the sample has already been processed since the data is the just the periodic announcement of the remote participant) while a DATA(uP) (or an update changing locators) is being processed on one of the metta-traffic unicast reception threads, then processing the DATA(P) could segfault while iterating over a collection of locators that the DATA(uP) processing has already deleted.
This PR fixes that data race by avoiding processing a sample which has already been processed, thus avoiding re-processing of periodic announcements.
- _N/A_: Tests that thoroughly …
> [20276] Discard already processed samples on PDPListener

- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
- test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
This PR fixes an interoperability issue introduced in #3733 occurring when a different vendor sends a DATA(p) which parameter list is to contain a parameter with PID 0x8007, which in Fast DDS is a custom PID (`PID_NETWORK_CONFIGURATION_SET`). When that happens, the deserialization in Fast DDS most likely fails or even worse gets a wrong interpretation.
Tested with [CycloneDDS ShapesDemo](https://github.com/atolab/dds-ishapes) and Fast DDS ShapesDemo (setting the `auto_fill_type_information` to `false` using eProsima/ShapesDemo#107).
@Mergifyio backport 2.12.x
- _N/A_: New feature has been documented/Current behavior is correctly …
> [20306] Ignore 0x8007 if coming from other vendor

- src/cpp/fastdds/log/Log.cpp
- src/cpp/fastdds/log/LogResources.hpp
Every log call gets the verbosity of the log by calling `get_log_resources()->GetVerbosity()`. Prior to this PR, the call to `get_log_resources()` would copy the internal shared pointer, which can become a costly operation, specially in a multithreaded context. This PR changes that internal method to return a `const` reference to the shared pointer instead of a copy.
- _N/A_: New feature has been documented/Current behavior is …
> [20283] Return const reference in get_log_resources

- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
- test/blackbox/common/BlackboxTestsPubSubFragments.cpp
When a keyed fragmented change is completed, notify the data instance and add the change in that moment instead of adding the change when it is still not fully assembled. This PR also makes the Stateless/full readers  take the serialized key only from the fragment number `1`.  
- **N/A**New feature has been documented/Current behavior is correctly described in the documentation.
> [20257] Add a keyed fragmented change to the reader data instance only when its completed

- tools/fds/server.cpp
While closing the terminal by clicking the X button, it seems that the signal emitted was SIGHUP.
For that reason, by handling that signal the application properly closes in those scenarios.
It may be interesting to handle this signal also in several eProsima products. What do you think about the following list, @Mario-DL?
Fast DDS CLI, Fast DDS pipe, router, monitor, record, replay, spy.
**EDIT:**
After [research](https://www-uxsup.csx.cam.ac.uk/courses/moved.Building/signals.pdf) , I've included the following signals to handle as terminate:
1. SIGQUIT: Quit signal. Similar to SIGINT, but also produces a core dump of the process.
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its …
> [19587] Include variety of terminate proccess signals handler in discovery server

- src/cpp/rtps/messages/submessages/DataMsg.hpp
- test/blackbox/common/BlackboxTestsKeys.cpp
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
This PR corrects the behavior of the DataWriters on keyed topics. Currently, if the DataReader does not `expect_inline_qos`, then the DataWriter is not sending the key despite of publishing on a keyed topic.
This PR makes the DataWriter always send the key regardless of the configuration of the reader if the topic is keyed.
_Note: the builtin endpoints are retrieving the key in their listeners. In fact, its the first thing they do (`computeKey()`). It is true that they are the filling the `instancehandle` from the `PID_ENDPOINT_GUID` instead of the `PID_KEY_HASH` which could be arguable if we are strict, but in essence, both carry the same information, the complete `guid` of the entity_ 
- **N/A** Any new/modified methods have been properly …
> [20239] Make DataWriters always send the key hash on keyed topics

- .github/workflows/documentation-tests.yaml
- .github/workflows/sanitizer-tests.yaml
Modify GitHub CI workflow for fastdds 3.0.x
-N/A Applicable backports have been included in the description.
> GitHub CI for 3.0.x

- src/cpp/rtps/transport/TCPChannelResource.h
- src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
- src/cpp/rtps/transport/TCPChannelResourceBasic.h
- src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
- src/cpp/rtps/transport/TCPChannelResourceSecure.h
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/TCPTransportInterface.h
- test/unittest/transport/mock/MockTCPChannelResource.cpp
- test/unittest/transport/mock/MockTCPChannelResource.h
In some instances, requesting server info after client connection caused exceptions (transport endpoint is not connected). This behavior was observed after PR #4258.
We now also use ASIO's non-throwing methods for this request, ensuring any errors are appropriately handled.
> [20262] Add non-throwing getters for socket info

- test/unittest/rtps/DataSharing/SHMSegmentTests.cpp
While compiling with `gcc 13.2.0` [here](https://github.com/eProsima/Fast-DDS/pull/4340), a `maybe-unitialized` warning was triggered. This PR fixes the issue by giving an initial value to the pointer.
> [20272] Avoid a maybe-uninitialized warning 

- include/fastdds/dds/log/Log.hpp
- src/cpp/fastdds/log/Log.cpp
This commit introduces a new ostream serialization function for the Log::Kind enumeration, allowing seamless output to ostream objects. The function includes a switch statement of Log::Kind values to their corresponding string representations (INFO, WARNING, ERROR).
> Add serialization for Log::Kind to ostream

- include/fastrtps/config/doxygen_modules.h
- include/fastrtps/types/AnnotationParameterValue.h
- include/fastrtps/types/TypeIdentifierTypes.h
- include/fastrtps/types/TypeObjectHashId.h
- include/fastrtps/xmlparser/XMLEndpointParser.h
- include/fastrtps/xmlparser/XMLProfileManager.h
This PR fixes some minor typos and declares some extra `groups` into the `doxygen_modules.h` file that fixes a compilation warning stating that the `@ingroup` doxygen macros did not point to a valid group. 
Before doxygen `1.10.0` it was not considered a warning, but, as we define `WARN_AS_ERROR` to `YES` in the `doxyfile.in`, we fail to compile with with `doxygen >= 1.10.0` since it is treated as a warning henceforth.
Two considerations:
* This PR does NOT upgrade the `doxyfile.in` to `1.10.0` yet, so building with `doxygen 1.10.0` and `-DBUILD_DOCUMENTATION=ON` outputs a bunch of info messages complaining that some of the configuration options are obsolete, but now, the compilation finishes successfully.
* Some of the fixes affect the `/types` directory which is going to be deprecated …
> [20413] Fix doxygen docs warnings. Prepare for compiling with Doxygen 1.10.0

- src/cpp/rtps/DataSharing/DataSharingPayloadPool.cpp
- src/cpp/rtps/DataSharing/ReaderPool.hpp
- test/dds/communication/CMakeLists.txt
- test/dds/communication/PubSubMain.cpp
- test/dds/communication/PublisherMain.cpp
- test/dds/communication/PublisherModule.cpp
- test/dds/communication/PublisherModule.hpp
- test/dds/communication/SubscriberMain.cpp
- test/dds/communication/SubscriberModule.cpp
- test/dds/communication/SubscriberModule.hpp
- test/dds/communication/definitions_example.json
- test/dds/communication/simple_data_sharing_stress.json
- test/dds/communication/test_build.py
When a DataSharing compatible publisher and subscriber were launched at high frequency (publication interval set to `0`), it happened two different issues:
* The current `notified_end` of the segment iterator was being updated before being actually checked, making an `assert()` compare two different versions of this iterator.
* On the other hand, unrelated with the previous observation, a corner case of advancing twice the `next_payload_` counter could occur.
Apart from the included test, in order to reproduce the first issue it is enough to launch a `BasicConfigurationExample` with a `bounded` type and no sleep between`writes()`. Launching, killing and relaunching the subscriber should trigger the `assertion`.
For reproducing the second issue, launch the subscriber first and then the …
> [20227] Prevent index overflow and correctly assert the end iterator in DataSharing

- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
- test/unittest/dds/profiles/test_xml_profile.xml
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
This PR introduces a check to ensure that the history QoS is consistent in both DataWriter and DataReader creation.
In this case, it checks that if history kind is set as `KEEP_LAST`, the history depth must be higher than zero.
**Edit**: Check between history depth and resource limits' `max_samples_per_instance` also included
Fixes #4365 
Related documentation PR: eProsima/Fast-DDS-docs#664
> [20401] Check History QoS inconsistencies

- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/TCPTransportInterface.h
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
- test/unittest/transport/mock/MockTCPv4Transport.h
- test/unittest/transport/mock/MockTCPv6Transport.h
This pull request addresses a bug related to the initialization of TCP servers when multiple interfaces are added to the whitelist. The issue stemmed from the unnoticed overwriting of the acceptors_ map because of the comparison of locators without properly setting their addresses.
> [20238] Enabling multiple interfaces through whitelist in TCP servers 

- src/cpp/rtps/transport/TCPChannelResource.cpp
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
- test/unittest/transport/mock/MockTCPv4Transport.h
- test/unittest/transport/mock/MockTCPv6Transport.h
When a client sends an openLogicalPortRequest while the server's input channels are already closed, it previously resulted in the deletion of the requested logical port from pending_logical_output_ports_, making server reconnection impossible. This update addresses the issue by ensuring that a port in pending_logical_output_ports_ is only removed if it is being transferred to the logical_output_ports_ vector. This change is enables effective server reconnection after an initial failure in an openLogicalPort request.
@Mergifyio backport 2.12.x 2.10.x 2.6.x
- N/A New feature has been documented/Current behavior is correctly described in the …
> [20141] Fix TCP reconnection after open logical port failure

- examples/cpp/dds/SecureHelloWorldExample/HelloWorldPublisher.cpp
As a consequence of https://github.com/eProsima/Fast-DDS/pull/4375, the `DDSSecureHelloWorldExample publisher` is failing to initialize. This PR just modifies the history `depth` value to be the same as the `max_samples_per_instance`.
I also checked to launch other examples modifying the `max_samples_per_instance` and are OK. Nonetheless, I encourage the reviewer to double check that.
_Note: We may cherry pick this commit in https://github.com/eProsima/Fast-DDS/pull/4408 and https://github.com/eProsima/Fast-DDS/pull/4406 and backport only to `2.10.x`_
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests …
> [20485] Fix SecureHelloworldExample

- tools/fastdds/shm/clean.py
Fix the regular expression that leads to skipping the processing of shared lock files by `fastdds shm clean` command.
To reproduce the problem you can use next script:
```
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> port_lock_re = re.compile('^fastrtps_port\\d{,5}_el|_sl')
>>> bool(port_lock_re.match('fastrtps_port7777_el'))
True
>>> bool(port_lock_re.match('fastrtps_port7777_sl'))
False      <----------------------------------------------------- here is a problem
>>> 
```
After this fix, the behavior will be as follow:
```
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re …
```
> Fix the shared memory cleaning script.

- include/fastdds/rtps/attributes/ServerAttributes.h
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
- test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
This PR intends to solve a race condition on PDP discovery phase, in which a data UP is received and processed while its corresponding previously received data P is still being processed.
As a result, the participant proxy created and registered can be cleared before calling assignRemoteEndpoints, as the PDP mutex is released just before (on purpose to avoid interlocking problems).
This issue has been reported by TSAN in this particular scenario, when the data P is received in the UDP multicast thread and then the data UP in the unicast one. However, this problem should also affect other scenarios such as:
- Same but with SHM transport.
- Same but receiving data P in unicast thread and data UP in multicast one.
- Losing remote participant's liveliness (events thread) while still …
> [19696][20409] Fix data race on PDP

- src/cpp/rtps/transport/TCPTransportInterface.cpp
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
This feature adds support for the unlikely case in which two participants configured with the LARGE_DATA builtin transports obtain randomly the same listening port. This case can only occur if the participants are located in different hosts and, thus, each of them has a different IP address.
Due to the logic implemented in the channel negotiation of the LARGE_DATA topology, unnecessary channels might be created if this case occurs, which will be addressed in the future.
@Mergifyio backport 2.12.x 2.10.x 2.6.x
- [_N/A_] Any new/modified methods have been properly documented using Doxygen. 
- [_N/A_] New feature has been added to the `versions.md` file (if applicable).
- [_N/A_] New feature has been documented/Current behavior is correctly described in the documentation.
> [20438] LARGE_DATA Participants logic with same listening ports

- include/fastdds/dds/builtin/typelookup/TypeLookupManager.hpp
- include/fastdds/dds/builtin/typelookup/TypeLookupReplyListener.hpp
- include/fastdds/dds/builtin/typelookup/TypeLookupRequestListener.hpp
- src/cpp/fastdds/builtin/typelookup/TypeLookupManager.cpp
- src/cpp/fastdds/builtin/typelookup/TypeLookupReplyListener.cpp
- src/cpp/fastdds/builtin/typelookup/TypeLookupRequestListener.cpp
This pull request addresses an issue where Fast DDS fails to discover certain types when receiving a significant number of dynamic types (approximately 25).
This PR implements the `onWriterChangeReceivedByAll` listener for both `TypeLookupReplyListener` and `TypeLookupRequestListener`. This enables the deletion of changes received by all readers matched with the writer from the history. It prevents the `CacheChange` from becoming saturated, thus enabling the system to accommodate further changes effectively.
@Mergifyio backport 2.12.x 2.10.x 2.6.x
- _N/A_; Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- N/A …
> [20311] Add missing TypeLookup listeners

- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- test/blackbox/common/DDSBlackboxTestsDataReader.cpp
- test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
This addresses a regression in ROS 2 (ros2/ros2#1527) after #4375 was merged.
Whenever a DataWriter is created taking the default `DataWriterQos`, and changing the history depth to a value greater than 400, the creation of the DataWriter fails. Same happens when creating a DataReader.
This PR partially reverts #4375, so the inconsistency is shown as a warnings instead of making the entity creation fail.
*For the other branches, we'll include this as part of the corresponding backport of #4375)
> [20504] Just show warning when inconsistency between depth and max_samples_per_instance

- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
This PR removes a `FASTDDS_TODO_BEFORE` 2.14 since it's preventing compilation. I will be addressed in a follow up before the v2.14.0 release
> [20510] Remove FASTDDS_TODO_BEFORE 2.14

- cmake/common/test_wrapper.cmake.in
- test/CTestCustom.cmake.in
- test/communication/CMakeLists.txt
- test/dds/communication/CMakeLists.txt
- test/dds/discovery/CMakeLists.txt
- test/performance/latency/CMakeLists.txt
- test/performance/throughput/CMakeLists.txt
- test/performance/video/CMakeLists.txt
- test/profiling/CMakeLists.txt
- test/system/tools/fastdds/CMakeLists.txt
- test/system/tools/fds/CMakeLists.txt
[`FindPythonInterp`](https://cmake.org/cmake/help/latest/policy/CMP0148.html) has been deprecated since CMake 3.12. This PR finds the python interpreter within CMake files using the supported [`FindPython3`](https://cmake.org/cmake/help/latest/module/FindPython3.html#module:FindPython3). This change if motivated by the intention of supporting Ubuntu 24.04, that ships CMake 3.28.3, version in which a CMake warning about `FindPythonInterp` is shown; this warning was introduced in CMake 3.27.
- _N/A_: Any new/modified methods have been properly documented using …
> [20511] Remove use of deprecated FindPythonInterp

- include/fastdds/dds/domain/DomainParticipantListener.hpp
- include/fastdds/rtps/transport/TCPTransportDescriptor.h
- include/fastdds/rtps/writer/IReaderDataFilter.hpp
- include/fastrtps/config.h.in
- src/cpp/rtps/transport/TCPTransportInterface.cpp
Up until this PR, the `FASTDDS_TODO_BEFORE` macro added a semicolon after its `static_assert`. This means that when using the macro, if a semicolon is added, a second semicolon ends up on the source after pre-processing, which can result in a compiler warning because of that extra semicolon. This PR: …
> [20517] Force usage of semicolon in FASTDDS_TODO_BEFORE macro

- src/cpp/utils/threading/threading_win32.ipp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/common/BlackboxTestsNetworkConf.cpp
- test/blackbox/common/BlackboxTestsTransportUDP.cpp
- test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
Fix warnings when compiling for Windows x86
> Fix warnings when compiling for Windows x86 [20519]

- include/fastdds/rtps/transport/TCPTransportDescriptor.h
- resources/xsd/fastRTPS_profiles.xsd
- src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
- src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/TCPTransportInterface.h
- src/cpp/rtps/xmlparser/XMLParser.cpp
- test/mock/rtps/TCPTransportDescriptor/fastrtps/transport/TCPTransportDescriptor.h
- test/system/tools/xmlvalidation/XMLTesterExample_profile.xml
- test/system/tools/xmlvalidation/all_profile.xml
- test/system/tools/xmlvalidation/transportDescriptor_profile.xml
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
Previously, the `non_blocking_send` mode for TCP was set as a non-consolidated QoS. It will now be configured as an attribute of the `TCPTransportDescriptor`.
Related documentation PR: eProsima/Fast-DDS-docs https://github.com/eProsima/Fast-DDS-docs/pull/678
> [20502] TCP non_blocking_send moved to TCPTransportDescriptor

- src/cpp/rtps/xmlparser/XMLElementParser.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/regressions/20187_profile_bin.xml
When a value out of the range is assigned to the attribute `port` of `thread_settings`, an exception was thrown but not catched. This PR adds a catch of out-of-range exception and a regression test.
@Mergifyio backport 2.13.x 
> [20187] Add catch of out-of-range exception for thread settings port

- include/fastdds/rtps/attributes/PropertyPolicy.h
- include/fastdds/rtps/common/Property.h
- src/cpp/rtps/attributes/PropertyPolicy.cpp
- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/rtps/security/SecurityManager.h
- test/blackbox/CMakeLists.txt
- test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
- test/blackbox/auth_handshake_props_profile.xml
- test/blackbox/common/BlackboxTestsSecurity.cpp
- versions.md
This PR adds the documentation for configuring the Authentication Handshake behavior through the following properties:
* max_handshake_requests
* initial_handshake_resend_period
* handshake_resend_period_gain
It also includes a simple `PropertyParser` for parsing properties as `int` and `double`.
<Related documentation PR: eProsima/Fast-DDS-docs#681
> [20439] Expose Authentication Handshake Properties 

- .github/workflows/documentation-tests.yaml
- .github/workflows/mac-ci.yml
- .github/workflows/sanitizer-tests.yaml
- .github/workflows/thread-sanitizer.yaml
- .github/workflows/windows-ci.yml
While backporting fixes and ABI compatible features to other supported versions branches, some of those backports can have conflicts caused by the cherry-pick.
In order to improve the performance of our CI and don't waste runners process time, **this PR avoids running any GitHub CI if the PR has been labeled with the `conflicts` label.**
**NOTE**: For the PR purposes, it has been labeled as `conflicts` to ensure that the GitHub CI is not run.
- **N/A** Any new/modified methods have been properly documented using …
> [20486] Avoid running GitHub CI if PR has conflicts

- include/fastdds/rtps/common/LocatorSelectorEntry.hpp
- include/fastdds/rtps/transport/TransportInterface.h
- src/cpp/CMakeLists.txt
- src/cpp/rtps/network/NetworkFactory.cpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/TCPTransportInterface.h
- src/cpp/rtps/transport/TransportInterface.cpp
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/rtps/discovery/CMakeLists.txt
- test/unittest/rtps/network/CMakeLists.txt
- test/unittest/statistics/dds/CMakeLists.txt
- test/unittest/statistics/rtps/CMakeLists.txt
- test/unittest/transport/CMakeLists.txt
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
- versions.md
Introduce new `OpenOutputChannels` and `CloseOutputChannels` methods to the `TransportInterface` base class, both accepting a `LocatorSelectorEntry` argument. This enhancement provides improved control over creating or destroying communication channels between participants.
- This PR depends on  #4300 and must be merged after that one. 
- ❌ Changes are ABI compatible. 
> [20492] OpenOutputChannels / CloseOutputChannels that receive a LocatorSelectorEntry

- src/cpp/rtps/transport/TCPTransportInterface.cpp
This PR introduces a hotfix to check the error code returned by asio when requesting the local_endpoint before trying to convert it to a locator. 
- [_N/A_] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [_N/A_] Any new/modified methods have been properly documented using Doxygen. 
- [_N/A_] New feature has been added to the `versions.md` file (if applicable).
- [_N/A_] New feature has been documented/Current behavior is correctly described in the documentation.
> [20599] Protect asio exception hotfix

- .github/workflows/reusable-windows-ci.yml
- .github/workflows/ubuntu-ci.yml
The reusable windows CI workflow was effectively ignoring the input branch, which results in all nightly jobs running with master.
This changes have also been applied on:
* #4484 
* #4482 
* #4481
- _N/A_; The code follows the style guidelines of this project. 
- _N/A_; Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_; Any new/modified methods have been properly documented using Doxygen. 
- _N/A_; Changes are ABI compatible. 
- _N/A_; Changes are API compatible. 
- _N/A_; New feature has been added to the `versions.md` file (if applicable).
- _N/A_; New feature has been documented/Current behavior is correctly described in the documentation.
> [20542] Fix input branch on reusable windows CI

- include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
- src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
- src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
- src/cpp/fastdds/xtypes/type_representation/TypeObjectUtils.cpp
- test/unittest/dds/xtypes/type_representation/TypeObjectUtilsTests.cpp
This PR fixes problems gathering the dependencies of indirect hash TypeIdentifiers.
> [20572] Fixes for indirect hashes dependencies.

- .github/workflows/address-sanitizers.yaml
- .github/workflows/config/asan.repos
- .github/workflows/config/asan_colcon.meta
- .github/workflows/config/tsan_colcon.meta
- .github/workflows/reusable-mac-ci.yml
- .github/workflows/reusable-ubuntu-ci.yml
- .github/workflows/reusable-windows-ci.yml
- .github/workflows/thread-sanitizer.yaml
Since the roll out of [Github Ubuntu 22.04 (20240310) Image](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240310.1), ASan and TSan jobs have been failing. The issue was reported in actions/runner-images#9491 and fixed in actions/runner-images#9513. Until that fix is deployed, this PR:
1. Sets kernel param `vm.mmap_rnd_bits` to 28 as a workaround
2. Pins the CMake version used in all 3 sanitizer jobs.
- _N/A_: Changes …
> [20542] Pin CMake version and vm.mmap_rnd_bits in sanitizer workflows

- .github/workflows/address-sanitizers.yaml
#4558 Corrected the GTest version used for Fast DDS ASan tests, but did not do so for the Discovery Server tests job. This PR fixes that.
Fix already included in:
* 2.13.x: #4566
* 2.12.x: #4567
* 2.10.x: #4568
* 2.6.x: #4569
> [20630] Use correct version of GTest on DS ASan tests

- .github/workflows/nightly-mac-ci.yml
- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/nightly-windows-ci.yml
This PR updates the nightly jobs to select the reusable workflow version depending on the branch tested. Sadly, `uses` keyword is context agnostic, so the version cannot be taken from the `fastdds-branch` matrix. Instead, a separate specific job for each tested version needs to be created. Furthermore, this PR makes the security option a matrix parameter, so both `ON` and `OFF` configurations are run for all versions in all platforms.
A manually triggered job can be seen [here](https://github.com/eProsima/Fast-DDS/actions/runs/8338751045).
- _N/A_: Any new/modified …
> [20662] Select reusable workflow version depending on target branch in nightly jobs

- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/xmlparser/XMLElementParser.cpp
- src/cpp/utils/UnitsParser.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/regressions/20608_profile_bin.xml
- test/unittest/xmlparser/regressions/20610_profile_bin.xml
This PR addresses the regressions described in [20608](https://eprosima.easyredmine.com/issues/20608) and [20610](https://eprosima.easyredmine.com/issues/20610). One has to  do with catching an out of bounds exception and the other with fixing the regex pattern.
> [20608][20610] Address XMLProfiles fuzzer regressions

- .github/pull_request_template.md
- .github/workflows/nightly-mac-ci.yml
- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/nightly-windows-ci.yml
- RELEASE_SUPPORT.md
This PR marks 2.12.x as an end-of-life version, by:
Related documentation PR: eProsima/Fast-DDS-docs#733
> [20553] Set 2.12.x as EOL

- test/unittest/logging/LogTests.cpp
- test/unittest/logging/log_macros/LogMacros.hpp
- test/unittest/logging/log_macros/LogMacrosDefaultTests.cpp
Test `LogMacrosTests.default_macros_test` has been sporadically failing in Github CI, especially on Windows.
Analysis showed it was due to a race condition in `HELPER_WaitForEntries`, and the test not accounting for the value of `FASTDDS_ENFORCE_LOG_INFO`.
This PR fixes the race condition in `HELPER_WaitForEntries` by early returning the collection of log entries, and fixes `default_macros_test` by always waiting for 3 entries and then checking that the expected number of entries is returned, also taking into consideration the value of `FASTDDS_ENFORCE_LOG_INFO`.
> [20655] Fix flakey Log tests

- src/cpp/rtps/transport/network/NetmaskFilterKind.cpp
This PR refactors the `std::ostream& operator <<` so that it uses a plain switch instead of an unordered map, since the previous implementation was failing to compile under some compilers `clang 15` because the enum class does not define any hashing function. It seems that our supported compilers could deduce that the enum class was in fact an int and that's why it did not get detected on CI.
- _N/A_: New …
> [20672] Use a plain switch for NetmaskFilterKind std::ostream& operator<<

- include/fastdds/rtps/writer/LivelinessManager.h
- src/cpp/rtps/builtin/liveliness/WLP.cpp
- src/cpp/rtps/builtin/liveliness/WLPListener.cpp
- src/cpp/rtps/writer/LivelinessManager.cpp
- test/blackbox/api/dds-pim/PubSubParticipant.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp
- test/blackbox/common/BlackboxTestsLivelinessQos.cpp
- test/unittest/rtps/writer/LivelinessManagerTests.cpp
This PR brings a bugfix when asserting `AUTOMATIC` `MANUAL_BY_PARTICIPANT` liveliness kinds. In the scenario of having a participant with two datareaders (each of them with a lease duration of 2 secs) and other two participants with one publisher each one configured with `AUTOMATIC_LIVELINESS`. If we suddenly kill one of the publishers (network disconnection or Ctrl+C), the `on_liveliness_changed()` is not received on the reader side when we would expect it to happen (after 2 secs).
The problem stems from the fact that currently, in the reader-side participant, it is enough having an alive writer with the same kind (`AUTOMATIC_LIVELINESS`) to assert the liveliness of all of its readers with the same kind regardless of the participant.
This PR makes the liveliness assertion …
> [20584] Effectively assert automatic/manual_by_participant liveliness

- CMakeLists.txt
- package.xml
- versions.md
> [20025] Bump version to v2.12.2

- .github/workflows/address-sanitizers.yaml
- .github/workflows/documentation-tests.yaml
- .github/workflows/mac-ci.yml
- .github/workflows/thread-sanitizer.yaml
- .github/workflows/ubuntu-ci.yml
- .github/workflows/windows-ci.yml
- include/fastrtps/subscriber/SubscriberHistory.h
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastdds/publisher/DataWriterImpl.hpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/fastrtps_deprecated/participant/ParticipantImpl.h
- src/cpp/fastrtps_deprecated/publisher/PublisherImpl.h
- src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.h
- src/cpp/rtps/DataSharing/ReaderPool.hpp
- src/cpp/rtps/DataSharing/WriterPool.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.h
- src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
- src/cpp/rtps/history/BasicPayloadPool_impl/Base.hpp
- src/cpp/rtps/history/BasicPayloadPool_impl/PreallocatedWithRealloc.hpp
- src/cpp/rtps/history/TopicPayloadPool_impl/Dynamic.hpp
- src/cpp/rtps/history/TopicPayloadPool_impl/DynamicReusable.hpp
- src/cpp/rtps/history/TopicPayloadPool_impl/Preallocated.hpp
- src/cpp/rtps/history/TopicPayloadPool_impl/PreallocatedWithRealloc.hpp
- src/cpp/rtps/transport/TCPTransportInterface.h
- src/cpp/rtps/transport/UDPTransportInterface.h
- src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
- src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.hpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
This PR:
1. Enables running Github Ubuntu CI on `pull_request` events.
2. Fixes hidden overloads erroneously left out by #4516 
3. Enables running Github CI on PRs targeting intermediate branches (not `master`). 
> [20679] Run Github Ubuntu CI on PRs

- src/cpp/rtps/reader/StatelessReader.cpp
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
When some fragments are lost on every sample, best-effort readers were not notifying `on_sample_lost` events.
> [20351] Fix on_sample_lost notification on best-effort readers for framented samples

- src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
- test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
- test/unittest/statistics/rtps/CMakeLists.txt
- test/unittest/statistics/rtps/mock/Publisher/fastdds/publisher/DataWriterHistory.hpp
This PR fixes a misbehavior of the monitor service that was not truly managing instances since it requires a `DataWriterHistory` instead of a `WriterHistory`. Cachechanges owned by instances are now properly removed in successive updates to the same instance.
@Mergifyio backport 2.13.x 
> [20625] Monitor service properly managing instances 

- .github/workflows/address-sanitizers.yaml
- .github/workflows/documentation-tests.yaml
- .github/workflows/mac-ci.yml
- .github/workflows/reusable-mac-ci.yml
- .github/workflows/reusable-ubuntu-ci.yml
- .github/workflows/reusable-windows-ci.yml
- .github/workflows/thread-sanitizer.yaml
- .github/workflows/ubuntu-ci.yml
- .github/workflows/windows-ci.yml
This PR changes the way Github CI is managed. From now on, to run CI, a label `run-ci` needs to be added to the PR. Once the CI starts, that label is removed and `ci-pending` one is added.
This PR depends on:
* eProsima/eProsima-CI#80
- _N/A_: New feature has been documented/Current behavior is …
> [20648] Only run PRs CI when run-ci label is added

- .github/workflows/ubuntu-ci.yml
- test/CMakeLists.txt
- test/blackbox/CMakeLists.txt
- test/unittest/dds/participant/CMakeLists.txt
- test/unittest/utils/CMakeLists.txt
When both PKCS#11 and DNS tests had to be disabled, the filter expression for gtest was incorrectly generated.
This made Ubuntu and MacOS CI on github fail.
Additionally, this PR fixes the commands used to detect whether the DNS local entries for the corresponding tests have been added, and adds some related informational messages to the CMake files.
@Mergifyio backport 2.13.x
- *N/A* New feature has been …
> [20652] Improve filtering of DNS tests

- test/blackbox/common/DDSBlackboxTestsListeners.cpp
Blackbox test `sample_lost_be_dw_be_dr_fragments` has been failing from time to time.
It fails because more samples than expected are lost.
The socket buffer size was only configured for the reader so fragments could have been lost in the writer.
This PR configures the socket buffer size in both the reader and the writer.
- This will not be directly backported, but cherry-picked in the backports of #4187, which is the one that added the offending test. Those …
> [20692] Make sample_lost_be_dw_be_dr_fragments test less flakey

- include/fastdds/dds/domain/DomainParticipantFactory.hpp
- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
- versions.md
DomainParticipant XML profile configuration allows setting the [domain id](https://fast-dds.docs.eprosima.com/en/latest/fastdds/xml_configuration/domainparticipant.html#domainparticipant-configuration) out of the rtps.
That domain ID is considered in the domain participant creation only if [the domain participant profile name is defined](https://github.com/eProsima/Fast-DDS/blob/5c87d9d02173f190f7b69cb4dbbb6041d9fcf177/src/cpp/fastdds/domain/DomainParticipantFactory.cpp#L242).
This PR stores (if exists) the Domain ID value while loading the default XML profile, and exposes new methods to simplify participant creation without requiring neither the Domain ID (uses the one set in the XML, or `0` by default), neither the QoS (uses the qos set in the XML, or PARTICIPANT_DEFAULT_QOS by default) …
> [20543] Create Participant with default profile (use environment XML configuration)

- src/cpp/rtps/transport/TCPChannelResource.cpp
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
Since TCP actually allocates twice the size of the requested buffer, TCP `non_blocking_send` should not skip a send until this limit is reached.
This PR doubles the limit from which a send should not be tried if TCP `non_blocking_send` is set to true.
> [20589] Set real TCP non_blocking_send limitation

- test/blackbox/common/DDSBlackboxTestsListeners.cpp
The test `reliable_on_unack_sample_removed` regularly fails in MacOS Github CI due to the removal of unacknowledged samples (even though they are correctly received). This pr increases the ack waiting time to allow the acknowledge and make the test pass.
> [20654] Increase ack waiting time in reliable_on_unack_sample_removed

- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
- test/blackbox/common/BlackboxTestsTransportSHM.cpp
- test/unittest/transport/SharedMemTests.cpp
As originally reported in #4504 a port could be open first with ReadShared and then with ReadExclusive the internal state of the port was incorrectly changed. This meant that the same port could be used at the same time for unicast and multicast.
This PR fixes #4634 by checking incompatibilities inside `lock_read_exlcusive` / `lock_read_shared` methods of the Port class.
> [20701] Enforce SHM ports open mode exclusions

- include/fastdds/dds/core/policy/QosPolicies.hpp
- src/cpp/fastdds/publisher/DataWriterHistory.cpp
- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- src/cpp/fastrtps_deprecated/publisher/PublisherHistory.cpp
- src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
- test/mock/rtps/PublisherHistory/fastdds/publisher/DataWriterHistory.hpp
- test/mock/rtps/PublisherHistory/fastrtps/publisher/PublisherHistory.h
- test/performance/throughput/ThroughputPublisher.cpp
- test/performance/throughput/ThroughputSubscriber.cpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
- test/unittest/dds/topic/TopicTests.cpp
This PR forces the ResourceLimitsQoS values (`max_samples`, `max_instances` and `max_samples_per_instance`) to be considered as unlimited if a value **greater than zero** is **NOT** provided.
Fixes #4609
Related documentation PR: eProsima/Fast-DDS-docs#738
> [20722] Force unlimited ResourceLimits if lower or equal to zero

- include/fastdds/rtps/writer/ReaderProxy.h
- src/cpp/rtps/writer/ReaderProxy.cpp
- test/unittest/rtps/writer/ReaderProxyTests.cpp
As spotted by https://github.com/omg-dds/dds-rtps/issues/35, Fast DDS ignores AckNack messages where the `count` field is `0`.
This PR adds a unit test for `ReaderProxy::check_and_set_acknack_count`, and fixes the issue by changing the check on `acknack_count` from *last received* to *next expected*.
> [20729] Allow processing of AckNack submessages with count == 0

- .github/pull_request_template.md
This PR adds a check for the PRs to add XML API if needed.
- _N/A_ Changes are ABI compatible. 
> [20750] Add check for XML API to PR template

- test/blackbox/common/DDSBlackboxTestsOwnershipQos.cpp
This PR increases the sleep between samples sent to miss the deadline in ownership flaky tests " exclusive_kind_non_keyed_reliable_deadline"
@Mergifyio backport 2.13.x 2.10.x 
> [20653] Increase sleep to miss the deadline in macOS flaky tests

- .github/workflows/nightly-sanitizers-ci.yml
Both sanitizer CI (PR/request review/workflow dispatch) and nightly sanitizer CI (cron) have the same workflow name, whereas the other nightly workflows include a ` (nightly)` suffix.
This PR includes that suffix to distinguish the workflows.
- _N/A_ Changes are ABI compatible.  …
> [20705] Fix nightly sanitizer CI workflow name

- .github/workflows/config/ci.meta
- .github/workflows/reusable-ubuntu-ci.yml
This PR adds Fast DDS Shapes Demo to the packages built in Ubuntu Gibthub CI so we have certainty that changes in Fast DDS do not broke Shapes Demo compilation.
- _N/A_: New feature has been …
> [20786] Build ShapesDemo on Ubuntu Github CI

- src/cpp/rtps/network/NetworkFactory.cpp
- src/cpp/rtps/network/NetworkFactory.h
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/blackbox/common/BlackboxTestsTransportSHM.cpp
This PR refactors the constructor of RTPSParticipantImpl, and changes the calculation of the ports used when set to 0 on the input locators.
> [18002] Internal refactor on port handling

- src/cpp/fastdds/core/policy/ParameterList.cpp
There is a new warning on CI https://ci.ros2.org/view/packaging/job/packaging_linux/3405/clang-tidy/folder.112366245/
This should fix the warning
> Removed warning

- include/fastdds/dds/subscriber/DataReader.hpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- test/blackbox/common/DDSBlackboxTestsDataReader.cpp
This PR corrects the behavior of `get_first_untaken_info()` so that it retrieves the first valid cache change (checking whether the change is in the future or not), instead of just returning the first one in the instance (sorted by sourcetimestamp).
In the scenario of having multiple reliable writers and one reader with history size > 1 in the same topic, it can happen that `get_first_untaken_info()` returns `OK` (as it is not currently checking whether the change is in the future) but `take()` returns `NO_DATA`  because the change is in the future.
In addition, a brief doxygen documentation is added to be aware that the method is meant to be followed by a `read()` or `take()` since it does not modify the status condition of the entity.
Fixes …
> [20706] Make reader get_first_untaken_info() coherent with read()/take()

- src/cpp/rtps/builtin/data/ReaderProxyData.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
This bug was found testing ShapesDemo against 3.0.x-devel. The problem is DataRepresentationQos is not taken into account when calculating cdr serialized size of Data(w)/Data(r). This PR fixes this.
> MonitorService fails serializing Data(w)/Data(r) in some cases [20772]

- include/fastdds/dds/subscriber/DataReader.hpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
- versions.md
With this PR, `DataReader::return_loan` starts returning OK when given a loanable sequence with no loans, i.e.;
1. A loanable sequence with a set maximum (no loans are performed)
2. A empty loanable sequence
**IMPORTANT**: Even though these changes are API and ABI compatible, this a behavioral change and cannot target a patch release.
- _N/A_; Applicable backports have been included in the description.
> [20583] DataReader::return_loan returns OK on loanable sequences without loans

- src/cpp/fastdds/xtypes/dynamic_types/DynamicTypeBuilderFactoryImpl.cpp
This PR fixes a bug in `DynamicTypeBuilderFactory::create_type_w_type_object` when creating a inheriting structure.
- [NO] Commit messages follow the project guidelines. 
- [N/A] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
> [Hotfix] Structure DynamicType inheritance from TypeObject

- test/blackbox/common/DDSBlackboxTestsDataReader.cpp
This PR forwards a test fix from https://github.com/eProsima/Fast-DDS/pull/4708 regarding the `StackAllocatedSequence`.
Note, I checked with `master` and OK, but the reviewer is encouraged to ask manually for a specific ci despite I added the `skip-ci`. I am leaving the label though for now.
- _N/A_ New feature has been documented/Current …
> [20706] Bugfix in DDSBlackboxTestsDataReader test

- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/rtps/security/SecurityManager.h
- test/blackbox/common/BlackboxTestsSecurity.cpp
- test/unittest/rtps/security/SecurityHandshakeProcessTests.cpp
- test/unittest/rtps/security/SecurityTests.cpp
- test/unittest/rtps/security/SecurityTests.hpp
- test/unittest/rtps/security/SecurityValidationRemoteTests.cpp
This is a fix for #4553, which reported an increase in memory consumption when the partition of a secure DataWriter is changed. The consumption came from the history of the `participant_volatile_message_secure_writer_` not being correctly cleared.
This PR:
* adds a black-box test reproducing the behavior depicted in #4553
* converts `volatile_writer_` in the security tests into a `StrictMock`, and adds expectations for the added change to be released
* Fixes #4553 by making `SecurityManager` implement `rtps::WriterListener` and removing changes from history when they are acknowledged (i.e. making `participant_volatile_message_secure_writer_` truly behave as volatile)
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding …
> [20658] Fix leak in `SecurityManager::participant_volatile_message_secure_writer_`

- include/fastrtps/types/MemberDescriptor.h
- include/fastrtps/xmlparser/XMLProfileManager.h
- resources/xsd/fastRTPS_profiles.xsd
- src/cpp/dynamic-types/AnnotationDescriptor.cpp
- src/cpp/dynamic-types/DynamicType.cpp
- src/cpp/dynamic-types/MemberDescriptor.cpp
- src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
- src/cpp/rtps/xmlparser/XMLProfileManager.cpp
- test/system/tools/xmlvalidation/XMLTesterExample_profile.xml
- test/system/tools/xmlvalidation/all_profile.xml
- test/system/tools/xmlvalidation/types_profile.xml
- test/unittest/dynamic_types/DynamicTypesTests.cpp
- test/unittest/dynamic_types/types_profile.xml
This PR:
- Fixes various things regarding the handling of `@key` annotation on dynamic types:
- Copy the type annotations when creating MemberDescriptors
- Fix `AnnotationDescriptor::key_annotation()` implementation
- Fix population of `is_key_defined_` in `DynamicType::copy_from_builder()`
- Simplify `DynamicType::key_annotation()` implementation
- On loading types from XML, add the `@key` annotation only to the member builder and not to the dynamic type, as `@key` only makes sense for members but not types.
- Adds the `key` attribute to members in XSD
- _N/A_: New …
> [20733] Fix support for @key annotation in Dynamic types

- test/unittest/rtps/security/SecurityHandshakeProcessTests.cpp
- test/unittest/rtps/security/SecurityTests.cpp
- test/unittest/rtps/security/SecurityTests.hpp
- test/unittest/rtps/security/SecurityValidationRemoteTests.cpp
This PR fixes an incorrect memory access error in the SecurityTests. The same `CacheChange` `kx_change` was being deleted and after accessed in the lambda defined within the `expect_kx_exchange` function.
The fix proposes separating the concerns of deletion and addition, defining a CacheChange for each one (in particular, a stack-allocated one for the addition). 
**Important** Backports are not being included since backports from #4673 have not been merged and this could be cherry-picked.
- _N/A_ New feature has been documented/Current …
> [20945] Fix SecurityTest unittests memory error

- include/fastdds/dds/publisher/Publisher.hpp
- include/fastdds/dds/publisher/qos/DataWriterQos.hpp
- include/fastdds/dds/subscriber/Subscriber.hpp
- include/fastdds/dds/subscriber/qos/DataReaderQos.hpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.hpp
- src/cpp/fastdds/publisher/Publisher.cpp
- src/cpp/fastdds/publisher/PublisherImpl.cpp
- src/cpp/fastdds/publisher/PublisherImpl.hpp
- src/cpp/fastdds/publisher/qos/DataWriterQos.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/fastdds/subscriber/Subscriber.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.hpp
- src/cpp/fastdds/subscriber/qos/DataReaderQos.cpp
- test/blackbox/common/DDSBlackboxTestsDataReader.cpp
- test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
- test/unittest/dds/publisher/PublisherTests.cpp
- test/unittest/dds/subscriber/SubscriberTests.cpp
This PR 
* Implement the method `copy_from_topic_qos()`. 
* Define the value `DATAWRITER_QOS_USE_TOPIC_QOS` and `DATAREADER_QOS_USE_TOPIC_QOS`. These values can be used to indicate that the DataWriter or DataReader should be created with a combination of the default DataWriter QoS and the Topic QoS using `copy_from_topic_qos()`.
* Add the previous logic to the costructor of `DataReaderImpl` and `DataWriterImpl`.
* Remove `copy_from_topic_qos()` from `UnsupportedPublisherMethods` and `UnsupportedSubscriberMethods` tests.
Related documentation PR:
* eProsima/Fast-DDS-docs/pull/752
- N/A Applicable backports have been …
> [20861] Implement copy_from_topic_qos method

- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.hpp
- src/cpp/fastdds/subscriber/DataReaderImpl/SampleLoanManager.hpp
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/publisher/PublisherTests.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
The endpoints implementation (DataReaderImpl and DataWriterImpl) were calling `is_plain` method without the data representation, so it was not being considered.
This PR includes the data representation as an argument to `is_plain` so it is considered in both cases.
@Mergifyio backport 2.13.x
> [20742] Run `is_plain` method with the corresponding data representation

- src/cpp/utils/threading/threading_pthread.ipp
Fixes:
* #4225
- _N/A_  Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
> Address compilation issue for GLIBC version prior to 2.30

- .github/workflows/reusable-ubuntu-ci.yml
- .github/workflows/reusable-windows-ci.yml
- test/system/tools/fastdds/CMakeLists.txt
- tools/fastdds/fastdds.bat
- tools/fastdds/ros-discovery.bat
This PR addresses failing github CI system tests.
* It fixes Python installation version in Windows & Ubuntu Github CIs (macOs was already doing it).
* Selects the appropriate python version in the launcher used in `.bat` tool files by means of an environment variable `PYTHON_VERSION` {Major.Minor}.
* Prevents `Qt` from setting-up Python, as we are who manage the Python installation
_Notes:_ 
* In windows, `pywin32` is not listed as a required python package at the `Python Dependencies` step as it is a requirement of `colcon` and it is installed along with it.
* Python version is not fixed in the sanitizers jobs since system tests are not run there. 
Work done in #4731 precedes this PR.
@Mergifyio backport 2.13.x 2.10.x 2.6.x 
- _N/A_ Tests that thoroughly check the new feature have been …
> [20965] Fix Python Installation version in Github CI. Address failing system tests environment issues.

- .github/pull_request_template.md
This PR updates the pull request template to take into consideration possible library core behavior changes, and consider them as in the same level as ABI breaks.
- __N/A__ The code follows the style guidelines of this project. 
- __N/A__ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- __N/A__ Changes are API compatible. 
- __N/A__ New feature has been …
> [20994] Consider library behavior changes as ABI breaks in the PR template checklist

- fastdds.repos
After switching the `3.0.x-devel` branch to `master`, the fastdds.repos file that is used to refer the repositories and Fast DDS dependencies versions need to be switched to `master` too.
This PR updates the .repos file to use `master` branches.
- __N/A__ The code follows the style guidelines of this project. 
- __N/A__ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- __N/A__ Changes are API compatible. …
> [20893] Update .repos to use 'master' branches

- include/fastdds/rtps/transport/TransportInterface.h
- include/fastrtps/transport/TransportInterface.h
- src/cpp/rtps/transport/TCPChannelResource.cpp
- src/cpp/rtps/transport/TCPChannelResource.h
- src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
- src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/UDPTransportInterface.cpp
- src/cpp/rtps/transport/UDPTransportInterface.h
- src/cpp/rtps/transport/UDPv4Transport.cpp
- src/cpp/rtps/transport/UDPv6Transport.cpp
- src/cpp/rtps/transport/asio_helpers.hpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
- test/unittest/transport/UDPv4Tests.cpp
- test/unittest/transport/UDPv6Tests.cpp
**Note for backports**: `s_minimumSocketBuffer` should be deprecated.
Before this PR, setting too high a value for `sendBufferSize` or `receiveBufferSize` in a transport descriptor could lead to an error setting the buffer sizes. This error was silently discarded.
The changes try to set the configured buffer size, halving it on an error until it gets the minimum allowed value (i.e. maxMessageSize).
Note: Since modifications need to be made on the backport, and the next patch release is 2.10.4, we will first
backport to 2.10.x, perform the modifications there, and then port to other supported branches.
- _N/A_ New feature has been added to the `versions.md` file …
> [20976] Handle errors when setting socket buffer sizes

- tools/fastdds/fastdds.bat
- tools/fastdds/ros-discovery.bat
@MiguelCompany identified an error introduced in #4759 as the `PYTHON_VERSION`  does not necessarily need to be defined when executing the `fastdds.bat` or `ros-discovery.bat` scripts.  
The change simply requires a specific version of Python only if `PYTHON_VERSION` is defined.
Tested on Windows.
@Mergifyio backport 2.14.x 2.13.x 
Cherry-pick on #4765 and #4766
- _N/A_  Any new/modified methods have been properly documented using Doxygen. 
- _N/A_  Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _N/A_  New feature has been added to the `versions.md` file (if applicable).
- _N/A_  New …
> [21009] Do not require PYTHON_VERSION to be defined in .bat files

- src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
- src/cpp/rtps/builtin/data/ReaderProxyData.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
- test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
Previously, Writer|ReaderProxyData always reported DataSharing as AUTO. This PR set it to ON or OFF based on the PID_DATASHARING.
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x 
> [20933] Set DataSharing in Writer|ReaderProxyData

- include/fastdds/rtps/transport/TransportInterface.h
- include/fastrtps/transport/TransportInterface.h
- src/cpp/rtps/transport/TCPChannelResource.cpp
- src/cpp/rtps/transport/TCPChannelResource.h
- src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
- src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/UDPTransportInterface.cpp
- src/cpp/rtps/transport/UDPTransportInterface.h
- src/cpp/rtps/transport/UDPv4Transport.cpp
- src/cpp/rtps/transport/UDPv6Transport.cpp
- src/cpp/rtps/transport/asio_helpers.hpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
- test/unittest/transport/UDPv4Tests.cpp
- test/unittest/transport/UDPv6Tests.cpp
This is a manual backport of #4760 where `s_minimumSocketBuffer` has been deprecated instead of removed.
> [21036] Handle errors when setting socket buffer sizes (backport #4760)

- tools/fastdds/fastdds.bat
- tools/fastdds/ros-discovery.bat
A small improvement that changes the loop populating `args` variable into using the built-in `%*`.
See docs [here](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/call#batch-parameters)
- _N/A_ New feature has been documented/Current …
> [21037] Use `%*` instead of loop in `.bat` scripts

- .github/workflows/utils/log_parser.py
This PR adds a workaround the prevent reading errors when generating sanitizer reports either because of unexpected characters or early-finishing files. It decodes information as `utf-8` and replaces any strange character with a mark (?) given the case.
- __NO__ Changes are backport compatible: they do **NOT** break ABI nor change library core …
> [20991] Fix sanitizers CI test summary report

- .github/workflows/reusable-ubuntu-ci.yml
Before this PR, when running the Ubuntu CI manually, if the `input.fastdds-branch` did not exist on ShapesDemo, the job fails, as the `input.fastdds-branch` is used as fallback branch for calling `get_related_branch_from_repo` for ShapesDemo.
In fact, it the PR is to an intermediate branch without a corresponding ShapesDemo branch, the job will also fail. The reason why it was not failing in normal PRs is that before the fallback check, the action checks for the existence on the base branch from the PR, and as ShapesDemo branching model is the same as Fast DDS' it was using the basing without having to check the fallback.
With this PR, the fallback branch is explicitly set on the reusable workflow so when running manual dispatching, the fallback branch is valid. …
> [20989] Set fallback branch for get_related_branch_from_repo correctly

- include/fastdds/dds/subscriber/qos/DataReaderQos.hpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.cpp
- src/cpp/fastdds/subscriber/qos/DataReaderQos.cpp
- src/cpp/fastdds/utils/QosConverters.cpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/common/DDSBlackboxTestsDataReader.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
- test/unittest/dds/subscriber/SubscriberTests.cpp
- versions.md
This PR updates the DataReaderQoS reformatting the TypeConsistencyQos:
1. `DataReaderQos` shall have:
- `TypeConsistencyEnforcementQosPolicy::type_consistency`
- `DataRepresentationQosPolicy::representation`
2. `DataReader::TypeConsistencyQos` shall be removed
- Related documentation PR: eProsima/Fast-DDS-docs#779
> [21053] Move DR TypeConsistencyEnforcement & DataRepresentation from TypeConsistency to DataReaderQos

- src/cpp/rtps/builtin/BuiltinProtocols.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.h
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
It's been reported that when several participants are created in the same process, and log warnings are enabled, a call to `delete_participant()` triggers the following warning several times:
`[RTPS_READER Warning] Automatically unmatching on ~WriterProxy -> Function ~WriterProxy`
Debugging revealed that these were shown for the built-in reliable readers.
This PR adds a mechanism to automatically unmatch the built-in endpoints when a participant is deleted.
The mechanism consists of performing the same actions executed when receiving a DATA(p|UD), without triggering the participant listener.
- _N/A_ New feature …
> [21055] Automatically unmatch remote participants on participant deletion

- test/unittest/transport/SharedMemTests.cpp
This PR tries to fix a MacOS flaky test by refactoring the behavior of the test.
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x 
- __N/A__ New feature has been added to the `versions.md` file (if applicable).
- __N/A__ New feature has been documented/Current behavior is correctly described in the documentation.
> [20993] Fix ShmTransport buffer recovery MacOS flaky test

- .github/workflows/reusable-windows-ci.yml
In previous Windows CI refactors, the usage of the selected VS tool (Win v141 / VS 2017 and Win v142 / VS2019) was missed.
This PR restores the tool selection for proper configuration and build per selected platform.
@Mergifyio backport 2.13.x 2.10.x 2.6.x 
- **N/A** Changes are API …
> [21092] Run selected VS tool on Windows CI

- .github/workflows/reusable-windows-ci.yml
Visual Studio 2017 build is no longer supported for Fast DDS future release v3.0.0.
For that reason, this PR removes its usage in windows CI, by removing the `v141` build.
To test it, this PR has the `no-test` label.
- **N/A** New feature has …
> [21092] Remove Windows v141 / VS 2017 build from master / 3.x CI

- test/blackbox/common/DDSBlackboxTestsBasic.cpp
This fixes the test added in #4817 so the library settings are correctly restored after the test, instead of being reset to the default.
> [21055] Minor fix in DDSBlackboxTestsBasic.cpp

- test/unittest/rtps/discovery/EdpTests.cpp
- test/unittest/rtps/discovery/PDPTests.cpp
This PR fixes a compilation issue with `gmock` and `PDP/EDPTests` unittests. It seems that `ParticipantSecurityAttributes` were just forward declared.
_Note: compiling `google-distribution` `release-1.11.0` solves the issue._
- __NO__ …
> Fix PDP & EDP unittest compilation

- src/cpp/rtps/builtin/liveliness/WLP.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- src/cpp/rtps/writer/LivelinessManager.cpp
- src/cpp/rtps/writer/LivelinessManager.hpp
- test/blackbox/common/BlackboxTestsLivelinessQos.cpp
- test/unittest/rtps/writer/LivelinessManagerTests.cpp
This PR corrects a misbehavior given in a single writer - multiple readers scenario. When the writer is destroyed, the `WriterProxy` is removed from readers. When it is removed from the first one, the `LivelinessManager::remove_writer()` returns `false` as `--writer.count` is `1`, hence the `liveliness_changed` callback is not triggered (`callback_` within `LivelinessManager` is not invoked). When the `WriterProxy` is deleted from the second reader, the `LivelinessManager::remove_writer()` correctly removes the writer and fires the `callback`. The problem in this case is that, later, in `WLP::sub_liveliness_changed()` the `update_liveliness_changed_status()` is only called for this later reader, since the first one is not matched anymore and `reader->matched_writer_is_matched()` returns …
> [21065] Bugfix: correct liveliness state in a multiple reader - one writer scenario

- src/cpp/CMakeLists.txt
- src/cpp/fastdds/publisher/filtering/ReaderFilterCollection.hpp
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- src/cpp/rtps/reader/reader_utils.cpp
- src/cpp/rtps/reader/reader_utils.hpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsContentFilter.cpp
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/statistics/dds/CMakeLists.txt
This PR fixes a bug that caused the content filter to also be applied to `unregister` and `disposed` samples. Since in those messages the only fields populated (if any) are the ones annotated with `@key`, the `unregister` and `dispose` samples did not pass the filter (in general) and thus were being discarded. This caused several issues:
1. When writing to more than 10 instances with default Qos (keep last 1, max_instances 10), only the first 10 samples were been received.
2. In best effort, when setting the history depth and max instances appropriately, all samples were received, but calls to `unregister` or `dispose` followed by a `write` were triggering `sample_lost` events, as the received sequence numbers were not consecutive (because of the filtering out of the …
> [20815] Only apply content filter to ALIVE changes

- test/profiling/allocations/AllocTestPublisher.cpp
- test/profiling/allocations/AllocTestPublisher.hpp
- test/profiling/allocations/AllocTestSubscriber.cpp
- test/profiling/allocations/AllocTestSubscriber.hpp
- test/profiling/allocations/test_xml_profile.xml
This PR makes the AllocTests compatible with changes implemented in 3.x.
- _N/A_ Check CI results: failing …
> [21081] AllocTest in 3.x

- include/fastdds/rtps/participant/RTPSParticipantListener.h
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
This PR removes the discovery callback overloads on `RTPSParticipantListener` not receiving `should_be_ignored`.
- _N/A_ Applicable …
> [21097] Remove RTPSParticipant listener overloaded callbaks

- src/cpp/CMakeLists.txt
Static library generation is not working in 3.x. This PR fixes it.
- *N/A* Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
> Fix compilation when building static library [21059]

- include/fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp
- src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
This PR fixes some Doxygen errors when generating the API reference with Doxygen versions prior to 1.8.19, as it is the case of Fast DDS docs RTD page, which is generated in [Ubuntu 20.04](https://github.com/eProsima/Fast-DDS-docs/blob/93f6c1913e0075dfefbbc9f72edfe7d0684ba23b/readthedocs.yaml#L9) and therefore with Doxygen 1.8.17.
Although [Doxygen documentation](https://doxygen.nl/manual/commands.html#cmdparam) documents the `dir` attribute of the `param` directive to be one of `[in]`, `[out]`, and `[in,out]`, doxygen/doxygen#7881 introduced, among other things, the possibility to set the `dir` attribute to `[in out]`, which #4746 introduced in several places.
Mind that in the dev machines this "mistake" went undetected because of the use of Ubuntu 22.04 (Doxygen 1.9.1).
Also, even …
> [21144] Fix doxygen errors for versions prior to 1.8.19

- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.hpp
- test/blackbox/common/DDSBlackboxTestsStatistics.cpp
This PR fixes a wrong behavior that occurs when closing an application making an intensive use of statistics. If in the shutdown pipeline, after a manual removal of entities (`delete_datareader`, `delete_subscriber`, `delete_topic`) if  `delete_contained_entities()` was called, it caused a race when alive endpoints try to keep using the statistics builtin endpoints (writers).
> [20816] Properly delete builtin statistics writers upon `delete_contained_entities()` 

- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastdds/rtps/attributes/WriterAttributes.h
- include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp
- include/fastrtps/xmlparser/XMLParser.h
- src/cpp/rtps/xmlparser/XMLElementParser.cpp
- src/cpp/rtps/xmlparser/XMLParser.cpp
- src/cpp/rtps/xmlparser/XMLProfileManager.cpp
- test/unittest/dds/publisher/PublisherTests.cpp
- test/unittest/xmlparser/XMLProfileParserTests.cpp
PR #4893 introduced an ABI break changing the flow controller descriptor names to `std::string`. This PR reverts that change and handles the flow controller names in a collection within `XMLParser`. It also defines a `clear()` method intended to clean the collection upon `XMLProfileManager` destruction.
*Note* I introduced a `mutex` but I dont think it is needed 100% since the XMLParser configuration may be something sequential, but I introduced it anyways.
**Important** A cherry pick of this PR should be merged in the following backports
* #4905 
* #4906
* #4907
- __NO__ New feature has been added to the `versions.md` file (if …
> [21136] Bugfix: Revert XML Flow controller names to `const char*`

- CMakeLists.txt
- include/fastrtps/types/DynamicLoanableSequence.hpp
This fixes a doxygen warning introduced by #4876.
These changes must be included in:
* #4902
* #4903
* #4904
- _N/A_: New feature has been documented/Current behavior is …
> [20815] Fix doxygen warning about undocumented param in deleted functions

- test/examples/CMakeLists.txt
- test/examples/test_configuration.py
- test/examples/test_hello_world.py
Current example tests are defined under the same pytest. That makes the "all examples" test fail if the timeout (300 sec) is reached. It didn't happen before but while including new examples (and their corresponding tests) this timeout has been reached.
This PR splits the pytest file with all example tests into different pytest files under different directories, so each of them would run independently with the same timeout (300 sec).
The corresponding compose file for each test has been configured in the same directoy on build time.
**Note**: This has been done assuming the name matches: 
- compose file: `example_name`.compose.yml
- test_`example_name`.py
- ❌ Changes are backport compatible: they do **NOT** …
> [21162] Split example tests in different ctest tests

- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupRequestListener.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
This PR fixes two minor data races and solves a bugfix in which the Proxy Pool was running out of Proxies due multiple requests of the TypeLookup Service. Now, if the type is not known, a copy of the Proxy is made to avoid blocking the discovery.
- _N/A_ Applicable backports …
> [20953] Fix Proxy block in TypeLookup Service

- src/cpp/rtps/builtin/discovery/endpoint/EDP.h
- test/unittest/rtps/discovery/EdpTests.cpp
This PR changes the values of the `MatchingFailureMask` so they can be directly used through the `std::bitset` API. Before this PR, the following code:
```c++
EDP::MatchingFailureMask mask;
mask.set(EDP::MatchingFailureMask::different_typeinfo);
```
resulted in a C++ exception as follows:
```
"bitset::set: __position (which is 16) >= _Nb (which is 16)"
```
> [21165] Correctly initialize `MatchingFailureMask` constants to be used with the `std::bitset` API

- .github/workflows/documentation-tests.yaml
- .github/workflows/reusable-mac-ci.yml
- .github/workflows/reusable-sanitizers-ci.yml
- .github/workflows/reusable-ubuntu-ci.yml
This PR uses a token for the setup-ccache action from in the CI, which is behind the CI failures on post steps due to exceeding github API usage rate limits
- _N/A_; The code follows the style guidelines of this project. 
- _N/A_; Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_; Any new/modified methods have been properly documented using Doxygen. 
- _N/A_; Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _N/A_; Changes are API compatible. 
- _N/A_; New feature has been added to the `versions.md` file (if applicable).
- _N/A_; New feature has been documented/Current behavior is correctly …
> [21168] Use token for ccache action

- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
This PR fixes a build warning that occurs when building Fast DDS without security, introduced in:
- #4875 
Added the `skip-ci` label (PR is by default run with security) and triggering manual CI without security
- _N/A_ New feature has …
> [21120] Fix EDP build warning wihtout security

- src/cpp/xmlparser/XMLDynamicParser.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/regressions/21153_profile_bin.xml
- test/unittest/xmlparser/regressions/21154_profile_bin.xml
This PR addresses some XML fuzzer regressions that affects DynamicTypes Parsing. It is for that reason that there are no backports. In summary, it was a non-captured `std::out_of_range` exception and  a `nullptr` check missing. I tried also protecting analogous code snippets within the file.
- __NO__ New feature has been documented/Current behavior is correctly described in the documentation. 
- ❌ Applicable backports have been included in the description.
> [21153, 21154] Address XMLDynamicParser Fuzzer regressions 

- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.h
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
This PR postpones the execution of the _process_backup_discovery_database_restore_ method until after the initialization of builtinProtocols and the TypeLookUpManager.
> [20936] Change backup restore order

- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- test/blackbox/api/dds-pim/PubSubParticipant.hpp
- test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
This PR fixes a bug that was avoiding discovery when a DS server tries to connect to another server which has a smaller physical port. The logic implemented in https://github.com/eProsima/Fast-DDS/pull/4586 needs to be used to fix the issue.
It also adds support to automatically set the logical port of remote servers when the participant `discoveryProtocol` is configured as `DiscoveryProtocol::SERVER`, which was missing.
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x 
- _N/A_ New feature has been documented/Current behavior is correctly …
> [21170] Fix DS servers not connecting due to ports logic

- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastdds/rtps/attributes/HistoryAttributes.h
- include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
- include/fastdds/rtps/attributes/ResourceManagement.hpp
- src/cpp/fastdds/publisher/DataWriterHistory.hpp
- src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp
- src/cpp/rtps/DataSharing/ReaderPool.hpp
- src/cpp/rtps/DataSharing/WriterPool.hpp
- src/cpp/rtps/history/CacheChangePool.h
- src/cpp/rtps/history/PoolConfig.h
- src/cpp/rtps/history/TopicPayloadPool.hpp
- src/cpp/statistics/fastdds/subscriber/qos/DataReaderQos.cpp
- src/cpp/xmlparser/attributes/PublisherAttributes.hpp
- src/cpp/xmlparser/attributes/SubscriberAttributes.hpp
- test/mock/dds/DataWriterHistory/fastdds/publisher/DataWriterHistory.hpp
- test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.h
- test/unittest/statistics/rtps/mock/Publisher/fastdds/publisher/DataWriterHistory.hpp
- versions.md
This PR migrates the ResouceManagement file from `include/fastdds/rtps/resources/` to `include/fastdds/rtps/attributes/`.
This is part of a set of migrations and refactors related to the new mayor version v3.0.0.
Related python PR:
- eProsima/Fast-DDS-python/pull/144
- **N/A** New feature has been documented/Current …
> [21130] Migrate ResourceManagement to rtps attributes API

- src/cpp/xmlparser/XMLDynamicParser.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/regressions/21181_profile_bin.xml
This PR fixes the 69667 ClusterFuzz-External issue.
**Note**: changes are not backport compatible nor API compatible because have been caused by the Dynamic Types refactor, which is not.
> [21181] Fix parse XML dynamic type fuzzer issue

- examples/cpp/configuration/SubscriberApp.cpp
- include/fastdds/dds/publisher/qos/DataWriterQos.hpp
- include/fastdds/dds/subscriber/qos/DataReaderQos.hpp
- include/fastdds/rtps/attributes/PropertyPolicy.h
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/subscriber/qos/DataReaderQos.cpp
- src/cpp/fastdds/utils/QosConverters.cpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/unittest/dds/subscriber/SubscriberTests.cpp
This PR reviews that the API of QoS is identical for all entities that share a common QoS. It also makes the PropertyPolicyQoS of DataWriters and DataReader unmutable (such as the one of Participants), until a deeper study is made on what Policies should be mutable on enabled entities.
- Python tests has also been updated: https://github.com/eProsima/Fast-DDS-python/pull/145
- ❌ Changes are backport compatible: they do **NOT** break ABI nor change library …
> [21077] Update Fast DDS docs QoS examples

- .github/workflows/mac-ci.yml
- .github/workflows/nightly-mac-ci.yml
- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/reusable-mac-ci.yml
- .github/workflows/reusable-sanitizers-ci.yml
This PR performs the following improvements in this project CI:
- Avoid CCache in all workflows, keeping it configurable in most of them for debug purposes
- Avoid CCache also in nightlys
**Important**: Backports must remove nightly workflows
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x 
- **N/A** Changes are backport compatible: they do **NOT** break ABI nor change library core …
> [21158] CI - Avoid CCache in workflows and nightlys

- examples/cpp/dds/RequestReplyExample/Calculator.hpp
- include/fastdds/dds/xtypes/dynamic_types/detail/dynamic_language_binding.hpp
- src/cpp/fastdds/builtin/type_lookup_service/detail/rpc_types.hpp
- src/cpp/fastdds/xtypes/dynamic_types/MemberDescriptorImpl.cpp
- src/cpp/statistics/types/monitorservice_types.hpp
- test/blackbox/types/statistics/monitorservice_types.hpp
- test/feature/dynamic_types/DynamicTypesTests.cpp
- test/unittest/dds/topic/DDSSQLFilter/data_types/ContentFilterTestType.hpp
TypeObject doesn't allow to contain the information whether a enumeration is signed or unsigned. It only stores the *bit_bound*. To avoid conflicts we were restricting the creation of enumerations using Dynamic Language Binding to only signed integers.
- *N/A* Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- Related documentation PR: eProsima/Fast-DDS-docs#821
> Only signed integers are permited in Dynamic Language Binding enumerations [21201]

- .github/workflows/reusable-ubuntu-ci.yml
- test/CMakeLists.txt
- test/profiling/CMakeLists.txt
This PR removes the `valgrind` build dependency for building profiling tests, as its installation was causing CI problems due to 404 responses from ubuntu's security repositories.
- _N/A_: New feature has been added to the `versions.md` file (if …
> [21219] Remove Valgrind build dependency for profiling tests

- .github/workflows/reusable-ubuntu-ci.yml
- test/CMakeLists.txt
- test/profiling/CMakeLists.txt
- test/profiling/MemoryTestTypes.cpp
- test/profiling/MemoryTestTypes.h
This PR is a combination of backporting #4986 with the addition of the CI changes introduced in #4960. It enable compilation of profiling tests in Ubuntu CI.
As it only affects the alternative builds step, `no-test` label is added.
- _N/A_: Changes are …
> [21219] Build profiling tests as alternate build in Ubuntu CI 

- .github/pull_request_template.md
- README.md
- RELEASE_SUPPORT.md
This PR updates the release support table with the internal decisions regarding the EOL of the current LTS and supported Fast DDS branches.
- **N/A** New feature …
> [21224] Update release support table 

- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/transport/UDPTransportInterface.cpp
- src/cpp/rtps/transport/UDPTransportInterface.h
- src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
- src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
- test/blackbox/common/BlackboxTestsTransportTCP.cpp
This PR uses the features introduced in https://github.com/eProsima/Fast-DDS/pull/4586 to ALWAYS create a connection channel for the TCP when initial peers are configured.
> [20650] Create InitialConnection for TCP initial peers 3.x & 2.14

- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- test/blackbox/common/BlackboxTestsTransportTCP.cpp
This PR uses the features introduced in https://github.com/eProsima/Fast-DDS/pull/4584 to ALWAYS create a connection channel for the TCP when initial peers are configured.
@Mergifyio backport  2.10.x 2.6.x
> [20650] Create InitialConnection for TCP initial peers 2.13 & 2.10 & 2.6

- test/examples/test_configuration.py
- test/examples/test_content_filter.py
- test/examples/test_custom_payload_pool.py
- test/examples/test_delivery_mechanisms.py
- test/examples/test_delivery_mechanisms_isolated.py
- test/examples/test_hello_world.py
- test/examples/test_xtypes.py
Some example tests have been failing due to both participants trying to print in stdout simultaneously (not mutex control on printing).
That has caused issues on CI (check [this nightly ](https://github.com/eProsima/Fast-DDS/actions/runs/9736649860) for instance).
This PR fixes the counting method so the line is not skipped if already found one of the expected outputs (`SENT` or `RECEIVED`)
Example of the obtained output:
`Sample: 'Delivery mechanisms' with index: 'Sample: '2Delivery mechanisms' with index: '' SENT2' RECEIVED`
- **N/A** Any new/modified methods …
> [21219] Fix flakyness on test with participants in the same container

- src/cpp/fastdds/publisher/DataWriterImpl.cpp
Bugfix to the changes introduced in #4966 in `DataWriterImpl.cpp`.
- __NO__  New feature has been documented/Current behavior is correctly described in the documentation. 
- __NO__ Applicable backports have been included in the description.
- …
> [21272] Fix assertion in TopicPayloadPool::release_history

- include/fastrtps/types/DynamicLoanableSequence.hpp
This PR updates a comment section that makes build fail in documentation jobs.
Note that the name of the PR branch is the same as the one failing in documentation:
- eProsima/Fast-DDS-Docs/pull/836 …
> [21256] Manual fix for documentation generation

- src/cpp/rtps/writer/ReaderLocator.cpp
- src/cpp/rtps/writer/ReaderLocator.hpp
- src/cpp/rtps/writer/ReaderProxy.hpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- test/mock/rtps/ReaderLocator/rtps/writer/ReaderLocator.hpp
- test/performance/latency/LatencyTestPublisher.cpp
- test/performance/latency/LatencyTestPublisher.hpp
- test/performance/latency/LatencyTestSubscriber.cpp
- test/performance/latency/LatencyTestSubscriber.hpp
- test/performance/latency/main_LatencyTest.cpp
Some of the `Latency tests` failed in mac from time to time, in particular, the intraprocess ones. Analysis revealed the following backtrace:
```
libfastdds.3.0.0.dylib!eprosima::fastdds::rtps::BaseReader::downcast(eprosima::fastdds::rtps::RTPSReader*) (/Users/mardom/dds_ws/src/fastdds/src/cpp/rtps/reader/BaseReader.cpp:236)
libfastdds.3.0.0.dylib!eprosima::fastdds::rtps::StatefulWriter::intraprocess_delivery(eprosima::fastdds::rtps::CacheChange_t*, eprosima::fastdds::rtps::ReaderProxy*) (/Users/mardom/dds_ws/src/fastdds/src/cpp/rtps/writer/StatefulWriter.cpp:483)
libfastdds.3.0.0.dylib!eprosima::fastdds::rtps::StatefulWriter::deliver_sample_to_intraprocesses(eprosima::fastdds::rtps::CacheChange_t*) (/Users/mardom/dds_ws/src/fastdds/src/cpp/rtps/writer/StatefulWriter.cpp:642) …
```
> [21232] Fix flaky latency tests on mac

- test/performance/latency/LatencyTestPublisher.cpp
- test/performance/latency/LatencyTestPublisher.hpp
- test/performance/latency/LatencyTestSubscriber.cpp
- test/performance/latency/LatencyTestSubscriber.hpp
- test/performance/latency/main_LatencyTest.cpp
This PR takes the latency tests fix from #5009 and brings it to `2.x`. 
@Mergifyio backport 2.13.x 2.10.x 
- __NO__ New feature has been documented/Current behavior is correctly described in the documentation.
> [21232] Fix Latency tests - `2.x backports`

- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/dds/domain/DomainParticipantFactory.hpp
- include/fastdds/dds/domain/DomainParticipantListener.hpp
- include/fastdds/dds/publisher/DataWriter.hpp
- include/fastdds/dds/publisher/Publisher.hpp
- include/fastdds/dds/subscriber/DataReader.hpp
- include/fastdds/dds/subscriber/Subscriber.hpp
- include/fastdds/rtps/common/ChangeKind_t.hpp
- include/fastdds/rtps/common/FragmentNumber.h
- include/fastdds/rtps/common/MatchingInfo.h
- include/fastdds/rtps/common/SequenceNumber.h
- include/fastdds/rtps/common/Types.h
This PR is a manual backport to 2.14.x of two PRs:
* #4700
* #5011 
This work has been done so the following docs PR passes CI:
* eProsima/Fast-DDS-docs#796
Related PRs:
* eProsima/Fast-DDS-python/pull/154
* eProsima/Fast-DDS-docs#796
- _N/A_:  Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _N/A_:  New feature has been added to the `versions.md` file (if applicable).
- Related documentation PR: eProsima/Fast-DDS-docs#796
> [21114] Remove doxygen warnings (#4700, #5011)

- .github/workflows/nightly-mac-ci.yml
- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/nightly-windows-ci.yml
- .github/workflows/weekly-mac-ci.yml
- .github/workflows/weekly-ubuntu-ci.yml
- .github/workflows/weekly-windows-ci.yml
This PR removes `2.6.x` nighties and sets up weekly jobs for running on `2.6.x`.
- __NO__ New feature has been documented/Current behavior is correctly described in the documentation. 
- __NO__ Applicable backports have been included in …
> [21244] Migrate `2.6.x` ci jobs from nighties to weeklies

- include/fastdds/dds/publisher/DataWriter.hpp
- include/fastdds/dds/subscriber/DataReader.hpp
This PR adjusts some Doxydoc so that the pydoc generated for Fast DDS Python does not make RTD build failed. This PR is a follow up of:
* #5016
This PR is related to:
* eProsima/Fast-DDS-docs#796
- Related documentation PR: eProsima/Fast-DDS-docs#796
- _N/A_: If this is a critical bug fix, backports to the …
> [21114] Adjust doxygen so Fast DDS Python pydoc makes RTD build

- src/cpp/rtps/messages/MessageReceiver.cpp
- versions.md
`MessageReceiver` is setting the vendor _id for all RTPS submessages but for `Data` and `DataFrag`. This PR sets the vendor_id for this last submessages.
> Setting vendor_id on received CacheChange_t [21214]

- CMakeLists.txt
- package.xml
- versions.md
This PR updates the required files to bump `Fast DDS` version to `v2.6.9`.
It also updates `versions.md`.
- _N/A_ Applicable backports have …
> [21244] Bump version to v2.6.9

- src/cpp/rtps/builtin/liveliness/WLP.cpp
- src/cpp/rtps/reader/StatefulReader.cpp
- src/cpp/rtps/reader/StatelessReader.cpp
- test/blackbox/common/BlackboxTestsLivelinessQos.cpp
- test/blackbox/common/DDSBlackboxTestsROS2.cpp
- test/blackbox/common/ros2/Context.hpp
- test/blackbox/common/ros2/DataReaderHolder.hpp
- test/blackbox/common/ros2/DataWriterHolder.hpp
- test/blackbox/common/ros2/GenericHolder.hpp
- test/blackbox/common/ros2/Node.hpp
- test/blackbox/common/ros2/PublicationNode.hpp
- test/blackbox/common/ros2/SubscriptionNode.hpp
- test/blackbox/common/ros2/TopicHolder.hpp
PR #4822 (and its backports) introduced a regression that was not detected until we requested ROS 2 rolling to use branch 2.14.x [here](https://github.com/ros2/ros2/pull/1570)
This PR:
1. Adds infrastructure to create Blackbox tests that simulate the behavior of ROS 2 node
2. Adds a ROS2 black-box test trying to mimick the test that regressed
3. Add a standard black-box regression test for the issue discovered
4. Fixes the issue
> [21245] Fix topic interference on `liveliness_changed` status

- include/fastdds/rtps/common/ChangeKind_t.hpp
- include/fastdds/rtps/common/FragmentNumber.hpp
- include/fastdds/rtps/common/MatchingInfo.hpp
- include/fastdds/rtps/common/SequenceNumber.hpp
- include/fastdds/rtps/common/Types.hpp
This fixes a bug between doxygen >1.9.7 and breathe 4.35.0
This fixes a bug between doxygen >1.9.7 and breathe 4.35.0.
- **N/A** If this is a critical bug fix, backports to the critical-only supported branches …
> [21288] Remove doxygen directive @group in enumerations and typedefs

- .github/workflows/weekly-mac-ci.yml
- .github/workflows/weekly-ubuntu-ci.yml
- .github/workflows/weekly-windows-ci.yml
The cron expression was overlooked during the review so the CI that was supposed to be run only at 00:00 on Mondays it is being triggered every hour in Monday.
- …
> [21309] Fix weekly CI cron expression

- test/performance/latency/CMakeLists.txt
- test/performance/latency/XFAIL_LATENCY.list
- test/performance/latency/XFAIL_LATENCY_SECURITY.list
This PR fixes compilation of performance tests without security in `2.6.x`, label latency tests with security in another file.
- _N/A_  Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_  Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _N/A_  Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_  Changes are API compatible. 
- _N/A_  New feature has been added to the `versions.md` file (if applicable).
- _N/A_  New feature has been documented/Current behavior is correctly described in the documentation. 
- …
> [21267] Fix `2.6.x` latency security XFAIL compilation without security

- examples/cpp/configuration/CLIParser.hpp
- examples/cpp/configuration/PublisherApp.cpp
- examples/cpp/configuration/README.md
- examples/cpp/configuration/SubscriberApp.cpp
Duration QoS were not behaving as expected when they were not configured through the CLI. This PR only set up those QoS if the related argument has been provided in the CLI.
**Note**: This PR is in top of (and must be merged after):
- #4958 
- **N/A** New feature has been added to the `versions.md` file (if …
> [19563] Fix non-defined duration Qos in configuration example

- src/cpp/rtps/messages/MessageReceiver.cpp
- tools/fds/server.cpp
After testing compilation on VS2022, this PR fixes compilation error in Debug.
> [21335] Fix compilation on VS 2022 in Debug

- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- test/mock/rtps/ReaderProxyData/fastdds/rtps/builtin/data/ReaderProxyData.hpp
- test/mock/rtps/WriterProxyData/fastdds/rtps/builtin/data/WriterProxyData.hpp
- test/unittest/rtps/discovery/EdpTests.cpp
Currently `EDP::valid_matching` expects both TypeInfomation are exactly equal. This PR makes this checking more flexible, allowing to pass when they have only `EK_COMPLETE` or `EK_MINIMAL` equals.
Depends on:
- #4985 
- *N/A* Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- *N/A* If this is a critical bug fix, backports to …
> Make more flexible EDP::valid_matching with TypeInformation [21260]

- src/cpp/CMakeLists.txt
> fix: fix typo in CMakeLists.txt

- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/reusable-ubuntu-ci.yml
- .github/workflows/reusable-windows-ci.yml
- .github/workflows/ubuntu-ci.yml
- .github/workflows/weekly-ubuntu-ci.yml
This PR addresses the following points related to the github CI:
* Change windows reusable ci to use new merge meta files eProsima CI action
* Add weekly ubuntu CI to test 2.x branches with CDR 1.1.x
* move the if (!skip-ci) inside the reusable workflows (as done in other repos with the run-build input), but keep the if (!conflicts) in the PR workflow so the GitHub CI requirement is not satisfied if skipped by conflicts.
* Refactor ubuntu ci - python build job:
build packages-select `fastdds_python` package
- _N/A_ Any …
> [21267] Add Ubuntu weekly ci

- CMakeLists.txt
- package.xml
- versions.md
This PR bumps the project version to 2.14.3
- _N/A_: Applicable …
> [21311] Bump version to 2.14.3

- CMakeLists.txt
- package.xml
This PR bumps the project version to 2.13.6
- _N/A_: Applicable …
> [21310] Bump version to v2.13.6

- .github/pull_request_template.md
- .github/workflows/nightly-mac-ci.yml
- .github/workflows/nightly-sanitizers-ci.yml
- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/nightly-windows-ci.yml
- .github/workflows/weekly-sanitizers-ci.yml
- RELEASE_SUPPORT.md
This PR sets 2.13.x as EOL, and fixes nigtly sanizer job for 2.6x (OOS) …
> [21310] Set 2.13.x as EOL

- include/fastdds/rtps/common/EntityId_t.hpp
- src/cpp/statistics/rtps/GuidUtils.hpp
The EntityID of the MonitorService DataWriter is `0x004000D2`, which is not included in the statistics data writer range ([GuidUtils.hpp::37](https://github.com/eProsima/Fast-DDS/blob/4e8dd38f0550b4a5d963b4d82dfe7a988db07ee1/src/cpp/statistics/rtps/GuidUtils.hpp#L37)).
Hence, the discovery database fails to recognize the DataWriter and issues an error ([DiscoveryDataBase.cpp::400](https://github.com/eProsima/Fast-DDS/blob/4e8dd38f0550b4a5d963b4d82dfe7a988db07ee1/src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp#L400)) when the writer is discovered.
@Mergifyio 2.14.x
- _N/A_ Any new/modified methods have been properly …
> [21371] Change monitor service writer entity id

- examples/cpp/configuration/CLIParser.hpp
The configuration example crashed when no entity argument was provided because of the lack of entity check at the beginning of the parsing arguments method.
This PR fixes the issue by checking the arguments.
- **N/A** New feature …
> [21386] Fix lack of entity arguent issue in configuration example

- include/fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp
This PR adds missing DynamicType header file in `ITypeObjectRegistry`.
- _N/A_ If this is a critical bug …
> Add missing DynamicType includes

- .github/workflows/reusable-ubuntu-ci.yml
- .github/workflows/reusable-windows-ci.yml
- CMakeLists.txt
- examples/cpp/static_edp_discovery/CLIParser.hpp
- examples/cpp/static_edp_discovery/PublisherApp.hpp
- examples/cpp/topic_instances/CLIParser.hpp
- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/utils/UnitsParser.cpp
Due to an infrastructure issue with an internal action for Windows, the CI was not properly applying some CMake arguments while testing Fast DDS on Windows. Among others, the examples were not built, so CI passed even though.
This PR fixes the build issue, and tests the changes in the infrastructure to ensure it does not happen anymore.
It was detected also a build issue when security and log info were disabled. In this PR it has been introduced a CI job that builds Fast DDS without any additional arguments / flags, and the error fix has been introduced too.
Finally, building with warnings as error has been set also from the main CMakeLists.txt file.
Related eProsima-CI pr:
- https://github.com/eProsima/eProsima-CI/pull/116
- **N/A** Any new/modified methods have been properly documented …
> [21387] Fix build issues and update CI infrastructure to detect them

- .github/workflows/reusable-ubuntu-ci.yml
- .github/workflows/reusable-windows-ci.yml
This PR fixes the windows CI that was using a removed eProsima-CI action, and includes a vanilla build job in ubuntu CI.
As part of the CI, it is backported to 2.6.x
@Mergifyio backport  2.10.x 2.6.x  …
> [21387] Fix windows CI and add vanilla build step in ubuntu CI

- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.hpp
- src/cpp/rtps/builtin/BuiltinProtocols.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
- versions.md
This PR modifies the behavior of TypeLookup service to ensure compatibility with the Discovery Server. Participants now issue the TypeLookupRequest to the participant that sent them the Data (r|w), rather than to the participant containing the endpoint. This adjustment allows servers to respond to their clients, thereby keeping discovery traffic limited to servers. Additionally, it addresses minor changes to improve functionality with the Discovery Server.
- This PR is on top of https://github.com/eProsima/Fast-DDS/pull/4716 and must be merged after it.
- _N/A_ New feature has been documented/Current behavior is …
> [20953]  Support Type-Lookup Service with new new GUID-less Discovery Server

- examples/cpp/configuration/CLIParser.hpp
- examples/cpp/configuration/PublisherApp.cpp
Fixed wait bug in configuration example. By default, Publisher was waiting for one Subscriber to start publishing. Changed the condition to 0.
- _N/A_ New feature has been documented/Current behavior is correctly described in the …
> [21420] Fix wait argument in configuration example

- CMakeLists.txt
Some installation paths contained a `//`, this PR fixes those, even though they are not harmful.
**IMPORTANT**: Same change needs to be backported to 2.10.x, but it'd be easier from the 2.14.x PR.
- _N/A_: New feature has been documented/Current …
> [21364] Remove double // in some installation paths

- include/fastdds/dds/core/policy/ParameterTypes.hpp
- include/fastdds/rtps/builtin/data/ParticipantBuiltinTopicData.hpp
- include/fastdds/rtps/common/ProductVersion_t.hpp
- include/fastdds/rtps/common/Types.hpp
- src/cpp/fastdds/core/policy/ParameterSerializer.hpp
- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
- src/cpp/rtps/builtin/data/ParticipantProxyData.hpp
- src/cpp/rtps/builtin/data/ProxyDataConverters.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
- versions.md
This PR introduces a new custom pid PID_PRODUCT_VERSION (0x8000) used to send the Fast DDS version.
Depends on:
- #4930
> [21198] Add product version on Participant Discovery information

- include/fastdds/rtps/common/Locator.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
- versions.md
This PR links the definition of the SHM locator kind to the Fast DDS major version. That way, we avoid keeping SHM locators from participants of different majors, as the port structure will be different (the SHM port ABI version will change from major to major).
This PR fixes compatibility issues with 2.x versions when all the participants have an SHM transport without requiring further modifications on any 2.x version.
- A static assert is added to ensure the value
- _N/A_: …
> [19036] Link SHM locator kind with Fast DDS major version

- src/cpp/rtps/history/WriterHistory.cpp
A memory issue is reported by ASAN when running tests using security such as BlackboxTests_DDS_PIM.Security.BuiltinAuthenticationPlugin_second_participant_creation_loop.
The issue is that the events thread might call `SecurityManager::resend_handshake_message_token`, which internally calls `WriterHistory::remove_change_and_reuse`, the latter not being (atomically) thread safe. If at the same time a handshake is processed (`SecurityManager::on_process_handshake`) from another thread, this may resolve in a change being added to the aforementioned writer history. As a result a change is added to `History::m_changes` vector, which would invalidate the iterator dealt with in `WriterHistory::remove_change_and_reuse` without protection.
Two potential solutions are proposed:
- Take the …
> [21435] Solve SecurityManager memory issue

- include/fastdds/rtps/builtin/data/PublicationBuiltinTopicData.hpp
- include/fastdds/rtps/builtin/data/SubscriptionBuiltinTopicData.hpp
- include/fastdds/rtps/participant/ParticipantDiscoveryInfo.hpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/rtps/builtin/data/ProxyDataConverters.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.h
- test/blackbox/common/RTPSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSWithRegistrationReader.hpp
- test/blackbox/common/RTPSWithRegistrationWriter.hpp
- versions.md
This PR:
* Adds `topic_kind` to `PublicationBuiltinTopicData` and `SubscriptionBuiltinTopicData`.
* Removes `@ingroup` from the doxygen documentation of `ParticipantDiscoveryStatus`.
* Makes the creation of RTPS endpoints fail when the entity id is not consistent with the topic kind specified in the corresponding attributes.
- __NO__: Changes are API compatible. 
> [21437] Builtin data related improvements

- PLATFORM_SUPPORT.md
- RELEASE_SUPPORT.md
- roadmap.md
This PR updates the roadmap document (removes already implemented features), the platform support (removes ubuntu 20.04 and vs141 from tier 2 to tier 3), and the release support (includes 3.x version) …
> [21366] Update roadmap, release support and platform support docs

- examples/cpp/flow_control/CMakeLists.txt
- examples/cpp/flow_control/FlowControl.idl
- examples/cpp/flow_control/FlowControlTypeObjectSupport.cxx
- examples/cpp/flow_control/PublisherApp.cpp
- examples/cpp/flow_control/PublisherApp.hpp
- examples/cpp/rtps/CLIParser.hpp
During release testing, a crash in the flow controller example was caught. This PR fixes windows build in Debug mode, and fixes the crash in the flow controller example execution.
Edit: it has been added also a commit setting the extensibility explicitly, and regenerating the example types.
- **N/A** New …
> [21469] Fix windows issue with flow controller example

- include/fastdds/config/doxygen_modules.hpp
- include/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
- include/fastdds/rtps/builtin/data/ContentFilterProperty.hpp
- src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
- test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
This PR corrects some `@ingroup` doxygen calls mainly because some groups are defined under a `DOXYGEN_SHOULD_SKIP_THIS_PUBLIC` but then referenced in public headers. 
The `@defgroup statistics_module` should belong to a valid public group, because it is referenced in public headers.
In addition an `usued local variable` warning is addressed.
- _N/A_ …
> [21366] Address some warnings when generating windows installer for v3.0.0

- include/fastdds/rtps/common/InstanceHandle.h
This PR is a mimic of
- #5125 
which is opened by an eProsima Team member in order to run internal CI.
No tests are needed, but just the library build.
This fix may also be needed in the 2.10.x Iron version, so it is marked as a backportable PR.
@Mergifyio backport 2.10.x  …
> [21470] Apply @Blast545 contribution: Add unsigned specification to literals (#5125)

- src/cpp/rtps/messages/MessageReceiver.cpp
This is a follow-up of #5122 that fixes an `unused parameter 'participant'` warning in the oss-fuzz build.
- __N/A__ If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- __N/A__ Check CI …
> [21442] Fix warning in oss fuzz build

- README.md
- versions.md
This PR sets `versions.md` to `v3.0.0` and removes `v3.0.0` warning from README.md.
- _N/A_ Applicable backports have been included in the …
> [21366] Bump versions to v3.0.0

- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.h
- test/blackbox/common/BlackboxTestsSecurity.cpp
This PR fixes a behavior that changed in https://github.com/eProsima/Fast-DDS/commit/f2e5ce making simple secure participants not match.
The `tcp client` sends its `DATA[P]` to the tcp server, the server starts the security handshake but the client is not able to accept the security handshake request because it does not have the discovery information from the server participant.
- _N/A_ If this is a critical bug fix, backports to the critical-only supported branches have been …
> [20181] Hotfix: Secure simple participants with `initialpeers` over `TCP` match

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
This PR updates the arguments of internal discovery database api to use constant references for string arguments.
Fixes #5175
- **NA** If this is a critical bug fix, …
> [21512] Set string arguments as const references

- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatefulWriter.hpp
- src/cpp/utils/SystemInfo.cpp
- src/cpp/utils/time_t_helpers.hpp
When investigating a system undergoing larger system clock adjustments, I noticed that in some places, std::chrono::system_clock and std::chrono::high_resolution_clock are used for handling timeouts and status check intervals.
However, std::chrono::system_clock  is definitely not steady, and std::chrono::high_resolution_clock is not steady quite often (see [cppreference](https://en.cppreference.com/w/cpp/chrono/high_resolution_clock)).
When undergoing clock adjustments (manually or due to clock server synchronization), timeouts and status checks might no longer be triggered when relying on timestamps based on std::chrono::system_clock.
- _N/A_ Any new configuration API has an …
> [21314] Improve resilience against clock adjustments

- src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.cpp
- src/cpp/fastdds/xtypes/dynamic_types/AnnotationDescriptorImpl.hpp
*Edit: Fix the problem that gcc-9 cannot compile. The code should take into account version compatibility issues. Now our vehicle communication domain controllers all use gcc-9 and g++-9. You should take this into consideration*
Fixes: #5170
Fixes: #5150
- **N/A** …
> [21514] Make Fast DDS build compatible with gcc9

- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupReplyListener.cpp
- src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
- test/unittest/dds/xtypes/type_representation/TypeObjectUtilsTests.cpp
DDS Router is having problems redirecting the TypeInformation from one side to another. This PR tries to solve this making the TypeLookupService registers the `EK_MINIMAL` TypeObject built from the received `EK_COMPLETE` TypeObject.
> [21563] TypeLookupService: also register the minimal created from the received complete TypeObject

- .github/workflows/reusable-ubuntu-ci.yml
This PR use a new eProsima-CI action to install Qt. This migration has been done in order to reach better scalability setting all the external action in the CI repo, so any change required in the action only needs to be done there.
Related PRs:
- https://github.com/eProsima/eProsima-CI/pull/119
- https://github.com/eProsima/ShapesDemo/pull/173
**Note**: As part of a CI update, this PR needs to be backported also to 2.6.x.
@Mergifyio backport 2.14.x 2.10.x 2.6.x 
- **N/A** Any new configuration API has an equivalent XML API (with the corresponding …
> [21535] Use eProsima-CI action to install Qt

- src/cpp/utils/time_t_helpers.hpp
This PR reverts a behavior change introduced in #5018.
Regarding **backports**, we'll need to add this change to #5189, which is the only backport of #5018.
> [21609] Revert behavior change on `current_time_since_unix_epoch`

- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- test/blackbox/common/DDSBlackboxTestsOwnershipQos.cpp
- test/unittest/dds/subscriber/DataReaderHistoryTests.cpp
During interoperability testing, some flakiness on [Test_Ownership_3](https://omg-dds.github.io/dds-rtps/test_description.html#test-ownership-3) unveiled that a reader with exclusive ownership and a `KEEP_ALL` history may return a mix of samples from writers with different strengths.
This PR adds a regression test and fixes the issue by removing inappropriate samples during the take operation.
> [21519] Fix issue with exclusive ownership and unordered samples

- CMakeLists.txt
- test/mock/rtps/NetworkFactory/rtps/network/NetworkFactory.hpp
- test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
- test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
- test/unittest/rtps/discovery/CMakeLists.txt
- test/unittest/rtps/discovery/EdpTests.cpp
- test/unittest/rtps/security/SecurityTests.hpp
Fix compilation errors in Ubuntu 24.04 using `-Werror`.
Depends on:
- eprosima/fast-dds-gen#395
Fixes the related error in eprosima/fast-dds-gen#395 and also this error:
```
[ 66%] Building CXX object test/unittest/dds/status/CMakeFiles/ListenerTests.dir/__/__/__/__/src/cpp/fastdds/xtypes/type_representation/TypeObjectUtils.cpp.o
In file included from /usr/include/c++/13/vector:66,
from /home/ricardo/workspace/eprosima/fastdds/include/fastdds/dds/core/policy/QosPolicies.hpp:24,
from /home/ricardo/workspace/eprosima/fastdds/include/fastdds/rtps/builtin/data/PublicationBuiltinTopicData.hpp:27,
from /home/ricardo/workspace/eprosima/fastdds/include/fastdds/dds/builtin/topic/PublicationBuiltinTopicData.hpp:22,
from /home/ricardo/workspace/eprosima/fastdds/src/cpp/fastdds/publisher/DataWriterImp …
```
> [21624] Fix compilation errors in Ubuntu 24.04 using `-Werror`

- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
This PR addresses a critical issue with iterator handling in the loop that processes elements of `connected_servers_`. The original implementation encountered an assertion failure due to invalid iterator increments after removing elements from the container.
Comment for the reviewer:
- Alternative approach to fix the problem: Given that the `connected_servers_` list is expected to contain at most one element with the matching `guidPrefix`, another viable solution could be to use a break statement within the `if (it->guidPrefix == pdata->m_guid.guidPrefix)` condition. This would immediately exit the loop after finding and removing the element, eliminating the need to handle iterator invalidation explicitly.
- __NO__: Tests that thoroughly check the new …
> [21649] Correct iterator increment after erasing elements in `connected_servers_list`

- CMakeLists.txt
- package.xml
Bumps Fast DDS's version to `v3.0.1`.
- **N/A** Applicable …
> [21561] Bump version to 3.0.1

- examples/cpp/request_reply/README.md
The example readme was not updated with the latest behavior changes done before its refactor was merged.
This PR updates the `README` to include real examples of usage.
Fixes #5231
- **N/A** New feature has been documented/Current …
> [21671] Update request reply example `README`

- examples/cpp/xtypes/PublisherApp.cpp
Example segfault if xml env var is not configured previously:
``` bash
./build/fastdds/examples/cpp/xtypes/xtypes publisher --xml-type
Error getting dynamic type "HelloWorld".
Segmentation fault (core dumped)
```
This PR fixes the behavior to correctly fail in that case …
> [21652]  Fix xtypes example segfault if xml env var is not set

- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDP.h
This PR removes the `validMatching` deprecated methods in `EDP`
- **N/A**Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Applicable backports have been included in the …
> [21706] Remove unused `validMatching` methods in `EDP`

- tools/fastdds/xml_ci/parser.py
The Fast DDS CLI tool does not properly display the validation argument in the help message. 
This PR updates the help message to show proper argument.
- **N/A** If this is a critical bug fix, backports to the critical-only supported …
> [21720] Modify help command of XML CLI tool

- src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
All statistics types are currently being registered and propagated (via TypeLookupService), except the type of `_fastdds_monitor_service_status` topic (`MonitorServiceStatusData`). This PR corrects that behaviour.
- **N/A** Applicable backports have been included in …
> [21740] Register and propagate MonitorService status type object

- CMakeLists.txt
- package.xml
- versions.md
Preparing for releasing v2.10.5, this PR bumps the version correspondingly.
- _N/A_: Check CI results: …
> [21557] Bump version to 2.10.5

- src/cpp/rtps/messages/MessageReceiver.cpp
- src/cpp/rtps/reader/reader_utils.cpp
- test/blackbox/common/BlackboxTestsTransportUDP.cpp
We currently don't have support for key-only payloads bigger than the KEY_HASH length.
Receiving such kind of messages produces a segfault in DataReaderHistory.
This PR adds a regression test reproducing the issue, and fixes it by considering the incoming change as irrelevant.
It has been done this way so it is acknowledged in reliable topics, thus avoiding the offending data to be resent.
@Mergifyio backport 2.6.x
- _N/A_: New feature has been documented/Current behavior is correctly described in …
> [21751] Discard changes with big key-only payload and no key hash

- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
Asan CI job detects a memory leak when TypeLookupManager is destroyed having still replies to be received. It was detected in eprosima/fast-dds#5109
- *N/A* Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- *N/A* New feature has been documented/Current behavior is correctly described in the …
> [21760] Fix memory leak deleting TypeLookupManager

- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl.cpp
- src/cpp/fastdds/topic/TopicImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
- test/blackbox/common/DDSBlackboxTestsPersistence.cpp
- test/blackbox/common/RTPSBlackboxTestsPersistence.cpp
- test/blackbox/common/RTPSBlackboxTestsPersistenceNonIntraprocess.cpp
- test/blackbox/common/RTPSWithRegistrationReader.hpp
- test/blackbox/common/RTPSWithRegistrationWriter.hpp
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/publisher/DataWriterTests.cpp
- test/unittest/dds/subscriber/DataReaderTests.cpp
- versions.md
This PR:
* Allows the creation of a  DataWriter/Reader with a `PERSISTENT` durability, but behaving as `TRANSIENT`.
* When in `TRANSIENT`, if no persistence guid is given, it fallbacks to `TRANSIENT_LOCAL`.
* Refactors BB `make_transient()` `make_persitent()` pubsub API to be clearer about the intention of making a transient or persistent endpoint. 
* Adds BB tests for the purpose.
- Related documentation PR: eProsima/Fast-DDS-docs#907
> [21538] Allow all `durability` configurations

- CMakeLists.txt
- fastdds.repos
- tools/fastdds/xml_ci/parser.py
- tools/fds/CMakeLists.txt
This other PR:
* Moves `fastdds_profiles.xsd` and `fastdds_static_discovery.xsd` installation directory to `.../share/fastdds` (previously in `.../share`) .
* Removes redundant cmake installation of `fastdds_profiles.xsd` within the `/tools` `CMakeLists.txt`.
**IMPORTANT** this PR must be merged along with:
* https://gitlab.intranet.eprosima.com/eProsima/fastdds-installers/-/merge_requests/20. In turn, this MR has to be backported to `3.0.x` branch
This MR:
* Makes the windows uninstaller script to completely remove the `fastdds x.x.x`  installation directory.
* Makes the windows installer to place the `*.xsd` files into `(install_prefix)\share\fastdds` 
* https://github.com/eProsima/Fast-DDS-docs/pull/925
@Mergifyio backport 3.0.x
- _N/A_ Tests that thoroughly check the new feature have …
> [21564] [21666] Change `xsd` files installation directory to `share/fastdds` and remove icons on windows uninstall

- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.h
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- test/dds/communication/CMakeLists.txt
- test/dds/communication/PubSubMain.cpp
- test/dds/communication/PublisherMain.cpp
- test/dds/communication/PublisherModule.cpp
- test/dds/communication/PublisherModule.hpp
- test/dds/communication/SubscriberMain.cpp
- test/dds/communication/SubscriberModule.cpp
- test/dds/communication/SubscriberModule.hpp
- test/dds/communication/dyn_network/CMakeLists.txt
- test/dds/communication/dyn_network/Dockerfile
- test/dds/communication/dyn_network/dynamic_interfaces.compose.yml
- test/dds/communication/dyn_network/launch_subscriber.bash
- test/dds/communication/security/PublisherMain.cpp
- test/dds/communication/security/PublisherModule.cpp
- test/dds/communication/security/PublisherModule.hpp
- test/dds/communication/security/SubscriberMain.cpp
- test/dds/communication/security/SubscriberModule.cpp
- test/dds/communication/security/SubscriberModule.hpp
This PR adds a regression test based in Ubuntu containers for one long standing issue with dynamic network interfaces that was preventing communication when a participant was created with no network interfaces available.
It fixes the issue by correctly updating the locators on the proxy data of the participant, and all its readers or writers created with the default locators.
@Mergifyio backport 3.0.x 2.14.x 2.10.x
- _N/A_ If this is a critical bug fix, backports to the critical-only supported branches have …
> [17283] Fix issues in Dynamic Network Interfaces

- include/fastdds/dds/domain/qos/DomainParticipantQos.hpp
- include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp
- src/cpp/fastdds/domain/qos/DomainParticipantQos.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
- versions.md
DomainParticipantQos objects contain an attribute of kind `FlowControllerDescriptorList`, which is a vector of `FlowControllerDescriptor` shared pointers. Currently the comparison of two equivalent DomainParticipantQos objects is failing when the elements in this list are not the same (determined by memory address) instead of dereferencing and performing the comparison element-wise. This PR fixes this behaviour.
> [21745] Fix flow_controllers comparison in DomainParticipantQos equality operator

- test/unittest/dds/participant/ParticipantTests.cpp
CreateTopicWithDifferentTypeName_negative is failing on Mac due to a `std::system_error` exception launched by SharedMemory transport when the test is closing. The problem is the created participant is not deleted accordantly.
@Mergifyio backport 3.0.x 2.14.x 2.10.x
- _N/A_: If …
> [21802] Fix CreateTopicWithDifferentTypeName_negative flaky test

- include/fastdds/rtps/participant/RTPSParticipant.h
- include/fastdds/rtps/reader/RTPSReader.h
- include/fastdds/rtps/writer/RTPSWriter.h
- src/cpp/rtps/participant/RTPSParticipant.cpp
- src/cpp/rtps/reader/RTPSReader.cpp
- src/cpp/rtps/writer/RTPSWriter.cpp
- test/blackbox/api/dds-pim/PubSubParticipant.hpp
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/BlackboxTests.cpp
- test/blackbox/common/BlackboxTests.hpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
- test/blackbox/common/BlackboxTestsPubSubBasic.cpp
- test/blackbox/common/BlackboxTestsSecurity.cpp
- test/blackbox/common/DDSBlackboxTestsDataReader.cpp
- test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
- test/blackbox/common/DDSBlackboxTestsPersistence.cpp
- test/blackbox/common/RTPSBlackboxTests.cpp
- test/blackbox/common/RTPSBlackboxTestsBasic.cpp
- test/blackbox/common/RTPSBlackboxTestsReader.cpp
- test/blackbox/common/RTPSBlackboxTestsWriter.cpp
- test/blackbox/common/RTPSWithRegistrationReader.hpp
- test/blackbox/common/RTPSWithRegistrationWriter.hpp
- test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
This PR adds the test implementation from the test plan:
`DDS`
* `DataWriter::get_matched_subscriptions()`
* `DataWriter::get_matched_subscription_data()`
* `DataReader::get_matched_publications()`
* `DataReader::get_matched_publication_data()`
`RTPS`
* `RTPSParticipant::get_publication_info()`
* `RTPSParticipant::get_subscription_info()`
* `RTPSReader::matched_writers_guids()` (in the implementation PR, this was changed to pure virtual)
* `RTPSWriter:matched_readers_guids()` (in the implementation PR, this was changed to pure virtual)
- **N/A**  New feature has been documented/Current behavior is correctly …
> [21710] DataWriter/Reader get_matched_publication/subscription() Test implementation

- include/fastdds/dds/xtypes/type_representation/detail/dds_xtypes_typeobject.hpp
- src/cpp/fastdds/builtin/type_lookup_service/detail/TypeLookupTypes.hpp
- src/cpp/statistics/types/monitorservice_types.hpp
- src/cpp/statistics/types/types.hpp
- test/blackbox/types/core/core_types.hpp
- test/blackbox/types/statistics/monitorservice_types.hpp
- test/blackbox/types/statistics/types.hpp
- test/dds-types-test/declarations.hpp
- test/dds-types-test/external.hpp
- test/dds-types-test/helpers/basic_inner_types.hpp
- test/dds-types-test/unions.hpp
- test/unittest/dds/xtypes/serializers/idl/types/union_struct/gen/union_struct.hpp
- test/unittest/dds/xtypes/serializers/json/types/comprehensive_type/gen/ComprehensiveType.hpp
This PR regenerate project types using latest Fast DDS-Gen v4.0.2
- **N/A** Applicable backports have …
> [21783] Regenerate types with latest Fast DDS-Gen v4.0.2

- test/dds/communication/dyn_network/CMakeLists.txt
PR #5282 introduces a test which uses `docker`. If `docker` executable is not found launches a FATAL_ERROR. This could happens inside a docker container. This PR fixes this changing the FATAL_ERROR to WARNING. …
> [21828] Warn instead of fail when `dds.communication.dynamic_interfaces` cannot be built

- include/fastdds/dds/domain/DomainParticipant.hpp
- include/fastdds/dds/domain/DomainParticipantFactory.hpp
- include/fastdds/dds/publisher/Publisher.hpp
- include/fastdds/dds/subscriber/Subscriber.hpp
- src/cpp/fastdds/domain/DomainParticipant.cpp
- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.hpp
- src/cpp/fastdds/publisher/Publisher.cpp
- src/cpp/fastdds/publisher/PublisherImpl.cpp
- src/cpp/fastdds/publisher/PublisherImpl.hpp
- src/cpp/fastdds/subscriber/Subscriber.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.cpp
- src/cpp/fastdds/subscriber/SubscriberImpl.hpp
- src/cpp/xmlparser/XMLProfileManager.cpp
- src/cpp/xmlparser/XMLProfileManager.h
- test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
- test/unittest/dds/participant/CMakeLists.txt
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/profiles/test_xml_profile.xml
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/dds/publisher/PublisherTests.cpp
- test/unittest/dds/subscriber/CMakeLists.txt
- test/unittest/dds/subscriber/SubscriberTests.cpp
- test/utils/FileUtils.hpp
This PR extends public API with methods meant to fill QoS structures given a raw XML string containing pertinent profile configurations. For each QoS getter from XML there are three method variants:
- `get_X_qos_from_xml` without profile name : the first encountered profile of the expected kind (participant, publisher, etc.) is parsed.
- `get_X_qos_from_xml` given profile name : fills the QoS structure with the profile whose name coincides with the one provided.
- `get_default_X_qos_from_xml`  :  fills the structure with the default profile of the expected kind (participant, publisher, etc.) found in the XML string.
This API extension provides backwards compatibility after having made XMLParser private (done in Fast-DDS 3 release).
Merge after:
- …
> [21745] Add QoS getters from raw XML

- examples/cpp/flow_control/README.md
The flow control example readme refers in a certain subsection to "Hello World" instead of the "Flow Control" example.
This PR fixes that.
@Mergifyio backport 3.0.x  …
> Fix wrong Data type referred in flow control example README

- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
PR #5182 introduced a regression that was not detected since we don't have a CI that builds on Debug mode.
The changes on said PR assumed that a change in the owner of an instance when processing an incoming change would only be due to the change coming from a writer with a bigger strength.
But if the change has an _Unregister_ status, the owner would obviously change to a writer different from the incoming change.
This PR converts the assertion on an additional condition to the `if` that decides whether to remove changes from other writers.
@Mergifyio backport 3.0.x 2.14.x 2.10.x
- The ASAN job is showing the regression in the logs, so it is considered enough. I run a manual one [here](https://github.com/eProsima/Fast-DDS/actions/runs/11348632008) 
- _N/A_: Any new/modified methods have …
> [21900] Fix DataReaderHistory regression

- CMakeLists.txt
- package.xml
This PR reverts the bump to 3.2.0.
Fixes #5338
- **N/A** …
> Revert bump to 3.2.0

- test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
TypeLookupSettings was used in the version 2.14.3 which is now redundant and removed from code but this structure is still hanging in the mock code. which this work removes to keep the code clean.
This fix should be done for the 3.1.x and 3.0.x other old branches are unaffected by this.
- **N/A** New …
> Legacy redundunt TypeLookupSettings removed from mock

- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/RTPSDomainImpl.hpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.hpp
- src/cpp/rtps/reader/BaseReader.cpp
- src/cpp/rtps/reader/BaseReader.hpp
- src/cpp/rtps/reader/LocalReaderPointer.hpp
- src/cpp/rtps/writer/ReaderLocator.cpp
- src/cpp/rtps/writer/ReaderLocator.hpp
- src/cpp/rtps/writer/ReaderProxy.hpp
- src/cpp/rtps/writer/StatefulWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- src/cpp/utils/RefCountedPointer.hpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
- test/mock/rtps/ReaderLocator/rtps/writer/ReaderLocator.hpp
- test/unittest/utils/CMakeLists.txt
- test/unittest/utils/RefCountedPointerTests.cpp
This PR addresses a race issue happening in stressed intraprocess scenarios when `EDP's` writer intends to use the remote local reader pointer of an already removed participant. This happens because the participant hasn't received the other's one disposal yet (as it goes through transport). 
Some [ci flaky tests](https://github.com/eProsima/Fast-DDS/actions/runs/10829350591/job/30046734211) have already been identified to be related with this issue.
The proposed solution introduces a new state in the Readers `LocalReaderViewStatus` in which the reader will notify that it is inactive as soon as it is destroyed and *noone* is using it.
On the other side, the remote local writers using pointers to it, now holds a `LocalReaderPointer` which wraps the raw reader's pointer plus the view. An …
> [21293] Fix destruction data-race on participant removal in intra-process

- src/cpp/rtps/security/SecurityManager.cpp
- test/dds/communication/security/CMakeLists.txt
- test/dds/communication/security/multiple_secure_ds_pubsub_secure_crypto_communication.py
This PR addresses an assertion triggering in the `SecurityManager` as a consequence of not being able to retrieve a new change for the `participant_stateless_msg_writer`
> [21696] Fix `SecurityManager` assertion in `Secure DS`

- include/fastdds/statistics/monitorservice_types.idl
- src/cpp/statistics/types/monitorservice_types.hpp
- src/cpp/statistics/types/monitorservice_typesCdrAux.hpp
- src/cpp/statistics/types/monitorservice_typesCdrAux.ipp
- src/cpp/statistics/types/monitorservice_typesPubSubTypes.cxx
- src/cpp/statistics/types/monitorservice_typesPubSubTypes.hpp
- src/cpp/statistics/types/monitorservice_typesTypeObjectSupport.cxx
- src/cpp/statistics/types/monitorservice_typesTypeObjectSupport.hpp
- test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
- test/blackbox/types/statistics/monitorservice_types.hpp
- test/blackbox/types/statistics/monitorservice_typesCdrAux.hpp
- test/blackbox/types/statistics/monitorservice_typesCdrAux.ipp
- test/blackbox/types/statistics/monitorservice_typesPubSubTypes.cxx
- test/blackbox/types/statistics/monitorservice_typesPubSubTypes.hpp
- test/blackbox/types/statistics/monitorservice_typesTypeObjectSupport.cxx
- test/blackbox/types/statistics/monitorservice_typesTypeObjectSupport.hpp
This PR brings the test plan implementation for the `Extended Incompatible QoS` monitor service feature.
> [21756] Extended Incompatible QoS for Monitor Service Tests implementation

- src/cpp/rtps/attributes/RTPSParticipantAttributes.cpp
Compilation with `FASTDDS_SHM_TRANSPORT_DISABLED` should properly manage the shm transport in `LARGE_DATA` modes.
> [21959] Check if `SHM` transport is disabled in `LARGE_DATA` modes

- examples/cpp/configuration/CMakeLists.txt
- examples/cpp/content_filter/CMakeLists.txt
- examples/cpp/custom_payload_pool/CMakeLists.txt
- examples/cpp/delivery_mechanisms/CMakeLists.txt
- examples/cpp/discovery_server/CMakeLists.txt
- examples/cpp/flow_control/CMakeLists.txt
- examples/cpp/hello_world/CMakeLists.txt
- examples/cpp/request_reply/CMakeLists.txt
- examples/cpp/rtps/CMakeLists.txt
- examples/cpp/security/CMakeLists.txt
- examples/cpp/static_edp_discovery/CMakeLists.txt
- examples/cpp/topic_instances/CMakeLists.txt
- examples/cpp/xtypes/CMakeLists.txt
This PR updates the examples CMakeList to build with `Release` CMake build type mode, if the mode has not been specified.
@Mergifyio backport 3.1.x 3.0.x 
This PR is related to:
- https://github.com/eProsima/Fast-DDS-Gen/pull/416
- **N/A** If this is a critical bug …
> [21725] Update examples CMakeList to force default CMAKE_BUILD_TYPE

- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDP.h
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.h
- src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
- src/cpp/statistics/rtps/monitor-service/MonitorService.hpp
- src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.cpp
- src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.hpp
- src/cpp/statistics/rtps/monitor-service/interfaces/IProxyObserver.hpp
- test/mock/rtps/PDP/rtps/builtin/discovery/participant/PDP.h
- test/unittest/statistics/rtps/mock/StatisticsBase/statistics/rtps/StatisticsBase.hpp
- test/unittest/statistics/rtps/mock/StatisticsBase/statistics/rtps/monitor-service/MonitorService.hpp
This PR brings the feature implementation of the `extended incompatible qos` for the monitor service.
This PR must be merged after.
* #5294 
- Related documentation PR: eProsima/Fast-DDS-docs#945
> [21841] Extended Incompatible QoS for Monitor Service Feature implementation

- src/cpp/xmlparser/XMLDynamicParser.cpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/regressions/22054_profile_bin.xml
> [22054] Address `XMLDynamicParser` regression

- include/fastdds/statistics/monitorservice_types.idl
- src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
- src/cpp/rtps/builtin/discovery/endpoint/EDP.h
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.h
- src/cpp/statistics/rtps/monitor-service/MonitorService.cpp
- src/cpp/statistics/rtps/monitor-service/MonitorService.hpp
- src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.cpp
- src/cpp/statistics/rtps/monitor-service/MonitorServiceListener.hpp
- src/cpp/statistics/rtps/monitor-service/interfaces/IProxyObserver.hpp
- src/cpp/statistics/types/monitorservice_types.hpp
- src/cpp/statistics/types/monitorservice_typesCdrAux.hpp
- src/cpp/statistics/types/monitorservice_typesCdrAux.ipp
- src/cpp/statistics/types/monitorservice_typesPubSubTypes.cxx
- src/cpp/statistics/types/monitorservice_typesPubSubTypes.hpp
- src/cpp/statistics/types/monitorservice_typesTypeObjectSupport.cxx
- src/cpp/statistics/types/monitorservice_typesTypeObjectSupport.hpp
- test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
- test/blackbox/types/statistics/monitorservice_types.hpp
- test/blackbox/types/statistics/monitorservice_typesCdrAux.hpp
- test/blackbox/types/statistics/monitorservice_typesCdrAux.ipp
- test/blackbox/types/statistics/monitorservice_typesPubSubTypes.cxx
- test/blackbox/types/statistics/monitorservice_typesPubSubTypes.hpp
- test/blackbox/types/statistics/monitorservice_typesTypeObjectSupport.cxx
- test/blackbox/types/statistics/monitorservice_typesTypeObjectSupport.hpp
- test/mock/rtps/PDP/rtps/builtin/discovery/participant/PDP.h
- test/unittest/statistics/rtps/mock/StatisticsBase/statistics/rtps/StatisticsBase.hpp
- test/unittest/statistics/rtps/mock/StatisticsBase/statistics/rtps/monitor-service/MonitorService.hpp
- versions.md
This PR adds the `Extended incompatible QoS for monitor service` feature.
- Related documentation PR: eProsima/Fast-DDS-docs#947
> [21706] Feature: Extended incompatible QoS for monitor service

- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/rtps/security/SecurityManager.h
- test/blackbox/api/dds-pim/PubSubReader.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/BlackboxTestsSecurity.cpp
`SecurityManager` did not ensure that `participant_stateless_secure_writer` history changes were released when the remote participant was authenticated, leading to a high resource utilization.
This PR:
* Decreases the default initial preallocated pool payload sizes experimentally:
* Participant stateless was 6292 bytes, so it was left to the closest (2^n), 8192.
* Participant secure volatile was 692, so it was left to 1024.
* Makes the `participant stateless secure writer` history to remove the change when `participants cryptography` succeeds. In this way we ensure that authentication has finished in both sides. This was important because having authorized the remote is not a sufficient condition to remove the change as the remote may require us to resend until it completes the …
> [22033] Release `participant_stateless` secure builtin writer history change when authentication has finished

- CMakeLists.txt
- package.xml
This bumps version on 2.10.x to 2.10.6
- _N/A_ Applicable backports have …
> [21755] Bump version to 2.10.6

- src/cpp/rtps/RTPSDomainImpl.hpp
- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/security/OpenSSLInit.hpp
- test/blackbox/common/BlackboxTestsSecurity.cpp
This PR fixes a crash in `OpenSSL` provoked when the `atexit` callback from `openssl` is triggered upon process destruction, making it to trigger a `SIGSEV` on an already released `OpenSSL` resource.
In addition, `OpenSSL` is now a Meyers singleton attached to `RTPSDomainImpl`.
In accordance with [the best practices using OpenSSL](https://developers.redhat.com/articles/2022/10/31/best-practices-application-shutdown-openssl#) and its [documentation](https://docs.openssl.org/master/):
* Initialization is done through `OpenSSL_init_crypto` (available in all versions along with the `OPENSSL_INIT_NO_ATEXIT` option) that makes `atexit` not being registered.
* If `atexit` is not registered, user has to explicitly call `OpenSSL_cleanup()` (also, supported across versions). 
@Mergifyio backport …
> [22024] Improve `OpenSSL` lifecycle handling

- CMakeLists.txt
- package.xml
- test/system/tools/fastdds/CMakeLists.txt
- test/system/tools/fastdds/tests.py
- tools/fastdds/discovery/parser.py
- tools/fastdds/fastdds.py
- tools/fds/server.cpp
- tools/fds/server.h
Modify the cli command tool to provide the version of the installed Fast DDS. Modify CMakeLists.txt in fastdds repository to export 'package.xml' to install directory.
- _N/A_ If this is a critical bug fix, backports to the …
> [21698] Add -v or --version to cli command tool

- thirdparty/filewatch/FileWatch.hpp
solves error: template-id not allowed for constructor in C++20 [-Werror=template-id-cdtor]
Fixes #5340
- **N/A** If this is a critical bug fix, backports to …
> Fix `-Werror=template-id-cdtor`

- .github/workflows/reusable-windows-ci.yml
- examples/cpp/hello_world/CLIParser.hpp
- examples/cpp/hello_world/PublisherApp.cpp
- examples/cpp/hello_world/PublisherApp.hpp
- test/examples/CMakeLists.txt
- test/examples/configuration.compose.yml
- test/examples/content_filter.compose.yml
- test/examples/custom_payload_pool.compose.yml
- test/examples/delivery_mechanisms.compose.yml
- test/examples/delivery_mechanisms_isolated.compose.yml
- test/examples/discovery_server.compose.yml
- test/examples/flow_control.compose.yml
- test/examples/hello_world.compose.yml
- test/examples/request_reply.compose.yml
- test/examples/request_reply_isolated.compose.yml
- test/examples/rtps.compose.yml
- test/examples/security.compose.yml
- test/examples/static_edp_discovery.compose.yml
- test/examples/test_hello_world.py
- test/examples/topic_instances.compose.yml
- test/examples/windows/Dockerfile
- test/examples/xtypes_complete.compose.yml
- test/examples/xtypes_minimal.compose.yml
- versions.md
This PR introduces example testing in windows (for the moment, just the `hello_world_example`) by 
* Refactoring the current ci example testing so that the docker composes can be used for Linux and Windows.
* Creating a new cmake target in which the windows testing image is created with the provided `Dockerfile`
* It also adds a new cli argument to the `hello_world` example `matched` so the publisher does not start publishing until it has discovered a minimum of participants. 
Follow up work
* Include the rest of the examples in the testing.
* Maybe separate the windows ci in two jobs: one for building the core library and the other one for testing  
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and …
> [21886] Feature: Windows ci example testing

- src/cpp/rtps/security/SecurityManager.cpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/TCPTransportInterface.h
- src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
- test/unittest/transport/TCPv4Tests.cpp
- tools/fds/server.cpp
This PR is a partial backport of https://github.com/eProsima/Fast-DDS/pull/5382, which fixes a bug where a TCP client connecting to `localhost` is unable to identify the locator of a TCP discovery server with a custom GUID listening on `any`. This causes the client to create two different channels for the same connection, where the latest can never be reached. The reason is that the server's locator is not considered from the same host due to its custom GUID. Hence, the server transforms the client's locator into `localhost` but the client does not do the same with the server's locator.
The proposed fix is to create a new entry into the `channel_resources_` map for each local interface available. In this way, every locator with local address will reuse the same TCP channel, instead of …
> [22056] Fix TCP discovery server locators translation (backport #5382)

- src/cpp/security/authentication/PKIDH.cpp
- test/blackbox/common/BlackboxTestsSecurity.cpp
- test/dds/communication/security/secure_msg_crypto_besteffort_pub_profile.xml
- test/dds/communication/security/secure_msg_submsg_crypto_besteffort_pub_profile.xml
- test/dds/communication/security/secure_msg_submsg_crypto_besteffort_sub_profile.xml
- test/dds/communication/security/secure_submsg_crypto_besteffort_pub_profile.xml
- test/dds/communication/security/secure_submsg_crypto_besteffort_sub_profile.xml
- test/dds/communication/security/simple_secure_besteffort_pub_profile.xml
- test/dds/communication/security/simple_secure_besteffort_sub_profile.xml
- test/unittest/security/authentication/AuthenticationPluginTests.hpp
- test/unittest/security/authentication/BuiltinPKIDHTests.cpp
- versions.md
[DDS security](https://www.omg.org/spec/DDS-SECURITY/1.1/About-DDS-SECURITY/) specifies the possibility of selecting the key agreement algorithm used to generate the shared secret at the end of the authentication phase.
The Fast DDS [documentation](https://fast-dds.docs.eprosima.com/en/latest/fastdds/security/auth_plugin/auth_plugin.html) indicates that `Elliptic Curve Diffie-Hellman (ECDH)` is used, but this is only the case if a participant from other vendor starts the authentication and proposes that method.
This pull request:
1. Changes the default key agreement algorithm to the one indicated in the documentation
2. Adds a new `dds.sec.auth.builtin.PKI-DH.preferred_key_agreement` property that allows choosing the preferred algorithm to use.
@Mergifyio backport 3.1.x
We will backport …
> [22280] New property to select preferred key agreement algorithm

- src/cpp/utils/IPLocator.cpp
- src/cpp/xmlparser/XMLElementParser.cpp
- test/unittest/utils/LocatorTests.cpp
- test/unittest/xmlparser/CMakeLists.txt
- test/unittest/xmlparser/XMLElementParserTests.cpp
Currently DNS name resolution is only attempted when parsing UDP locators from an XML profile. This PR extends that functionality to TCP locators by moving that logic to `IPLocator::setIPvX(Locator_t& locator, const std::string& ipvx)`.
> [21506] Allow domain names (DNS) when parsing TCP locators XML elements

- roadmap.md
This PR updates the roadmap with cool ideas for the future development of Fast DDS. …
> [21924] Roadmap update

- CMakeLists.txt
- package.xml
- Related PR: https://github.com/eProsima/Fast-DDS-docs/pull/971 …
> [21560] Bump to 2.14.4

- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
#5257 introduced a disposal guid mangling in secure clients. 
This PR fixes a Secure PDPClient null pointer check when when accessing the local participant proxy data.
> [22343] Bugfix: Add pointer sanity check before accessing `ParticipantProxyData`

- src/cpp/security/accesscontrol/Permissions.cpp
- src/cpp/security/authentication/PKIDH.cpp
- src/cpp/security/authentication/PKIIdentityHandle.h
- test/blackbox/common/BlackboxTestsSecurity.cpp
This PR changes the strings transmitted in `dds.cert.algo`, `dds.ca.algo`, and `dds.perm_ca.algo` to the ones
specified in [DDS-SEC-1.1](https://www.omg.org/spec/DDS-SECURITY/1.1/PDF).
In order to provide interoperability with legacy implementations, a new `transmit_algorithms_as_legacy` sub-property has been added to the builtin plugins configuration properties.
- Related documentation PR: eProsima/Fast-DDS-docs#974
> [22353] Use correct algorithm strings on PermissionsToken and IdentityToken

- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- test/blackbox/api/dds-pim/PubSubParticipant.hpp
- test/blackbox/common/BlackboxTestsTransportTCP.cpp
This PR fixes the behavior of Unique Network Flows with TCP transports. When activated, the logical port should be changed instead of modifying the physical port. This allows the communication of participants with TCP transports and the `fastdds.unique_network_flows` property activated, ensuring that the listening port specified is not modified.
> [22055] Fix unique network flows with TCP transports

- src/cpp/rtps/writer/StatefulWriter.cpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
This PR addresses a TSAN potential deadlock by lock inversion report between `StatefulWriter::matched_reader_remove()` and (async)`FlowController::run()`.
> [22339] Fix tsan potential deadlock between `StatefulWriter` and `FlowController`

- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
This PR avoids setting multicast metatraffic locators for PDPClients.
> [21433] Improve PDPClients initialization

- src/cpp/rtps/DataSharing/DataSharingListener.cpp
In the run() function of DataSharingListener, due to time jumps, the wait() function may occasionally experience spurious wakeups and throw a const boost::interprocess_exception.  After executing continue in the catch block, the code attempts to lock the mutex again while it's already locked, which leads to a std::system_error exception being thrown(e.what(): Resource deadlock avoided), ultimately causing the program to crash.
- _N/A_ New feature has been documented/Current behavior is …
> Fix double-locking issue in `DataSharingListener`

- src/cpp/rtps/persistence/sqlite3.h
This PR fixes https://github.com/eProsima/Fast-DDS/issues/5525
As this is a security issue: @mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x 2.6.x
- N/A Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- N/A New feature has been documented/Current …
> Update sqlite from 3.36.0 to 3.47.2

- src/cpp/rtps/security/SecurityManager.cpp
This PR improves the debugging process by adding a proper logging right before running `SecurityManager::cancel_init()` in [this catch block](https://github.com/eProsima/Fast-DDS/blob/2.6.9/src/cpp/rtps/security/SecurityManager.cpp#L386-L393)
More details in this ticket https://github.com/eProsima/Fast-DDS/issues/5531
Fixes #(issue) 
- _NA_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _NA_ Any new/modified methods have been properly documented using Doxygen. 
- _NA_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _NA_ New feature has been added to the `versions.md` file (if applicable).
- …
> Log any errors before cancel_init()

- src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
- test/blackbox/common/DDSBlackboxTestsStatistics.cpp
happened to find this miscalculation during https://github.com/ros2/rmw_fastrtps/issues/789.
i believe that comments are the correct values, so that default Duration_t adjusted accordingly in milliseconds.
@mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x
> [22537] Fix EDP reliability timings

- src/cpp/rtps/security/SecurityManager.cpp
- test/unittest/rtps/security/SecurityInitializationTests.cpp
This PR is a follow up of [#5530](https://github.com/eProsima/Fast-DDS/pull/5530/files) updating the macro log and adding regression tests.
After merging, manual backport the commits to the corresponding already created backport branches:
* [#5544 Log any errors before cancel_init() (backport #5530)](https://github.com/eProsima/Fast-DDS/pull/5544) has been created for branch `3.1.x`
* [#5545 Log any errors before cancel_init() (backport #5530)](https://github.com/eProsima/Fast-DDS/pull/5545) has been created for branch `3.0.x`
* [#5546 Log any errors before cancel_init() (backport #5530)](https://github.com/eProsima/Fast-DDS/pull/5546) has been created for branch `2.14.x`
* [#5547 Log any errors before cancel_init() (backport #5530)](https://github.com/eProsima/Fast-DDS/pull/5547) has …
> [22545] Add test for security initialization error

- .github/workflows/reusable-mac-ci.yml
- .github/workflows/reusable-sanitizers-ci.yml
- .github/workflows/reusable-ubuntu-ci.yml
This adds `submodules: true` to the checkout actions on all reusable workflows, making them consistent with the windows one, and thus enabling the IDL parser feature tests.
@Mergifyio backport 3.1.x 3.0.x 2.14.x 2.10.x 2.6.x …
> [22596] Update submodules when cloning Fast DDS on CI

- test/system/tools/fastdds/CMakeLists.txt
- test/system/tools/fastdds/tests.py
- tools/fastdds/shm/clean.py
- tools/fastdds/shm/parser.py
- versions.md
This PR enables to clean Datasharing files from the CLI. It adds a new argument (-f/--force) that will clean all datasharing segments found in the SHM directory. It does NOT check if these files are in use. It is user responsibility to ensure that the CLI is not called with the new argument at runtime, which would cause errors if new endpoints are initialized.
Issue related: https://github.com/eProsima/Fast-DDS/issues/5308
- https://github.com/eProsima/Fast-DDS-docs/pull/1012
> [21861] Enable Datasharing segments clean from CLI 

- .github/workflows/nightly-windows-master.yml
This PR splits Fast DDS tests, and runs some of them in parallel, to avoid exceeding the maximum allowed GitHub Workflow time.
Windows Nightly CI run:
https://github.com/eProsima/Fast-DDS/actions/runs/12687477053
- _N/A_ New feature has been added to the …
> [22277] Split Windows nightly tests using name filter regex

- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.hpp
- test/blackbox/common/BlackboxTestsNetworkConf.cpp
This is a follow-up of https://github.com/eProsima/Fast-DDS/pull/5461, attempting to solve https://github.com/ros2/ros2/issues/1617.
In that concrete scenario (where builtin + TCP transports are used in clients), the problem is that while the TCP (and UDP) transports are rightly able to create a receiver in the dedicated "unique flow" port, shared memory fails for that same port as the other process is already listening on it. However this was not being handled properly, so once matched, the publisher attempts to send data to the wrongfully announced shared memory locator.
Note that the underlying problem is that, when creating unique network flows, all transports are requested to create a receiver for a specific port all together. This is, the creation of unique flow receivers is only …
> [22519] Decouple transport receivers creation using unique network flows

- src/cpp/fastdds/domain/DomainParticipantFactory.cpp
- src/cpp/rtps/RTPSDomain.cpp
- test/blackbox/common/DDSBlackboxTestsBasic.cpp
During MacOs testing in other PR, it was detected that the `DOMAIN` category used in some logs `EPROSIMA_LOG_...(DOMAIN)` collides with a `#define DOMAIN` in `math.h` in the DeveoperTools under `MacOs`.
This PR solves the issue by adding a prefix depending on the domain.
> [22657] Fix log category name macro collision in `MacOS` 

- UPGRADING.md
This PR adds a warning in the migration guide to Fast DDS v3 about XTypes.
- https://github.com/eProsima/Fast-DDS-docs/pull/1021
> [22706] Warn about XTypes in Fast DDS v3

- src/cpp/rtps/writer/StatefulWriter.cpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
When the entire history is acked in volatile, given that the entries are deleted from the history, check_acked_status satisfies min_low_mark >= get_seq_num_min() because seq_num_min is unknown. This makes try_remove to fail, because it tries to remove changes but there were none. This causes prepare_change to not perform the changes, since the history was full and could not delete any changes.
- _N/A_ New feature has been documented/Current behavior is correctly described in the …
> [22658] Reliable volatile change dropped when all history acked 

- src/cpp/rtps/RTPSDomain.cpp
- test/blackbox/common/BlackboxTestsTransportCustom.cpp
- test/blackbox/common/DDSBlackboxTestsDSEasyMode.cpp
- test/unittest/dds/participant/CMakeLists.txt
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/profiles/test_xml_service_easy_mode.xml
Adding a Discovery Server as central discovery point might introduce small delays in discovery in resource limited CPUs. When using services in ROS2, this might cause some of the server's responses to fail due to timeout. However, the `max_blocking_time` can be automatically increased for services in Easy Mode.
- https://github.com/eProsima/Fast-DDS-docs/pull/1024
- _N/A_: If this is a critical bug fix, backports to the critical-only supported branches have been …
> [22721] Increase 'max_blocking_time' in Easy Mode

- src/cpp/fastdds/publisher/DataWriterHistory.cpp
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
on_unacknowledged_sample_removed callback is called when writer with keep all history is used, when the history was full but before max_blocking_time a sample was acknowledged, as is_acked was checked before the waiting time, and is not re-checked. This should not happen, as keep all should never drop an unacknowledged sample.
> [22648] Unacknowledged sample removed in KeepAll mode

- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
This PR modifies the info that gets fed into the `fastdds.physical_data` host element, the `machine_id` instead of the `host_id` as it was before.  
- _N/A_ New feature has been documented/Current behavior is correctly described in the …
> [22735] Make the machine id the physical data host info

- CMakeLists.txt
- include/fastdds/fastdds_dll.hpp
- include/fastdds/utils/TimedMutex.hpp
- src/cpp/fastdds/xtypes/serializers/json/dynamic_data_json.cpp
- src/cpp/utils/SystemInfo.cpp
- src/cpp/utils/TimedConditionVariable.cpp
- src/cpp/utils/shared_memory/RobustExclusiveLock.hpp
- src/cpp/utils/shared_memory/RobustSharedLock.hpp
- thirdparty/filewatch/FileWatch.hpp
Support compilation using MinGW. Version: MSYS2-MinGW-V14.2, x86_64-w64-mingw32.
1. The ‘COMPILE_TOOLS’ compilation option is turned off when compiling with MinGW because there are still some issues that have not been resolved here, but it does not affect the use of the main body of fastdds.
2. The import and export settings in thefastdds_dll.hpp file were changed to adapt to the symbol import and export rules of mingw. Tests found that these changes were effective.
3. The macro definition 'MINGW_COMPILER' has been added in cmakelists.txt to control some code to move towards new branches, which are used to resolve library dependency differences between compilers.
4. Some compile-time warnings that do not affect use have been canceled. 'ws2_32' and 'mswsock' libraries have been manually …
> [22704] Support compiler MSYS2-MinGW

- include/fastdds/dds/rpc/exceptions.hpp
- include/fastdds/dds/rpc/exceptions/RpcBrokenPipeException.hpp
- include/fastdds/dds/rpc/exceptions/RpcException.hpp
- include/fastdds/dds/rpc/exceptions/RpcFeedCancelledException.hpp
- include/fastdds/dds/rpc/exceptions/RpcInputFeedCancelledException.hpp
- include/fastdds/dds/rpc/exceptions/RpcOperationError.hpp
- include/fastdds/dds/rpc/exceptions/RpcTimeoutException.hpp
- include/fastdds/dds/rpc/interfaces.hpp
- include/fastdds/dds/rpc/interfaces/RpcClientReader.hpp
- include/fastdds/dds/rpc/interfaces/RpcClientWriter.hpp
- include/fastdds/dds/rpc/interfaces/RpcFuture.hpp
- include/fastdds/dds/rpc/interfaces/RpcServerReader.hpp
- include/fastdds/dds/rpc/interfaces/RpcServerWriter.hpp
- include/fastdds/dds/rpc/interfaces/RpcStatusCode.hpp
This adds the generic interfaces that the code generated by Fast DDS Gen for RPC interfaces will use.
> [22722] Support interfaces for RPC generated code

- src/cpp/rtps/transport/asio_helpers.hpp
This should fix #4684 by applying the last suggested changes
- __NO__: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
> [22756] Fix error handling logic in `try_setting_buffer_size`

- test/feature/idl_parser/CMakeLists.txt
This is a follow-up of #5567 that tries to clone the test IDLs submodule when the folder is not present.
- _N/A_ If this is a critical bug …
> [22651] Update dds-types-test submodule instead of fail build

- CMakeLists.txt
- package.xml
- versions.md
> [22514] Bump version to 3.1.2

- examples/cpp/dds/Configurability/ConfigurabilityPublisher.cpp
In the example: In `examples/cpp/ddds/Configurability/ConfigurabilityPublisher.cpp`, I found that the variable  `no_keys` has not been assigned a valid value and defaults to only 1, which will cause the following loop to only process once. According to the example code, multiple loops need to be executed based on the input  `user_configuration.no_keys`.
After modification, subscribers can receive additional data:
pub:
sub:
- [_N/A_] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ _N/A_] Any new/modified methods have been properly documented using Doxygen. 
- [_N/A_ ] Any new configuration API has an equivalent XML API (with the corresponding XSD …
> Fix for DDS Examples: Configurability

- src/cpp/CMakeLists.txt
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/builtin/discovery/participant/simple/PDPStatelessWriter.cpp
- src/cpp/rtps/builtin/discovery/participant/simple/PDPStatelessWriter.hpp
- src/cpp/rtps/builtin/discovery/participant/simple/SimplePDPEndpoints.hpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- src/cpp/rtps/writer/StatelessWriter.hpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
- test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/rtps/reader/CMakeLists.txt
- test/unittest/statistics/dds/CMakeLists.txt
This fixes a high CPU and network usage situation with PDP simple discovery when a new participant is created in a network where there is a high number of existing participants.
An ABI compatible backport would be manually done to 2.14.x, and we will backport to other 2.x supported branches from there.
> [22604] Filter interested readers on PDP writer

- test/unittest/dds/participant/ParticipantTests.cpp
Build of tests fails after #5593 has been merged.
- _N/A_ If this is a critical bug fix, backports to …
> [22627] Fix build after #5593

- include/fastdds/rtps/common/Types.hpp
- src/cpp/fastdds/core/policy/ParameterList.cpp
- src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
- src/cpp/rtps/messages/MessageReceiver.cpp
> Review `FASTDDS_TODO_BEFORE` for release 3.2.0

- tools/fds/CliDiscoveryManager.cpp
- tools/fds/CliDiscoveryManager.hpp
This PR flushes the Logs in the destructor of the CliDiscoveryManager to ensure that all logs are processed before ending the application. This fixes the flaky test in Windows `test_fast_discovery_no_XML` in which, in some cases, the application was finishing before processing the Error logs, resulting in a false failed test.
- _N/A_ Changes are API …
> [22729] Flush logs in CliDiscoveryManager

- include/fastdds/dds/rpc/RemoteExceptionCode_t.hpp
- include/fastdds/dds/rpc/exceptions.hpp
- include/fastdds/dds/rpc/exceptions/RemoteInvalidArgumentError.hpp
- include/fastdds/dds/rpc/exceptions/RemoteOutOfResourcesError.hpp
- include/fastdds/dds/rpc/exceptions/RemoteUnknownExceptionError.hpp
- include/fastdds/dds/rpc/exceptions/RemoteUnknownOperationError.hpp
- include/fastdds/dds/rpc/exceptions/RemoteUnsupportedError.hpp
- include/fastdds/dds/rpc/exceptions/RpcBrokenPipeException.hpp
- include/fastdds/dds/rpc/exceptions/RpcException.hpp
- include/fastdds/dds/rpc/exceptions/RpcFeedCancelledException.hpp
- include/fastdds/dds/rpc/exceptions/RpcOperationError.hpp
- include/fastdds/dds/rpc/exceptions/RpcRemoteException.hpp
- include/fastdds/dds/rpc/exceptions/RpcTimeoutException.hpp
- test/blackbox/common/DDSBlackboxTestsRPC.cpp
This PR adds definitions for the remote exceptions mentioned in DDS-RPC 1.0
> [22917] Add definitions for remote exceptions

- examples/cpp/discovery_server/CLIParser.hpp
- examples/cpp/discovery_server/ClientPublisherApp.cpp
- examples/cpp/discovery_server/ClientSubscriberApp.cpp
- examples/cpp/discovery_server/Helpers.hpp
- examples/cpp/discovery_server/ServerApp.cpp
Remove SHM option from discovery server example.
@Mergifyio backport 3.1.x
Fixes #5670 
> [22903] Remove SHM option from discovery server example

- tools/fds/server.cpp
This PR fixes Issue (https://github.com/eProsima/Fast-DDS/issues/5214) in which the SECURITY field does not show the real state of the Discovery Server initialized.
In 3.2.0 the CLI display was modified and 3.0.2 was the EOL, so no backports are needed.
- _N/A_ New feature has been added to the `versions.md` file (if …
> [21614] Fix Security tag in DS CLI

- .github/workflows/reusable-sanitizers-ci.yml
Sanitizer jobs have been silently failing to find `psutil` when executing tests requiring the cli discovery tool, specially the `asan_discovery_server_test`, which is required in all the tests. This PR adds it.
- **N/A** New …
> [22938] Add missing `psutil` python module in sanitizers ci

- include/fastdds/rtps/writer/StatelessWriter.h
- src/cpp/CMakeLists.txt
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/builtin/discovery/participant/simple/PDPStatelessWriter.cpp
- src/cpp/rtps/builtin/discovery/participant/simple/PDPStatelessWriter.hpp
- src/cpp/rtps/builtin/discovery/participant/simple/SimplePDPEndpoints.hpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/writer/StatelessWriter.cpp
- test/blackbox/api/dds-pim/PubSubParticipant.hpp
- test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
- test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
- test/unittest/dds/publisher/CMakeLists.txt
- test/unittest/statistics/dds/CMakeLists.txt
Manual backport ABI compatible from: #5604  
This fixes a high CPU and network usage situation with PDP simple discovery when a new participant is created in a network where there is a high number of existing participants.
@Mergifyio backport 2.10x
- _NA_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _NA_ New feature has been added to the `versions.md` file (if applicable).
- _NA_ New feature has been documented/Current behavior is correctly described in the documentation.
> [22710] Filter interested readers on PDP writer (backport #5604)

- include/fastdds/dds/domain/qos/ReplierQos.hpp
- include/fastdds/dds/domain/qos/RequesterQos.hpp
- src/cpp/fastdds/rpc/ServiceImpl.hpp
- test/blackbox/api/dds-pim/ReqRepHelloWorldReplier.cpp
- test/blackbox/api/dds-pim/ReqRepHelloWorldRequester.cpp
- test/blackbox/api/dds-pim/TCPReqRepHelloWorldReplier.cpp
- test/blackbox/api/dds-pim/TCPReqRepHelloWorldRequester.cpp
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/rpc/ServiceTests.cpp
This PR removes validations for Service, types and topic name fields of ReplierQos and RequesterQos structures.
This checks are unnecessary: all required information about Service or DDS entities can be obtained from the associated RPC Service instance. Unnecessary unit tests has been deleted.
ReplierQos and RequesterQos contructors have been also modified to set Reliability Qos as Reliable by default in both dds endpoints. …
> Remove unnecessary validations in ReplierQos and RequesterQos

- include/fastdds/dds/core/policy/QosPolicies.hpp
- include/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
- resources/xsd/fastdds_profiles.xsd
- src/cpp/fastdds/utils/QosConverters.cpp
- src/cpp/rtps/attributes/ServerAttributes.cpp
- src/cpp/rtps/attributes/ServerAttributes.hpp
- src/cpp/xmlparser/XMLParser.cpp
- src/cpp/xmlparser/XMLParserCommon.cpp
- src/cpp/xmlparser/XMLParserCommon.h
- test/blackbox/common/DDSBlackboxTestsDSEasyMode.cpp
- test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
- test/unittest/xmlparser/XMLParserTests.cpp
- test/unittest/xmlparser/XMLProfileParserTests.cpp
- test/unittest/xmlparser/test_xml_deprecated.xml
- test/unittest/xmlparser/test_xml_profile.xml
- test/unittest/xmlparser/test_xml_profile_env_var.xml
- test/unittest/xmlparser/test_xml_rooted_deprecated.xml
- test/unittest/xmlparser/test_xml_rooted_profile.xml
- versions.md
This PR adds a new member in RTPSParticipant attributes to store the IP of the Discovery Server when using ROS 2 Easy Mode.
- IP can be configured through C++ using WireProtocolConfigQos `easy_mode` setter.
- IP can be configured through XML using `easy_mode_ip` tag.
- Related documentation PR: https://github.com/eProsima/Fast-DDS-docs/pull/1043
> [22872] Configure ROS 2 Easy Mode via C++ and XML

- include/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
- resources/xsd/fastdds_profiles.xsd
- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.h
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/builtin/liveliness/WLP.cpp
- src/cpp/rtps/flowcontrol/FlowControllerImpl.hpp
- src/cpp/xmlparser/XMLElementParser.cpp
- test/blackbox/api/dds-pim/PubSubParticipant.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
- test/blackbox/common/BlackboxTestsPubSubFlowControllers.cpp
- test/dds/xtypes/BaseCases/Case11.json
- test/dds/xtypes/BaseCases/Case12.json
- test/dds/xtypes/TypeLookupServicePublisher.cpp
- test/dds/xtypes/TypeLookupServicePublisher.h
- test/dds/xtypes/TypeLookupServiceSubscriber.cpp
- test/dds/xtypes/TypeLookupServiceSubscriber.h
- test/dds/xtypes/TypeLookupService_main.cpp
- test/dds/xtypes/test_build.py
- test/mock/rtps/RTPSParticipantAttributes/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
- versions.md
This PR introduces the feature of setting a flow controller for the builtin rtps data writers of PDP and EDP.
This PR is on top of the refactor done in #5679 
The feature has been documented in this [PR](https://github.com/eProsima/Fast-DDS-docs/pull/1042)
Todo:
- Related documentation PR: eProsima/Fast-DDS-docs#1042
> [22849] Builtin flow controller

- test/blackbox/common/DDSBlackboxTestsListeners.cpp
As a consequence of #5540, the expectations in discovery phase of the test had to be adjusted.
Thanks @juanlofer-eprosima for giving the hint of that PR.
> [22937] Fix `several_writers_on_unack_sample_removed` flaky test

- test/dds-types-test/aliasesPubSubTypes.cxx
- test/dds-types-test/annotationsPubSubTypes.cxx
- test/dds-types-test/appendablePubSubTypes.cxx
- test/dds-types-test/arraysPubSubTypes.cxx
- test/dds-types-test/bitsetsPubSubTypes.cxx
- test/dds-types-test/constantsPubSubTypes.cxx
- test/dds-types-test/declarationsPubSubTypes.cxx
- test/dds-types-test/enumerationsPubSubTypes.cxx
- test/dds-types-test/externalPubSubTypes.cxx
- test/dds-types-test/finalPubSubTypes.cxx
- test/dds-types-test/helpers/basic_inner_typesPubSubTypes.cxx
- test/dds-types-test/inheritancePubSubTypes.cxx
- test/dds-types-test/keyPubSubTypes.cxx
- test/dds-types-test/mapsPubSubTypes.cxx
- test/dds-types-test/member_idPubSubTypes.cxx
- test/dds-types-test/mutablePubSubTypes.cxx
- test/dds-types-test/optionalPubSubTypes.cxx
- test/dds-types-test/primitivesPubSubTypes.cxx
- test/dds-types-test/sequencesPubSubTypes.cxx
- test/dds-types-test/stringsPubSubTypes.cxx
- test/dds-types-test/structuresPubSubTypes.cxx
- test/dds-types-test/unionsPubSubTypes.cxx
This PR updates types with Fast DDS Gen v4.0.4
> [22858] Update types with Fast DDS Gen v4.0.4

- include/fastdds/rtps/builtin/discovery/participant/PDP.h
- src/cpp/fastdds/builtin/typelookup/TypeLookupManager.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/builtin/liveliness/WLP.cpp
This PR is a manual backport of the refactor done in this [PR](https://github.com/eProsima/Fast-DDS/pull/5723)
- __NO__ New feature has been documented/Current behavior is correctly described in the documentation.
> [22964] Refactor builtin writers & readers creation (backport #5723)

- src/cpp/fastdds/builtin/type_lookup_service/TypeLookupManager.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/builtin/discovery/participant/PDP.h
- src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
- src/cpp/rtps/builtin/liveliness/WLP.cpp
This PR is a manual backport of the refactor done in this [PR](https://github.com/eProsima/Fast-DDS/pull/5680)
Manually backported to fast 2.14.x in this [PR](https://github.com/eProsima/Fast-DDS/pull/5724)
> [22964] Refactor builtin writers & readers creation

- include/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.hpp
- src/cpp/rtps/attributes/RTPSParticipantAttributes.cpp
- src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
This improves the segment size and port queue capacity configuration on LARGE_DATA and EASY_MODE. 
- _NA_: Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- **NO**: Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
> [22974] Improve SHM configuration on large data transports

- RELEASE_SUPPORT.md
- roadmap.md
- versions.md
This PR updates the `release_support` , `versions` and `roadmap` for `Fast DDS v3.2.0`
- **N/A** Applicable backports have …
> [22858] Prepare for Release v3.2.0

- CMakeLists.txt
- package.xml
This PR bumps project version to Fast DDS v3.2.0.
Merge after #5715  …
> [22858] Bump version to 3.2.0

- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
PR https://github.com/eProsima/Fast-DDS/pull/5687 added a log error trace to `DomainParticipantImpl::unregister_type` when attempting to unregister a type that is still being used. As a consequence, several log traces started to appear when deleting ROS 2 nodes, since `unregister_type` gets called by `rmw_fastrtps_shared_cpp::remove_topic_and_type` when destroying publications and subscriptions, regardless of whether the type is still being used by other publications/subscriptions. This can make tests checking for error traces to fail, which can be avoided by just reducing the log category.
- _N/A_ Any new/modified methods have …
> Reduce trace category when failing to unregister type

- include/fastdds/rtps/RTPSDomain.hpp
- src/cpp/fastdds/domain/DomainParticipantImpl.cpp
- src/cpp/rtps/RTPSDomain.cpp
- src/cpp/rtps/RTPSDomainImpl.hpp
- test/blackbox/api/dds-pim/PubSubParticipant.hpp
- test/blackbox/common/DDSBlackboxTestsDSEasyMode.cpp
- test/unittest/dds/participant/CMakeLists.txt
- test/unittest/dds/participant/ParticipantTests.cpp
- test/unittest/dds/profiles/test_xml_easy_mode_config.xml
This PR adds support for manually configuring ROS 2 Easy Mode using easy_mode_ip in RTPSParticipantAttributes. If the Easy Mode IP is manually configured, the value of the ROS2_EASY_MODE environment variable is ignored.
This PR depends on 
- https://github.com/eProsima/Fast-DDS/pull/5689
and must be merged after that one.
- Related documentation PR: https://github.com/eProsima/Fast-DDS-docs/pull/1045
- _N/A_ If this is a critical bug fix, backports to the critical-only …
> [22873] Setup ROS 2 Easy Mode at participant creation

- test/blackbox/common/BlackboxTestsDiscovery.cpp
- test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
This PR provides some fixes in a couple of tests [failing in the nighties](https://github.com/eProsima/Fast-DDS/actions/runs/14160373873/job/39664997070)
> [22995] Fix `MacOS` nightly flaky tests

- test/feature/idl_parser/CMakeLists.txt
- test/feature/idl_parser/IdlParserTests.cpp
- test/feature/idl_parser/no_path_included.idl
This PR modifies the IDL parsing tests to make sure the **include_paths** parameter is actually required in the corresponding tests.
@Mergifyio backport 3.1.x
- __NO__: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- __NO__: Any new/modified methods have been properly documented using Doxygen. 
- __NO__: Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- __NO__: New feature has been added to the `versions.md` file (if applicable).
- __NO__: New feature has been documented/Current behavior is correctly described in the documentation.
> IDL parsing tests included paths

- .github/workflows/reusable-mac-ci.yml
- .github/workflows/reusable-sanitizers-ci.yml
- .github/workflows/reusable-windows-ci.yml
This PR adds Fast CDR branch selection in sanitizers and Windows/Mac  jobs, similarly to how it is done in Ubuntu CI.
> [22955] Get correct Fast CDR related branch in CI

- utils/scripts/update_generated_code_from_idl.sh
Update excluded idl files from fastdds gen CI fixing the changes introduced in [this PR](https://github.com/eProsima/Fast-DDS/pull/5735).
- _NA_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
> Update excluded idl files from fastdds gen CI

- test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
PR #5738 did not correctly fixed the `monitor_service_extended_qos` test. Permutation of the elements must be taken in consideration when comparing the two vectors of incompatibilities. 
NOTE: This PR is not backported since its commit will be cherry-picked in #5739 and #5740 after being merged. …
> [23011] Fix `monitor_service_advanced_extended_incompatible_qos` test

- CMakeLists.txt
- package.xml
This PR bumps the project version to `3.2.1`
- **N/A** …
> [22959] Bump version to 3.2.1

- test/system/tools/fastdds/CMakeLists.txt
- test/system/tools/fastdds/test_discovery_parser.py
- tools/fastdds/discovery/fastdds_daemon/process_handler/process_handler.py
- tools/fastdds/discovery/parser.py
- tools/fds/CliDiscoveryEntrypoint.cpp
- tools/fds/CliDiscoveryManager.cpp
- tools/fds/CliDiscoveryManager.hpp
- tools/fds/CliDiscoveryParser.hpp
This PR modifies the behavior of certain commands of the CLI:
- `auto` and `start` are now equivalent.
- A `domain` argument and an `IP:domain` pair are now mandatory for `auto`, `start`, `add` and `set` commands.
- `set` command modifies the active remote connection, so ROS2_EASY_MODE needs to be updated after running it.
It also improves the CLI error notification
- Related tests: https://github.com/eProsima/Discovery-Server/pull/114
- Related documentation PR: …
> [23008] Update CLI commands for Easy Mode

- src/cpp/fastdds/rpc/ReplierImpl.cpp
- src/cpp/fastdds/rpc/RequesterImpl.cpp
- test/blackbox/api/dds-pim/ReqRepHelloWorldRequester.cpp
- test/blackbox/api/dds-pim/ReqRepHelloWorldRequester.hpp
- test/blackbox/common/BlackboxTestsPubSubBasic.cpp
This PR fixes the way `related_sample_identity` is handled in `ReplierImpl` and `RequesterImpl` for cases where it already has a value when the request is performed.
> [23048] Fix `related_sample_identity` handling in RPC entities

- CMakeLists.txt
Fix cmakelists problem about mingw-compile
There are some thing wrong with the CmakeLists.txt on MinGW-Compile. The "target_link_libraries" appears in the wrong place where the "fastdds" was not decleared as a lib. I'm sorry about this because I didn't notice I used cmake cache last time.
- __N/A__ New feature has been added to the `versions.md` file (if applicable).
- __N/A__ New feature has been documented/Current behavior is correctly described …
> Fix cmake problem about MinGW-Compile.

- CMakeLists.txt
- package.xml
This PR  bumps Fast DDS version to `v2.6.10`.
- **N/A**  Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A**  Any new/modified methods have been properly documented using Doxygen. 
- **N/A**  Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- **N/A**  Changes are API compatible. 
- …
> [21559] Bump version to 2.6.10

- .github/workflows/mac-ci.yml
- .github/workflows/nightly-mac-2.10.x.yml
- .github/workflows/nightly-mac-2.14.x.yml
- .github/workflows/nightly-mac-3.1.x.yml
- .github/workflows/reusable-mac-ci.yml
- .github/workflows/weekly-mac-2.6.x.yml
`Brew` now installs `asio 1.34` in which `io_service` was removed.
This PR forces mac ci to use asio from thirdparty. 
- **N/A** New feature has been documented/Current behavior is correctly …
> [23082] Force Asio Thirdparty in MacOS CI

- .github/workflows/nightly-mac-master.yml
PR #5769 missed updating master nightly, this PR fixes it. …
> [23082] Force Asio THIRDPARTY in Mac nightly master

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantsAckStatus.hpp
- src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoverySharedInfo.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
- test/blackbox/api/dds-pim/PubSubParticipant.hpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
This PR aims to improve efficiency of DS routines by reducing the number of messages sent (Data(p), Data(r) and Data(w)). It does so by:
- Avoiding re-sending the server's Data(p) to relevant participants every time its own Data(p) is added to the `pdp_queue` (when a new client is discovered). Now a direct message to the new discovered client is sent instead of adding the server's Data(p) to the queue, which led to multiple sends to all direct clients. 
- Sending just one Data(p) and Data(r/w) to direct clients by considering a three-state value (unmatched, sent & matched) for `DiscoveryParticipantsAckStatus` instead of just a boolean. In this way the Discovery DB avoids re-sending repeated data when processing topics.
Related PR: 
- https://github.com/eProsima/Discovery-Server/pull/115 …
> [22814] Improve DS routines

- RELEASE_SUPPORT.md
This PR updates the RELEASE_SUPPORT to v2.6.10.
- **N/A** …
> [21559] Update 2.6.x `RELEASE_SUPPORT` to 2.6.10

- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
- src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
- src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
- test/blackbox/common/BlackboxTestsDiscovery.cpp
This PR attempts to fix a couple of race conditions detected in scenarios where a large number of clients are present:
- PDP and EDP messages are stored in two queues which are not atomically swapped, which could create situations such as processing a data r/w of a data P already received but to be processed in the next server routine iteration.
- When a data UP is received (or manually inserted if a participant is dropped), it remains in the internal participants map but with its change updated. The item will be deleted only after the data UP is acked by all participants. If a new data P is received before this occurs, it will not be correctly processed. As a result, when the data UP is acked the item will be deleted from the participants map, and if a data r/w was to be processed …
> [23088] Solve Discovery Server race conditions

- test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
This PR adds the regression test pending for PR #5766.
The added test checks that `type_information` is always copied between `ProxyData` copies/assignments, even if the type information is not assigned.
Thanks to @juanlofer-eprosima for detecting and iterating with the test.
- **N/A** …
> [23142] Add regression test checking type_information is always copied in `ProxyDatas` copies

- src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterCompoundCondition.hpp
- src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterPredicate.hpp
- src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterValue.hpp
- src/cpp/rtps/reader/BaseReader.cpp
This PR addresses issues #5790 and #5792
> [23110] Address some compilation warnings with GCC latest

- include/fastdds/rtps/attributes/RTPSParticipantAttributes.hpp
- src/cpp/fastdds/core/policy/ParameterSerializer.hpp
- src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
- src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
- src/cpp/rtps/builtin/data/ParticipantProxyData.hpp
- src/cpp/rtps/builtin/data/ReaderProxyData.cpp
- src/cpp/rtps/builtin/data/ReaderProxyData.hpp
- src/cpp/rtps/builtin/data/WriterProxyData.cpp
- src/cpp/rtps/builtin/data/WriterProxyData.hpp
- src/cpp/rtps/builtin/discovery/participant/PDP.cpp
- src/cpp/rtps/messages/CDRMessage.cpp
- src/cpp/rtps/messages/CDRMessage.hpp
- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- src/cpp/rtps/participant/RTPSParticipantImpl.hpp
- src/cpp/statistics/rtps/messages/RTPSStatisticsMessages.hpp
- test/blackbox/common/DDSBlackboxTestsMonitorService.cpp
- test/blackbox/common/DDSBlackboxTestsParticipant.cpp
- test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.hpp
- test/unittest/rtps/builtin/BuiltinDataSerializationTests.cpp
- test/unittest/rtps/discovery/PDPTests.cpp
- versions.md
This PR adds the optional `WireProtocolConfigQos` serialization to Data(p)s based on the property `fastdds.serialize_optional_qos`. 
It also makes monitor service to always serialize the optional qos for Data(p), Data(w) and Data(r).
- NO Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- Related documentation PR: eProsima/Fast-DDS-docs#1068
> [23169] Add `WireProtocolConfigQos` to optionals serialization and make `Monitor Service` always serialize optionals

- src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- test/blackbox/CMakeLists.txt
- test/blackbox/common/RTPSBlackboxTests.cpp
- test/blackbox/common/RTPSBlackboxTestsSecurity.cpp
- test/blackbox/common/RTPSWithRegistrationReader.hpp
- test/blackbox/common/RTPSWithRegistrationWriter.hpp
This PR fixes a bug in which, when secure writers or readers failed to register, cleanup is not properly performed.
No need for backport since `local_actions_on_.._removed()` was introduced in `3.2.x`.
- NO Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- NO Applicable backports have been included in the description.
> [23042] Bugfix: Properly delete secure endpoints if registration fails

- PLATFORM_SUPPORT.md
- RELEASE_SUPPORT.md
This PR adds some references and links to Fast DDS Documentation in the RELEASE_SUPPORT and PLARFORM_SUPPORT sections.
- _N/A_ Applicable …
> [21427] Add references to documentation in mds

- examples/cpp/rpc/ClientApp.cpp
- examples/cpp/rpc/ServerApp.cpp
This PR modifies the RPC example participant creations to load default profile form environment as the rest of the examples.
- **N/A**  Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- **N/A**  Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- **N/A**  Changes are API compatible. 
- **N/A**  New feature has been documented/Current behavior is correctly described in the …
> [23230] Bugfix: Create RPC example participants with default profile

- include/fastdds/dds/publisher/DataWriter.hpp
- include/fastdds/dds/topic/IContentFilter.hpp
- include/fastdds/rtps/common/WriteParams.hpp
- src/cpp/fastdds/publisher/DataWriter.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.cpp
- src/cpp/fastdds/publisher/DataWriterImpl.hpp
- test/blackbox/api/dds-pim/PubSubWriter.hpp
- test/blackbox/common/DDSBlackboxTestsContentFilter.cpp
- test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
- test/unittest/statistics/dds/StatisticsDomainParticipantStatusQueryableTests/mock/fastdds/publisher/DataWriterImpl.hpp
- versions.md
This PR brings the `prefiltering` feature in the `DataWriter`. This operation lets user to filter out destination readers from a particular sample based on the `SerializedPayload` and/or `WriteParams` by implementing the `IContentFilter` interface. 
It also extends the `FilteredSampleInfo` and the `WriteParams` structures to include a new member `UserWriteData` meant to be extended by the user.
- NO Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- Related documentation PR: eProsima/Fast-DDS-docs#1077
- NO Applicable backports have been included in the description.
> [23264] Feature: `DataWriter` sample prefilter

- include/fastdds/statistics/dds/domain/DomainParticipant.hpp
This PR includes the `ParticipantBuiltinTopicData` header in Statistics `DomainParticipant`, fixing compilation errors in Fast DDS Statistics Backend  (type not declared).
Related to:
- https://github.com/eProsima/Fast-DDS-statistics-backend/pull/274
@Mergifyio backport 3.2.x
- …
> Add ParticipantBuiltinTopicData header in Statistics DomainParticipant

- src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterFactory.cpp
- test/blackbox/common/DDSBlackboxTestsContentFilter.cpp
- test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp
This fixes a bug that disallows the creation of built-in content filters when the type support is registered with a custom type name.
@Mergifyio backport 3.2.x 2.14.x
This PR is on top of the following one, and should be merged after it:
- https://github.com/eProsima/Fast-DDS/pull/5861
> [23265] Allow creation of built-in content filters with different type name

- .github/workflows/nightly-windows-master.yml
- .github/workflows/reusable-windows-ci.yml
- .github/workflows/windows-ci.yml
This PR splits the windows reusable workflow in building and testing. In turn, testing was divided in three jobs:
* `blackbox`: including `BlackboxTests|ParticipantTests|SecureDiscoverServer|SimpleCommunication|system.`
* `examples`: including `example_tests`
* `unittests-I`: including `DDSSQLFilterValue`. This test suite runs in parallel
* `unittests-II`: excluding the rest of the former ones
Mind that the `fastdds_build` step does not build with `-DFASTDDS_EXAMPLE_TESTS` , instead it build with with `DFASTDDS_COMPILE_EXAMPLES` since generating the docker image for testing takes too long and it has to be regenerated again in the `fastdds_test` proper job again. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the …
> [23253] Split windows workflow in different test suites

- .github/workflows/reusable-windows-ci.yml
- .github/workflows/windows-ci.yml
> [23253] Split windows workflow (3.2.x backport)

- .github/workflows/reusable-ubuntu-ci.yml
> Correct CI Python fallback branch in 3.2.x

- include/fastdds/utils/IPLocator.hpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/utils/IPLocator.cpp
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
- test/unittest/utils/LocatorTests.cpp
This PR adds a new method `copyAddress` which allows to copy the whole address of one locator to another. It uses this method to replace the `setIPv4` method of `TCPTransportInterace` introduced in https://github.com/eProsima/Fast-DDS/pull/5382 which caused undesired warnings. 
It also excludes `TCPv6` cases from this logic, leaving TCPv6 comms as before https://github.com/eProsima/Fast-DDS/pull/5382.
@Mergifyio backport 3.1.x 2.14.x
- _N/A_ New feature has been …
> [22469] Avoid calling setIPv4 in TCPTransportInterface

- include/fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp
- src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterFactory.cpp
- src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.cpp
- src/cpp/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
- test/mock/xtypes/TypeObjectRegistry/fastdds/xtypes/type_representation/TypeObjectRegistry.hpp
- test/unittest/dds/xtypes/type_representation/TypeObjectRegistryTests.cpp
- versions.md
This adds a new getter to `ITypeObjectRegistry` that allows getting a `CompleteTypeObject` from a registered `TypeIdentifierPair`.
This is the follow-up that we decided to do in https://github.com/eProsima/Fast-DDS/pull/5867#discussion_r2144500362, so the related code in `DDSFilterFactory` has also been updated.
It also exports two methods and adds unit tests for them.
> [23346] Add get_complete_type_object to `ITypeObjectRegistry`

- src/cpp/utils/thread_impl/thread_impl_win32.ipp
- src/cpp/utils/threading/threading_pthread.ipp
This PR apply all the changes requested by uncrustify in all the .ipp files on fasdds.
-  __N/A__ Any new/modified methods have been properly documented using Doxygen. 
-  __N/A__ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
-  __N/A__ New feature has been added to the `versions.md` file (if applicable).
-  __N/A__ New feature has been documented/Current behavior is correctly described in the documentation. 
-  __N/A__ Applicable backports have been included in the description.
> [23362] Apply changes of uncrustify to all IPP files

- src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlGrammar.hpp
- src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlModule.hpp
- src/cpp/fastdds/xtypes/dynamic_types/idl_parser/IdlParser.hpp
- test/feature/idl_parser/CMakeLists.txt
- test/feature/idl_parser/IdlParserTests.cpp
- test/feature/idl_parser/idl_extra_cases/extra_structures.idl
- test/feature/idl_parser/idl_extra_cases/extra_unions.idl
- versions.md
This PR adds support for scoped types in the IDL Parser. The main changes are as follows:
1. Introduced the `ModuleStack` class to manage hierarchies of nested modules.
2. Updated usage of `DynamicTypeBuilder::get_descriptor`. Since it returns a copy of the Type Descriptor instead of a `shared_ptr` to the original, the previous logic for updating the descriptor after builder instantiation was incorrect. This logic has been moved before the builder instantiation.
3. Internal builder maps now store types using fully qualified names, enabling support for types with the same name in different scopes.
4. Enabled previously commented API functions related to module tree management.
5. Fixed `resolve_scope` method.
6. Added new test cases not covered in `dds-types-test`:
- Nested modules  
- …
> [22973] Support modules in IDL Parser

- CMakeLists.txt
- src/cpp/rtps/transport/TCPAcceptor.cpp
- src/cpp/rtps/transport/TCPAcceptor.h
- src/cpp/rtps/transport/TCPAcceptorBasic.cpp
- src/cpp/rtps/transport/TCPAcceptorBasic.h
- src/cpp/rtps/transport/TCPAcceptorSecure.cpp
- src/cpp/rtps/transport/TCPAcceptorSecure.h
- src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
- src/cpp/rtps/transport/TCPChannelResourceBasic.h
- src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
- src/cpp/rtps/transport/TCPChannelResourceSecure.h
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- src/cpp/rtps/transport/TCPTransportInterface.h
- src/cpp/rtps/transport/TCPv4Transport.cpp
- src/cpp/rtps/transport/TCPv6Transport.cpp
- src/cpp/rtps/transport/UDPChannelResource.h
- src/cpp/rtps/transport/UDPTransportInterface.cpp
- src/cpp/rtps/transport/UDPTransportInterface.h
- src/cpp/rtps/transport/UDPv4Transport.cpp
- src/cpp/rtps/transport/UDPv6Transport.cpp
- src/cpp/rtps/transport/test_UDPv4Transport.cpp
- src/cpp/utils/IPLocator.cpp
- test/blackbox/common/UDPMessageSender.hpp
- test/unittest/transport/AsioHelpersTests.cpp
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
- versions.md
This PR bumps thirdparty asio module to 1.34.2 release and fixes deprecated API related to `io_service`, `address_v4`, `address_v6` and `tcp::resolver`, avoiding build failures. Fixes:
- https://github.com/eProsima/Fast-DDS/issues/5726
@Mergifyio backport 3.2.x 2.14.x
- _N/A_ If this is a critical bug fix, backports to the critical-only supported …
> [22970] Bump to asio 1.34.2

- include/fastdds/dds/rpc/RPCTypeObjectSupport.hpp
- src/cpp/CMakeLists.txt
- src/cpp/fastdds/rpc/RPCTypeObjectSupport.cpp
- src/cpp/fastdds/rpc/RPC_idl.md
- versions.md
This adds methods to register the TypeObject of RPC exceptions and related types.
It is necessary in order to generate TypeObject registration of generated RPC request and reply types in Fast DDS Gen.
> [23268] Add methods for TypeObject registration of RPC types

- examples/cpp/rpc/ServerApp.cpp
- examples/cpp/rpc/ServerApp.hpp
- examples/cpp/rpc/types/calculatorClient.cxx
- examples/cpp/rpc/types/calculatorPubSubTypes.cxx
- examples/cpp/rpc/types/calculatorServer.cxx
- examples/cpp/rpc/types/calculatorServer.hpp
- examples/cpp/rpc/types/calculatorServerImpl.hpp
- examples/cpp/rpc/types/calculatorTypeObjectSupport.cxx
- examples/cpp/rpc/types/calculatorTypeObjectSupport.hpp
This PR update the RPC example code according to new RPC API and update the types generated code.
> Update RPC example types and code

- include/fastdds/rtps/common/CacheChange.hpp
- include/fastdds/rtps/common/SerializedPayload.hpp
- src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
- src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp
- src/cpp/rtps/DataSharing/DataSharingPayloadPool.cpp
- src/cpp/rtps/DataSharing/ReaderPool.hpp
- src/cpp/rtps/DataSharing/WriterPool.hpp
- src/cpp/rtps/common/SerializedPayload.cpp
- src/cpp/rtps/history/TopicPayloadPool.cpp
- src/cpp/rtps/messages/MessageReceiver.cpp
- src/cpp/rtps/reader/reader_utils.cpp
- test/blackbox/common/BlackboxTestsKeys.cpp
- test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp
- test/unittest/rtps/common/CacheChangeTests.cpp
- versions.md
This PR adds a new field to `SerializedPayload_t` to identify payloads that only have the serialization of the key of the data type.
- **NO**: Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
> [23372] Process key-only payloads

- .github/workflows/reusable-windows-ci.yml
Use WINDOWS 2022 as platform for CI testing instead of the current 2019 not supported version
- _NA_ Any new/modified methods have been properly documented using Doxygen. 
- _NA_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _NA_ New feature has been added to the `versions.md` file (if applicable).
- _NA_ New feature has been documented/Current behavior is correctly described in the documentation. 
- _NA_ Applicable backports have been included in the description.
> Use WINDOWS 2022 in CI

- .github/workflows/reusable-windows-ci.yml
- PLATFORM_SUPPORT.md
This PR updates the Windows GitHub Action Runner toolsets, including v143 (VS2022).
@Mergifyio backport 3.2.x (do NOT backport to 2.14 as this update has been included in https://github.com/eProsima/Fast-DDS/pull/5909)
- _NA_ Any new/modified methods have been properly documented using Doxygen. 
- _NA_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _NA_ New feature has been added to the `versions.md` file (if applicable).
- Related documentation PR: https://github.com/eProsima/Fast-DDS-docs/pull/1092
> [23355] Add VS143 toolset

- RELEASE_SUPPORT.md
- roadmap.md
- versions.md
This PR updates the `ROADMAP, RELEASE_SUPPORT` and `versions.md` for the `3.3.0` Release
- **N/A** New feature has been documented/Current behavior is correctly …
> [23269] Prepare for release v3.3.0

- src/cpp/rtps/transport/asio_helpers.hpp
- src/cpp/rtps/transport/test_UDPv4Transport.cpp
- test/blackbox/common/DDSBlackboxTestsListeners.cpp
This task aims to fix:
- `test_UDPv4Transport` does not actually set the socket buffer size
- `try_setting_buffer_size` final attempt sets an upper limit for the buffer size that is not implemented in the main loop
This PR is a frontport of the proper changes from https://github.com/eProsima/Fast-DDS/pull/5921
@Mergifyio backport 3.2.x
> [23459] Fix/socket buffer size handling

- cmake/common/eprosima_libraries.cmake
When forcing third-party usage with `-DTHIRPARTY_xxx=FORCE`, the Fast DDS build succeeds but leaves traces from the progress of `git submodule update` commands in stderr.
This PR fixes that by leveraging the [`--quiet` option](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt---quiet), so only error messages are printed to stderr.
- _N/A_: New feature has been added to the `versions.md` file …
> [23531] Add `--quiet` to `git submodule` invocations

- .github/workflows/reusable-windows-ci.yml
> [23085] Remove deprecated windows 2019 from ci in favor of 2022

- utils/scripts/update_generated_code_from_idl.sh
Add to code generator script the IDL that was introduced in https://github.com/eProsima/Fast-DDS/pull/5691
@Mergifyio backport 3.3.x 3.2.x
- _N/a_ Commit messages follow the project guidelines. 
- _N/a_ The code follows the style guidelines of this project. 
- _N/a_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/a_ Any new/modified methods have been properly documented using Doxygen. 
- _N/a_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _N/a_ New feature has been added to the `versions.md` file (if applicable).
- _N/a_ New feature has been documented/Current behavior is correctly described in the documentation.
> Add missing IDL to code generator script

- src/cpp/utils/threading/threading_osx.ipp
This PR avoids setting thread affinity with values equal to zero in MAC. 
-_N/A_ Any new/modified methods have been properly documented using Doxygen. 
> [23545] Avoid setting thread affinity of 0 in mac

- resources/xsd/fastdds_profiles.xsd
This PR adds the field `tcp_negotiation_timeout` to `fastdds_profiles.xsd`, which was missing.
> [23592] Add 'tcp_negotiation_timeout' to .xsd

- examples/cpp/rpc/Application.hpp
- examples/cpp/rpc/ClientApp.hpp
- examples/cpp/rpc/ServerApp.hpp
- examples/cpp/rpc/main.cpp
Some errors have been reported when the RPC example application is stopped using multiple SIGINT signals, due to signal handler implicitly calls async-signal-unsafe functions. This PR solves the problem.
@Mergifyio backport 3.3.x 3.2.x
> [23569] Improve signal handling in RPC example

- include/fastdds/rtps/common/OriginalWriterInfo.hpp
- src/cpp/fastdds/core/policy/ParameterSerializer.hpp
- versions.md
This PR removes the empty ParameterList that was added to the original_writer_info serialization to be compliant with  RTPS v2.5 standard. 
* Empty ParameterList was removed from OriginalWriterInfo struct and serialization
* Parameter size changes from 32 to 28 as we remove the parameter list end sentinel and the lenght (2+2)
* Some comments indicating where the QoS should have been added are also removed
- [_N/A_] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [_N/A_] Any new/modified methods have been properly documented using Doxygen. 
- [_N/A_] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [_N/A_] New feature has been added to the …
> [23571] Removing empty qos_list from original writer as indicated in RTPS standard 2.5

- examples/cpp/discovery_server/CLIParser.hpp
This PR fixes the `--topic` argument in the Discovery Server example to work as expected.
@Mergifyio backport 3.3.x 3.2.x
> Fix topic argument in Discovery Server example

- test/dds/xtypes/update_header_and_create_cases.py
- utils/scripts/update_generated_code_from_idl.sh
This PR updates dds-types-test submodule which now isolates types with const/typedefs inside a struct.
> [23709] Isolate types with const/typedefs inside a struct

- .github/workflows/reusable-ubuntu-ci.yml
Since Fast DDS python requires CMake version 3.24, we need to update the CI here accordingly.
> [23747] Update CMake version in fastdds_python_test

- test/blackbox/common/DDSBlackboxTestsListeners.cpp
This makes the blackbox test build when restricting to C++11.
> [23638] Avoid using auto in lambda arguments

- src/cpp/fastdds/core/condition/StatusConditionImpl.cpp
- src/cpp/fastdds/core/condition/StatusConditionImpl.hpp
- src/cpp/rtps/transport/TCPAcceptorSecure.cpp
- src/cpp/rtps/transport/TCPChannelResource.cpp
- src/cpp/rtps/transport/TCPChannelResource.h
- src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
- src/cpp/rtps/transport/TCPChannelResourceBasic.h
- src/cpp/rtps/transport/TCPChannelResourceSecure.cpp
- src/cpp/rtps/transport/TCPTransportInterface.cpp
- test/blackbox/common/BlackboxTestsTransportTCP.cpp
- test/unittest/transport/TCPv4Tests.cpp
- test/unittest/transport/TCPv6Tests.cpp
This PR attempts to solve the deadlock produced when a read operation never completes (e.g. peer blocks before ending a transmission), and the TCP channel resource is disconnected (normally on closure while cleaning the associated transport).
Summing up, the solution consists in shutting down the socket before acquiring the culprit read mutex, so that any ongoing write/read operations are aborted even if not completed.
In addition, some other changes in this PR target general thread safety and attempt to improve overall resilience:
- New "disconnecting" state to protect from concurrent connect/disconnects.
- Assert that socket options are only configured before connection is established.
- _N/a_ Any new/modified methods have been properly documented …
> [23655] Solve TCP disconnect while incomplete read deadlock
