eProsima/Fast-DDS

test/profiling/CMakeLists.txt

On my OS X machine I get these errors with master (aba41d8):
```
[  1%] Built target SequenceNumberTests
[  5%] Built target ThroughputControllerTests
[  8%] Built target UDPv6Tests
[ 11%] Built target TimedEventTests
[ 14%] Built target UDPv4Tests
[ 21%] Built target test_UDPv4Tests
[ 64%] Built target fastrtps
Scanning dependencies of target RTPSPubSubProfiling
[ 65%] Building CXX object test/profiling/CMakeFiles/RTPSCommsProfiling.dir/RTPSAsSocketReader.cpp.o
[ 66%] Building CXX object test/profiling/CMakeFiles/RTPSPubSubProfiling.dir/RTPSPubSubProfiling.cpp.o
[ 67%] Linking CXX executable ROS2FEATURETEST
[ 68%] Built target ROS2FEATURETEST
[ 69%] Linking CXX executable BlackboxTests
[ 73%] Built target BlackboxTests
[ 77%] Built target UserDefinedTransportExample
[ 78%] Building CXX …
```

use Boost_INCLUDE_DIRS to make boost headers available

---

include/fastrtps/TopicDataType.h
include/fastrtps/attributes/PublisherAttributes.h
include/fastrtps/publisher/PublisherHistory.h
include/fastrtps/rtps/attributes/HistoryAttributes.h
include/fastrtps/rtps/common/CacheChange.h
include/fastrtps/rtps/common/SerializedPayload.h
include/fastrtps/rtps/history/CacheChangePool.h
include/fastrtps/rtps/history/History.h
src/cpp/participant/ParticipantImpl.cpp
src/cpp/publisher/PublisherHistory.cpp
src/cpp/publisher/PublisherImpl.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
src/cpp/rtps/builtin/liveliness/WLP.cpp
src/cpp/rtps/history/CacheChangePool.cpp
src/cpp/rtps/history/History.cpp
src/cpp/rtps/history/ReaderHistory.cpp
src/cpp/rtps/history/WriterHistory.cpp
src/cpp/rtps/reader/FragmentedChangePitStop.cpp
src/cpp/subscriber/SubscriberHistory.cpp
src/cpp/subscriber/SubscriberImpl.cpp
test/blackbox/RTPSAsSocketReader.hpp
test/blackbox/RTPSAsSocketWriter.hpp
test/blackbox/RTPSWithRegistrationReader.hpp
test/blackbox/RTPSWithRegistrationWriter.hpp
test/profiling/RTPSAsSocketReader.cpp
test/profiling/RTPSAsSocketWriter.cpp

See https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/issues/36#issuecomment-229835500 for more background.
This pull request does a few things:
- changes the semantic of the "max payload size" like variables that are used throughout the code
- now it's the initial size of the payload, which may or may not be increased later on demand
- changes the semantic of the "type size" variable in the TopicDataType class
- it can now be 0 to indicate the type has no bounded size
- added an option to the parameter attributes (and the history attributes) called `allowPayloadResize`
- this option defaults to `false`
- when `true` it will allow the serialized payloads to be resized (increased) to accommodate larger messages than the initial payload size allowed
- removes a restriction that registered …

Large message pub sub

---

include/fastrtps/participant/Participant.h
include/fastrtps/rtps/participant/RTPSParticipant.h
src/cpp/participant/Participant.cpp
src/cpp/participant/ParticipantImpl.cpp
src/cpp/participant/ParticipantImpl.h
src/cpp/rtps/participant/RTPSParticipant.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h

I expose a new function for getting the names of existing participants inside a network. Useful for introspection.
https://github.com/Karsten1987/fastrtps_introspection/blob/master/src/fastrtps_info.cpp
I only expose the names for now, but it can be edited towards exposing (all) participantinfo.

(dev) expose getParticipantNames function in API

---

examples/C++/DeadlineQoSExample/CMakeLists.txt

As reported in ros2/ros2#260, `-lpthread` is needed when linking one of the examples on some ARM/Linux machines (e.g., rpi3).

Add pthread, needed on some ARM platforms

---

src/cpp/qos/WriterQos.cpp

The documentation specifies [here](https://github.com/eProsima/Fast-RTPS/blob/3cf7996c9cea21a4bdc4ee5f8dc6763069cd85f2/include/fastrtps/qos/QosPolicies.h#L60) that the default durability QoS for publishers/writers should be `TRANSIENT_LOCAL_DURABILITY_QOS` however it is not currently being set. As a result publishers currently have the default durability settings of `VOLATILE_DURABILITY_QOS` due to https://github.com/eProsima/Fast-RTPS/blob/3cf7996c9cea21a4bdc4ee5f8dc6763069cd85f2/include/fastrtps/qos/QosPolicies.h#L74

Set default durability for WriterQos to match documentation

---

include/fastrtps/transport/UDPv4Transport.h
include/fastrtps/transport/UDPv4TransportDescriptor.h
include/fastrtps/transport/UDPv6Transport.h
include/fastrtps/transport/UDPv6TransportDescriptor.h
src/cpp/transport/UDPv4Transport.cpp
src/cpp/transport/UDPv6Transport.cpp

I extended the `UDPv*TransportDescriptor.h` of a field called `TTL` in order to specify the time to live for each packet.
By default it's set to 1, but totally up to discussing whether or not this should be done like that or not.
Addresses the conflicts in https://github.com/eProsima/Fast-RTPS/issues/64

introduce user transport option to set time to live

---

fastrtpsgen/src/com/eprosima/fastrtps/fastrtpsgen.java

On macOS (only tested with Sierra), following error occurred using fastrptsgen:
```
Exception in thread "main" java.lang.NullPointerException
at com.eprosima.fastrtps.fastrtpsgen.globalInit(fastrtpsgen.java:444)
at com.eprosima.fastrtps.fastrtpsgen.execute(fastrtpsgen.java:263)
at com.eprosima.fastrtps.fastrtpsgen.main(fastrtpsgen.java:1089)
```
This pull request fixes the null pointer exception and adds macOS support for fastrptsgen.
Sorry for closing and reopening the PR, but this one is much clearer with just a few lines of changed code. I hope it helps!

Adding macOS support for fastrtpsgen

---

CMakeLists.txt

`find_eprosima_thirdparty()` was missing the second argument.

Fix finding Android's ifaddrs.{c,h}

---

src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.cpp

When building with "-DSECURITY=ON" the following CLang warnings appear: http://ci.ros2.org/job/ci_osx/1932/warnings10Result/
This PR fixes the `-Wmissing-braces` warnings

fix_missing_braces_warning

---

include/fastrtps/log/Log.h

This PR fixes a warning issued by clang regarding undefined behavior in the macro expansion of COMPOSITE_LOG_NO_INFO:
```sh
In file included from /builds/openrov/fastrtps-build/Fast-RTPS/src/cpp/rtps/builtin/liveliness/WLP.cpp:34:
In file included from /builds/openrov/fastrtps-build/Fast-RTPS/include/fastrtps/rtps/builtin/data/WriterProxyData.h:24:
In file included from /builds/openrov/fastrtps-build/Fast-RTPS/include/fastrtps/rtps/builtin/data/../../../attributes/TopicAttributes.h:27:
/builds/openrov/fastrtps-build/Fast-RTPS/include/fastrtps/rtps/builtin/data/../../../attributes/../log/Log.h:188:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if COMPOSITE_LOG_NO_INFO 
^
/builds/openrov/fastrtps-build/Fast-RTPS/include/fastrtps/rtps/builtin/ …
```

Fixed clang undefined behavior warning

---

cmake/modules/FindAsio.cmake
cmake/modules/FindTinyXML2.cmake

Find modules override the CMake package registry by default.  On Windows, we have no standard file system hierarchy to check for installed libraries and using the CMake package registry [[1]] is the easiest way to advertise installed dependencies to dependents.
These changes will force CMake to look in the package registry by passing the CONFIG directive to find_package, if no package is found, the existing find module logic will be used.
This change should not affect builds on systems where the existing logic is successful unless those systems also include entries in the CMake package registry and those entries are invalid.
[1]: https://cmake.org/cmake/help/v3.5/manual/cmake-packages.7.html#id20

Check the CMake registry for pre-configured Asio and TinyXML2 packages.

---

src/cpp/fastrtps.rc

If I try to build this project on Windows without MFC installed, then I get this error:
```
C:\dev\ros2\src\eProsima\Fast-RTPS\src\cpp\fastrtps.rc(33): fatal error RC1015: cannot open include file 'afxres.h'. [C:\dev\ros2\build\fastrtps\src\cpp\fastrtps_static.vcxproj]
```
According to this SO post, this can safely be replaced with #include "windows.h":
http://stackoverflow.com/questions/3566018/cannot-open-include-file-afxres-h-in-vc2010-express
This does fix the problem on my machine.

use windows.h rather than afxres.h

---

test/communication/CMakeLists.txt
test/communication/liveliness_assertion.py
test/communication/simple_communication.py

The first commits adds assertions to ensure that the environment variables are set. Currently that is not the case due to a regression introduced in a recent change (https://github.com/eProsima/Fast-RTPS/commit/e2cdc510c6580b84f7e212dbf02604fbc400260f#diff-fbc16c4a3512de5bc6e9f097923f254aR47).
With that change the test fails with an `AssertionError` and doesn't try to invoke a subprocess with `None` which results in infinite hangs on our buidllarm (e.g. http://ci.ros2.org/job/ci_windows/2384/).
---
The second commit simply moves the important environment variables above the `PATH` which makes the tests pass cleanly.
---
But the logic to append the `PATH` should still be revised since it doesn't work correctly. It seems that the same pattern exists in other CMake files too.

Fix test env

---

include/fastrtps/transport/UDPv4Transport.h
include/fastrtps/transport/UDPv6Transport.h

Fixes the remaining compiler warnings from our macOS CI job:
- before:
- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2252)](http://ci.ros2.org/job/ci_osx/2252/)
- warnings: http://ci.ros2.org/job/ci_osx/2252/warnings10Result/new/file.1218138969/
- after:
- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2255)](http://ci.ros2.org/job/ci_osx/2255/)
You could also disable this warning, but I think this fix is pretty straightforward.
Thanks for working on the 1.5.0 release, I'm excited to use it!

use override consistently

---

cmake/modules/FindTinyXML2.cmake

This is the most minimal patch I could make that fixes https://github.com/eProsima/Fast-RTPS/issues/113.
A more complete fix might be to convert that custom FindTinyXML2 file to always produce an imported target and update the rest of the project's CMake code to not depend on things like `TINYXML2_INCLUDE_DIR` and `TINYXML2_SOURCE_DIR`.

work around to support TinyXML2 5.0.0

---

include/fastrtps/xmlparser/XMLProfileParser.h
src/cpp/Domain.cpp
src/cpp/xmlparser/XMLProfileParser.cpp
test/unittest/xmlparser/XMLProfileParserTests.cpp

Was using the XML endpoint the other day, and ran across "fillSubscribertAttributes" and "fillPublishertAttributes" methods which looked to be typos (extra T in each).
Feel free to ignore if intentional.

Fix typo in XML API

---

src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
src/cpp/rtps/reader/CompoundReaderListener.cpp

This is one approach for fixing a crash that can occur when [the onNewCacheChageAdded of the custom ReaderListener in ROS 2](https://github.com/ros2/rmw_fastrtps/blob/af079efdc2636c79ca6f83de37a508b4b0cbdbe9/rmw_fastrtps_cpp/src/types/writer_info.hpp#L45) (used for listening to info about the graph e.g. topic names and types) is being called _after_ we have [removed the listener](https://github.com/ros2/rmw_fastrtps/blob/af079efdc2636c79ca6f83de37a508b4b0cbdbe9/rmw_fastrtps_cpp/src/rmw_node.cpp#L267..L271). I am not too familiar with the fastrpts codebase so there might be a different approach that is more appropriate.
An example of when this is likely to happen is an executable that creates a publisher but is in the process of shutting down before it finally gets advertised. I'm having a …

Prevent onNewCacheChangeAdded from being called after ReaderLister has been destroyed

---

include/fastrtps/rtps/common/SequenceNumber.h

When compiling Fast-RTPS with gcc 7.1 and -O2, a warning is issued:
Fast-RTPS/include/fastrtps/rtps/messages/../common/SequenceNumber.h:190:5: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]
if(seq1.high > seq2.high)
I believe that this is actually a bogus warning, but it
has real consequences; the outcome of this warning is
that gcc optimizes away the check.  We can workaround
this problem by assigning the result of the base + 255
to an intermediate variable, then comparing against this
intermediate variable instead.  This gets rid of the warning.
This should fix #126 
Signed-off-by: Chris Lalancette <clalancette@gmail.com>

Quiet signed overflow warning on gcc 7.1

---

include/fastrtps/rtps/exceptions/Exception.h

Modern gcc/glibc prints this warning when building
Fast-RTPS:
Fast-RTPS/src/cpp/rtps/exceptions/Exception.cpp:58:13: warning: In the GNU C Library, "minor" is defined
by <sys/sysmacros.h>. For historical compatibility, it is
currently defined by <sys/types.h> as well, but we plan to
remove this soon. To use "minor", include <sys/sysmacros.h>
directly. If you did not intend to use a system-defined macro
"minor", you should undefine it after including <sys/types.h>.
void Exception::minor(const int32_t &minor)
I follwed the latter advice and undefined the minor
macro, which quiets down the warning.
This should fix #127 
Signed-off-by: Chris Lalancette <clalancette@gmail.com>

Quiet a warning about "minor" being doubly defined.

---

include/fastrtps/subscriber/Subscriber.h
src/cpp/subscriber/Subscriber.cpp
src/cpp/subscriber/SubscriberImpl.cpp
src/cpp/subscriber/SubscriberImpl.h

This PR is trying to address the problem described in ros2/rclcpp#280. The problem is best described in [this](https://github.com/ros2/rclcpp/issues/280#issuecomment-347333437) comment but I will summarize it here and give a example what the exact problem is.
Consider a use case where a publisher publishes 100 messages and the subscriber has a history depth of 10. Additionally assume that the subscriber hasn't started processing any incoming message.
In ROS 2 we use a [SubscriberListener](https://github.com/ros2/rmw_fastrtps/blob/de0d6d343eb4798f94890b007ae31596a448ddc4/rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_subscriber_info.hpp#L36) to get notified about new data. `onNewDataMessage` is being triggered for every incoming message (so 100 times in this example). The custom listener …

expose getUnreadCount from history in subscriber

---

src/cpp/rtps/resources/TimedEventImpl.cpp

The internal representation of temporary of type
`std::string` is freed by its destructor in `c_str()`
Signed-off-by: Ethan Gao <ethan.gao@linux.intel.com>

Fix issue of wrapper object use after free

---

src/cpp/rtps/security/SecurityManager.cpp

Currenly `SecurityManager.cpp:201` and `SecurityManager.cpp:215` cause the warning `declaration of 'exception' hides previous local declaration` on windows. This moves outer declaration  lower to eliminate them.

Fix warning on windows about hidden local declaration

---

include/fastrtps/rtps/common/CacheChange.h
src/cpp/rtps/messages/RTPSMessageGroup.cpp
src/cpp/rtps/writer/ReaderProxy.cpp

Given a gap list of sequence numbers 8, 9, 10, 15, 16, 19, 20, 23, 27, 28
The gapList.base field for the gap message was not set correctly causing the first gap sequence to be skipped by teh receiver.
This change correctly set the gapList.base to be +1 from the gapStart value. in our example: gapStart==8, gapList.base==11 gapList.set[15, 16, 19, 20, 23, 27, 28]
Previously, the gap values would be set incorrectly as such: gapStart==8, gapList.base==8 gapList.set[9, 10, 15, 16, 19, 20, 23, 27, 28] causing the gap seqnum 8 to be missed by the receiver.
Issue: #182

Incorrect gapList.base field in GAP submessage

---

src/cpp/security/OpenSSLInit.cpp

This function has been deprecated causing warning with recent versions of OpenSSL
https://www.openssl.org/docs/man1.1.0/crypto/ERR_remove_state.html

fix deprecated openssl call

---

CMakeLists.txt

Fast-RTPS now requires fastcdr to compile the security plugins https://github.com/eProsima/Fast-RTPS/blob/8d89897fc9ec3f7e49057bfb2fbaa0d10b7abcf4/src/cpp/security/cryptography/AESGCMGMAC_Transform.h#L24
So it needs to be find_package with the "REQUIRED" option if `SECURITY` is passed to cmake.
Without this patch Fast-RTPS cmake prints `-- fastcdr library not found...` and then fails at compilation time:
```
In file included from /tmp/fastrtps_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/security/../../security/cryptography/AESGCMGMAC.h:27:0,
from /tmp/fastrtps_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/security/SecurityPluginFactory.cpp:22:
/tmp/fastrtps_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/security/../../security/cryptography/AESGCMGMAC_Transform.h:24:25: fatal error: fastcdr/Cdr.h: No such …
```

fastcdr is now required if security is on

---

include/fastrtps/rtps/builtin/discovery/endpoint/EDPSimple.h

Last commit introduced new warnings:
https://ci.ros2.org/job/ci_osx/3559/warnings11Result/
With this patch: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3561)](http://ci.ros2.org/job/ci_osx/3561/)

add missing override to fix clang warnings

---

CMakeLists.txt

This PR adds a `INSTALL_EXAMPLES` option that, if set to OFF, doesn't install the examples' code to the install prefix.

add INSTALL_EXAMPLES option defaulting to ON

---

examples/C++/SecureHelloWorldExample/HelloWorld.cxx
include/fastrtps/rtps/writer/RTPSWriter.h
include/fastrtps/rtps/writer/StatefulWriter.h
include/fastrtps/rtps/writer/StatelessWriter.h
include/fastrtps/rtps/writer/WriterListener.h
src/cpp/publisher/PublisherImpl.cpp
src/cpp/publisher/PublisherImpl.h
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
test/blackbox/BlackboxTests.cpp
test/blackbox/PubSubWriter.hpp
test/blackbox/RTPSAsSocketWriter.hpp

This PR correctly handles the removal of changes from the publisher history when the durability QOS is set to VOLATILE.
This should fix ros2/ros2#539

Remove samples on volatile publishers

---

src/cpp/security/accesscontrol/CommonParser.cpp

This fixes #245 making domains->id_range->max optional on the governance file

Making 'max' tag optional

---

include/fastrtps/publisher/Publisher.h
include/fastrtps/rtps/Endpoint.h
include/fastrtps/subscriber/Subscriber.h
src/cpp/publisher/Publisher.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPStatic.cpp
src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/rtps/messages/RTPSMessageGroup.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp
src/cpp/rtps/writer/RTPSWriter.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
src/cpp/subscriber/Subscriber.cpp
src/cpp/subscriber/SubscriberImpl.h

Modified getAttributes behaviour for Publisher, Subscriber and EndPoint. Now it wiil return a reference instead of a copy. Also some style changes were done.

Modified getAttributes behaviour.

---

include/fastrtps/attributes/ParticipantAttributes.h
include/fastrtps/attributes/PublisherAttributes.h
include/fastrtps/attributes/SubscriberAttributes.h
include/fastrtps/attributes/TopicAttributes.h
include/fastrtps/qos/ParameterTypes.h
include/fastrtps/qos/QosPolicies.h
include/fastrtps/qos/ReaderQos.h
include/fastrtps/qos/WriterQos.h
include/fastrtps/rtps/attributes/PropertyPolicy.h
include/fastrtps/rtps/attributes/RTPSParticipantAttributes.h
include/fastrtps/rtps/attributes/ReaderAttributes.h
include/fastrtps/rtps/attributes/WriterAttributes.h
include/fastrtps/rtps/common/BinaryProperty.h
include/fastrtps/rtps/common/PortParameters.h
include/fastrtps/rtps/common/Property.h
include/fastrtps/rtps/flowcontrol/ThroughputControllerDescriptor.h
src/cpp/xmlparser/XMLParser.cpp

Micro XRCE-DDS support `data_writer` and `data_reader` entities which correspond with `publisher` and `subscriber` in FastRTPS, so in order to support XML representations for the XRCE entities the XMLParser has been modified.

XMLParser for datawriter and datareader

---

src/cpp/transport/TCPChannelResource.cpp
src/cpp/transport/TCPTransportInterface.cpp

Add an extra check to avoid a compilation error with versions of asio previous of 1.12.0 calling a release method of the sockets.

Fix errors with versions of asio previous to 1.12.0

---

src/cpp/transport/TCPTransportInterface.cpp

This PR fixes an error introduced by #285. When the socket is closed, the receive call returns 0 (i.e. 0 bytes were read) and the thread keeps looping because the channel has not been closed.

Fix deadlock on TCP

---

include/fastrtps/rtps/common/Types.h
include/fastrtps/transport/tcp/RTCPMessageManager.h
include/fastrtps/transport/tcp/test_RTCPMessageManager.h
include/fastrtps/utils/System.h
src/cpp/CMakeLists.txt
src/cpp/rtps/RTPSDomain.cpp
src/cpp/transport/TCPTransportInterface.cpp
src/cpp/transport/tcp/RTCPMessageManager.cpp
src/cpp/transport/tcp/test_RTCPMessageManager.cpp
src/cpp/utils/System.cpp
test/unittest/transport/CMakeLists.txt

- Fixed issue when server rejects a bind connection request due to protocol version causing the client to retry forever.
- Fixed protocol version used.
- Improved Fast-RTPS current protocol version management.
- Added possibility to expand both client and server behaviour on errors in RTCP while negotiation.
- Added "virtual physical port" on tcp clients instead of always report 0. This fixes several clients on the same machine issue.
- Added System.h file to utils folder as helper when retrieving system information.

TCP bugfixing

---

include/fastrtps/rtps/network/ReceiverResource.h
src/cpp/rtps/network/ReceiverResource.cpp

Avoid creation of a new CDRMessage_t at OnDataReceived's stack.

Reuse CDRMessage_t at OnDataReceived method

---

include/fastrtps/rtps/reader/StatefulReader.h
src/cpp/rtps/reader/StatefulReader.cpp

Joining duplicated code on new method and fixing post on reader history semaphore when processing heartbeats

Fixing semaphore on stateful reader.

---

src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.cpp

Fixing block counter initialization detected when running ROS2 tests.

Fix ROS2 test_security failures.

---

include/fastrtps/rtps/writer/StatefulWriter.h
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/rtps/writer/StatefulWriter.cpp

This should fix #177 by sending [n, n-1] heartbeats when writer history is empty.

Sending [n, n-1] heartbeat when history is empty

---

include/fastrtps/transport/TCPTransportInterface.h
src/cpp/transport/TCPTransportInterface.cpp
test/unittest/transport/TCPv4Tests.cpp
test/unittest/transport/TCPv6Tests.cpp

- TCP internal buffers are now configured by maxMessageSize instead of socket sizes.
- If TCP detects a message bigger than its buffer capacity, now drops all the expected bytes that don't fit instead of trying to read a TCP header again.
- TCPv4 tests updated to use default message, and sockets buffer sizes.

Fixed TCP max msg size and TCPv4 Tests.

---

include/fastrtps/rtps/builtin/liveliness/WLP.h
src/cpp/rtps/builtin/liveliness/WLP.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/rtps/security/SecurityManager.cpp
test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h

Avoid error messages when matching builtin WLP endpoints.
```
2018-11-14 09:51:32.262 [SECURITY Error] Cannot find remote reader 9a.dd.34.40.e7.49.e8.ca.d9.2c.27.d|ff.2.0.c7 -> Function encode_writer_submessage
2018-11-14 09:51:32.262 [RTPS_WRITER Error] Cannot encrypt HEARTBEAT submessage for writer a0.4f.5e.5c.56.16.b2.6f.34.7c.29.1|ff.2.0.c2 -> Function add_heartbeat
```

Fixing liveliness protection

---

include/fastrtps/rtps/messages/RTPS_messages.h

This pull request move submessage IDs from defines to enum in order to avoid collision with the submessage IDs used in Micro XRCE-DDS Agent, and other potential collisions.

Moved submessage IDs from defines to enum.

---

src/cpp/rtps/builtin/data/ReaderProxyData.cpp
src/cpp/rtps/builtin/data/WriterProxyData.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/rtps/security/SecurityManager.cpp
src/cpp/rtps/security/SecurityManager.h
test/unittest/rtps/security/SecurityInitializationTests.cpp
test/unittest/rtps/security/SecurityTests.hpp

This fixes an issue in which a non-secure participant was sending security information on discovery when building with security.

Fixing security_info

---

include/fastrtps/xmlparser/XMLParserCommon.h
include/fastrtps/xmlparser/XMLProfileManager.h
src/cpp/xmlparser/XMLParserCommon.cpp
src/cpp/xmlparser/XMLProfileManager.cpp

[#Refs 3937](https://eprosima.easyredmine.com/issues/3937) Create the management to check if exists an environment variable to load the DEFAULT_FASTRTPS_PROFILES.xml. The name of the environment variable is **FASTRTPS_DEFAULT_PROFILES_FILE**

Create Environment Variable for default XML file

---

include/fastrtps/utils/eClock.h
src/cpp/CMakeLists.txt

[Refs #3794](https://eprosima.easyredmine.com/issues/3794) Fix some issues trying to compile Fast-RTPS on Windows without Visual Studio

Refs #3794. Fix compilation issues using Codeblocks for Windows [3810]

---

cmake/modules/FindTinyXML2.cmake
cmake/packaging/Config.cmake.in

This change accounts for an added namespace in `tinyxml2`  > v7.0.0 (introduced in leethomason/tinyxml2#645)

Account for potential target namespace for tinyxml2 [4107]

---

test/blackbox/CMakeLists.txt

This fixes an issue introduced on c9f0616cc435c6c91e5c3f7698415404bab58247 provoking the individual blackbox tests not being correctly added

Hotfix: Bringing back individual blackbox tests. [4112]

---

src/cpp/rtps/RTPSDomain.cpp

Although section 9.3.1.5 of the [RTPS standard](https://www.omg.org/spec/DDSI-RTPS/About-DDSI-RTPS/) does not impose a restriction on the guidPrefix value other than the first two bytes, it seems that other implementations may produce error output when certain part of the guidPrefix is all 0's (see ros2/ros2#621).
So in order to keep them happy, this hotfix ensures that participantId starts from 1 instead of 0.

Made participant id start on 1 instead of 0.

---

src/cpp/transport/UDPv4Transport.cpp
src/cpp/transport/UDPv6Transport.cpp

This should fix #343 and fix #347 by forcing SO_REUSEPORT to be used alongside SO_REUSEADDRESS on all the platforms supporting it (including QNX)

Forcing SO_REUSEPORT when defined. [4109]

---

src/cpp/rtps/messages/MessageReceiver.cpp

This partially solves #142 by processing key-only data submessages of up to 16 bytes as if they were empty submessages with a key-hash parameter on the inline qos.
This will improve the interoperability with OpenSplice implementations reported in #142

Partially processing key-only data submessages [4321]

---

test/CMakeLists.txt
test/profiling/CMakeLists.txt
test/profiling/allocations/AllocTestCommon.cpp
test/profiling/allocations/AllocTestCommon.h
test/profiling/allocations/AllocTestPublisher.cpp
test/profiling/allocations/AllocTestPublisher.h
test/profiling/allocations/AllocTestSubscriber.cpp
test/profiling/allocations/AllocTestSubscriber.h
test/profiling/allocations/AllocTest_main.cpp
test/profiling/allocations/CMakeLists.txt
test/profiling/allocations/README.md
test/profiling/allocations/README.txt
test/profiling/allocations/allocation_plot.py
test/profiling/allocations/test.sh

Created a new profiling test to analyze the number of allocations made on each different steps of the execution(Discovery, Communication, Undiscovery).
The main goal is to have the CI system to keep a historical record of the amount of (de)allocations happening after the creation of all entities. This would allow triggering an alarm when an increment is detected.

New Allocation test [4259]

---

include/fastrtps/rtps/common/CacheChange.h
include/fastrtps/rtps/common/FragmentNumber.h
include/fastrtps/rtps/common/SequenceNumber.h
include/fastrtps/rtps/messages/CDRMessage.h
include/fastrtps/rtps/messages/CDRMessage.hpp
include/fastrtps/rtps/reader/RTPSReader.h
include/fastrtps/rtps/writer/ReaderProxy.h
include/fastrtps/utils/fixed_size_bitmap.hpp
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/rtps/messages/RTPSMessageGroup.cpp
src/cpp/rtps/messages/submessages/AckNackMsg.hpp
src/cpp/rtps/messages/submessages/GapMsg.hpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/timedevent/HeartbeatResponseDelay.cpp
src/cpp/rtps/reader/timedevent/InitialAckNack.cpp
src/cpp/rtps/writer/RTPSWriterCollector.h
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
test/unittest/rtps/common/SequenceNumberTests.cpp
test/unittest/rtps/flowcontrol/ThroughputControllerTests.cpp
test/unittest/utils/BitmapRangeTests.cpp
test/unittest/utils/CMakeLists.txt

A `template<class T, class Diff = DiffFunction<T>, size_t NBITS=256> BitmapRange` class holding a bitmap on a fixed size array of uint32_t.
Type T is required to behave like an unsigned integer type, and shall at least have addition with `uint32_t` and `>=` operators.
The `BitmapRange` class will have the following fields:
```
// Alias to improve readability.
using bitmap_type = std::array<uint32_t, (NBITS + 31) / 32>;
T base;              // Holds first item in the range.
bitmap_type bitmap;  // Holds bitmap.
size_t num_bits;     // Number of significant bits set in the bitmap.
```
Operations implemented:
- Default constructor
- Constructor from base: `explicit BitmapRange(const T& base)`
- Getter and setter for base
- Add an item: `bool add(const T& item)`
- Bitmap getter for …

Fixed size bitmaps [4320]

---

include/fastrtps/qos/ParameterList.h
include/fastrtps/qos/ParameterTypes.h
include/fastrtps/qos/QosPolicies.h
include/fastrtps/rtps/builtin/data/ParticipantProxyData.h
include/fastrtps/rtps/builtin/data/ReaderProxyData.h
include/fastrtps/rtps/builtin/data/WriterProxyData.h
include/fastrtps/rtps/messages/MessageReceiver.h
include/fastrtps/rtps/messages/RTPSMessageCreator.h
src/cpp/qos/ParameterList.cpp
src/cpp/qos/ParameterTypes.cpp
src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
src/cpp/rtps/builtin/data/ReaderProxyData.cpp
src/cpp/rtps/builtin/data/WriterProxyData.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
src/cpp/rtps/builtin/liveliness/WLPListener.cpp
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/rtps/messages/RTPSMessageGroup.cpp
src/cpp/rtps/messages/submessages/DataMsg.hpp
test/mock/rtps/MessageReceiver/fastrtps/rtps/messages/MessageReceiver.h
test/mock/rtps/ParticipantProxyData/fastrtps/rtps/builtin/data/ParticipantProxyData.h
test/mock/rtps/QosPolicies/fastrtps/qos/QosPolicies.h
test/unittest/security/authentication/AuthenticationPluginTests.hpp
test/unittest/transport/test_UDPv4Tests.cpp

Reducing allocations by removing ParameterList_t (a vector of Parameter_t*) and also avoiding dynamic creation of Parameter_t classes

Remove ParameterList_t [4370]

---

src/cpp/transport/UDPTransportInterface.cpp
src/cpp/utils/IPFinder.cpp

This solves an issue when sending multicast on Windows machines with more than one interface where some of them are disconnected. In that case, the default multicast route may not be the first one.
This PR may fix ros2/rmw_fastrtps#246

Fixed error sending multicast on Windows in some scenarios. [4542]

---

src/cpp/rtps/reader/StatefulReader.cpp

This error occurs when the user unlock the reader mutex in the callback
onNewCacheChangeAdded().

Refs #4543. Fixed error notifying changes. [4567]

---

include/fastrtps/utils/collections/ResourceLimitedContainerConfig.hpp
include/fastrtps/utils/collections/ResourceLimitedVector.hpp
test/unittest/utils/CMakeLists.txt
test/unittest/utils/ResourceLimitedVectorTests.cpp

Adding a wrapper of `std::vector` with control over the initial and maximum number of allocated elements, and linear capacity grow with configurable increment.
This is an initial step towards allocation behavior configuration.
This PR introduces two new data types
A struct with `initial`, `maximum` and `increment` fields of type `size_t`, defining the allocation behaviour of a collection. 
Setting the same value on `initial` and `maximum` will define a preallocated fixed-size policy.
A wrapper of `std::vector` with the following functionality:
* Constructor receiving a `ResourceLimitedContainerConfig`
* Adding elements: `T* push_back()` (copy and move) and `T* emplace_back(...)`
* Removing elements: `bool remove(const T&)` and `bool remove_if(predicate)`
* Traversing the collection: …

Resource limited vector [4421]

---

examples/C++/Benchmark/BenchmarkPublisher.cpp
examples/C++/Benchmark/BenchmarkSubscriber.cpp

This PR should fix the configuration error that prevent the Benchmark run with TCP enabled.
Fixes #395

Refs #4642 Too old configuration method [#395]

---

include/fastrtps/rtps/attributes/ReaderAttributes.h
include/fastrtps/rtps/attributes/WriterAttributes.h
include/fastrtps/rtps/common/CacheChange.h
include/fastrtps/rtps/reader/timedevent/HeartbeatResponseDelay.h
include/fastrtps/rtps/reader/timedevent/InitialAckNack.h
include/fastrtps/rtps/writer/ReaderProxy.h
include/fastrtps/rtps/writer/StatefulWriter.h
include/fastrtps/rtps/writer/timedevent/NackResponseDelay.h
include/fastrtps/rtps/writer/timedevent/PeriodicHeartbeat.h
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/builtin/discovery/participant/PDPSimpleListener.cpp
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/timedevent/HeartbeatResponseDelay.cpp
src/cpp/rtps/reader/timedevent/InitialAckNack.cpp
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
src/cpp/rtps/writer/timedevent/NackResponseDelay.cpp
src/cpp/rtps/writer/timedevent/PeriodicHeartbeat.cpp
test/blackbox/BlackboxTests.cpp

Improved the time needed for discovering remote participants and theirs entities.
- Reconfigured the attributes of EDP endpoints.
- Using shrinked locators in several places not used yet.

Improved discovery time [4661]

---

include/fastrtps/rtps/attributes/ReaderAttributes.h
include/fastrtps/rtps/attributes/WriterAttributes.h
include/fastrtps/rtps/messages/MessageReceiver.h
include/fastrtps/rtps/messages/RTPS_messages.h
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/transport/test_TCPv4Transport.cpp
src/cpp/transport/test_UDPv4Transport.cpp

This should fix #375 by correctly handling the cases where the `octetsToNextHeader ` field on the submessage header is zero

Correctly handling octetsToNextHeader value zero [4665]

---

test/profiling/allocations/test_xml_profiles.xml

This PR modifies the profiles XML file of the allocation test with a preallocated fixed size of one matching subscriber on each publisher.

Using matchedSubscribersAllocation on allocations test [4704]

---

src/cpp/rtps/writer/ReaderProxy.cpp

Guillaume (Clearpath) noticed the following warning:
"Requested Changes: 1068 [...]  not found (low mark: 1067)"
This warning is no longer relevant after changes to ReaderProxy PR #411 and this PR removes it.

Removing warning message in ReaderProxy [4720]

---

src/cpp/subscriber/SubscriberHistory.cpp

This makes the behavior on the allocation resource limits consistent on the subscriber and publisher history.
For any entity with a `KEEP_LAST` history policy, its history depth is taken into consideration for the resource limits.

Made Subscriber history resource limits dependent on history depth [4782]

---

cmake/modules/CheckForPthreads.c
cmake/modules/FindThreads.cmake

In order to resolve linking issues that appear when running Fast-RTPS with ASan [1] due to the asan library providing the symbol whose absense is being used as a test for the need to link pthreads.
This CMake pull request [2] addresses the issue by using a different function as the heuristic and has been accepted upstream as part of the 3.14-rc2 release.
This commit drops the version of FindThreads.cmake from that release into the local CMake modules directory where it should take precedence over the system-provided one.
This file can be removed when the cmake_minimum_required version is 3.14 or newer as the system version should be sufficient.
It would be nice to modify this module to print a warning when it is no longer needed. I tried to find a means to check the minimum version rather …

Vendor FindThreads.cmake from CMake 3.14-rc2. [4790]

---

src/cpp/CMakeLists.txt

This problem manifests when I am building ROS2 build on Windows. When building `rmw_fastrtps_shared_cpp.dll`, it doesn't need to link with `tinyxml2.lib` but which is included in linker command. It's because `fastrtps` exposes the linked libs, and it is eventually propagating to `fastrtps-targets.cmake`. After making those linked libs for `fastrtps` to be `PRIVATE`, I am able to pass and build the rest of packages.
Here is the code snippet from `fastrtps-targets.cmake`:
```
set_target_properties(fastrtps PROPERTIES
INTERFACE_COMPILE_DEFINITIONS "FASTRTPS_DYN_LINK"
INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
INTERFACE_LINK_LIBRARIES "fastcdr;tinyxml2;\$<\$<BOOL:OFF>:OpenSSL::SSL\$<SEMICOLON>OpenSSL::Crypto>;\$<\$<BOOL:1>:iphlpapi\$<SEMICOLON>Shlwapi>"
)
```
Here is the log …

[Windows] No need to expose linked libs when the target is a shared lib

---

src/cpp/transport/TCPTransportInterface.cpp
test/realtime/mutex_testing_tool/CMakeLists.txt

Refs #5142 Fixing WAN [5144]

---

include/fastrtps/rtps/attributes/RTPSParticipantAttributes.h
include/fastrtps/rtps/common/PortParameters.h
src/cpp/rtps/network/NetworkFactory.cpp
test/unittest/rtps/common/CMakeLists.txt
test/unittest/rtps/common/PortParametersTests.cpp
test/unittest/rtps/network/CMakeLists.txt

It checks the calculated port so it is able to detect other potential overflows when calculating the port number.
Fixes [#261](https://github.com/ros2/rmw_fastrtps/issues/261).

Maximum Domain ID limitation [5151]

---

src/cpp/transport/UDPTransportInterface.cpp
src/cpp/transport/UDPv4Transport.cpp
src/cpp/transport/UDPv6Transport.cpp
test/unittest/transport/UDPv4Tests.cpp

This PR allows filters-out non-local addresses from the whitelist.

Filter non-local addresses on whitelist [5041]

---

src/cpp/rtps/RTPSDomain.cpp

Because of the code [here](https://github.com/eProsima/Fast-RTPS/blob/f6ebf154a97089136c4906de11f535969708f2a0/src/cpp/rtps/RTPSDomain.cpp#L113), the RTPS Domain GUID can potentially be not unique between multiple participant hosted on different computer. This happens because the host ID component is initialized with eProsima magic number (0x010f) and the last two digit of the IPv4 address of the first interface enumerated by `getifaddrs`.
On some systems where there are several network interfaces, this scheme is not sufficient for generating a mostly unique `hostId` to be used for the RTPS Domain and collision can happen in the case where the first interface enumerated is an interface used by the system in isolation with the actual network. In addition, the `appId` (the process ID …

RTPS Domain hostid part of the GUID match first interface IP [4970]

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h

This PR enables automatic calculation of the port when receiving a value of 0 on the endpoint custom locators.

Well-known port calculation on endpoint locators [5040]

---

fastrtpsgen/build.gradle

The old method was holding a file open during the entire execution, causing races and the build to sometimes succeed or fail

Fix Resource Generation on windows in fastrtspgen

---

include/fastrtps/rtps/writer/StatefulWriter.h
src/cpp/rtps/writer/StatefulWriter.cpp

Not calling `onWriterChangeReceivedByAll` twice for the same sequence number.

Fix for StatefulWriter.check_acked_status [5270]

---

test/performance/ThroughputPublisher.cpp
test/performance/ThroughputPublisher.h
test/performance/ThroughputSubscriber.cpp
test/performance/ThroughputSubscriber.h
test/performance/ThroughputTypes.h
test/performance/main_LatencyTest.cpp
test/performance/main_ThroughputTest.cpp
test/performance/main_VideoTest.cpp

Fixes #463
Allows multiple static data sizes between tests.
Help messages fixed.

Refs #5020 Static data now allows different sizes between tests. [5029]

---

src/cpp/rtps/reader/StatelessReader.cpp

StatelessReader: losing fragments causes not removing old changes from FragmentPitStop.

StatelessReader: losing fragments causes not removing old changes from FragmentPitStop. [5360]

---

doc/README.html.in
roadmap.md

Final documentation updates

---

src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp

On PR #488 we changed the constructor of Duration_t to receive nanoseconds instead of fraction. 
Some constants on EDPSimple.cpp were left unchanged.

Fix EDP default timings

---

src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
test/blackbox/BlackboxTestsVolatile.cpp

Found an issue (ros2/ros2#703) with late joining volatile readers on volatile writers. 
**Reproduction steps:**
1. Reliable volatile asynchronous publisher is created, and a call to write is performed.
2. A matching reliable volatile subscriber is created.
3. A new call to write is performed.
**Expected result:**
A call to the subscription listener is made shortly after the write call.
**Observed result:**
The call to the listener is made after a time that matches the heartbeat period.
**Explanation:**
1. The subscriber may receive the initial heartbeat before discovering the publisher (thus ignoring it)
2. The publisher has not received the pre-emptive ACKNACK, so it hasn't repeated the initial heartbeat.
3. When the second write call is made, the publisher sends a DATA message for …

Fix for volatile reliable [5425]

---

include/fastrtps/subscriber/SubscriberHistory.h

Fixing a data race on SubscriberHistory that was found by ROS2 sanitizer jobs.

Fixing data race on SubscriberHistory [5455]

---

cmake/dev/java_support.cmake
fastrtpsgen/build.gradle

update source and target for fastrtpsgen to java 7
fix issue with long PATH env variables during build 
fixes issue #550

Fix fastrtpsgen.jar build on Windows [5667]

---

fastrtpsgen/build.gradle
fastrtpsgen/src/main/java/com/eprosima/fastrtps/fastrtpsgen.java

If we use a java version higher than java 6, problems will be like #555 and #550 . 
The method for TemplateManager tmanager has been changed, so it needed be updated.
Now if you use openjdk-1.8 and gradle 5.4.1, everything is fine.
*Remember to fix file /thirdparty/idl/idl.gradle*
`compileJava { sourceCompatibility = 1.8 targetCompatibility = 1.8 }`
Fixes #550

Use java 1.8 or greater for fastrtpsgen.jar generation [5666]

---

src/cpp/xmlparser/XMLParser.cpp

Leave it as it was until we take a decision on how to show the error to the user

Bugfix/default xml profile load log error [5596]

---

src/cpp/rtps/writer/StatefulWriter.cpp

On destroying the stateful writer, StatefulWriter::perform_nack_supression sometimes gets called after deleting mp_periodicHB, which causes a Segmentation fault

Stateful writer destruction race condition [5746]

---

include/fastrtps/transport/UDPChannelResource.h
include/fastrtps/transport/UDPTransportInterface.h
src/cpp/transport/UDPChannelResource.cpp
src/cpp/transport/UDPTransportInterface.cpp
test/unittest/transport/UDPv4Tests.cpp

This probably fixes issue #235, as it is related with a hang during participant destruction.

Fix closing multicast UDP channel with whitelist [5732]

---

test/unittest/rtps/writer/LivelinessManagerTests.cpp

To test this, run cmake with:
* -DGTEST_INDIVIDUAL=OFF
* -DGTEST_INDIVIDUAL=ON
Then run `LivelinessManagerTests`. All tests should pass with both options.

Fixing liveliness manager tests that would fail with GTEST_INDIVIDUAL=OFF

---

src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp

participant_data->m_availableBuiltinEndpoints |= DISC_BUILTIN_ENDPOINT_PUBLICATION_ANNOUNCER | DISC_BUILTIN_ENDPOINT_SUBSCRIPTION_DETECTOR | DISC_BUILTIN_ENDPOINT_PUBLICATION_DETECTOR | DISC_BUILTIN_ENDPOINT_SUBSCRIPTION_ANNOUNCER;
Tests pass in both fast and Discovery server

Refs: #5916 Bugfix/pdp server edp attributes 

---

include/fastrtps/log/Log.h
src/cpp/log/Log.cpp

Now Log::Run() calls mResources.mCv.notify_all() instead of notify_one() to encompass a multiple thread-flush scenario.
All tests pass on Windows.
```
void Log::Flush()
{
std::unique_lock<std::mutex> guard(mResources.mCvMutex);
if (!mResources.mLogging && !mResources.mLoggingThread)
{
// already killed
return;
}
// Wait till the background thread signals and...
mResources.mCv.wait(guard, [&]()
{   // ... either the logging has ended or the queue is flushed
return !mResources.mLogging || mResources.mLogs.BothEmpty();
});
}
```

Added a Flush method to the log in order to prevent logged info leakage [#5880]

---

include/fastrtps/rtps/common/LocatorSelectorEntry.hpp

Nightly Linux builds are complaining of a possibly uninitialized usage.

Fixing valgrind error on Nightly builds [6108]

---

src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/WriterProxy.cpp
src/cpp/rtps/reader/WriterProxy.h
test/mock/rtps/StatefulReader/fastrtps/rtps/reader/StatefulReader.h
test/unittest/rtps/reader/WriterProxyTests.cpp

Reducing physical memory consumption by keeping only the sequence number of the received changes on WriterProxy

Only storing received changes in WriterProxy [6159]

---

src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/WriterProxy.cpp

This will fix #671 by removing the offending assertion and explaining why it is safe to do so.

Fix assertion on WriterProxy [6225]

---

include/fastrtps/utils/collections/ResourceLimitedVector.hpp

This PR fixed an assertion failure. The application fails with next log:
```
[INFO] [showimage]: Subscribing to topic 'image'
showimage: /home/ricardo/workspace/eprosima/ros2/eloquent/src/eProsima/Fast-RTPS/include/fastrtps/rtps/writer/../common/../../utils/collections/ResourceLimitedVector.hpp:341: bool eprosima::fastrtps::ResourceLimitedVector<_Ty, _KeepOrderEnabler, _LimitsConfig, _Alloc, _Collection>::ensure_capacity() [with _Ty = eprosima::fastrtps::rtps::Locator_t; _KeepOrderEnabler = std::integral_constant<bool, false>; _LimitsConfig = eprosima::fastrtps::ResourceLimitedContainerConfig; _Alloc = std::allocator<eprosima::fastrtps::rtps::Locator_t>; _Collection = std::vector<eprosima::fastrtps::rtps::Locator_t>]: La declaración `configuration_.increment > 0' no se cumple.
```

Added copy constructor to ResourceLimitedVector. [6247]

---

include/fastrtps/rtps/common/SequenceNumber.h

All modern compilers supported by Fast-RTPS define `uint64_t` so preventing the definition of the method `to64long` doesn't have a sense now. Additionally, it caused compilation errors when building on 32 bits platforms that support `uint64_t`, a type that is used in a lot of parts of Fast-RTPS code without checkings.
Fixes #686

Refs #6270 Remove deprecated guards. [6273]

---

test/blackbox/BlackboxTestsDeadlineQos.cpp
test/blackbox/BlackboxTestsLifespanQoS.cpp
test/blackbox/BlackboxTestsLivelinessQos.cpp
test/blackbox/PubSubReader.hpp

Changed times in deadline and lifespan tests:
* Deadline tests fail occasionally when the deadline timer does not expire "on time". To fix this I have decreased the `deadline_period` respect to the `writer_sleep` (i.e. the time we sleep between sending samples) in `*ShortDeadline` tests. To ensure that `*LongDeadline` tests fail less often, I have increased the `deadline_period` respect to the `writer_sleep`.
* LongLifespan test can fail if the reader has not received the sample by the time we execute the expectations. I have fixed this by making the reader block until all samples have been received
* Also increases `lease_duration` in a liveliness test that failed yesterday (05/09/2019) on master

Updates to deadline and lifespan tests [6290]

---

test/communication/Publisher.cpp
test/communication/Subscriber.cpp
test/performance/LatencyTestPublisher.cpp
test/performance/LatencyTestSubscriber.cpp
test/performance/ThroughputPublisher.cpp
test/performance/ThroughputSubscriber.cpp
test/performance/VideoTestPublisher.cpp
test/performance/VideoTestSubscriber.cpp
test/performance/main_LatencyTest.cpp
test/performance/main_VideoTest.cpp
test/profiling/MemoryTestPublisher.cpp
test/profiling/MemoryTestSubscriber.cpp
test/profiling/allocations/AllocTestPublisher.cpp
test/profiling/allocations/AllocTestSubscriber.cpp
test/profiling/allocations/AllocTest_main.cpp
test/profiling/main_MemoryTest.cpp

This PR removes the usage of `eClock` from our tests. To test the changes:
* Do a grep and ensure that there are no occurrences of `eClock`
* Check that performance tests are built successfully (cmake flags are `-DEPROSIMA_BUILD_TESTS=ON`, `-DPERFORMANCE_TESTS=ON` and `-DPROFILING_TESTS=ON`)

Removing eClock from tests [6321]

---

test/blackbox/BlackboxTestsPersistence.cpp
test/blackbox/RTPSWithRegistrationWriter.hpp

Async test may remove from history (default depth 1) samples before the writer's thread retrieve them.
Added an option to allow chaging history_depth value, and modified AsyncRTPSAsReliableWithPersistence test to use it.

Refs #6280 Added history_depth option. [6295]

---

src/cpp/rtps/security/SecurityManager.cpp
src/cpp/rtps/security/SecurityManager.h

Fixes a deadlock when:
One thread:
- Locks `StatelessReader.mp_mutex` at `StatelessReader.cpp:259` (processDataMsg)
- Tries to lock `SecurityManager.temp_data_lock_` at `SecurityManager.cpp:1773` (match_builtin_key_exchange_endpoints)
Another thread has received a new Data(p) message
- Locks `SecurityManager.temp_data_lock_` at SecurityManager.cpp:1737` (match_builtin_endpoints)
- Tries to lock `StatelessReader.mp_mutex` at `StatelessReader.cpp:61` (matched_writer_add)

Refs #6246 Separate temp_data and mutexes for volatile and stateless. [6319]

---

test/performance/LatencyTestPublisher.cpp

Calculates the roundtrip time (i.e. divides by 2) as soon as the time is pushed into the vector, as other calculations were missing this factor.

More fixes to latency tests [6344]

---

include/fastrtps/subscriber/Subscriber.h

This PR restores two methods that were removed from the Subscriber API on v1.9.0, adding them as inline aliases.

Restoring subscriber API [6350]

---

test/performance/ThroughputPublisher.cpp
test/performance/ThroughputSubscriber.cpp

In case KEEP_LAST, set the history depth to at least the burst demand
In case KEEP_ALL, the the topic resource limit max samples to at least the burst demand

Fix history depth and history resources in throughput tests [6357]

---

CMakeLists.txt

VC Generator forces you to specify architecture (Win32 or x64) when the Buildsystem is generated (first stage), for example:
``
project > cmake -A x64 -B build64 .
``
then on the build (second stage) a config (Release, Debug, ...) is specified, for example:
``
project > cmake --build build64 --config Debug
``
as foonathan_memory_vendor was implemented once the project was generated for an architecture (x64 for example) no other architecture was allowed, for example the following command:
``
project > cmake -A Win32 -B build32 .
``
wouldn't generate any vcxproj because it identifies that this project was already generated (unfortunately for the wrong architecture).

[6337] Allow foonathan_memory_vendor to behave as any other target under VC generator.

---

include/fastrtps/config.h.in
src/cpp/CMakeLists.txt
src/cpp/publisher/PublisherImpl.cpp
src/cpp/subscriber/SubscriberImpl.cpp
test/CMakeLists.txt

Added a CMake configuration option: `-DSTRICT_REALTIME=ON`
This option enables strict real-time. In this case, several API functions have a real-time behaviour.
* `Publisher::write()` - Uses ReliabilityQosPolicy.max_blocking_time
* `Subscriber::takeNextData()` - Uses ReliabilityQosPolicy.max_blocking_time
* `Subscriber::readNextData()` - Uses ReliabilityQosPolicy.max_blocking_time

Added STRICT_REALTIME option [6355]

---

src/cpp/rtps/security/SecurityManager.cpp
src/cpp/rtps/security/SecurityManager.h

This PR fixes #6246.
It adds a protecting mutex to the AuthenticationInfo event, which could be canceled incorrectly on receiving `data(p)` messages from new participants.

Refs #6246 Protecting AuthInfo timed event. [6345]

---

CMakeLists.txt

Revert "Allow foonathan_memory_vendor to behave as any other target under VC generator. (#716)"
This reverts commit e7d8844b0ed9610bb22c7c83b2c044577124e60e.

Revert #716

---

fastrtps.repos

Changes the version of FastCDR needed by fastrtps.repos to fix generated cmake paths.

Refs #6341 FastCDR version that fixes cmake paths. [6377]

---

include/fastrtps/rtps/resources/TimedEvent.h
src/cpp/rtps/builtin/discovery/participant/timedevent/RemoteParticipantLeaseDuration.cpp
src/cpp/rtps/resources/TimedEvent.cpp
src/cpp/rtps/resources/TimedEventImpl.cpp
src/cpp/rtps/resources/TimedEventImpl.h

This PR fixes a leak introduced by #726. 
When a remote participant is dropped due to its lease duration being elapsed, the RemoteParticipantLeaseDuration event is not deleted.
Before #726, it was configured to self destruct upon success, but now the event may be triggered without triggering a participant drop. This adds the requirement on TimedEvent to allow to be marked for destruction (i.e. changing its self-destruction behavior on demand).

Fix leak on RemoteParticipantLeaseDuration [6438]

---

include/fastrtps/rtps/attributes/RTPSParticipantAttributes.h
include/fastrtps/rtps/builtin/discovery/participant/PDPSimple.h
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
src/cpp/rtps/security/SecurityManager.cpp

This PR addresses ros2/rmw_fastrtps#315 by allowing the user to disable multicast traffic for builtin endpoints.

Flag to avoid builtin multicast [6450]

---

include/fastrtps/xmlparser/XMLParserCommon.h
resources/xsd/fastRTPS_profiles.xsd
src/cpp/xmlparser/XMLElementParser.cpp
src/cpp/xmlparser/XMLParserCommon.cpp
test/unittest/xmlparser/XMLProfileParserTests.cpp
test/unittest/xmlparser/test_xml_profiles.xml
test/unittest/xmlparser/test_xml_profiles_rooted.xml

This PR allows the user to disable the new flag to avoid choose multicast locators from the list received from remote participants.
* Updated *fastRTPS_profiles.xsd* reference file.
* Added parser logic for the new flag.
* Added the option and checks in `XMLParserTests`.

Refs #6451 Added XML config option for avoid_builtin_multicast flag. [6452]

---

src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
src/cpp/rtps/builtin/liveliness/WLP.cpp
test/unittest/xmlparser/XMLProfileParserTests.cpp
test/unittest/xmlparser/test_xml_profiles_rooted.xml

This will improve the communications between a participant without the avoid_multicast flag set and another participant with it.

Adding avoid_multicast to PDP and WLP [6467]

---

examples/C++/Configurability/UseCasePublisher.cpp
examples/C++/Configurability/UseCaseSubscriber.cpp
examples/C++/Keys/keys.cpp
examples/C++/LateJoiners/latejoiners.cpp
examples/C++/SampleConfig_Controller/sampleconfig_safest.cpp
examples/C++/SampleConfig_Events/sampleconfig_triggers.cpp
examples/C++/SampleConfig_Multimedia/sampleconfig_fastest.cpp

I identified that the following C++ examples had memory leaks:
- Configurability
- Keys
- LateJoiners
- SampleConfig_Controller
- SampleConfig_Events
- SampleConfig_Multimedia

Fixing memory leaks in some C++ examples [6485]

---

src/cpp/CMakeLists.txt

Fixes #751 
To test this PR:
* Revert changes in this PR
* Install fastrtps in a local directory: `mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=install/ && make install`
* Navigate to the source directory of one of the examples, for instance the `HelloWorld`, and build it: `mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=<dir>/install .. && make`
You should get errors about include files not being found.
Repeat the same steps with changes in this PR. You should now be able to build the `HelloWorld`.

Fixing fastrtps installation [6487]

---

CMakeLists.txt

Download the current `PROJECT_VERSION` tag of the documentation instead of `latest`.

BUILD_DOCUMENTATION version [6502]

---

CMakeLists.txt

Download the current `PROJECT_VERSION` tag of the documentation instead of `latest`.

BUILD_DOCUMENTATION version - 1.9.x [6503]

---

include/fastrtps/publisher/PublisherHistory.h
include/fastrtps/subscriber/SubscriberHistory.h
test/blackbox/PubSubReader.hpp
test/blackbox/PubSubWriter.hpp

* This PR modifies the Blackbox tests to provide local copies of Participant, Subscriber, and Publisher attributes, to reproduce the issue and catch it with valgrind checks.
* Removes the `const reference` members in `PublisherHistory` and `SubscriberHistory` that caused the issue when these attributes went out of scope.
Fixes #758

Hotfix/member ref [6508]

---

test/performance/ThroughputPublisher.cpp
test/performance/ThroughputPublisher.h
test/performance/ThroughputSubscriber.cpp

* ThroughputPublisher:
* Members latency_t and latency renamed to throughput_t and throughput
* The time spent recovering in included in the time measurements
* If the subscriber does not acknowledge the TEST_ENDS, we return true, finishing the experiments.
* Style compliance
* ThroughputSubscriber:
* Style compliance
* Move default in switch to the end
* couts for improving console output readability
* t_start_ after cout to avoid timing a time consuming operation
* On TEST_ENDS, wait for data publisher removal

Refs #6569: Re-work throughput test to properly time [6575]

---

examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.cpp
examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.h
examples/C++/DDS/HelloWorldExample/HelloWorldSubscriber.cpp
examples/C++/DDS/HelloWorldExample/HelloWorldSubscriber.h
include/dds/core/detail/macros.hpp
include/dds/sub/status/DataState.hpp
include/fastdds/dds/subscriber/SampleInfo.hpp
include/fastdds/dds/topic/DataReader.hpp
src/cpp/dds/topic/DataReader.cpp
src/cpp/dds/topic/DataReaderImpl.cpp
src/cpp/dds/topic/DataReaderImpl.hpp
test/xtypes/TestSubscriber.cpp
test/xtypes/TestSubscriber.h

Implementation of SampleInfo_t.
Includes an example conversion between both SampleInfo_t structs, that must be refined once SubscriberHistory migrates.

DDS::SampleInfo Implementation. [6617]

---

include/fastdds/rtps/builtin/discovery/participant/PDP.h
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
src/cpp/rtps/builtin/liveliness/WLPListener.cpp
src/cpp/rtps/resources/ResourceEvent.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
test/communication/Publisher.cpp
test/communication/Subscriber.cpp

This PR fixes most data races and ABBA locks reported by *helgrind*.
There exists a detected ABBA lock between reader's and WLP's mutexes that can be solved by commenting out the line 976 of WLP.cpp, but then some liveliness tests time out or fail.
We will address a better solution for that issue in the future.

Refs #6557 Fixing helgrind issues.

---

include/fastdds/rtps/common/CacheChange.h
include/fastdds/rtps/reader/RTPSReader.h
include/fastdds/rtps/reader/StatefulReader.h
include/fastdds/rtps/reader/StatelessReader.h
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/rtps/messages/submessages/DataMsg.hpp
src/cpp/rtps/reader/FragmentedChangePitStop.cpp
src/cpp/rtps/reader/FragmentedChangePitStop.h
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp
src/cpp/rtps/writer/RTPSWriterCollector.h
test/unittest/rtps/common/CMakeLists.txt
test/unittest/rtps/common/CacheChangeTests.cpp

This is part of the Fragmentation API refactor.
The `dataFragments_` vector is removed by having the list of missing fragments implemented inside the data payload. The first 4 bytes of each fragment will have the index of the next missing fragment.

Remove fragment state vector on CacheChange_t [6623]

---

src/cpp/rtps/writer/StatefulWriter.cpp

This should fix #747 improving the edge case where check_acked_status is called between a reader being matched and reception of its acknack message

Improvements on check_acked_status [6612]

---

include/fastdds/rtps/reader/StatelessReader.h
src/cpp/rtps/reader/FragmentedChangePitStop.cpp
src/cpp/rtps/reader/FragmentedChangePitStop.h
src/cpp/rtps/reader/StatelessReader.cpp

This is a follow-up of #789 
In order to avoid dynamic allocations and improve performance, this PR changes StatelessReader to avoid the usage of FragmentedChangePitStop, by having a single change pending reconstruction per matched writer.
The only drawback is that it removes the reception of fragments from unknown writers, but that should only happen with DATA(p) messages which are usually small enough to be sent on a single DATA message.

Remove pitstop usage from StatelessReader [6642]

---

test/performance/ThroughputPublisher.cpp
test/performance/ThroughputSubscriber.cpp
test/performance/ThroughputSubscriber.h

Publisher
* Discover data subscriber before sending TEST_STARTS command
* Wait for ack when sending TEST_STARTS
* Only wait whatever is left of `recovery_time`
Subscriber
* wait_for_unread_samples instead of attempting to `take` all the time

Refs #6611: Bugfix/throughput wait and sync [6678]

---

examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.cpp
examples/C++/DDS/HelloWorldExample/HelloWorldPublisher.cpp
examples/C++/DDS/HelloWorldExample/HelloWorldSubscriber.cpp
include/fastdds/dds/builtin/typelookup/common/TypeLookupTypes.hpp
include/fastdds/dds/domain/DomainParticipant.hpp
include/fastdds/dds/topic/TypeSupport.hpp
src/cpp/fastdds/builtin/typelookup/common/TypeLookupTypes.cpp
src/cpp/fastdds/domain/DomainParticipant.cpp
src/cpp/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/fastdds/domain/DomainParticipantImpl.hpp
src/cpp/fastdds/publisher/PublisherImpl.cpp
src/cpp/fastdds/subscriber/SubscriberImpl.cpp
src/cpp/fastdds/topic/DataReaderImpl.cpp
src/cpp/fastdds/topic/DataWriterImpl.cpp
src/cpp/fastdds/topic/TypeSupport.cpp
test/dds/communication/Publisher.cpp
test/xtypes/TestPublisher.cpp
test/xtypes/TestSubscriber.cpp

This PR makes TypeSupport a base class, still compatible with TopicDataType but by storing it as `shared_ptr`.

Feature/pim typesupport [6639]

---

src/cpp/qos/ParameterList.cpp

This PR:
* Brings back compatibility with XTypes 1.1 on PID_TYPE_CONSISTENCY
* Ensures correct alignment when reading a parameter list

[1.9.x] Fix reception of ParameterList [6685]

---

doc/dds-core-xtypes/README.md
examples/ModernC++/xtypes/main.cpp
include/dds/core/xtypes/DynamicData.hpp
test/dds/core/xtypes/CMakeLists.txt

* Added assignment operators for primitive, string and wstring DynamicData. 
* Added examples of assignment in `examples/ModernC++/xtypes`.
* README applies the max line length limit (except for base64 image).
* Added some assignment examples in the README.
* Commented `cmake_minimum_required(VERSION 3.13)` in `test/dds/core/xtypes`.

Assignment operators.

---

include/fastrtps/types/DynamicData.h

The `GetKind()` is marked as inline when it is defined in the cpp. If an external library call this function will crash.

Removed unused inline

---

fastrtpsgen/build.gradle

Fixes https://github.com/eProsima/Fast-RTPS/issues/820, by applying https://github.com/eProsima/Fast-RTPS-Gen/pull/11.
Ouput:
```console
$ fastrtpsgen -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
fastrtpsgen version 1.7.2
```

[1.7.x] Fixing version file generation for correct 'fastrtpsgen -version' output

---

doc/design/intra-process.md

* This design isolates all message traffic from the wire, that is, tools like **wireshark™** will become useless. Given that most of our customers actually run intraprocess code, and report their issues using **wireshark™** traces, these changes will create a support nightmare. A workaround may be to supply a flag to inhibit the intraprocess behavior for debugging purposes, stating clearly, that it should be turn off during performance test.
* Once a shared memory transport is developed for interprocess purposes, an intraprocess mechanism would be pointless. That's because the trade off between speed gain and source complexity would be very expensive. From memory consumption point of view using an interprocess discovery database would yield more benefits that having per-process discovery …

Noticing some design side-effects

---

CMakeLists.txt
include/dds/core/xtypes/DynamicData.hpp
src/cpp/CMakeLists.txt

- Removed EPROSIMA_BUILD_XTYPES_STANDALONE option. 
- DDS headers are now installed always.
- Added new hierarchical copy and move constructors for DynamicData.

Refs #6763 SOSS-DDS Xtypes

---

cmake/modules/FindTinyXML2.cmake

FindTinyXML2.cmake's current behavior is to always call `find_package` even if the options for `THIRDPARTY` or `TINYXML2_FROM_SOURCE` aren't set. So on systems with a TinyXML2 installation this means that those options are effectively ignored as find_package will pick up the system level install.
This PR does a simple check to only call find_package if those options aren't set without modifying any of the fallback code.

Only call find_package for TinyXML2 if thirdparty options are off

---

include/fastrtps/xmlparser/XMLProfileManager.h
src/cpp/xmlparser/XMLProfileManager.cpp

This PR is linked with [ros2/rmw_fastrtps 355 PR](https://github.com/ros2/rmw_fastrtps/pull/335). It has been done so that the RMW layer does not show log errors when a profile is not found.
* Add an optional parameter `log_error` for only logging the error when user specifies on member functions:
* `XMLProfileManager::fillParticipantAttributes`
* `XMLProfileManager::fillPublisherAttributes`
* `XMLProfileManager::fillSubscriberAttributes`
* Style compliance on:
* XMLProfileManager.h
* XMLProfileManager.cpp

Backport/optional log fill attr from profiles [6740]

---

include/fastrtps/types/TypesBase.h

This PR adds the alias `ResponseCode` for the new enum `ReturnCode_t` which replaces the old enum `ResponseCode`.

Refs #6789 Added alias for ResponseCode compatibility.

---

doc/design/intra-process.md

This PR is meant to discuss the design of the intra-process delivery mechanism. It is orthogonal to #810, as intra-process is meant to skip the transport API completely.

Intra process delivery design [6779]

---

include/fastrtps/xmlparser/XMLProfileManager.h
src/cpp/fastrtps_deprecated/xmlparser/XMLProfileManager.cpp

This PR is linked with [ros2/rmw_fastrtps 355 PR](https://github.com/ros2/rmw_fastrtps/pull/335). It has been done so that the RMW layer does not show log errors when a profile is not found.
* Add an optional parameter `log_error` for only logging the error when user specifies on member functions:
* `XMLProfileManager::fillParticipantAttributes`
* `XMLProfileManager::fillPublisherAttributes`
* `XMLProfileManager::fillSubscriberAttributes`
* Style compliance on:
* XMLProfileManager.h
* XMLProfileManager.cpp

Refs #6715: Feature/optional log fill attr from profiles [6738]

---

include/fastrtps/utils/collections/foonathan_memory_helpers.hpp
src/cpp/rtps/builtin/data/ProxyHashTables.hpp

This PR fixes a failed assertion in foonathan library:
```
[foonathan::memory] Assertion failure in function insert_impl (/home/ricardo/workspace/eprosima/fastrtps/master/build/Debug/foonathan_memory_vendor/foo_mem-ext-prefix/src/foo_mem-ext/src/detail/free_list.cpp:239): Assertion "no_nodes > 0" failed.
```
The reason is `memory_pool` needs more space because foonathan uses space for debug purposes.

Fixed assertion in foonathan library on Debug. [6903]

---

src/cpp/rtps/builtin/discovery/participant/PDP.cpp

This is intended to fix a deadlock that causes tests to hang on the ROS 2 buildfarm (ros2/build_cop#248) using Fast-RTPS `v1.9.2`. There's more info here: https://github.com/ros2/build_cop/issues/248#issuecomment-555625379.
This PR avoids deadlock by releasing the PDP mutex before calling `remove_remote_participant()`. It seems like a reasonable thing to do since `remove_remote_participant()` [acquires the lock internally](https://github.com/eProsima/Fast-RTPS/blob/daabbc72b79b094cb9fe684655726105f27bdc7d/src/cpp/rtps/builtin/discovery/participant/PDP.cpp#L856), though I don't know if releasing the lock momentarily breaks any assumptions in `check_remote_participant_lifeliness()`.

Fix deadlock between PDP and StatefulReader

---

src/cpp/rtps/builtin/discovery/participant/PDP.cpp

* Fix deadlock between PDP and StatefulReader
This releases the PDP mutex before calling a function that may try to
acquire the mutex on a StatefulReader.
Signed-off-by: Shane Loretz<sloretz@openrobotics.org>
Signed-off-by: Shane Loretz <sloretz@osrfoundation.org>
* Removing unnecessary lock().

Fix deadlock between PDP and StatefulReader (backport of #871)

---

include/fastdds/rtps/common/EntityId_t.hpp

Internally STL implementation of hash tables (unordered_map and set) use modulus operation to choose in which bucket put each element. Using an uniform distributed hash guarantees that the buckets get evenly filled and access time is minimum.
Until now we were using the whole EntityId_t interpret as a number as hash. That led to a non-uniform, unsuitable distribution because within each EntityId_t are kept flags not merely a counter. Now, only the counter value is used solving the speed issue.
This pull request contents has already been updated on 1.9.x (see #868).

Updating std::hast<EntityId_t> to get a better unordered containers distribution [6895]

---

include/fastrtps/rtps/messages/MessageReceiver.h
src/cpp/rtps/messages/MessageReceiver.cpp

This PR converts MessageReceiver::findAllReaders into a templated method, in order to avoid dynamic memory allocations when the std::function object is copied.

[1.9.x] Templating MessageReceiver::findAllReaders [6897]

---

include/fastdds/rtps/messages/MessageReceiver.h
src/cpp/rtps/messages/MessageReceiver.cpp

This PR converts MessageReceiver::findAllReaders into a templated method, in order to avoid dynamic memory allocations when the std::function object is copied.

[master] Templating MessageReceiver::findAllReaders [6913]

---

test/blackbox/BlackboxTestsPubSubFragments.cpp
test/blackbox/PubSubReader.hpp
test/blackbox/PubSubWriter.hpp

This PR increases the reception buffer on the test.
The test is failing a lot after allowing fragment delivery on synchronized transport, because we are now sending 5 packets per change, each packet with max size, at fast rate, and the receiving buffer gets full.

[1.9.x] Increase recv buffer on PubSubAsNonReliableData300kb

---

include/fastrtps/rtps/builtin/discovery/participant/timedevent/DSClientEvent.h
include/fastrtps/rtps/builtin/discovery/participant/timedevent/DServerEvent.h
include/fastrtps/rtps/resources/ResourceEvent.h
include/fastrtps/rtps/resources/TimedEvent.h
include/fastrtps/utils/TimedConditionVariable.hpp
src/cpp/publisher/PublisherImpl.cpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.cpp
src/cpp/rtps/builtin/discovery/participant/timedevent/DServerEvent.cpp
src/cpp/rtps/builtin/liveliness/WLP.cpp
src/cpp/rtps/reader/WriterProxy.cpp
src/cpp/rtps/resources/ResourceEvent.cpp
src/cpp/rtps/resources/TimedEvent.cpp
src/cpp/rtps/resources/TimedEventImpl.cpp
src/cpp/rtps/resources/TimedEventImpl.h
src/cpp/rtps/security/SecurityManager.cpp
src/cpp/rtps/writer/LivelinessManager.cpp
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/subscriber/SubscriberImpl.cpp
test/mock/rtps/TimedEvent/fastrtps/rtps/resources/TimedEvent.h
test/unittest/rtps/resources/timedevent/TimedEventTests.cpp
test/unittest/rtps/resources/timedevent/mock/MockEvent.cpp
test/unittest/rtps/resources/timedevent/mock/MockEvent.h

This PR aims to reduce dynamic allocations spotted when calling `async_wait` on an asio::steady_timer.
It is a refactor of the `ResourceEvent` and `TimedEventImpl` classes that drops the usage of asio for the timed events.

[1.9.x] Timed events refactor [6920]

---

src/cpp/rtps/writer/StatefulWriter.cpp

Avoid sending several piggyback heartbeat in a RTPS message with several DATA. This behavior occurs when `StatefulWriter::send_any_unsent_changes()` packs several DATA.

Improving piggyback heartbeat sending. [1.9.x]

---

include/fastrtps/rtps/writer/StatefulWriter.h
src/cpp/rtps/writer/StatefulWriter.cpp

Improvement sending only GAP for sequence number greater/equal than history minimum sequence number. In other case, force to send a piggyback heartbeat.

Improve sending GAP [1.9.x]

---

include/fastrtps/rtps/history/ReaderHistory.h
src/cpp/rtps/history/ReaderHistory.cpp

Since ReaderHistory sorts by source_timestamp, this PR improves the assertion of CacheChange_t.

Improving ReaderHistory sorting [1.9.x]

---

include/fastrtps/rtps/history/History.h
include/fastrtps/rtps/history/ReaderHistory.h
include/fastrtps/rtps/reader/RTPSReader.h
src/cpp/rtps/history/History.cpp
src/cpp/rtps/history/ReaderHistory.cpp
src/cpp/rtps/reader/RTPSReader.cpp
src/cpp/rtps/reader/StatefulReader.cpp

Added a mechanism to improve the performance with consecutive calls to `History::get_change()`.

Improvement in consecutives History::get_change [1.9.x]

---

src/cpp/rtps/writer/ReaderProxy.cpp

More details on internal issue [6947]
If publisher starts sending data BEFORE the EDP is finished, and we configured reliable sending to resend previous changes to newly discovered endopoints, it may occur that a new change is sent before the older ones. This new change will be ACK'd automatically on intraprocess.
Once the old changes are sent, the new already ACK'd change will get stuck on the ReaderProxy history. From then on, no change in the ReaderProxy will ever be removed.
On non-intraprocess, the ACK mechanism depends on acknacks, and is not done automatically, so the problem does not occur.
This PR tries to further clean the change history on the ReaderProxy to avoid the issue.

[master] clean ReaderProxy cache on acked_changes_set [6947]

---

src/cpp/rtps/writer/StatefulWriter.cpp

Adding proxy to matched_readers_ before calculating there_are_remote_readers_

[1.9.x] Fix calculation of there_are_remote_readers_

---

include/fastrtps/rtps/common/CacheChange.h
include/fastrtps/utils/fixed_size_bitmap.hpp
test/blackbox/BlackboxTestsPubSubFragments.cpp

This PR changes the std::set with the list of pending fragments with a FragmentNumberSet_t.

[1.9.x] Not using std::set on ChangeForReader_t [7093]

---

test/blackbox/BlackboxTests.cpp
test/blackbox/BlackboxTests.hpp
test/blackbox/BlackboxTestsAcknackQos.cpp
test/blackbox/BlackboxTestsDeadlineQos.cpp
test/blackbox/BlackboxTestsDiscovery.cpp
test/blackbox/BlackboxTestsLatencyBudgetQos.cpp
test/blackbox/BlackboxTestsLifespanQoS.cpp
test/blackbox/BlackboxTestsLivelinessQos.cpp
test/blackbox/BlackboxTestsNetworkConf.cpp
test/blackbox/BlackboxTestsPersistence.cpp
test/blackbox/BlackboxTestsPubSubBasic.cpp
test/blackbox/BlackboxTestsPubSubFlowControllers.cpp
test/blackbox/BlackboxTestsPubSubFragments.cpp
test/blackbox/BlackboxTestsPubSubHistory.cpp
test/blackbox/BlackboxTestsRTPS.cpp
test/blackbox/BlackboxTestsRealtimeAllocations.cpp
test/blackbox/BlackboxTestsSecurity.cpp
test/blackbox/BlackboxTestsTransportTCP.cpp
test/blackbox/BlackboxTestsTransportUDP.cpp
test/blackbox/BlackboxTestsVolatile.cpp
test/blackbox/utils/data_generators.cpp
test/blackbox/utils/lambda_functions.cpp
test/blackbox/utils/print_functions.cpp
test/unittest/rtps/history/CacheChangePoolTests.cpp

There was a missing include in one header file for `std::for_each`. Also, `INSTANTIATE_TEST_CASE_P` is deprecated in favor `INSTANTIATE_TEST_SUITE_P`. I'm not sure why the last coma in the macro was necessary.

Include What You Use BlackboxTests.hpp

---

include/fastrtps/rtps/history/CacheChangePool.h
include/fastrtps/rtps/resources/ResourceManagement.h
include/fastrtps/xmlparser/XMLParserCommon.h
resources/xsd/fastRTPS_profiles.xsd
src/cpp/rtps/history/CacheChangePool.cpp
src/cpp/rtps/writer/RTPSWriter.cpp
src/cpp/xmlparser/XMLElementParser.cpp
src/cpp/xmlparser/XMLParserCommon.cpp
test/unittest/rtps/history/CacheChangePoolTests.cpp

Adds a DYNAMIC_REUSABLE memory mode
This memory mode starts with an empty pool (much like DYNAMIC),
but the allocated slots for CacheChange are not freed, they are
added to the pool of free changes for future reuse insted.

[1.9.x] Use cache change pool when DYNAMIC_RESERVE [7020]

---

src/cpp/rtps/transport/UDPTransportInterface.cpp

In UDPTransportInterface::select_locators, IsLocatorSupported() is called with unicast[j].kind instead of unicast[j]. This is an error because IsLocatorSupported() receives a Locator_t as parameter, so when passing unicast[i].kind an instance of a Locator_t with kind UDP and port_number (unicast[i].kind) is created and passed to IsLocatorSupported().
This bug can cause problems when a Participant registers a Transport UDP and an additional transport like, for example, TCP. In that case UDPTransportInterface::IsLocatorSupported over TCP locators will return true because TCP locators will be converted to Locator_t (kind = UDP, port = TCP.Kind) in the call to IsLocatorSupported.

Bugfix: UDPTransportInterface::select_locators [7147]

---

include/fastrtps/transport/TCPChannelResource.h
src/cpp/transport/TCPChannelResourceBasic.cpp

`asio::write()` ensures all data is sent. This function avoids an error using `asio::basic_stream_socket::send()` with large fragments.
Fixed #941.

TCP transport: using asio::write to send data. <1.9.x>

---

include/fastdds/rtps/transport/TCPChannelResource.h
src/cpp/rtps/transport/TCPChannelResourceBasic.cpp

`asio::write()` ensures all data is sent. This function avoids an error using `asio::basic_stream_socket::send()` with large fragments.
Fixed #941.

TCP transport: using asio::write to send data. <master> [7224]

---

src/cpp/rtps/writer/StatefulWriter.cpp

Avoid sending several piggyback heartbeat in a RTPS message with several DATA. This behavior occurs when `StatefulWriter::send_any_unsent_changes()` packs several DATA.

Improving piggyback heartbeat sending. [master]

---

src/cpp/transport/UDPTransportInterface.cpp

In UDPTransportInterface::select_locators, IsLocatorSupported() is called with unicast[j].kind instead of unicast[j]. This is an error because IsLocatorSupported() receives a Locator_t as parameter, so when passing unicast[i].kind an instance of a Locator_t with kind UDP and port_number (unicast[i].kind) is created and passed to IsLocatorSupported().
This bug can cause problems when a Participant registers a Transport UDP and an additional transport like, for example, TCP. In that case UDPTransportInterface::IsLocatorSupported over TCP locators will return true because TCP locators will be converted to Locator_t (kind = UDP, port = TCP.Kind) in the call to IsLocatorSupported.

Bugfix: UDPTransportInterface::select_locators <1.9.x> [7231]

---

include/fastdds/rtps/history/ReaderHistory.h
src/cpp/rtps/history/ReaderHistory.cpp

Since ReaderHistory sorts by source_timestamp, this PR improves the assertion of CacheChange_t.

Improving ReaderHistory sorting [master]

---

CMakeLists.txt
test/performance/latency/LatencyTestTypes.hpp
test/performance/latency/main_LatencyTest.cpp
test/performance/throughput/ThroughputTypes.hpp
test/performance/throughput/main_ThroughputTest.cpp
test/performance/video/VideoTestTypes.hpp
test/performance/video/main_VideoTest.cpp

[1.9.x] Correct clang warnings due to overwritten methods [7263]

---

test/performance/throughput/ThroughputPublisher.cpp

From [Windows nightly 187](http://jenkins.eprosima.com:8080/job/FastRTPS%20Nightly%20Master%20Windows/label=windows-secure,platform=Win32,toolset=v141/187/consoleFull)
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\xutility(3520): warning C4389: '==': signed/unsigned mismatch (compiling source file C:\fastrtps-nightly\e0db3111\src\fastrtps\test\performance\throughput\ThroughputPublisher.cpp) [C:\fastrtps-nightly\e0db3111\build\fastrtps\test\performance\throughput\ThroughputTest.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\xutility(3533): note: see reference to function template instantiation '_InIt std::_Find_unchecked1<_InIt,_Ty>(_InIt,const _InIt,const _Ty …
```

Solve throughput test compiler warning in Windows <master>

---

src/cpp/subscriber/SubscriberHistory.cpp
test/blackbox/BlackboxTests.hpp
test/blackbox/BlackboxTestsPubSubHistory.cpp
test/blackbox/PubSubReader.hpp
test/blackbox/PubSubWriter.hpp
test/blackbox/types/KeyedHelloWorld.cpp
test/blackbox/types/KeyedHelloWorld.h
test/blackbox/utils/data_generators.cpp
test/blackbox/utils/print_functions.cpp

SubscriberHistory::remove_change_sub should remove from
the general RTPS history even though it didn't find
the change in the instance's history.
Failing to do so will result on the same change returned
once and again every time a new change is added
to the subscriber's history

Ref. 7288 Change removed when not on instance [7289]

---

include/fastrtps/subscriber/SubscriberHistory.h
src/cpp/subscriber/SubscriberHistory.cpp

SubscriberHistory::deserialize_change must return the result of the deserialization
and SubscriberHistory::takeNextData should propagate errors on deserialization and removal from history

Ref. 7290 propagate errors on take_next_data [7292]

---

include/fastdds/rtps/builtin/BuiltinProtocols.h
src/cpp/rtps/builtin/BuiltinProtocols.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp

Applies the same treatment given to the locators received via DATA, to the locators pass into the RemoteServerAttributes.
Basically the locators become localhost if possible to speed things up.

[7138] Updated PDP to solve discovery-server issue on localhost.

---

test/performance/throughput/throughput_tests.py

The throughput ctest now names output CSV files with delivery system

Name CSVs with delivery <master> [7425]

---

include/fastrtps/rtps/common/CDRMessage_t.h
include/fastrtps/rtps/writer/StatelessWriter.h
src/cpp/publisher/PublisherImpl.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
test/blackbox/BlackboxTestsPubSubFragments.cpp

The async thread was not awaken to send the next unsent fragments after sending the first 256. This PR fixes this.

Fixed error sending more than 256 fragments <1.9.x> [7403]

---

include/fastrtps/rtps/attributes/RTPSParticipantAllocationAttributes.hpp
include/fastrtps/rtps/common/CDRMessage_t.h
include/fastrtps/rtps/messages/RTPSMessageGroup.h
include/fastrtps/xmlparser/XMLParser.h
include/fastrtps/xmlparser/XMLParserCommon.h
resources/xsd/fastRTPS_profiles.xsd
src/cpp/CMakeLists.txt
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/messages/RTPSMessageGroup.cpp
src/cpp/rtps/messages/RTPSMessageGroup_t.hpp
src/cpp/rtps/messages/SendBuffersManager.cpp
src/cpp/rtps/messages/SendBuffersManager.hpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/xmlparser/XMLElementParser.cpp
src/cpp/xmlparser/XMLParserCommon.cpp
test/unittest/xmlparser/XMLProfileParserTests.cpp
test/unittest/xmlparser/test_xml_profiles.xml

This PR:
* Adds a `SendBuffersManager` class, responsible of RTPSMessageGroup_t allocation
* Adds a `send_buffers` field to `RTPSParticipantAllocationAttributes` with the allocation options for the pool of `RTPSMessageGroup_t` instances
* Adds the corresponding XML parsing and test

RTPSMessageGroup_t preallocation <1.9.x> [7165]

---

include/fastrtps/rtps/messages/RTPSMessageGroup.h

This fixes a build error introduced on #938 when building without security.
Skipping tests, as they are always run with security enabled.

Fixed build without security after #938

---

src/cpp/publisher/PublisherHistory.cpp

Not passing `max_blocking_time` to add_change_ unless strict realtime is enabled.
This was detected due to failures under valgrind on the blackbox test `PubSubKeepAll`, that sets max_blocking_time to 0

Fix handling of STRICT_REALTIME <1.9.x>[7368]

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h

If the ReceiverResources are registered during the RTPSParticipantImpl construction, they may start receiving data before the Participant initialization is finished, causing a system crash.
This PR delays the registering the ReceiverResource until RTPSParticipantImpl::enable.
A new parameter on RTPSParticipantImpl::createReceiverResources specifies if the resource registration should be defered (for example, on resources created on initialization) or performed immediately (for resources created after initialization).

Avoid data races between ReceiverResource and Participant initialization [7475]

---

test/blackbox/BlackboxTestsLivelinessQos.cpp

When the reader has automatic liveliness, but the writer does not, a PDP announcement from the writer can make the reader assert the liveliness of the writer, which is not expected by some tests. This PR tries to avoid this situation by increasing the PDP announcement period of the writer on those tests.

Avoid unwanted recoveries on liveliness tests <1.9.x> [7468]

---

include/fastrtps/rtps/writer/ReaderProxy.h
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/WriterProxy.cpp
src/cpp/rtps/reader/WriterProxy.h
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
test/mock/rtps/ReaderLocator/fastrtps/rtps/writer/ReaderLocator.h
test/mock/rtps/ReaderProxyData/fastrtps/rtps/builtin/data/ReaderProxyData.h
test/mock/rtps/WriterProxyData/fastrtps/rtps/builtin/data/WriterProxyData.h

This PR reduces the memory consumption of `ReaderProxy` and `WriterProxy` by keeping just the necessary items from the corresponding proxy data.

[1.9.x] Reduce proxies memory consumption [7038]

---

include/fastrtps/rtps/builtin/BuiltinProtocols.h
src/cpp/rtps/builtin/BuiltinProtocols.cpp
src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
test/unittest/rtps/history/CacheChangePoolTests.cpp

Applies the same treatment given to the locators received via DATA, to the locators pass into the RemoteServerAttributes.
Basically the locators become localhost if possible to speed things up.

[7138] Bugfix/discovery server localhost

---

include/fastdds/dds/core/policy/ParameterTypes.hpp
include/fastdds/rtps/common/Types.h
include/fastdds/rtps/messages/MessageReceiver.h
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/security/SecurityManager.cpp
src/cpp/rtps/security/SecurityManager.h
test/unittest/rtps/security/SecurityInitializationTests.cpp
test/unittest/rtps/security/SecurityTests.cpp

Message receiver improvements <master> [7485]

---

include/fastdds/rtps/common/EntityId_t.hpp
include/fastdds/rtps/messages/CDRMessage.h
include/fastdds/rtps/messages/CDRMessage.hpp
src/cpp/fastrtps_deprecated/utils/IPFinder.cpp
test/blackbox/BlackboxTestsPersistence.cpp
test/performance/latency/LatencyTestTypes.cpp
test/performance/throughput/ThroughputTypes.cpp

I was experimenting with ubsan on your test examples and noticed it found an aliasing issue on these lines. When I compile this code, the aliasing isn't 4 byte aligned so the assignment might behavior strangely. `memcpy` may make more sense in this case.
Here's a [code sample](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,j:1,lang:c%2B%2B,source:'%23include+%3Ccstdlib%3E%0A%23include+%3Ccstdint%3E%0A%23include+%3Ciostream%3E%0A%0Atypedef+unsigned+char+octet%3B%0A%0Astruct+MyClass%0A%7B%0A++++static+constexpr+unsigned+int+size+%3D+4%3B%0A++++char+offset%3B%0A++++octet+value%5Bsize%5D%3B%0A++++MyClass(const+uint32_t+id)%0A++++%7B%0A++++++uint32_t*+aux+%3D+(uint32_t*)(value)%3B%0A++++++*aux+%3D+id%3B%0A++++%7D%0A%7D%3B%0A%0Aint+main()+%7B%0A++MyClass+my_class(42)%3B%0A++std …

Identity id alias fixes [7489]

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp

Introduced after correctly forcing compilation checks on logInfo.

Fixed logInfo warnings on RTPSParticipantImpl.cpp <1.9.x> [7524]

---

src/cpp/rtps/builtin/discovery/participant/PDP.cpp

This should fix one case of #929

Protect add_participant_proxy_data on initPDP. <1.9.x> [7531]

---

include/fastrtps/utils/TimedConditionVariable.hpp

When `TimedConditionVariable::wait_until` receives a `max_blocking_time` in the past, the calculations lead to a negative number on the timespec struct. This leads to EINVAL being returned from pthread_cond_timed_wait.

Fixing wait_until when time is in the past <1.9.x> [7210]

---

include/fastrtps/utils/TimedConditionVariable.hpp

When `TimedConditionVariable::wait_until` receives a `max_blocking_time` in the past, the calculations lead to a negative number on the timespec struct. This leads to EINVAL being returned from pthread_cond_timed_wait.

Fixing wait_until when time is in the past <master> [7211]

---

include/fastrtps/rtps/reader/StatelessReader.h
src/cpp/rtps/reader/StatelessReader.cpp
test/blackbox/BlackboxTestsDiscovery.cpp
test/blackbox/PubSubReader.hpp

This is a port of #1005 from 1.9.x
* Refs #7552. Only accepting changes from unknown writers when they are ALIVE.
* Refs #7552. Added blackbox test.

Only accepting ALIVE changes from unknown trusted writers <1.8.x> [7588]

---

include/fastrtps/rtps/builtin/discovery/endpoint/EDPSimple.h
src/cpp/rtps/builtin/discovery/endpoint/EDPClient.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp

This fixes #1007 by making the template method `EDPSimple::serialize_proxy_data` private and adding two protected proxy methods for the two possible instantiations of the template.
NOTE: CI jobs have been updated to build on release mode

Avoid problems with template method inlining. [7601]

---

include/fastdds/rtps/reader/StatelessReader.h
src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
src/cpp/rtps/reader/StatelessReader.cpp
test/blackbox/BlackboxTestsDiscovery.cpp
test/blackbox/PubSubReader.hpp

This is a port of #1005 from 1.9.x
* Refs #7552. Only accepting changes from unknown writers when they are ALIVE.
* Refs #7552. Added blackbox test.

Only accepting ALIVE changes from unknown trusted writers <master> [7587]

---

src/cpp/rtps/messages/submessages/DataMsg.hpp

Wireshark complains when the length of a fragment is not multiple of 4 bytes. This usually happens on the last fragment, as the fragment size is usually multiple of 4.

Fixed submessage_size calculation on last data_frag <1.9.x>[7535]

---

include/fastrtps/rtps/reader/StatelessReader.h
src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
src/cpp/rtps/reader/StatelessReader.cpp
test/blackbox/BlackboxTestsDiscovery.cpp
test/blackbox/PubSubReader.hpp

When a participant with a fixed id is deleted and recreated on the same process, other participants may ignore him because:
* When being deleted, more than one DATA(p)[UD] may be sent, and on the other participant
* The first one makes the matched_writer be removed, and history_record is correctly updated
* When the second one is processed, it is accepted (as the writer id is trusted) and the guid of the writer is added to the history_record with a sequence number of (usually) 2. It is passed to the PDPListener callback, which will do nothing, as it refers to an already removed participant
* When the participant is created again, the DATA(p) announcing it (with sequence number 1) is received by the other participant, but the history_record has an entry with the same guid and sequence …

Only accepting ALIVE changes from unknown trusted writers <1.9.x> [7586]

---

src/cpp/rtps/reader/RTPSReader.cpp

This is a port of #1006 from 1.8.x
Only a partial port is done, as the main issue was already corrected during a refactoring
* Ensure persistence_guid_count_ is deleted when it reaches to zero to free memory
* Change the condition to delete the records from count == 0 to count <= 0 for robustness

Delete history_record when endpoint is unmatched <1.9.x> [7602]

---

src/cpp/rtps/reader/RTPSReader.cpp

This is a port of #1006 from 1.8.x
Only a partial port is done, as the main issue was already corrected during a refactoring
* Ensure persistence_guid_count_ is deleted when it reaches to zero to free memory
* Change the condition to delete the records from count == 0 to count <= 0 for robustness

Delete history_record when endpoint is unmatched <master> [7603]

---

src/cpp/rtps/reader/StatelessReader.cpp
src/cpp/transport/test_UDPv4Transport.cpp
test/blackbox/BlackboxTests.hpp
test/blackbox/BlackboxTestsPubSubFragments.cpp
test/blackbox/PubSubReader.hpp
test/blackbox/utils/data_generators.cpp

Precisely what the title says. I have the impression this was the intent of the original author, but I may be wrong. Without this patch, I can reliably get `SerializedPayload_t` instances where `length > max_size`, though in most cases by a small margin (which would explain why this could've been missed). However, larger messages would often result in segfaults.
**Note:** I'm targeting `1.9.x` because that's the Fast-RTPS version ROS 2 uses. It could be easily ported forward.

Do not reuse cache change if sample does not fit. [7609]

---

src/cpp/rtps/builtin/data/WriterProxyData.cpp

This solves issue #1014 
After #1003 the Endpoint GUID received on incoming messages was no longer being stored. This can lead to failing endpoint matching.

Store endpoint GUID from message <1.9.x> [7610]

---

include/fastrtps/qos/ParameterTypes.h
include/fastrtps/rtps/common/Types.h
include/fastrtps/rtps/messages/MessageReceiver.h
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/rtps/messages/SendBuffersManager.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/rtps/security/SecurityManager.cpp
src/cpp/rtps/security/SecurityManager.h
test/unittest/rtps/security/SecurityInitializationTests.cpp
test/unittest/rtps/security/SecurityTests.cpp

This PR contains several improvements related to MessageReceiver:
* Allows the reception of messages bigger than 64K if the transport layer supports them
* The style has been applied, and some clean-up has been performed
* When built with security, if the participant is not configured as secure, no data is allocated for the temporary decryption buffer. To accomplish this it was necessary to create the receiver resources after initializing the security manager, but the internal call to `create_entities` needed the receiver resources to be already created. In order to solve this circular dependency, the `init` method had to be split in two phases, and the unit tests of the `SecurityManager` had to be updated accordingly.

Message receiver improvements <1.9.x> [7482]

---

src/cpp/rtps/builtin/discovery/participant/PDP.cpp

This is a cherry-pick of #871 to the `ros2-eloquent` branch.
@dirk-thomas FYI

[eloquent backport] Fix deadlock between PDP and StatefulReader (#871)

---

include/fastrtps/subscriber/SubscriberHistory.h
src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp

This is a port of #962 from 1.9.x
SubscriberHistory::deserialize_change must return the result of the deserialization
and SubscriberHistory::takeNextData should propagate errors on deserialization and removal from history

Propagate errors on take_next_data <master> [7702]

---

src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
test/blackbox/BlackboxTests.hpp
test/blackbox/BlackboxTestsPubSubHistory.cpp
test/blackbox/PubSubReader.hpp
test/blackbox/PubSubWriter.hpp
test/blackbox/types/KeyedHelloWorld.cpp
test/blackbox/types/KeyedHelloWorld.h
test/blackbox/utils/data_generators.cpp
test/blackbox/utils/print_functions.cpp

This is a port of #961 from 1.9.x [7288]

Remove from history when change is not on instance <master> [7701] 

---

test/unittest/rtps/security/SecurityHandshakeProcessTests.cpp
test/unittest/rtps/security/SecurityValidationRemoteTests.cpp

This is a port of #984 from 1.9.x

Fixing valgrind errors on security unit tests. [7704]

---

include/fastdds/rtps/common/CDRMessage_t.h
include/fastdds/rtps/messages/RTPSMessageCreator.h
include/fastdds/rtps/network/ReceiverResource.h
src/cpp/dds/topic/DataWriterImpl.cpp
src/cpp/fastrtps_deprecated/publisher/PublisherImpl.cpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/messages/RTPSMessageCreator.cpp
src/cpp/rtps/network/ReceiverResource.cpp
src/cpp/rtps/transport/ChannelResource.cpp
src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
test/blackbox/BlackboxTestsPubSubFragments.cpp
test/unittest/rtps/security/SecurityTests.hpp
test/unittest/security/authentication/AuthenticationPluginTests.hpp
test/unittest/security/cryptography/CryptographyPluginTests.hpp

The async thread was not awaken to send the next unsent fragments after sending the first 256. This PR fixes this.
Refactored as a port of #973

Fixed error sending more than 256 fragments <master> [7404]

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h

This is a port of #917 from 1.9.x

Removing unnecessary locators when detecting intraprocess only usecase <master> [7042]

---

include/fastdds/rtps/attributes/RTPSParticipantAllocationAttributes.hpp
include/fastdds/rtps/common/CDRMessage_t.h
include/fastdds/rtps/messages/RTPSMessageGroup.h
include/fastrtps/xmlparser/XMLParser.h
include/fastrtps/xmlparser/XMLParserCommon.h
resources/xsd/fastRTPS_profiles.xsd
src/cpp/CMakeLists.txt
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/messages/RTPSMessageGroup.cpp
src/cpp/rtps/messages/RTPSMessageGroup_t.hpp
src/cpp/rtps/messages/SendBuffersManager.cpp
src/cpp/rtps/messages/SendBuffersManager.hpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/rtps/xmlparser/XMLElementParser.cpp
src/cpp/rtps/xmlparser/XMLParserCommon.cpp
test/unittest/xmlparser/XMLProfileParserTests.cpp
test/unittest/xmlparser/test_xml_profiles.xml

This is a port of #938 and #979 and 3778a97 from 1.9.X

RTPSMessageGroup_t preallocation <master> [7166]

---

include/fastrtps/utils/TimedMutex.hpp

Backport #932 to fix Windows builds with latest Visual Studio versions.

[eloquent backport] Removes internal windows header (#932)

---

resources/xsd/fastRTPS_profiles.xsd
src/cpp/rtps/xmlparser/XMLElementParser.cpp

We discovered that several structures like LivelinessQosPolicy were initializing its Duration_t elements to non-default values:
```c++
RTPS_DllAPI LivelinessQosPolicy()
: Parameter_t(PID_LIVELINESS, PARAMETER_KIND_LENGTH + PARAMETER_TIME_LENGTH)
, QosPolicy(true)
, kind(AUTOMATIC_LIVELINESS_QOS)
, lease_duration(TIME_T_INFINITE_SECONDS, TIME_T_INFINITE_NANOSECONDS)  <---
, announcement_period(TIME_T_INFINITE_SECONDS, TIME_T_INFINITE_NANOSECONDS)  <--- 
{
}
```
The ``XMLP_ret XMLParser::getXMLDuration( tinyxml2::XMLElement* elem, Duration_t& duration, uint8_t ident)`` override didn't modify this values in absence of the xml tag, thus, non-default values may be introduced. For example:
```xml
<liveliness>
<kind>AUTOMATIC</kind>
<lease_duration>
<sec>5</sec>
</lease_duration> …
```

Make sure that default values are enforced when parsing a Duration_t xml tag. [7738]

---

examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.cpp
examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.h
examples/C++/DDS/TypeLookupService/TypeLookupSubscriber.cpp
examples/C++/DDS/TypeLookupService/TypeLookupSubscriber.h
test/xtypes/TestPublisher.cpp
test/xtypes/TestPublisher.h
test/xtypes/TestSubscriber.cpp
test/xtypes/TestSubscriber.h

Publisher/subscribers should not access the ComainParticipant pointer
until it is fully constructed (i.e., until create_participant returns).
Some of the tests have pubsubs with listeners that access the participant
pointer when receiving a message. Depending on the timing, the receive
resources can be up and running and start receiving before the pointer
is stored internally. When the listener tries to access this pointer,
the test crashes.
Added a mutex lock to sync both parts (participant creation and
listener)

Lock on create_participant <master> [7836]

---

src/cpp/rtps/writer/ReaderProxy.cpp
test/mock/rtps/StatefulWriter/fastdds/rtps/writer/StatefulWriter.h
test/mock/rtps/WriterHistory/fastdds/rtps/history/WriterHistory.h

This PR tackles the #1042 issue.
With it, as part of starting a `ReaderProxy`,  a call to `acked_changes_set(SequenceNumber_t())` is performed to simulate an initial acknack from the reader. This has the effect of setting the ReaderProxy's low mark to the writer's first available change, which avoids the writer need to iterate through all the changes 0 to low mark the first time it sends data to the reader.
This is OK to do, since an initial heartbeat is sent to the reader notifying the writer's state right after discovery, which already tells the reader that the first change is low mark, so there is no need of sending any gap, nor requesting changes older than that.

Simulate initial acknack on ReaderProxy::start() [7838]

---

include/fastdds/rtps/common/Locator.h
include/fastdds/rtps/common/LocatorSelector.hpp
include/fastdds/rtps/network/SenderResource.h
include/fastdds/rtps/reader/StatefulReader.h
include/fastdds/rtps/transport/TCPTransportInterface.h
include/fastdds/rtps/transport/UDPTransportInterface.h
include/fastdds/rtps/transport/test_UDPv4Transport.h
src/cpp/rtps/builtin/discovery/participant/DirectMessageSender.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/WriterProxy.cpp
src/cpp/rtps/transport/TCPSenderResource.hpp
src/cpp/rtps/transport/TCPTransportInterface.cpp
src/cpp/rtps/transport/UDPSenderResource.hpp
src/cpp/rtps/transport/UDPTransportInterface.cpp
src/cpp/rtps/transport/test_UDPv4Transport.cpp
src/cpp/rtps/writer/RTPSWriter.cpp
src/cpp/rtps/writer/ReaderLocator.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
test/mock/rtps/StatefulReader/fastdds/rtps/reader/StatefulReader.h
test/unittest/transport/TCPv4Tests.cpp
test/unittest/transport/UDPv4Tests.cpp

This is important for shared-memory-transport because only one copy has to be done, so instead calling send one time per destination locator only one call is made passing a LocatorsIterator reference.

Transport Refactor: Send receives LocatorsIterator instead Locator_t <master> [7005]

---

include/fastrtps/qos/QosPolicies.h
src/cpp/qos/QosPolicies.cpp
test/blackbox/BlackboxTestsPubSubBasic.cpp

This should solve some interoperability problems discovered on ros2/build_farmer#268

Force aligned param length <1.9.x> [7840]

---

src/cpp/rtps/transport/TCPTransportInterface.cpp
src/cpp/rtps/transport/UDPTransportInterface.cpp

Since commit 83380dd1904e8aeadbed70b0279b12bc957cdd09 (PR #908 Transport Refactor: Send receives LocatorsIterator instead Locator_t). Some tests fail when running with Valgrind due to timeouts failure. This is because semantic of the send function in the transports was changed. Before, when timeout is reached the message is tried to be sent with time-out 0 and always return true. Now when timeout function fails.
This PR restores the old semantic.

Fixing send semantics [7893]

---

resources/xsd/fastRTPS_profiles.xsd
src/cpp/rtps/xmlparser/XMLElementParser.cpp
src/cpp/rtps/xmlparser/XMLParserCommon.cpp
test/performance/latency/CMakeLists.txt
test/performance/throughput/CMakeLists.txt

Notice that this pull request must be merged after #1046.
We noticed that Duration_t was ignoring the ``DURATION_INFINITY``, ``DURATION_INFINITE_SEC`` and ``DURATION_INFINITE_NSEC`` specifications given in the xml configuration files.
XSD schema was adapt to match, as much as possible, the documented behavior. XSD doesn't admit to restrict complex types with mixed test and subelements, thus, ``DURATION_INFINITY`` is only verified on parsing and ignored on validations against the schema.
Solving this problem another was detected on the performance test. The CTestFiles generated didn't include fastrtps dependencies on windows leading to systematic test failures. Because our continuos integration tests use colcon this behaviour wasn't noticed before (colcon populates the environment with all …

[7885] Modify Duration_t xml schema and parsing to match documented behaviour

---

include/fastdds/dds/core/policy/QosPolicies.hpp

Methods `getNames` and `setNames` were renamed, so we should keep an alias in order to maintain the old API.

Bring back removed API on PartitionQosPolicy. [7902]

---

src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp

I've seen some of the liveliness tests passing correctly but after a very long time (more than 50 seconds). I checked that 50 seconds is what the DATA(p) announcement period is set to on those tests. All of them were manual_by_topic and non-intraprocess.
The problem was that liveliness was not asserted when matched_readers_ was empty.
I have also seen that the call to `encrypt_cachechange` was suffering from the same problem on `StatelessWriter`. May have been the reason for the failures on `SimpleCommunicationSecureBestEffort`.
This PR fixes both problems.

Fixing unsent_change_added_to_history with no readers [7927]

---

src/cpp/rtps/writer/StatelessWriter.cpp

With this PR, the StatelessWriter synchronous delivery order is set to:
1. Intra-process.
2. Inter-process, but only if there are remote readers or fixed locators.
This posses a performance improvement for the intra-process case, since the RTPSMessageGroup construction only happens when it's needed (remote readers or fixed locators).
Note: this has been backported from #946

[eloquent] Stateless writer delivery improvement [7880]

---

include/fastdds/dds/core/policy/QosPolicies.hpp
include/fastdds/dds/publisher/qos/PublisherQos.hpp
include/fastdds/dds/topic/qos/DataReaderQos.hpp
include/fastdds/dds/topic/qos/DataWriterQos.hpp
include/fastdds/rtps/builtin/data/ParticipantProxyData.h
include/fastrtps/qos/QosPolicies.h
include/fastrtps/xmlparser/XMLParser.h

It seems that compilers are having problems when building (except on release) after #1059 was merged.
This PR helps them work better by avoiding the use of a template that was being aliased more than once.

Converting template into macro [7931]

---

include/fastdds/rtps/writer/StatefulWriter.h
src/cpp/rtps/writer/StatefulWriter.cpp

While checking #1062, I discovered that we could save some CPU usage with the changes on this PR. Note that it does not fix the issue, but I saw some improvement.
After further investigation, and recovering piggyback heartbeats on 6893b5dd2b703aa2ae416203e4e41461f1babd0d, this ~fixes~ #1062

Stateful writer improvements [7925]

---

src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp

When trying to open a SHM port (read exclusive), the open_port function logs an error if the port is already opened. This should be avoided because FastRTPS automatically tries another port number until a free port is found. Therefore, errors must not be logged to the user, errors in open_port are reported through exceptions that, in this case, are catched and filtered by the upper layer.

Remove unnecesary error log msg when opening a SHM port <master> [8030]

---

src/cpp/rtps/writer/ReaderProxy.cpp
test/mock/rtps/StatefulWriter/fastrtps/rtps/writer/StatefulWriter.h
test/mock/rtps/WriterHistory/fastrtps/rtps/history/WriterHistory.h

[ros2-eloquent] Simulate initial acknack on ReaderProxy::start() [7974]

---

include/fastdds/rtps/builtin/discovery/endpoint/EDPServer.h
include/fastdds/rtps/builtin/discovery/endpoint/EDPSimple.h
include/fastdds/rtps/builtin/discovery/participant/PDPServer.h
src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.h
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
src/cpp/rtps/builtin/discovery/participant/timedevent/DServerEvent.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp

Repairing client-server BACKUP operation
Former pull-request #662 introduce changes that prevent the proper operation of the BACKUP setup.
For ordinary SERVER participants an strategy was needed to handle *communication lost* vs *participant crash*. That is
because crashes require the clients to ignore any former assumption on the server participant state and start anew. This
was solved by adding a specific `GUID_t` to the SERVER participant (a per-instance one) that allow the clients to identify the
SERVER as a new instance (there was a crash).
For BACKUP server the above strategy is not required because they recover all its internal state from the backup file.
Clients can resume communication exactly in the same fashion as for a communication lost scenario.

Repairing client-server BACKUP operation [8027]

---

include/fastdds/rtps/builtin/discovery/endpoint/EDPServer.h
include/fastdds/rtps/builtin/discovery/endpoint/EDPSimple.h
include/fastdds/rtps/builtin/discovery/participant/PDPServer.h
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.h
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
src/cpp/rtps/builtin/discovery/participant/timedevent/DServerEvent.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp

During #1091 pull request works some issues which the PDP and EDP WriterHistory trimming were noticed. This pull request must be merged after #1091.
When an endpoint destruction notification is received then all its associated changes in the history should be removed. This removal cannot be done at once, the server must wait till all the clients acknowledge the changes. Thus, there is a collection of changes marked for disposal.
The disposal must be aborted if the endpoint we want to remove appears again. In order to detect that eventuality before removing an endpoint changes we check this endpoint is not in the discovery database (not alive). There was a bug on this step that is now repaired.
During the testing of trim operation under heavy exchange of discovery data several ABBA locks …

Server-Client trimming form discovery info update [8056]

---

src/cpp/fastrtps_deprecated/publisher/PublisherImpl.cpp
src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.cpp

It may be the case that lifetime has expired for several samples when the timer expires. This has been seen on some nightlies and on issue #1049 
This PR changes the behavior of the `lifespan_expired` method on the publisher and subscriber, so that several changes are processed until either a non-expired one is found or the history is empty.

Account for multiple expired changes on lifespan_expired. [8059]

---

include/fastdds/rtps/common/CacheChange.h
include/fastrtps/subscriber/SampleInfo.h
include/fastrtps/subscriber/Subscriber.h
include/fastrtps/subscriber/SubscriberHistory.h
src/cpp/fastrtps_deprecated/subscriber/Subscriber.cpp
src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.cpp
src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.h
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp

This adds a new method on `fastrtps::Subscriber` to get information about the first untaken sample. 
This is necessary in the context of ros2/rcl#591

Add get_first_untaken_info API [8062]

---

include/fastrtps/utils/IPFinder.h
src/cpp/fastrtps_deprecated/utils/IPFinder.cpp

The `scope_id` field on `info_IP` structure was never being used. Removing it solves the valgrind issues that appeared after enabling IPv6 on the CI dockers.

Removed unused field on info_IP [8070]

---

cmake/modules/FindThirdpartyBoost.cmake
src/cpp/CMakeLists.txt
src/cpp/rtps/network/NetworkFactory.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
src/cpp/rtps/transport/shared_mem/SharedMemTransportDescriptor.cpp
test/blackbox/BlackboxTestsTransportSHM.cpp
test/blackbox/CMakeLists.txt
test/unittest/transport/CMakeLists.txt

A compilation test for thirdparty/boost is performed by cmake, if this test failed, FastRTPS compilation is aborted with an error. As boost may not be supported in all platforms, this PR changes the behaviour. Now, if thirdparty/boost fail the test, the parts of FastRTPS using boost (that is SHM Transport) are not compiled. When the user try to use SHM transport an error will be logged.

Do not compile SHM transport if thirdparty/boost test fail <master> [8064]

---

src/cpp/rtps/builtin/data/WriterProxyData.cpp

This solves an interoperability regression introduced by #1004

Fixed deserialization of WriterProxyData <1.10.x>

---

examples/C++/HelloWorldExampleSharedMem/HelloWorld_main.cpp
src/cpp/rtps/transport/shared_mem/MultiProducerConsumerRingBuffer.hpp
src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
test/unittest/transport/SharedMemTests.cpp
test/unittest/transport/mock/SharedMemGlobalMock.hpp

This patch helps colaborating applications using SHM transport to recover when one of the applications is broken by ctrl-c or crash.
Before the patch, SHM ports opened for reading by the crashed application could be left inoperative for the rest of applications.
This is specially a problem for multicast ports opened by several processes.

SHM fault tolerance <1.10.x> [8118]

---

examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.cpp
examples/C++/DDS/HelloWorldExample/HelloWorldSubscriber.cpp
examples/C++/DDS/TypeLookupService/TypeLookupSubscriber.cpp
include/dds/domain/DomainParticipant.hpp
include/dds/sub/Subscriber.hpp
include/dds/sub/SubscriberListener.hpp
include/dds/sub/detail/Subscriber.hpp
include/dds/sub/qos/SubscriberQos.hpp
include/dds/sub/qos/detail/SubscriberQos.hpp
include/fastdds/dds/domain/DomainParticipant.hpp
include/fastdds/dds/publisher/Publisher.hpp
include/fastdds/dds/subscriber/Subscriber.hpp
include/fastdds/dds/subscriber/qos/SubscriberQos.hpp
include/fastrtps/attributes/SubscriberAttributes.h
src/cpp/CMakeLists.txt
src/cpp/dds/domain/DomainParticipant.cpp
src/cpp/dds/sub/Subscriber.cpp
src/cpp/fastdds/domain/DomainParticipant.cpp
src/cpp/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/fastdds/domain/DomainParticipantImpl.hpp
src/cpp/fastdds/publisher/qos/PublisherQos.cpp
src/cpp/fastdds/subscriber/Subscriber.cpp
src/cpp/fastdds/subscriber/SubscriberImpl.cpp
src/cpp/fastdds/subscriber/SubscriberImpl.hpp
src/cpp/fastdds/subscriber/qos/SubscriberQos.cpp
test/dds/communication/Subscriber.cpp
test/unittest/dds/participant/ParticipantTests.cpp
test/xtypes/TestSubscriber.cpp

- create_subscriber method following DDS standard
- unit test for create_subscriber
- link PSM Subscriber constructor to PIM implementation
- unit test for PSM Subscriber constructor
NOTE: This PR must be merged after #1073

DomainParticipant create_subscriber

---

test/unittest/dds/participant/ParticipantTests.cpp

Just a unit test to check DomainParticipant::delete_subscriber
NOTE: This PR must be merged after #1117

DomainParticipant delete_subscriber

---

CMakeLists.txt
src/cpp/CMakeLists.txt
src/cpp/rtps/participant/RTPSParticipantImpl.cpp

In FastRTPS 1.10.0 SHM is, by default, built-in transport.
This PR:
* Enable / disable SHM transport as built-in, on compilation time.
* Adds a cmake option SHM_TRANSPORT_DEFAULT (OFF by default) to enable SHM built-in compilation.

Disable SHM transport as built-in <1.10.x> [8134]

---

src/cpp/utils/Host.hpp

FastRTPS 1.10.0 crash by segfault when no network interfaces are detected in the machine.

Segfault when no network interfaces. <1.10.x> [8138]

---

src/cpp/fastdds/core/policy/ParameterList.cpp

This fixes #1134 by always considering PID_SENTINEL of length 0 (thus correctly following section 9.4.2.11 of RTPS)

Ignore plength for PID_SENTINEL <1.10.x>

---

CMakeLists.txt
examples/C++/HelloWorldExampleSharedMem/HelloWorldPublisher.cpp
examples/C++/HelloWorldExampleSharedMem/HelloWorldSubscriber.cpp
examples/C++/HelloWorldExampleSharedMem/HelloWorld_main.cpp
include/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.h
resources/xsd/fastRTPS_profiles.xsd
src/cpp/CMakeLists.txt
src/cpp/fastdds/core/policy/ParameterList.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/transport/shared_mem/MultiProducerConsumerRingBuffer.hpp
src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
src/cpp/rtps/transport/shared_mem/SharedMemTransportDescriptor.cpp
src/cpp/rtps/transport/shared_mem/test_SharedMemTransport.cpp
src/cpp/rtps/transport/shared_mem/test_SharedMemTransport.h
src/cpp/rtps/transport/shared_mem/test_SharedMemTransportDescriptor.h
src/cpp/rtps/xmlparser/XMLParser.cpp
src/cpp/utils/Host.hpp
test/blackbox/BlackboxTestsSecurity.cpp
test/blackbox/BlackboxTestsTransportSHM.cpp
test/communication/liveliness_assertion.360.xml
test/communication/liveliness_assertion.xml
test/mock/rtps/SharedMemTransportDescriptor/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.h
test/unittest/transport/SharedMemTests.cpp
test/unittest/transport/mock/SharedMemGlobalMock.hpp
test/unittest/xmlparser/SHM_transport_descriptors_config.xml
test/unittest/xmlparser/XMLProfileParserTests.cpp

Bringing in #1109, #1126, #1135, #1137 and #1138

Sync master with 1.10.x

---

include/fastdds/dds/topic/TopicDataType.hpp
include/fastdds/dds/topic/qos/TopicQos.hpp
src/cpp/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/fastdds/domain/DomainParticipantImpl.hpp
test/unittest/dds/participant/ParticipantTests.cpp

- Add `auto_fill_type_object` and `auto_fill_type_information` to `TopicDataType`
- Register the dynamic types to the factories when the data type is registered with `register_type`

dds type registration config

---

src/cpp/fastrtps_deprecated/utils/IPFinder.cpp

This header is necessary when compiling on FreeBSD.
I recognise this is deprecated, but ROS2 is still using v1.8.2 in the LTS Dashing branch, so I thought I would provide it for consideration.
The added header is necessary to avoid forward declarations of `struct sockaddr_in` and `struct sockaddr_in6`.
This doesn't appear to be an issue anywhere in the non-deprecated source files of the master branch.

add freebsd support

---

include/fastdds/dds/topic/Topic.hpp
include/fastdds/dds/topic/TopicDescription.hpp
src/cpp/fastdds/topic/Topic.cpp
src/cpp/fastdds/topic/TopicDescriptionImpl.hpp
src/cpp/fastdds/topic/TopicImpl.cpp
src/cpp/fastdds/topic/TopicImpl.hpp

Make the reference count API accessible from TopicDescription but hide it from the user on an implementation class

DDS Visibility of reference API from TopicDescription

---

examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.cpp
examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.h
examples/C++/DDS/HelloWorldExample/HelloWorldSubscriber.cpp
examples/C++/DDS/HelloWorldExample/HelloWorldSubscriber.h
examples/C++/DDS/TypeLookupService/TypeLookupSubscriber.cpp
examples/C++/DDS/TypeLookupService/TypeLookupSubscriber.h
include/dds/sub/DataReader.hpp
include/dds/sub/DataReaderListener.hpp
include/dds/sub/SubscriberListener.hpp
include/dds/sub/detail/DataReader.hpp
include/fastdds/dds/core/policy/QosPolicies.hpp
include/fastdds/dds/subscriber/DataReader.hpp
include/fastdds/dds/subscriber/Subscriber.hpp
src/cpp/CMakeLists.txt
src/cpp/dds/sub/DataReader.cpp
src/cpp/fastdds/subscriber/DataReader.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.hpp
src/cpp/fastdds/subscriber/Subscriber.cpp
src/cpp/fastdds/subscriber/SubscriberImpl.cpp
src/cpp/fastdds/subscriber/SubscriberImpl.hpp
test/dds/communication/Subscriber.cpp
test/unittest/dds/participant/ParticipantTests.cpp
test/unittest/dds/subscriber/SubscriberTests.cpp
test/xtypes/TestPublisher.cpp
test/xtypes/TestSubscriber.cpp
test/xtypes/TestSubscriber.h
test/xtypes/XTypesTests.cpp

- PIM implementation of create_datareader
- PIM implementation of delete_datareader
- PIM unit tests for create and delete datareader
- Unit testing including delete_subscriber failing if there is a datareader alive
- Adaptation of testcases and examples to delete datareaders and subscribers and topics before deleting participants
- PSM implementation of datareader constructor
- PSM unit tests for datareader constructor
- Testcase to ensure a Topic cannot be removed if there is a datareader using it
**Must be merged after #1153 **

DDS create_datareader

---

CMakeLists.txt
src/cpp/rtps/transport/shared_mem/RobustInterprocessCondition.hpp
src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
src/cpp/rtps/transport/shared_mem/SharedMemSegment.hpp
test/communication/liveliness_assertion.360.xml
test/communication/liveliness_assertion.xml
test/unittest/transport/SharedMemTests.cpp
thirdparty/boost/include/boost/interprocess/sync/interprocess_semaphore.hpp
thirdparty/boost/include/boost/interprocess/sync/posix/semaphore.hpp
thirdparty/boost/include/boost/interprocess/sync/spin/semaphore.hpp

This PR solves several SHM issues of v1.10.0 
* POSIX condition_variables are not robust for interprocess comunication. [glibc issue](https://sourceware.org/bugzilla/show_bug.cgi?id=21422)
A robust interprocess_condition is implemented based on semaphores.
This should fix FastRTPS issue #1144 
* SHM structures alignment is bad for some platforms provoking bus exceptions accesing atomics in shared memory. Also processes running in the same host compiled for different architectures (32/64-bit) failed to communicate.
This should fix issue FastRTPS #1133
Signed-off-by: AdolfoMartinez <adolfomartinez@eprosima.com>

RobustInterprocessCondition implementation <1.10.x> [8213]

---

src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
test/unittest/transport/SharedMemTests.cpp

To merge after #1147 
This PR solves SHM transport issues when there are mutiple subscribers and one of them freezes or is super slow processing messages. This could provoke the "slow" subscriber holds all the publisher buffers leading to a cotinuous publisher's segment overflow, so all subscribers stop receiving messages.
* Changes buffer-node / buffer-data allocation structure. Now buffer-nodes are allocated (at the segment creation stage) as fixed buffer-node pool independent from the buffer-data. This way, a node never change its address.
* The node contains an atomic validity counter so all subscribers can check whether its reference to the buffer has been invalidated. The node also contains atomic status counters to know how many subscribers are processing the buffer and in how many …

SHM Buffer recovery mechanishm <1.10.x> [8220]

---

include/fastdds/rtps/RTPSDomain.h
include/fastrtps/Domain.h
src/cpp/fastrtps_deprecated/Domain.cpp
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h

Now a simple client-server discovery strategy using UDP can be specified by setting an environment variable
**ROS2_AUTO_CLIENT_SERVER** or **FASTDDS_AUTO_CLIENT_SERVER** to *IPAddress:port* where the port is optional (if not given a default one of 11311 is used). 
For example ``127.0.0.1``, ``192.168.36.34:3253`` or ``192.168.36.34`` are well formed.
If both set, Ros variable has precedence over FastDDS one.
The first participant with an interface that matches the IPAddress will try to reserve the UDP port given. If not able
to reserved it, a server presence is assumed and the participant becames a client.
If the participant attributes specifies a different mechanism from simple discovery the **ROS_AUTO_CLIENT_SERVER** and **FASTDDS_AUTO_CLIENT_SERVER** are ignored.
Note that if the …

Allow setting up a client-server environment using a ROS1 alike environment variable

---

include/dds/core/Reference.hpp
include/fastdds/dds/core/status/StatusMask.hpp

This fixes some `-Wdeprecated-copy` warnings.

Fixing gcc 9 warnings [8231]

---

src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp

This PR is related with: https://github.com/eProsima/Fast-RTPS/pull/1160
The **ROS2_AUTO_CLIENT_SERVER** or **FASTDDS_AUTO_CLIENT_SERVER** environment variables are used to specify the server address. Now:
+ the server may use the addresses 127.0.0.1 or 0.0.0.0 to listening in all local machine interfaces.
+ the client may use the addresses 127.0.0.1 or 0.0.0.0 to be indicated the server is local.
To summarize one can setup intermachine communication by first launching a server as 127.0.0.1 or 0.0.0.0.
If a client launch later:
+ shares machine with the server it suffices to use 127.0.0.1 or 0.0.0.0 to communicate.
+ is in another machine must specify the real IP address of any of the server machine interfaces.
+ shares machine with the

Solve localhost issues on default server client discovery setup via environmental variable

---

src/cpp/fastrtps_deprecated/security/authentication/PKIDH.cpp
src/cpp/fastrtps_deprecated/security/authentication/PKIIdentityHandle.h
src/cpp/fastrtps_deprecated/security/cryptography/AESGCMGMAC_KeyFactory.cpp
src/cpp/fastrtps_deprecated/security/cryptography/AESGCMGMAC_Transform.cpp
src/cpp/fastrtps_deprecated/security/cryptography/AESGCMGMAC_Transform.h
src/cpp/fastrtps_deprecated/security/cryptography/AESGCMGMAC_Types.h
src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
test/unittest/security/authentication/CMakeLists.txt
test/unittest/security/cryptography/CMakeLists.txt
test/unittest/security/cryptography/CryptographyPluginTests.hpp

This should fix #1087 for branch 1.10.x
It has all the changes on #1162 applied on 1.10.x instead of master.

Support for OpenSSL 1.1.1d <1.10.x> [8224]

---

cmake/modules/FindThirdpartyBoost.cmake
src/cpp/rtps/transport/shared_mem/RobustInterprocessCondition.hpp
thirdparty/boost/include/boost/interprocess/sync/interprocess_semaphore.hpp
thirdparty/boost/test/ThirdpartyBoostCompile_test.cpp

This should fix #1168
Signed-off-by: AdolfoMartinez <adolfomartinez@eprosima.com>

Adding default ctor to interprocess_semaphore <1.10.x> [8229]

---

test/performance/video/VideoTestPublisher.cpp
test/performance/video/VideoTestSubscriber.cpp
test/profiling/MemoryTestPublisher.cpp
test/profiling/MemoryTestSubscriber.cpp
test/profiling/allocations/AllocTestPublisher.cpp
test/profiling/allocations/AllocTestSubscriber.cpp
utils/pcTests/HelloWorldTestLiveliness/HelloWorldPublisher.cpp
utils/pcTests/HelloWorldTestLiveliness/HelloWorldSubscriber.cpp

As profiling tests are not built on CI, api breaks were missed on them.
This PR fixes that.

Fix api break on profiling tests [8243]

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp

**HelloWorldExampleDS** failed when using default **tcp** setup. Debugging led to zero a bug in Fast-RTPS library. This bug was in the mechanism devoted to assessing if a **SERVER** or **BACKUP** participant is able to open the listener portsspecified.
If an **any** locator (``0.0.0.0``) is specified the library internally replaces it for locators associated to all available interfaces.The function that returns these interfaces generates UDPv4 locators that must be  modified to match the **any** locator kind provided (in this case TCPv4).

[8255] Solving validation error when creating SERVER or BACKUP participant

---

CMakeLists.txt

We are seeing some issues with shared memory on Windows

Disable SHM as default transport on Windows <2.0.x>

---

src/cpp/fastrtps_deprecated/security/cryptography/AESGCMGMAC_Transform.cpp

This fixes #1192 by correctly using zero-initialization (i.e. `{}` instead of `{0}`)

Fix #1192 using standard zero-initialization.

---

include/fastdds/rtps/transport/test_UDPv4Transport.h
include/fastdds/rtps/transport/test_UDPv4TransportDescriptor.h
include/fastdds/rtps/writer/StatefulWriter.h
src/cpp/rtps/transport/test_UDPv4Transport.cpp
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
test/blackbox/BlackboxTestsVolatile.cpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp

This PR:
* Adds generic filtering mechanisms to the test_udpv4 transport
* Improves sending gaps for holes in history
* Fixes locator selection when re-sending samples to specific readers
* Fixes late-joining reliable volatile readers never notifying samples on some cases

Fixes and improvements on StatefulWriter <2.0.x> [8324]

---

doxyfile.in
include/fastrtps/subscriber/Subscriber.h
include/fastrtps/types/TypeObject.h

Fixed doxygen <2.0.x>

---

include/fastrtps/utils/fixed_size_bitmap.hpp
src/cpp/rtps/transport/shared_mem/SharedMemChannelResource.hpp
src/cpp/rtps/transport/shared_mem/test_SharedMemChannelResource.hpp
test/unittest/utils/BitmapRangeTests.cpp

This PR adds a unit test for `BitmapRange::remove` and fixes an error found while investigating timing issues on big data.
This method is only used when sending fragments on a reliable writer, and should only provoke errors on some corner cases related to certain fragments requiring retransmission.

Fix error on BitmapRange::remove [8354]

---

include/fastdds/rtps/writer/ReaderLocator.h
src/cpp/rtps/writer/ReaderLocator.cpp
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
test/mock/rtps/ReaderLocator/fastdds/rtps/writer/ReaderLocator.h

`StatelessWriter` is using the `RTPSParticipantImpl::guid` to decide if use the intraprocess mechanism, but it should use its own GUID.

Fixing wrong check should be intraprocess [8356]

---

src/cpp/fastdds/core/policy/ParameterSerializer.hpp

Building Fast-RTPS 2.0.x issues a warning on my system because num_properties may be unitialized. This PR sets num_properties to 0 and adds a check on valid. I wasn't sure which branch to target. Let me know if this should be targeting master instead.
Builds `--packages-up-to rclcpp`, and tests `--packages-above fastrtps --packages-up-to rclcpp`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10686)](http://ci.ros2.org/job/ci_linux/10686/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6103)](http://ci.ros2.org/job/ci_linux-aarch64/6103/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8698)](http://ci.ros2.org/job/ci_osx/8698/)
* Windows [![Build …

Initialize num_properties to 0 in ParameterSerializer.hpp

---

include/fastdds/rtps/common/CacheChange.h
include/fastdds/rtps/history/History.h
include/fastdds/rtps/history/ReaderHistory.h
include/fastdds/rtps/history/WriterHistory.h
src/cpp/rtps/history/History.cpp
src/cpp/rtps/history/ReaderHistory.cpp
src/cpp/rtps/history/WriterHistory.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/writer/PersistentWriter.cpp

This PR should alleviate #1062, #1107 and #1120 
It includes the following:
* Fixes the case when removing a change due to reception of GAP not being returned to the change pool.
* Improves the min-max calculation on ReaderHistory, so the complete history is not traversed every time a new change is added or removed
* Improves reception of fragmented data, by avoiding copies of already received fragments.

Readers fixes and improvements <2.0.x> [8375]

---

include/fastdds/rtps/common/CacheChange.h
include/fastdds/rtps/writer/StatelessWriter.h
include/fastrtps/utils/fixed_size_bitmap.hpp
src/cpp/rtps/history/WriterHistory.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
test/unittest/utils/BitmapRangeTests.cpp

This PR alleviates #1062, #1107 and #1120 with several improvements on the writers.
* Several loops reduced on fragment management, on b2b528c, 071febe and c1151a8
* Changed algorithm on `StatefulWriter::check_acked_status` from `O(n*log(n))` to `O(n)` on 4340614
* Removed loop on `StatelessWriter::try_remove_change` on adcce30
* Implicit flow controller added to both writers on 3f7fef2 and efb08fc

Writer improvements <2.0.x> [8382]

---

test/performance/throughput/CMakeLists.txt

Since this issue is still open, and the test is failling constantly. I propose to disable it, and open a PR to re-enable it when the issue is corrected.

Disable TCP Throughput test <2.0.x> [7439]

---

examples/C++/Keys/keys.cpp
include/fastdds/dds/publisher/DataWriter.hpp
include/fastdds/rtps/common/CacheChange.h
include/fastdds/rtps/common/InstanceHandle.h
include/fastdds/rtps/writer/RTPSWriter.h
include/fastdds/rtps/writer/StatefulWriter.h
include/fastdds/rtps/writer/StatelessWriter.h
include/fastrtps/publisher/Publisher.h
include/fastrtps/publisher/PublisherHistory.h
src/cpp/fastdds/publisher/DataWriter.cpp
src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/publisher/DataWriterImpl.hpp
src/cpp/fastrtps_deprecated/publisher/Publisher.cpp
src/cpp/fastrtps_deprecated/publisher/PublisherHistory.cpp
src/cpp/fastrtps_deprecated/publisher/PublisherImpl.cpp
src/cpp/fastrtps_deprecated/publisher/PublisherImpl.h
src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
test/blackbox/BlackboxTestsDeadlineQos.cpp
test/blackbox/BlackboxTestsKeys.cpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
test/blackbox/utils/data_generators.cpp

Implementation of `unregister_instance()` and `dispose()` on Writer side.
* `unregister_instance()`: sends a `CacheChange_t` with `NOT_ALIVE_UNREGISTER`. When this `CacheChange_t` is acked by all, removes all samples of this instance from `PublisherHistory`.
* `dispose()`: sends a `CacheChange_t` with `NOT_ALIVE_DISPOSE`.
Also now `PublisherHistory::find_key()` cannot remove a instance slot.

Unregister/Dispose instances on Writer side [8437]

---

include/fastrtps/xmlparser/XMLProfileManager.h
src/cpp/rtps/xmlparser/XMLParser.cpp
src/cpp/rtps/xmlparser/XMLProfileManager.cpp
test/unittest/xmlparser/XMLProfileParserTests.cpp

This PR adds different error codes when extracting profiles from an XML file
* All profiles were successfully extracted --> `XMLP_ret::XML_OK`
* Only some profiles were successfully extracted --> `XMLP_ret::XML_NOK`
* No profile was successfully extracted --> `XMLP_ret::XML_ERROR`
This is of special importance since this error propagates up to the user when calling `XMLProfileManager::loadXMLFile`

Different return codes when extracting profile

---

examples/C++/DDS/DynamicHelloWorldExample/CMakeLists.txt
examples/C++/DDS/SecureHelloWorldExample/CMakeLists.txt
examples/C++/DDS/StaticHelloWorldExample/CMakeLists.txt
examples/C++/DDS/TypeLookupService/CMakeLists.txt
examples/C++/DDS/TypeLookupService/TypeLookupPublisher.cpp
examples/C++/SecureHelloWorldExample/CMakeLists.txt
examples/C++/StaticHelloWorldExample/CMakeLists.txt
examples/C++/XMLProfiles/CMakeLists.txt

- Fix segfault in DDSTypeLookupService when no XML file is found.
- Install examples XML and certs files.

Fix examples files installation <2.0.x> [8566]

---

examples/C++/DDS/Configurability/UseCasePublisher.cpp
examples/C++/DDS/Configurability/UseCaseSubscriber.cpp

The value for `max_samples_per_key` was not correctly set when the number of instances was set to 1.
Skipping tests, as examples are not checked by CI.

Fixing DDS Use case example [8567]

---

src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.hpp
src/cpp/fastdds/subscriber/SubscriberImpl.cpp
test/blackbox/CMakeLists.txt
test/blackbox/api/dds-pim/PubSubParticipant.hpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp
test/blackbox/common/DDSBlackboxTestsDataReader.cpp

It was detected that when no listener is set to a DataReader, `xxx_count_change` fields of `LivelinessChangedStatus` where always being read as 0.
A Blackbox test is added to reproduce the problem.
DataReaderImpl now has a copy of its `LivelinessChangedStatus` independent of the one in RTPSReader.
Status mask is checked before calling `on_liveliness_changed`.

Fixed behavior of get_liveliness_changed_status [8812]

---

src/cpp/rtps/messages/MessageReceiver.cpp

```
/home/johnny/ACE/src/fastrtps/src/cpp/rtps/messages/MessageReceiver.cpp:745:14: note: ‘fragmentSize’ was declared here
745 |     uint16_t fragmentSize;
|              ^~~~~~~~~~~~
/home/johnny/ACE/src/fastrtps/src/cpp/rtps/messages/MessageReceiver.cpp:842:39: warning: ‘fragmentsInSubmessage’ may be used uninitialized in this function [-Wmaybe-uninitialized]
842 |             reader->processDataFragMsg(&ch, sampleSize, fragmentStartingNum, fragmentsInSubmessage);
|             ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/johnny/ACE/src/fastrtps/src/cpp/rtps/messages/MessageReceiver.cpp:760:18: warning: ‘octetsToInlineQos’ may be used uninitialized in this function [-Wmaybe-uninitialized]
760 |         msg->pos += (octetsToInlineQos - …
```

Fixed maybe be used unitialized warnings

---

src/cpp/rtps/transport/shared_mem/RobustExclusiveLock.hpp
src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
src/cpp/rtps/transport/shared_mem/SharedMemSegment.hpp
src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
src/cpp/rtps/transport/shared_mem/SharedMemWatchdog.hpp
test/unittest/transport/SharedMemTests.cpp

When a SHM listener receives a message from an origin, the origin SHM segment is opened to read the message. The segment is kept open in order to read next messages from the same origin. But when the origin is closed the segment is not closed by the listener so the memory is not freed.
This PR adds the following feature:
* Remote SHM segments are watched by the SharedMemWatchdog to be closed when the origin segment has been closed or is in zombie state.

 Garbage collect remote SHM segments when origin Participant is closed / dead <master> [8607]

---

src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp

When a reader receives data, the liveliness of the corresponding writer was only being asserted for the `MANUAL_BY_TOPIC` case.

Correctly asserting liveliness on data reception [8820]

---

include/fastdds/rtps/writer/ReaderProxy.h
include/fastdds/rtps/writer/StatefulWriter.h
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
test/blackbox/RTPSBlackboxTestsBasic.cpp
test/blackbox/RTPSWithRegistrationWriter.hpp
test/mock/rtps/RTPSGapBuilder/rtps/messages/RTPSGapBuilder.hpp
test/unittest/rtps/writer/CMakeLists.txt

After the optimizations on #1190, when a reliable writer with holes in its history matches with a reliable reader, there were some cases where GAP messages were not being sent. 
This was particularly problematic with the builtin endpoints used for discovery, and is related with ros-planning/navigation2#1772, ros-planning/navigation2#1788, ros2/ros2#931 and ros2/rmw_fastrtps#932

Fix sending GAPs to late joiners [8880]

---

src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp

Correctly asserting liveliness on data reception <2.0.x> [8893]

---

include/fastdds/dds/core/policy/ParameterTypes.hpp
include/fastdds/dds/core/policy/QosPolicies.hpp
include/fastdds/rtps/common/CacheChange.h
include/fastdds/rtps/common/SequenceNumber.h
include/fastdds/rtps/messages/CDRMessage.hpp
include/fastrtps/types/AnnotationParameterValue.h
include/fastrtps/utils/collections/ResourceLimitedVector.hpp
include/fastrtps/utils/fixed_size_bitmap.hpp
src/cpp/dynamic-types/DynamicTypeBuilderFactory.cpp
src/cpp/fastdds/core/policy/ParameterSerializer.hpp
src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp
test/mock/dds/QosPolicies/fastdds/dds/core/policy/QosPolicies.hpp

There are a number of warning when I compile [performance_test](http://build.ros2.org/view/Fci/job/Fci__nightly-performance_ubuntu_focal_amd64/66/gcc/)
Most of them are related to `uint32_t` which this type corresponds with the literal `u` and not `ul`
Signed-off-by: ahcorde <ahcorde@gmail.com>

fixed warnings [8886]

---

src/cpp/CMakeLists.txt
src/cpp/rtps/security/SecurityManager.cpp
src/cpp/security/OpenSSLInit.hpp
test/unittest/rtps/network/CMakeLists.txt
test/unittest/rtps/security/CMakeLists.txt
test/unittest/security/authentication/AuthenticationPluginTests.hpp
test/unittest/security/authentication/CMakeLists.txt
test/unittest/security/cryptography/CMakeLists.txt
test/unittest/security/cryptography/builtinAESGCMGMACTests.cpp
test/unittest/transport/CMakeLists.txt

This PR avoids exporting the "openss_init" symbol in *nix systems.

Refs #8913 Avoid exporting "openssl_init". [8917]

---

src/cpp/CMakeLists.txt
src/cpp/rtps/security/SecurityManager.cpp
src/cpp/security/OpenSSLInit.hpp
test/unittest/rtps/network/CMakeLists.txt
test/unittest/rtps/security/CMakeLists.txt
test/unittest/security/authentication/AuthenticationPluginTests.hpp
test/unittest/security/authentication/CMakeLists.txt
test/unittest/security/cryptography/CMakeLists.txt
test/unittest/security/cryptography/builtinAESGCMGMACTests.cpp
test/unittest/transport/CMakeLists.txt

This is a backport of #1305 to 2.0.x:
* Refs #8913 Avoid exporting "openssl_init".
* Uncrustify
* Fixing not found header in Mac/Windows.

Avoid exporting "openssl_init"

---

include/fastdds/rtps/common/Guid.h
include/fastdds/rtps/common/Property.h
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
test/blackbox/CMakeLists.txt
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/common/DDSBlackboxTestsPersistenceGuid.cpp
test/blackbox/common/RTPSBlackboxTestsPersistenceGuid.cpp
test/blackbox/common/RTPSWithRegistrationReader.hpp
test/blackbox/common/RTPSWithRegistrationWriter.hpp
test/blackbox/persistence.xml
test/blackbox/utils/check_guid.py

This is a Work In Progress PR, do not merge until tests are added.
Adds a property `dds.persistence.guid` which value is a string representing a `GUID_t`, where the octets are dot-separated, and a `|` is used to mark the separation between guid prefix and entity id.

Persistence guid property [8858]

---

src/cpp/fastdds/core/policy/ParameterSerializer.hpp
src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/publisher/DataWriterImpl.hpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/common/BlackboxTests.hpp
test/blackbox/common/DDSBlackboxTestsPersistence.cpp
test/blackbox/utils/data_generators.cpp
test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
test/mock/rtps/WriterHistory/fastdds/rtps/history/WriterHistory.h

**Do not merge until #1291 is merged.**
This pull request supports the transmission of large data in cases of persistent DataWriter. When a persistent DataWriter is closed and restored, the history changes saved in the writer's database are restored to the writer's history along with the corresponding fragment size. This way, if the data is larger than the DataWriter transport sending socket, the fragment size is set.
This pull request also adds various Blackbox tests for the verification of the implemented functionality.

Support large data in persistence [8890]

---

src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
test/blackbox/common/BlackboxTestsPubSubFragments.cpp
test/blackbox/common/BlackboxTestsPubSubHistory.cpp
test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h

* New large data volatile blackbox tests
* New large data transient local blackbox tests
* New blackbox tests to check #8896 bug (Transient Local, Reliable, Keep Last 1)
* Change the Subscriber History condition to check if the History is Full (Fix for the #8896 bug)

Fix for late-joiners KEEP_LAST, RELIABLE, TRANSIENT_LOCAL [8986]

---

include/fastdds/rtps/messages/MessageReceiver.h
include/fastdds/rtps/writer/RTPSWriter.h
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/rtps/messages/RTPSMessageGroup.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp
src/cpp/rtps/writer/RTPSWriter.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
test/blackbox/api/dds-pim/PubSubWriterReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubWriterReader.hpp
test/blackbox/common/BlackboxTestsSecurity.cpp

This PR makes the payload protection behavior consistent on all cases.
Before this PR, encoding was performed on different places depending on fragmentation:
* Fragmented data was protected by code on `RTPSMessageGroup`
* Non-fragmented data was protected by code on `RTPSWriter`
Decoding was always done by code on descendants of `RTPSReader`
This produced a bug when using payload protection between endpoints on the same participant for big data types.
This PR leaves the responsibility of encoding to `RTPSMessageGroup`, and the decoding to `MessageReceiver`, both on the messages module.

Perform payload protection on messages module. [8973]

---

src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
test/blackbox/BlackboxTestsPubSubFragments.cpp
test/blackbox/BlackboxTestsPubSubHistory.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h

This is a backport of #1314 to 2.0.x
Signed-off-by: Laura Martin <laura@eprosima.com>

Fix for late-joiners KEEP_LAST, RELIABLE, TRANSIENT_LOCAL <2.0.x> [9015]

---

include/fastrtps/qos/ParameterTypes.h
include/fastrtps/rtps/builtin/data/ParticipantProxyData.h
include/fastrtps/rtps/builtin/data/ReaderProxyData.h
include/fastrtps/rtps/builtin/data/WriterProxyData.h
include/fastrtps/rtps/builtin/discovery/endpoint/EDPServer.h
include/fastrtps/rtps/builtin/discovery/endpoint/EDPSimple.h
include/fastrtps/rtps/builtin/discovery/endpoint/EDPStatic.h
include/fastrtps/rtps/builtin/discovery/participant/PDPServer.h
include/fastrtps/rtps/common/Guid.h
include/fastrtps/rtps/common/SampleIdentity.h
include/fastrtps/rtps/common/SequenceNumber.h
include/fastrtps/rtps/resources/AsyncWriterThread.h
include/fastrtps/transport/TCPv4TransportDescriptor.h
src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
src/cpp/rtps/builtin/data/ReaderProxyData.cpp
src/cpp/rtps/builtin/data/WriterProxyData.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.h
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
src/cpp/rtps/builtin/discovery/participant/timedevent/DServerEvent.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/writer/PersistentWriter.cpp
test/mock/rtps/TCPv4TransportDescriptor/fastrtps/transport/TCPv4TransportDescriptor.h
utils/doxygen/complete_doxyfile_api

Includes the commits:
- Repairing client-server BACKUP operation (#1091)
- Server-Client trimming form discovery info update (#1102)
- Updating from microseconds to milliseconds the pdp stateful writer events. (#995)

OSRF testing patches

---

cmake/common/check_configuration.cmake
cmake/modules/FindThirdpartyBoost.cmake

Fixes #1308 
adds compiler id for QNX when checking for compiler configuration
Fixes #1309 
prevents linking against librt when cross compiling for QNX

adds compiler id and removes librt for QNX

---

include/fastdds/rtps/common/SerializedPayload.h
src/cpp/fastdds/core/policy/ParameterSerializer.hpp

This prevents memcheck complaining about uninitialized memory access
if the serialization skips writing some bytes due to memory alignment.

Refs 9117. Initialize serialized payload buffer on realloc

---

test/blackbox/common/BlackboxTestsSecurity.cpp

Test BuiltinAuthenticationAndCryptoPlugin_payload_ok_same_participant_300kb was failing form time to time due to a sample not being received.
The writer was created with default history QoS (keep_last, 1), and sometimes the sample was overwritten before being completely sent. 
This PR fixes this by increasing the writer's history depth.

Increased writer depth on flaky test [9188]

---

src/cpp/fastrtps_deprecated/participant/ParticipantImpl.cpp

Return `false` if the type is not registered.
This is in line with the registration, that returns `false` if the type is already registered.

Return false if type not found unregistering type [9182]

---

src/cpp/rtps/transport/shared_mem/RobustExclusiveLock.hpp
src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
src/cpp/rtps/transport/shared_mem/SharedMemSegment.hpp
src/cpp/rtps/transport/shared_mem/SharedMemTransport.cpp
src/cpp/rtps/transport/shared_mem/SharedMemTransport.h
src/cpp/rtps/transport/shared_mem/SharedMemWatchdog.hpp
test/unittest/transport/SharedMemTests.cpp

Garbage collect remote SHM segments when origin Participant is closed… > 2.0.x [9029]

---

include/fastdds/rtps/common/SerializedPayload.h
src/cpp/fastrtps_deprecated/participant/ParticipantImpl.cpp

This is a backport of #1355 and #1348 to 2.0.x.
Resolves #1346

Memcheck errors on RMW [9206]

---

test/CMakeLists.txt

During the review of #1326, which is a backport of #1252, it was detected that the tests for the new CLI tool were dependant on `PERFORMANCE_TESTS` option, and a new `SYSTEM_TESTS` option was added.
This PR is a port of that part to master.

Add SYSTEM_TESTS cmake option [9210]

---

cmake/common/check_configuration.cmake
configure.ac
include/fastdds/rtps/common/CDRMessage_t.h
include/fastdds/rtps/common/EntityId_t.hpp
include/fastdds/rtps/common/SerializedPayload.h
include/fastdds/rtps/common/Types.h
include/fastdds/rtps/messages/CDRMessage.hpp
include/fastrtps/config.h.in
src/cpp/fastdds/builtin/typelookup/TypeLookupManager.cpp
src/cpp/fastdds/core/policy/ParameterList.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/liveliness/WLP.cpp
src/cpp/rtps/messages/RTPSMessageCreator.cpp
src/cpp/rtps/messages/submessages/AckNackMsg.hpp
src/cpp/rtps/messages/submessages/DataMsg.hpp
src/cpp/rtps/messages/submessages/GapMsg.hpp
src/cpp/rtps/messages/submessages/HeartbeatMsg.hpp
src/cpp/rtps/security/SecurityManager.cpp
src/cpp/security/cryptography/AESGCMGMAC_Transform.cpp
src/cpp/utils/IPLocator.cpp
test/profiling/main_MemoryTest.cpp
test/unittest/rtps/security/SecurityHandshakeProcessTests.cpp
test/unittest/rtps/security/SecurityTests.cpp

This PR substitutes the definition we were making of `__BIG_ENDIAN__` for `FASTDDS_IS_BIG_ENDIAN_TARGET`. This way, we avoid using compiler reserved notation, and also defining a macro that some other libraries like boost do not expect to have defined when the machine is little endian. Furthermore, it updates the Fast CDR submodule to the [v1.0.15 release](https://github.com/eProsima/Fast-CDR/releases/tag/v1.0.15).
This PR solves #1001

Endianness macro [9189]

---

src/cpp/rtps/transport/shared_mem/SharedMemSegment.hpp
src/cpp/utils/collections/node_size_helpers.hpp

Solving warnings and errors related with VS2015 v140 toolset faulty support to C++ 11 constexpr functions.

[9180] Solving VS2015 errors and warnings on sources

---

src/cpp/rtps/reader/WriterProxy.cpp

This solves sporadic segfaults on intraprocess when destroying a reader.
Solves [9270]

WriterProxy auto unmatch on destruction [9272]

---

src/cpp/rtps/writer/StatefulWriter.cpp
test/blackbox/BlackboxTestsPubSubHistory.cpp

This is a backport of #1324 to 2.0.x

Fix Writer history behavior when there are no matched readers <2.0.x> [9031]

---

include/fastdds/rtps/messages/CDRMessage.hpp

This should fix #1337 and fix #1338 
Parsing methods for sets of fragment and sequence numbers have been protected against an invalid number of bits on the bitmap.

Protect bitmap parsing methods <master> [9183]

---

include/fastdds/dds/core/policy/ParameterTypes.hpp
include/fastdds/rtps/builtin/data/ParticipantProxyData.h
include/fastdds/rtps/builtin/data/ReaderProxyData.h
include/fastdds/rtps/builtin/data/WriterProxyData.h
include/fastdds/rtps/builtin/discovery/endpoint/EDPServer.h
include/fastdds/rtps/builtin/discovery/endpoint/EDPSimple.h
include/fastdds/rtps/builtin/discovery/participant/PDPServer.h
include/fastdds/rtps/common/Guid.h
include/fastdds/rtps/common/SampleIdentity.h
include/fastdds/rtps/common/SequenceNumber.h
src/cpp/CMakeLists.txt
src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
src/cpp/rtps/builtin/data/ReaderProxyData.cpp
src/cpp/rtps/builtin/data/WriterProxyData.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/writer/StatefulWriter.cpp

This is a backport from master to solve a client-server discovery issue.
When a client was dropped the server reported it to all other clients but didn't remove the demise client information from the PDP and EDP history. This commit fixes this issue.

[8632] Solving discover server issues on participant drop.

---

src/cpp/rtps/builtin/data/ReaderProxyData.cpp
src/cpp/rtps/builtin/data/WriterProxyData.cpp

When receiving EDP information of writers and readers, their participant key can be directly obtained from PID_ENDPOINT_GUID.
This PR ignores PID_PARTICIPANT_GUID on them.
Related to #1380 

Handle missing PID_PARTICIPANT_GUID for readers and writers [9296]

---

src/cpp/CMakeLists.txt

Fixes https://github.com/eProsima/Fast-DDS/issues/1385 caused by #1267
CI Windows building and testing only fastrtps [![Build Status](https://ci.ros2.org/job/ci_windows/12170/badge/icon)](https://ci.ros2.org/job/ci_windows/12170/)

Fix broken Windows build: Use bare ${TINYXML2_LIBRARY}

---

include/fastdds/dds/subscriber/DataReader.hpp

Standard defined method `DataReader::get_topicdescription` was not being exported. This was resulting in linking errors in some platforms, i.e. #1344 

Export DataReader::get_topicdescription

---

examples/C++/DDS/HistoryKind/pastsamples.cpp

Changed reader's durability to transient local to prevent the time it took to match to the writer to influence the behavior of the example.

Changed durability to transient local [9170]

---

examples/C++/Keys/keys.cpp

This PR increases the Keys example (located on `examples/C++/Keys`). Now, at the end of the example, the writer disposes all keys and the reader waits until the dispose samples arrive.

Increase Keys example with disposing functionality [9205]

---

include/fastdds/rtps/builtin/discovery/DiscoveryDataBase.hpp
include/fastdds/rtps/builtin/discovery/DiscoveryDataFilter.hpp
include/fastdds/rtps/writer/IReaderDataFilter.hpp
include/fastdds/rtps/writer/ReaderProxy.h
include/fastdds/rtps/writer/StatefulWriter.h
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
test/mock/rtps/StatefulWriter/fastdds/rtps/writer/StatefulWriter.h

This PR:
1. Adds `IReaderDataFilter` virtual class for Reader proxies to query whether a change is relevant for them.
1. Adds a member `reader_data_filter_` to `StatefulWriter`. This also includes a setter and a getter.
1. Adds discovery data filter interfaces for PDP, EDP publications, and EDP subscriptions.
1. Adds a `DiscoveryDataBase` which implements the interfaces for PDP, EDP publications, and EDP subscriptions.
This way, each discovery writer query the discovery database for a specific change using its specialized filter. The Database will tell the filter whether a change is relevant for a given reader. This way the writer can avoid sending irrelevant messages to certain readers.

Discovery Data Filter

---

Public_API_foonathan_memory.md

Document stating the `foonathan_memory` API used in *eprosima Fast DDS* project

Add foonathan public API document [9395]

---

cmake/modules/FindThirdpartyBoost.cmake

Clang automatically links again atomic (if the gcc runtime toolchain is not used) and does not need to be added. I assume that most likely this passed the OSX CI given that the compiler id with a stock clang on OSX is actually rebranded to `AppleClang` and thus doesn't match the expression.
see https://bcain-llvm.readthedocs.io/projects/clang/en/latest/Toolchain/#atomics-library for more information.

remove latomic to clang

---

src/cpp/rtps/xmlparser/XMLProfileManager.cpp

Unit test failed on Windows and was inadvertently ignored on the review #1350

Fixed SKIP_DEFAULT_XML_FILE on Windows.

---

src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.cpp

The subcriptions writer must have separate sending enable for the DS 2.0 to work properly.

Fix enable separate sending in subscriptions writer [9477]

---

src/cpp/security/cryptography/AESGCMGMAC_Transform.cpp
src/cpp/security/cryptography/AESGCMGMAC_Transform.h

Previous implementation made CryptographyPluginTest.transform_preprocess_secure_submessage to have flaky behavior when key_id is zero. In this particular case, the method AESGCMGMAC_Transform::preprocess_secure_submessage instead of looking for a match through the local endpoints, the method looked only through the remote endpoints. This particular case is needed only during discovery.
The method has been updated to first look through the local endpoints (in case it is an user message) and, if there is no matching endpoint found, look in the remote endpoints for a match if the key_id is zero (in case it is a discovery message). 

Bugfix: preprocess_secure_submsg should look both local and remote endpoints [9465]

---

test/blackbox/common/RTPSWithRegistrationReader.hpp

Test `BlackboxTests_RTPS.RTPS.RTPSAsReliableWithRegistrationAndHolesInHistory.Intraprocess` was failing sporadically with an infinite loop. This PR solves a possible race when using late joiners on RTPS blackbox tests.

Fixed RTPSWithRegistrationReader

---

src/cpp/rtps/writer/ReaderLocator.cpp
src/cpp/rtps/writer/StatefulWriter.cpp

This is a port of #1444 from 2.0.x to master
Some improvements on StatefulWriter:
- Avoid trying to send a heartbeat if no reader is matched.
Although quite harmless, this may cause an ERROR log with security because the writer is unable to encrypt the message if there are no matched readers.
-  Avoid sending traffic to newly matched intraprocess reader.

Improvements on StatefulWriter <master>

---

src/cpp/subscriber/SubscriberHistory.cpp
test/blackbox/BlackboxTestsPubSubFragments.cpp
test/blackbox/BlackboxTestsPubSubHistory.cpp
test/blackbox/PubSubReader.hpp
test/mock/rtps/ReaderHistory/fastrtps/rtps/history/ReaderHistory.h

This is #1314 to `ros2_eloquent`
* Large data volatile tests
* Large data transient local tests
* Tests to check #8896 bug (Transient Local, Reliable, Keep Last 1)
Signed-off-by: Laura Martin <laura@eprosima.com>

Fix for late-joiners KEEP_LAST, RELIABLE, TRANSIENT_LOCAL <ros2_eloquent> [9016]

---

src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp

When an acknowledgement is notified to the database, check if the change has not been updated before marking it as acknowledge.
Marked as `no-test` until #1439 is merged

Server DDB: Check sample id on ack [9496]

---

src/cpp/rtps/writer/StatefulWriter.cpp
test/blackbox/BlackboxTestsPubSubHistory.cpp

This is a backport of #1324 to ros2_eloquent

Fix Writer history behavior when there are no matched readers <ros2_eloquent> [9032]

---

src/cpp/rtps/writer/StatefulWriter.cpp
test/blackbox/BlackboxTestsPubSubHistory.cpp

This is a backport of #1324 to 1.8.x

Fix Writer history behavior when there are no matched readers <1.8.x> [9033]

---

src/cpp/utils/collections/node_size_helpers.hpp

This PR takes into account foonathan/memory#89, avoiding the use of constants inside the `detail` namespace.

Account for new API on foonathan_memory [9534]

---

examples/C++/DDS/Configurability/UseCasePublisher.cpp
examples/C++/DDS/Configurability/UseCaseSubscriber.cpp
src/cpp/rtps/writer/ReaderLocator.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
test/unittest/transport/SharedMemTests.cpp

Some improvements on StatefulWriter:
* Avoid trying to send a heartbeat if no reader is matched.
Although quite harmless, this may cause an ERROR log with security because the writer is unable to encrypt the message if there are no matched readers.
* Avoid sending traffic to newly matched intraprocess reader.

Improvements on StatefulWriter

---

include/fastdds/rtps/messages/MessageReceiver.h
src/cpp/rtps/messages/MessageReceiver.cpp

This corrects a bug added on PR #1312 , where the first reader of the participant was always used to decode the encrypted message, even though that reader may not be matched to the sending writer, and thus, would not be able to decrypt it.

Do not relay on first reader only to decode encrypted message [9502]

---

include/fastdds/rtps/network/NetworkFactory.h
src/cpp/rtps/network/NetworkFactory.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp

When the user sets a multicast address to a DataReader, without specifying the port, the user multicast port is calculated wrongly.
This PR fixes this.

Fix wrong calculation of user multicast port [9599]

---

src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp

The removing of Data in a History was compared by the guid, but not by the instance Handle.
Different minor fixes.

[Discovery Server] Remove change in History comparing instance handle

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
test/blackbox/common/DDSBlackboxTestsPersistenceGuid.cpp

This PR adds a Participant's property `"dds.persistence.also-support-transient-local"`. When this property is set to `"true"`, TRANSIENT_LOCAL endpoints could use persistence database.

Add option to support TRANSIENT_LOCAL in persistence [9617]

---

src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp

New state disable for DiscoveryDataBase
New clear function, and clear method in PDPServer2 destruction.

[Discovery Server] Clear Database only one server version [9598]

---

include/fastdds/dds/core/policy/ParameterTypes.hpp
include/fastdds/rtps/builtin/data/ParticipantProxyData.h
include/fastdds/rtps/builtin/data/ReaderProxyData.h
include/fastdds/rtps/builtin/data/WriterProxyData.h
include/fastdds/rtps/builtin/discovery/endpoint/EDPServer.h
include/fastdds/rtps/builtin/discovery/endpoint/EDPSimple.h
include/fastdds/rtps/builtin/discovery/participant/PDPServer.h
include/fastdds/rtps/common/SampleIdentity.h
include/fastdds/rtps/common/SequenceNumber.h
src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
src/cpp/rtps/builtin/data/ReaderProxyData.cpp
src/cpp/rtps/builtin/data/WriterProxyData.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServer.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/writer/StatefulWriter.cpp

It's a port of #1241. Solves different issues:
- On client drop the trimming wasn’t working properly (test).
- Several synchronization issues were solved.
- Server announcement sample selection failed sometimes.
- #1295 partially port to solve GAP issues particular to foxy.
- On **BACKUP** servers:
- Deserialization required trim orphan samples.
- Deserialized samples were not given lease duration management.
- Sample origin was not persistent, allowing duplicate history entries.
- SQLite3 database transaction failures were not handled.

[8709] Porting ros2 eloquent updates to master

---

configure.ac

The `master` branch has long ago diverged from `2.0.x`, so the time has come for a version bump.

Bump version 2.1.0

---

include/fastrtps/utils/collections/foonathan_memory_helpers.hpp

An unused part of the public API was missing the modifications to be compatible with the new [foonathan_memory](https://github.com/foonathan/memory) API.

Forwardport of #1469 into master [9574]

---

src/cpp/security/accesscontrol/AccessPermissionsHandle.h
src/cpp/security/accesscontrol/Permissions.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
test/blackbox/common/BlackboxTestsSecurity.cpp
test/certs/governance_rule_order_test.smime
test/certs/governance_rule_order_test.xml
test/certs/governance_rule_order_test_inverse.smime
test/certs/governance_rule_order_test_inverse.xml

According to the standard, governance rules must be evaluated in order, and the first matching rule is applied.
We are using a map to store the rules before applying them, therefore, losing the original order.
Besides, the map object is never searched by key.
Changed the map for a vector.

governance rules order <master> [9583]

---

resources/xsd/fastRTPS_profiles.xsd

This PR allows validating XML files following the schema:
```xml
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles" >
<profiles>
<participant profile_name="Participant">
...
</participant>
<publisher profile_name="Pub1">
...
</publisher>
<subscriber profile_name="Sub1">
...
</subscriber>
<publisher profile_name="Pub2">
...
</publisher>
<subscriber profile_name="Sub2">
...
</subscriber>
</profiles>
</dds>
```
Without the `<xs::choice>` the schema doesn't allow defining a `<publisher>` after a `<subscriber>`.

Fixes profile section to allow multiple profiles in different order.

---

src/cpp/rtps/security/SecurityManager.cpp
src/cpp/rtps/security/SecurityManager.h
test/blackbox/BlackboxTestsSecurity.cpp
test/blackbox/api/dds-pim/PubSubParticipant.hpp
test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp

`VolatileSecureMessage`s received for local endpoints that still didn't discover the remote endpoint are stored to be processed when the local endpoint discovers the remote one. The `SecurityManager` keeps them on a map keyed by the remote endpoint GUID.
But if the remote endpoint matches with multiple local endpoints, multiple `VolatileSecureMessage` will be received, one per match. However, all of them share the same origin GUID, so only a single copy will be stored on the map. Once the first local endpoint discovers the remote and completes the security processing, it will remove the message from the map of pendings, leaving the rest of the local endpoints without the required information to complete the matching.
Instead of using the remote GUID as key, we should be using the …

Keep pending security messages directed for each local endpoint [9621]

---

test/unittest/transport/SharedMemTests.cpp

Test `SHMTransportTests.memory_bounds` was failing consistently on Windows 32 bits.
It seems there is a limit of 2GB per-process on the total allowed space of shared mem on that platform.
This PR makes the test aware of this limitation and refactors the test to improve its readability.

Fixes and improvements on SHMTransportTests.memory_bounds [9673]

---

src/cpp/security/accesscontrol/AccessPermissionsHandle.h
src/cpp/security/accesscontrol/Permissions.cpp
test/blackbox/BlackboxTestsSecurity.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
test/certs/governance_rule_order_test.smime
test/certs/governance_rule_order_test.xml
test/certs/governance_rule_order_test_inverse.smime
test/certs/governance_rule_order_test_inverse.xml

This is a port of #1474 to 2.0.x
According to the standard, governance rules must be evaluated in order, and the first matching rule is applied.
We are using a map to store the rules before applying them, therefore, losing the original order.
Besides, the map object is never searched by key.
Changed the map for a vector.

governance rules order <2.0.x> [9584]

---

cmake/modules/CheckLibatomic.cmake
src/cpp/CMakeLists.txt

Similar to the implementation of CheckAtomic.cmake from LLVM.
Signed-off-by: Pablo Bleyer <pablo@bleyer.org>

Add module and option to detect and enable linking with -latomic in environments that need it (#1495)

---

PLATFORM_SUPPORT.md
Public_API_foonathan_memory.md
QUALITY.md
Quality_Declaration_foonathan_memory.md
README.md

This backports all pull requests related to the Quality Declaration to <2.0.x>:
* Platform support #1397 
* Foonathan's API #1403 
* Update CI badges in README #1405 
* Foonathan memory Quality Declaration #1404 
* Fast DDS Quality Declaration #1400 
* Fixed broken link to Fast CDR Quality Declaration #1443

Backport Quality Declaration to <2.0.x> [9723]

---

CMakeLists.txt

There have been several improvements and fixes on the Shared Memory transport, like #1329 and #1330, that made it more robust.
This PR adds this transport to the default ones.

Include Shared Memory in the default transports. <2.0.x> [9726]

---

include/fastdds/rtps/transport/UDPTransportInterface.h
include/fastdds/rtps/transport/UDPv4Transport.h
include/fastdds/rtps/transport/UDPv6Transport.h
include/fastdds/rtps/transport/test_UDPv4Transport.h
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/transport/UDPTransportInterface.cpp
src/cpp/rtps/transport/UDPv4Transport.cpp
src/cpp/rtps/transport/UDPv6Transport.cpp
src/cpp/rtps/transport/test_UDPv4Transport.cpp
test/blackbox/BlackboxTestsDiscovery.cpp
test/blackbox/api/dds-pim/PubSubWriterReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubWriterReader.hpp

This should fix the issue reported on ros2/ros2#1052
Multicast was not correctly being sent through localhost interface when no network interface was detected. This PR changes the mechanism from adding a localhost initial peer to binding the outbound socket to the local interface.

Fix communications with localhost only <2.0.x> [9744]

---

include/fastdds/rtps/attributes/ServerAttributes.h
include/fastdds/rtps/history/ReaderHistory.h
include/fastdds/rtps/history/WriterHistory.h

`RemoteServerAttributes` and other *Discovery-Server* classes were promoted to the **fastdds** namespace without keeping a reference for them in the deprecated **fastrtps** namespace.

[Discovery Server] Preserve RTPS API compatibility in Discovery-Server v2.0

---

test/unittest/logging/LogTests.cpp

`std::string::difference_type` is of type `std::ptrdiff_t` which is the signed integer type of the result of subtracting two pointers.

Fix warning: change unsigned for signed comparison

---

src/cpp/rtps/history/TopicPayloadPoolRegistry.cpp
test/mock/rtps/TopicPayloadPoolProxy/rtps/history/TopicPayloadPoolRegistry_impl/TopicPayloadPoolProxy.hpp
test/unittest/rtps/history/CMakeLists.txt
test/unittest/rtps/history/TopicPayloadPoolRegistryTests.cpp

TopicPayloadPoolRegistryTests were incorrectly checking that allocating new pools after releasing was giving different pointers. This PR changes the order of the second creation, to force the system allocators giving different pointers.

Fixed TopicPayloadPoolRegistryTests [9801]

---

include/fastdds/rtps/history/IPayloadPool.h
src/cpp/rtps/history/BasicPayloadPool.hpp
src/cpp/rtps/history/BasicPayloadPool_impl/Preallocated.hpp
src/cpp/rtps/history/BasicPayloadPool_impl/PreallocatedWithRealloc.hpp
src/cpp/rtps/history/TopicPayloadPool.cpp
src/cpp/rtps/history/TopicPayloadPool.hpp
src/cpp/rtps/history/TopicPayloadPool_impl/Dynamic.hpp
src/cpp/rtps/history/TopicPayloadPool_impl/DynamicReusable.hpp
src/cpp/rtps/history/TopicPayloadPool_impl/Preallocated.hpp
src/cpp/rtps/history/TopicPayloadPool_impl/PreallocatedWithRealloc.hpp
test/unittest/rtps/history/TopicPayloadPoolTests.cpp

Valgrind detected [errors](http://jenkins.eprosima.com:8080/view/Nightly%20Fast%20DDS/job/nightly_fastdds_sec_master_linux/483/valgrindResult/pid=38327,0x0/) on the unit tests for TopicPayloadPool.
It was found that the constructor of `PayloadNode` was accessing the `data[1]` field. In the case where a payload of size 0 is requested, that part of the memory has not been allocated

Force size greater than 0 when getting payloads [9799]

---

package.xml

Building this package with ROS fails.
Error message:
```
Error(s) in package '/ros2_foxy/src/eProsima/Fast-DDS/package.xml':
The manifest contains invalid XML:
mismatched tag: line 20, column 22
```
This pull request fixes this error by changing `dev` to `depend` in `package.xml`.
This fixes the master branch, but this is also fixed in the 2.0.x branch with #1554

Fix mismatching tag in package.xml

---

package.xml

Currently, the 2.0.x branch is being used in ROS Foxy [[1](https://github.com/ros2/ros2/blob/master/ros2.repos#L41)] [[2](https://github.com/ros/rosdistro/blob/master/foxy/distribution.yaml#L911)]. Because the package.xml in this branch is malformed since 669a400b704b6e70752e559d4a5719d4a36a6296, all builds that build ROS 2 from source fail.
Error message:
```
Error(s) in package '/ros2_foxy/src/eProsima/Fast-DDS/package.xml':
The manifest contains invalid XML:
mismatched tag: line 20, column 22
```
This pull request fixes this error by changing `dev` to `depend` in `package.xml`.
This fixes the 2.0.x branch, but https://github.com/eProsima/Fast-DDS/pull/1553 fixes this for the master branch.

Fix mismatching tag in package.xml <2.0.x>

---

configure.ac
fastrtps.repos
package.xml
versions.md

Bump version to 2.0.2

---

src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp

#1555 introduced this unused variable. It doesn' look like the code needs to refer to the pair itself, so I thought it best to just remove the iterator variable.
Signed-off-by: Stephen Brawner <brawner@gmail.com>

Resolve unused variable warning

---

test/unittest/dds/participant/ParticipantTests.cpp
test/unittest/dds/publisher/DataWriterTests.cpp
test/unittest/dds/publisher/PublisherTests.cpp
test/unittest/dds/status/ListenerTests.cpp
test/unittest/dds/subscriber/DataReaderTests.cpp
test/unittest/dds/subscriber/SubscriberTests.cpp
test/unittest/dds/topic/TopicTests.cpp

The mock used for `TopicDataType` on some tests was not respecting the restriction on the type size

Fixed unit tests with BUILD_SECURITY=OFF

---

src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServer2.hpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners2.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners2.hpp
src/cpp/rtps/builtin/discovery/participant/PDPClient2.hpp
src/cpp/rtps/builtin/discovery/participant/PDPServer2.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer2.hpp
src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServerListener2.hpp

This PR fix the following errors in Discovery-Server v2:
* Remove virtual readers and writers from all topics.
* Fix find in map without verification
* Only assign remote endpoints to local participants.
* Replace `aux` namespace by the full namespace.
* Remove own DATA(p) from servers history.
* Do not send virtual changes.
* Fix double disposal error and change log priority
* Fixed client servers dispose by adding a final heartbeat to the packet with the server DATA(Up).
Merge after #1323

[Discovery Server] Fix Discovery-Server v2 bugs [9821]

---

package.xml

This PR mimicks the package dependencies from [ros2-gbp/fastrtps-release](https://github.com/ros2-gbp/fastrtps-release/blob/fcfe2fe9a9fb488f1ecc8c7a101b60775f205885/foxy/package.xml#L10-L20)

Improve dependencies on package.xml [9887]

---

tools/fds/fast-discovery-server.bat.in

Make the **fast-discovery-server.bat** batch handle whitespaces on installation path.

Correct fast-discovery-server.bat issue

---

src/cpp/rtps/messages/MessageReceiver.cpp

Delete continue statement in `MessageReceiver::willAReaderAcceptMsgDirectedTo` method. The condition previous the `continue` statement will never return true because the `MessageReceiver::removeEndpoint` ensures that after removing the last element of the vector, it is removed from the map `associated_readers_`.

Delete continue in MessageReceiver::willAReaderAcceptMsgDirectedTo [9213]

---

src/cpp/rtps/builtin/liveliness/WLP.cpp

The interval of WLP timer should be updated when remove_local_writer is called.
But the parameter min_automatic_ms_ and min_manual_by_participant_ms_ are in MILLI-second, we should call update_interval_millisec instead of update_interval.

Fix interval of WLP timer when remove_local_writer called.

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp

The byte c[3] will always be dropped when creating entityId, but it could be the only byte that contains information in the variable idnum on big endian system, especially when idnum is created by calling setEntityID(uint8_t id).

Update entityId on big endian system

---

src/cpp/rtps/xmlparser/XMLElementParser.cpp
test/unittest/xmlparser/XMLElementParserTests.cpp
test/unittest/xmlparser/wrapper/XMLParserTest.hpp

Method `XMLParser::getXMLOctetVector` modified to avoid seg fault.

Negative error clauses in XMLElementParser methods

---

test/unittest/xmlparser/XMLElementParserTests.cpp

This PR adds positive clauses tests for the following functions in `XMLElementParser.cpp`:
-   `getXMLParticipantAllocationAttributes()`
-   `getXMLDiscoverySettings()`
-   `getXMLLivelinessQos()`
-   `getXMLPublishModeQos()`
-   `getXMLHistoryMemoryPolicy()`

Positive clauses tests for XMLElementParser functions

---

include/fastdds/dds/topic/TopicDataType.hpp
versions.md

This PR adds several methods to the `TopicDataType` interface in a backwards compatible way.
See eProsima/Fast-DDS-Gen#42 for the support of these extensions on the code generator

Extend TopicDataType interface

---

test/unittest/xmlparser/XMLParserTests.cpp
test/unittest/xmlparser/wrapper/XMLParserTest.hpp

This PR adds unit tests for the following functions in `XMLParser.cpp`:
- `parseXML`
- `parse_tls_config`
- `parseProfiles`
- `parseXMLLibrarySettings`
- `loadXML`
- `fillDataNode` (publisher)
- `fillDataNode` (subscriber)
- `fillDataNode` (topic)
- `fillDataNode` (requester)
- `fillDataNode` (replier)

Added tests for XMLParser functions

---

test/unittest/xmlparser/XMLParserTests.cpp
test/unittest/xmlparser/wrapper/XMLParserTest.hpp

This PR adds unit tests for the following functions in `XMLParser.cpp`:
- `parseXMLParticipantProf`
- `parseXMLPublisherProf`
- `parseXMLSubscriberProf`
- `parseXMLRequesterProf`
- `parseXMLReplierProf`
- `parseXMLTopicData`

Added profs tests

---

CONTRIBUTING.md
QUALITY.md

This PR adds a code coverage policy which states that all contributions must at least keep (if not increase) the project's line coverage.

Code coverage policy [10005]

---

src/cpp/rtps/resources/ResourceEvent.cpp
test/unittest/rtps/resources/timedevent/TimedEventTests.cpp

This PR fixes random freezes when large data is transferring using RELIABLE reliability.
Tested for local participants only.
There is some kind of race condition in ResourceEvent class.
When timer put into pending list, its execution might be delayed depending on what step is being executed in `ResourceEvent::event_service` loop.
For StatefulReader there are two timers that fire periodically and use the same ResourceEvent. One timer is in WriterProxy (`heartbeat_response_`), another is in PDP (`resend_participant_info_event_`).
Thread 1: calls `heartbeat_response_->restart()`
Thread 1: successfully locks `ResourceEvent::mutex_`.
Thread 2: `ResourceEvent::event_service` waits on `ResourceEvent::mutex_`.
Thread 1: puts `heartbeat_response_` in pending list
Thread 1: releases lock
Thread 2: …

Remove unnecessary waiting in ResourceEvent loop [10028]

---

src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp

With the new change of ResourceEvent, the DDB does not work properly due to it resends the data (this means it erases the old data and create send it with new sequence number). If this happens before the ack arrives (this happens now that the routine starts faster) the Discovery Server get stucked in an infinite loop.

[Discovery-Server] Fix timing errors [10081]

---

src/cpp/rtps/transport/TCPTransportInterface.cpp

The TCPTransportInterface may segfault on destruction if a transport instance fails to initialize properly. This is due to the unguarded access to io_service_timers_thread_.
This PR duplicates the defensive logic that is used for io_service_thread_ in the same method.

Guard IO service timer thread against accidental null pointer dereference

---

thirdparty/boost/include/boost/config/platform/qnxnto.hpp

Fixes  #1631 add qnxnto.hpp in boost/config/platform to enable shared memory

add qnxnto.hpp in platform to enable shared memory

---

src/cpp/rtps/builtin/liveliness/WLP.cpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
test/blackbox/common/BlackboxTestsLivelinessQos.cpp

min_automatic_ms_ and min_manual_by_participant_ms_ should be reset to max() before canceling the WLP timer, otherwise the WLP timer will not be restarted next time calling add_local_writer.

Reset the minimum time before canceling WLP timer

---

src/cpp/utils/IPFinder.cpp

It is considered bad style to call exit() within a library function, as
this kind of error "handling" cannot be overridden by the calling
program.
As the function getIPs() has a boolean return type already, and the
Windows version actually uses it to convey success or failure, I
adjusted the behavior for the non-Windows version accordingly.

Do not exit the process if the IP detection fails

---

thirdparty/boost/include/boost/config/platform/qnxnto.hpp

This should fix #1635.
I omit CI, as it will not check QNX related changes.

Fix path on boost qnxnto.hpp

---

include/fastdds/rtps/common/Types.h
include/fastdds/rtps/common/VendorId_t.hpp
include/fastrtps/utils/System.h
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/common/GuidUtils.hpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/transport/TCPTransportInterface.cpp
src/cpp/rtps/transport/shared_mem/SHMLocator.hpp
src/cpp/rtps/transport/tcp/RTCPMessageManager.cpp
src/cpp/utils/Host.hpp
src/cpp/utils/System.cpp
src/cpp/utils/SystemInfo.hpp
test/mock/rtps/MessageReceiver/fastdds/rtps/messages/MessageReceiver.h
test/unittest/rtps/common/CMakeLists.txt
test/unittest/rtps/common/GuidUtilsTests.cpp

This should fix #1633 by using a random value on the 6-th and 7-th bytes of the GUID prefix.

Increasing GUID prefix uniqueness [10124]

---

src/cpp/rtps/history/ReaderHistory.cpp
test/blackbox/common/BlackboxTestsPubSubHistory.cpp

Take a Reader with a full history, where some of the changes in the history com from a given Writer.
When the writer unmatches, its changes should be removed from the reader's history and some space made for new changes.
However, although the changes are being removed, the `m_isHistoryFull` flag is not being updated, making the reader think the history is still full and discarding any new change.
Update the `m_isHistoryFull` flag when removing changes and make a regression test

Update full history flag on change removal [10169]

---

include/dds/core/detail/InstanceHandle.hpp
include/fastdds/dds/core/Entity.hpp
include/fastdds/dds/core/policy/QosPolicies.hpp
include/fastdds/dds/core/status/DeadlineMissedStatus.hpp
include/fastdds/dds/core/status/LivelinessChangedStatus.hpp
include/fastdds/dds/core/status/PublicationMatchedStatus.hpp
include/fastdds/dds/core/status/SampleRejectedStatus.hpp
include/fastdds/dds/core/status/SubscriptionMatchedStatus.hpp
include/fastdds/dds/domain/DomainParticipant.hpp
include/fastdds/dds/publisher/DataWriter.hpp
include/fastdds/dds/publisher/Publisher.hpp
include/fastdds/dds/subscriber/DataReader.hpp
include/fastdds/dds/subscriber/SampleInfo.hpp
include/fastdds/dds/subscriber/Subscriber.hpp
include/fastdds/dds/subscriber/qos/DataReaderQos.hpp
include/fastdds/dds/topic/TopicDataType.hpp
include/fastdds/dds/topic/TypeSupport.hpp
include/fastrtps/TopicDataType.h
include/fastrtps/qos/DeadlineMissedStatus.h
include/fastrtps/qos/LivelinessChangedStatus.h
include/fastrtps/qos/SampleRejectedStatus.hpp
src/cpp/fastdds/domain/DomainParticipant.cpp
src/cpp/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/fastdds/domain/DomainParticipantImpl.hpp
src/cpp/fastdds/publisher/DataWriter.cpp
src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/publisher/DataWriterImpl.hpp
src/cpp/fastdds/subscriber/DataReader.cpp
src/cpp/fastdds/topic/TypeSupport.cpp

This PR adds standard read/take APIs to the DataReader.
NB:
* destination is not master branch, but the main branch for the DataReader new APIs
* they all return UNSUPPORTED, as this PR just adds the APIs, not the implementation
This will be followed with a PR adding (failing) tests

Add new APIs returning unsupported [10143]

---

include/fastdds/rtps/messages/MessageReceiver.h
src/cpp/rtps/messages/MessageReceiver.cpp
test/communication/CMakeLists.txt
test/communication/multiple_subs_secure_crypto_communication.py
test/communication/secure_msg_crypto_besteffort_pub.xml
test/communication/secure_msg_crypto_besteffort_sub.xml
test/communication/secure_msg_submsg_crypto_besteffort_pub.xml
test/communication/secure_msg_submsg_crypto_besteffort_sub.xml
test/communication/secure_submsg_crypto_besteffort_pub.xml
test/communication/secure_submsg_crypto_besteffort_sub.xml

This PR includes:
- Fix the shared memory segment writing access while reading when the RTPS message and sub-messages are encrypted.
- Communication tests

Fixed the SHM segment smashing while reading with security <2.0.x> [10165]

---

cmake/packaging/Config.cmake.in
src/cpp/CMakeLists.txt

This PR fixes compilation of targets performing `find_package(fastrtps)` after #1634.
#1634 added a public dependency on `eProsima::atomic`, but external projects don't have the means to locate that package. To deal with this, this PR installs `FindAtomic.cmake` under `share/fastrtps/cmake/modules`, and extends `fastrtps-config.cmake` so it can locate it.

Install FindAtomic.cmake [9825]

---

include/fastdds/dds/log/Log.hpp
include/fastdds/rtps/common/Locator.h
include/fastdds/rtps/common/RemoteLocators.hpp
include/fastrtps/utils/IPLocator.h
src/cpp/fastdds/subscriber/SubscriberImpl.cpp
src/cpp/fastrtps_deprecated/participant/ParticipantImpl.cpp
src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.cpp
src/cpp/rtps/history/History.cpp
src/cpp/rtps/history/ReaderHistory.cpp
src/cpp/rtps/history/WriterHistory.cpp
src/cpp/rtps/xmlparser/XMLEndpointParser.cpp
src/cpp/rtps/xmlparser/XMLParser.cpp
src/cpp/utils/IPLocator.cpp
test/unittest/rtps/common/CMakeLists.txt
test/unittest/rtps/network/NetworkFactoryTests.cpp
test/unittest/utils/CMakeLists.txt
test/unittest/utils/IPLocatorTests.cpp
test/unittest/utils/LocatorTests.cpp

Merge after #1594.
- Modify serialization/deserialization functions of Locator related classes.
- Add unittest for `Locatot.h`, `RemoteLocators.hpp` and `LocatorListComparisons.hpp`.
- Deprecate function of `LocatorList_t` and change test where is used.
Note: Coverage has not been raised till 100% in every case due to some very specific error cases.

Locator coverage [10119]

---

include/fastdds/rtps/messages/MessageReceiver.h
src/cpp/rtps/messages/MessageReceiver.cpp
test/communication/CMakeLists.txt
test/communication/multiple_subs_secure_crypto_communication.py
test/communication/secure_msg_crypto_besteffort_pub.xml
test/communication/secure_msg_crypto_besteffort_sub.xml
test/communication/secure_msg_submsg_crypto_besteffort_pub.xml
test/communication/secure_msg_submsg_crypto_besteffort_sub.xml
test/communication/secure_submsg_crypto_besteffort_pub.xml
test/communication/secure_submsg_crypto_besteffort_sub.xml

This is a port of PR #1644 from 2.0.x to 2.1.x

Fixed the SHM segment smashing while reading with security <2.1.x>

---

fastrtps.repos

By referencing master branches users are allowed to build master sources using the vcs-colcon procedure.

Update fastrtps.repos to reference master branches

---

include/fastdds/rtps/messages/MessageReceiver.h
src/cpp/rtps/messages/MessageReceiver.cpp
test/communication/CMakeLists.txt
test/communication/multiple_subs_secure_crypto_communication.py
test/communication/secure_msg_crypto_besteffort_pub.xml
test/communication/secure_msg_crypto_besteffort_sub.xml
test/communication/secure_msg_submsg_crypto_besteffort_pub.xml
test/communication/secure_msg_submsg_crypto_besteffort_sub.xml
test/communication/secure_submsg_crypto_besteffort_pub.xml
test/communication/secure_submsg_crypto_besteffort_sub.xml

This is a port of PR #1644 from 2.0.x to master

Fixed the SHM segment smashing while reading with security <master>

---

src/cpp/utils/IPLocator.cpp
test/unittest/utils/LocatorTests.cpp

Hotfix of IPv6 to string.
Add tests from #1653 .

Locator IPv6 to string fix and add tests [10199]

---

test/unittest/rtps/discovery/CMakeLists.txt

This PR solves a linking error when compiling on Debug without security. Kudos to @MiguelCompany and @imontesino 

Fix Debug compilation without security [10220]

---

include/fastdds/dds/core/LoanableCollection.hpp
include/fastdds/dds/core/LoanableSequence.hpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
test/unittest/dds/collections/LoanableSequenceTests.cpp
test/unittest/dds/subscriber/DataReaderTests.cpp

The [review](https://github.com/eProsima/Fast-DDS/pull/1662#discussion_r553365805) of #1662 revealed a design flaw in the API of `LoanableCollection`. As the `max_samples` parameter of the `read / take` APIs is a signed integer, and there is a precondition on it being less than the collection's maximum, it doesn't make sense that the type for `LoanableCollection::size_type` is `uint32_t`.
This PR changes it to `int32_t`, adds a precondition to the `length` setter of `LoanableCollection`, and adds a test for the `length` setter.
It also changes the offending code found on the review of #1662.

Change LoanableCollection::size_type to int32_t [10221]

---

test/performance/throughput/ThroughputSubscriber.cpp
test/performance/throughput/ThroughputSubscriber.hpp

Error in Throughput Test. Type is removed from Subscriber when `TEST_ENDS` finishes, but `DataSubListener` can still be reading.
Fix: #1664 

Fix seg fault in throughput test [10206]

---

examples/C++/DDS/Benchmark/BenchmarkPublisher.cpp
examples/C++/DDS/Benchmark/BenchmarkSubscriber.cpp
examples/C++/DDS/ClientServerTest/EprosimaServer.cpp
examples/C++/DDS/DeadlineQoSExample/deadlinepayloadSubscriber.cxx
examples/C++/DDS/DisablePositiveACKs/DisablePositiveACKsSubscriber.cpp
examples/C++/DDS/Filtering/FilteringExampleSubscriber.cxx
examples/C++/DDS/FlowControlExample/FlowControlExampleSubscriber.cxx
examples/C++/DDS/HelloWorldExampleSharedMem/HelloWorldSubscriber.cpp
examples/C++/DDS/HelloWorldExampleTCP/HelloWorldSubscriber.cpp
examples/C++/DDS/Keys/keys.cpp
examples/C++/DDS/LifespanQoSExample/LifespanSubscriber.cpp
examples/C++/DDS/LivelinessQoS/LivelinessSubscriber.cpp
examples/C++/DDS/OwnershipStrengthQoSExample/OwnershipStrengthSubscriber.cxx
examples/C++/DDS/TypeLookupService/TypeLookupSubscriber.cpp
test/blackbox/api/dds-pim/ReqRepHelloWorldReplier.cpp
test/blackbox/api/dds-pim/ReqRepHelloWorldRequester.cpp
test/dds/communication/Subscriber.cpp
test/xtypes/TestSubscriber.cpp

This PR replaces the checks for `instance_state == eprosima::fastdds::dds::ALIVE_INSTANCE_STATE` with checks for `valid_data`, as it is the way indicated on the DDS standard to check if we can use the sample or not.

Check valid_data instead on instance_state [10250]

---

CMakeLists.txt
cmake/modules/FindAtomic.cmake
cmake/packaging/Config.cmake.in
src/cpp/CMakeLists.txt
test/unittest/transport/CMakeLists.txt

#1634 modifies how atomic dependencies were handled to solve issues in some platforms (mac or clang on linux). In particular global variables were replaced by interface targets for link dependencies. Because all dependent targets were PUBLIC in non-windows platforms it generated issues of target propagation in external projects because the new interface target was not exported.
#1652 worarounds the above mentioned issue by exporting the FindAtomic module and calling it from Fast-DDS config files.  This is not a good practice because the FindAtomic is not a real module (it doesn't actually search for a library but check if a library is required for build) and will soon be removed (libatomic dependency is deprecated in clang and gcc).
#1678 solves the #1634 issues by declaring the atomic …

Avoid calling FindAtomic in Fast-DDS config module [10239]

---

include/fastdds/dds/domain/DomainParticipant.hpp
src/cpp/fastdds/domain/DomainParticipant.cpp
test/unittest/dds/participant/ParticipantTests.cpp

new methods:
*  create_contentfilteredtopic
*  delete_contentfilteredtopic
*  create_multitopic
*  delete_multitopic
*  find_topic
*  get_builtin_subscriber
*  ignore_participant
*  ignore_topic
*  ignore_publictaion
*  ignore_subscription
*  delete_contained_entities
*  get_discovered_participants
*  get_discovered_participant_data
*  get_discovered_topics
*  get_discovered_topic_data
NOTE: Tests missing: get_discovered_participant_data & get_discovered_topic_data
These methods cannot be tested because there are no implementation of their parameter classes.

DomainParticipant new methods [10310]

---

src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp

Adds `logWarning` for small segment sizes, such as #1666.

Add Warning for small segment sizes in SHM [10409]

---

include/fastrtps/types/DynamicTypeBuilderFactory.h
src/cpp/dynamic-types/DynamicTypeBuilderFactory.cpp

Instead of using a hardcoded zero, use a constexpr which can also be used in other parts of the library when building a bound unlimited quantity.

Refs #10416: use constexpr BOUND_UNLIMITED [10416]

---

CMakeLists.txt

When compiling Fast-DDS on aarch64, I'm seeing the following note:
/usr/include/c++/9/atomic: In member function ‘bool std::atomic<_Tp>::compare_exchange_weak(_Tp&, _Tp, std::memory_order, std::memory_order) [with _Tp = eprosima::fastdds::rtps::SharedMemManager::BufferNode::Status]’:
/usr/include/c++/9/atomic:289:7: note: parameter passing for argument of type ‘eprosima::fastdds::rtps::SharedMemManager::BufferNode::Status’ changed in GCC 9.1
I found the bug report that led to this code change:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88469
If we pass `-Wno-psabi`, that will silence this warning.  Note
that we can unconditionally pass it on all GCC platforms without
problem.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

Silence ABI note on aarch64.

---

CMakeLists.txt
include/fastrtps/config.h.in
include/fastrtps/log/Log.h
test/unittest/rtps/resources/timedevent/CMakeLists.txt

Backport of LOG_NO_INFO refactor to ros2-eloquent.
Locally I have tested the following cases:
* Build type Debug: Log INFO are printed.
* Build type Debug and LOG_NO_INFO=ON: Log INFO are not printed.
* Build type Release: Log INFO are not printed.
* Build type Release and LOG_NO_INFO=OFF: Log INFO are printed.

<ros2-eloquent> Backport LOG_NO_INFO refactor [10348]

---

src/cpp/rtps/security/SecurityManager.cpp

Receiving a Cryptography message from a remote endpoint already unmatched is not an error. It was converted to Info instead, as other logs in the same context.
This is a port of #1734 into 2.1.x

Remove log error on receive crypto message from unmatched endpoint <2.1.x> [10487]

---

include/fastdds/dds/core/LoanableSequence.hpp
include/fastdds/dds/core/LoanableTypedCollection.hpp
include/fastdds/dds/core/StackAllocatedSequence.hpp

Joining code duplicated on `LoanableSequence` and `StackAllocatedSequence`.
This would allow using `LoanableTypedCollection<T>` when we implement type-safe readers and writers, as well as using a `StackAllocatedSequence<SampleInfo>` on internal code where we now use a `SampleInfoSeq`

Introduce new LoanableTypedCollection interface [10479]

---

src/cpp/rtps/security/SecurityManager.cpp

Receiving a Cryptography message from a remote endpoint already unmatched is not an error. It was converted to Info instead, as other logs in the same context.
This is a port of #1734 into master

Remove log error on receive crypto message from unmatched endpoint <master> [10486]

---

src/cpp/rtps/security/SecurityManager.cpp

Receiving a Cryptography message from a remote endpoint already unmatched is not an error. It was converted to Info instead, as other logs in the same context.

Remove log error on receive crypto message from unmatched endpoint <2.0.x> [10485]

---

src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastrtps_deprecated/publisher/PublisherImpl.cpp
src/cpp/fastrtps_deprecated/subscriber/SubscriberImpl.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPUtils.hpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
src/cpp/rtps/builtin/liveliness/WLP.cpp
src/cpp/rtps/history/TopicPayloadPoolRegistry.cpp
src/cpp/rtps/history/TopicPayloadPoolRegistry.hpp
src/cpp/rtps/history/TopicPayloadPoolRegistry_impl/TopicPayloadPoolRegistry.hpp
src/cpp/rtps/history/TopicPayloadPoolRegistry_impl/TopicPayloadPoolRegistryEntry.hpp
src/cpp/rtps/security/SecurityManager.cpp
test/unittest/rtps/history/TopicPayloadPoolRegistryTests.cpp
test/unittest/rtps/security/CMakeLists.txt

`TopicPayloadPoolRegistry` didn't rely on shared_ptr funcionality to reset the pool registry entries. Instead rely on a devoted `release` method that will check if the pool reference in the registry was the last one by doing:
```c++
if (pool.use_count() == 2)
```
The `DataWriterImpl::release_payload_pool` used:
```c++
auto topic_pool = std::static_pointer_cast<ITopicPayloadPool>(payload_pool_);
result = topic_pool->release_history(config, false);
TopicPayloadPoolRegistry::release(topic_pool);
```
were `topic_pool` construction increased the count to 3 preventing the actual reset of the pool entry. In order to avoid this sort of errors induced by local auxiliary variables now registry clean-up relies only on 'shared_ptr' reference tracking.

Solving reference counting mistake on DataWriterImpl use of TopicPayloadPool 

---

src/cpp/fastdds/domain/DomainParticipantFactory.cpp
src/cpp/rtps/history/TopicPayloadPoolRegistry.cpp
src/cpp/rtps/history/TopicPayloadPoolRegistry.hpp
src/cpp/rtps/history/TopicPayloadPoolRegistry_impl/TopicPayloadPoolRegistry.hpp
src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
src/cpp/utils/shared_memory/SharedMemWatchdog.hpp
test/unittest/dds/publisher/DataWriterTests.cpp
test/unittest/dds/subscriber/DataReaderTests.cpp

These singletons are used on the destruction of certain classes.
In order to avoid these singletons to be already destructed,
these classes keep a shared_pointer to an instance to the singleton.
This ensures that the singleton is destructed AFTER the class instance.

Fix singleton destruction order <master> [10533]

---

src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/common/BlackboxTestsNetworkConf.cpp
test/unittest/dds/publisher/DataWriterTests.cpp
test/unittest/dds/status/CMakeLists.txt
test/unittest/dds/subscriber/DataReaderTests.cpp

* Adding `fastdds.unique_network_flows` property interpretation on QoS
* Adding tests that fail on creation of endpoints requesting the new feature
* (Bonus) Additional invalid qos tests for DataReader

Extend endpoint QoS with new unique locators request feature [10496]

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
test/blackbox/common/BlackboxTestsTransportUDP.cpp

- Correctly set participant sub-entities multicast default locators when they are specified at the participant level and not at writer level.
- Added tests to check multicast discovery and user traffic.

Correctly set participant subentities multicast default locators [10134]

---

src/cpp/rtps/reader/RTPSReader.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp

The listener thread is not being stopped when the reader is dismissed. This can lead to problems if the listener processes a notification while the reader is being destroyed, as it may end up calling methods already removed from the vtable.

Stop listener thread on reader destructor <master> [10618]

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
test/blackbox/api/dds-pim/PubSubParticipant.hpp
test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp
test/blackbox/common/BlackboxTestsNetworkConf.cpp
test/blackbox/common/BlackboxTestsPubSubBasic.cpp

This PR implements the request for unique network flows on the readers.
Depends on #1749

Implementation of unique locators request feature for readers [10497]

---

include/fastdds/rtps/attributes/RTPSParticipantAllocationAttributes.hpp
include/fastdds/rtps/common/CacheChange.h
include/fastdds/rtps/common/ChangeKind_t.hpp
include/fastdds/rtps/common/LocatorSelector.hpp
include/fastrtps/subscriber/SampleInfo.h
include/fastrtps/types/AnnotationParameterValue.h
include/fastrtps/utils/collections/ResourceLimitedContainerConfig.hpp
include/fastrtps/utils/collections/ResourceLimitedVector.hpp
include/fastrtps/utils/fixed_size_bitmap.hpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/dds-pim/PubSubWriter.hpp

This PR fixes some build errors when `#include <Windows.h>` is present before including Fast DDS header files.

Fix build issues when windows.h is included before Fast DDS headers [10521]

---

include/fastrtps/xmlparser/XMLParser.h
include/fastrtps/xmlparser/XMLProfileManager.h
src/cpp/xmlparser/XMLParser.cpp
src/cpp/xmlparser/XMLParserImpl.hpp
src/cpp/xmlparser/XMLProfileManager.cpp
test/unittest/logging/mock/MockConsumer.h
test/unittest/xmlparser/CMakeLists.txt
test/unittest/xmlparser/XMLLoadFileTests.cpp

When the environment variable `FASTRPS_DEFAULT_PROFILES_FILE` is set pointing to the `DEFAULT_FASTRTPS_PROFILES.xml` file in the current directory, the file is loaded twice and LogErrors are shown stating that the profile already exists. This PR corrects the issue by using the absolute path when the default file is loaded. It also includes a regression test.

Load default XML only once [10188]

---

src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantInfo.hpp
src/cpp/rtps/builtin/discovery/endpoint/EDPServerListeners.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp

Test cases to test this bug: https://github.com/eProsima/Discovery-Server/pull/23.
Discovery server test cases: 28, 30.
When a server already knows a client by other server (remotely) and this client is pinging such server, this server never replies as this Data(P) was checked as known (the ParticipantProxyData already existed).

Set client known as remote to local if is pinging server [10548]

---

src/cpp/rtps/transport/shared_mem/RobustLock.hpp

fixes #1766 in 2.1.x
The robust lock path is changed from /dev/shmem to /var/lock as discussed with @IkerLuengo 
First we check if the directory /var/lock exists then mkdir it if it does not then proceed with the normal procedure of creating the locked file.
if PR is approved please cherry pick to 2.0.x as well, thank you.

provide an alternative path for robustlock files under QNX

---

CMakeLists.txt
include/fastdds/dds/log/Log.hpp
include/fastrtps/config.h.in
test/unittest/logging/LogTests.cpp
test/unittest/logging/log_macros/LogMacrosAllActiveTests.cpp
test/unittest/logging/log_macros/LogMacrosDefaultTests.cpp
test/unittest/logging/log_macros/LogMacrosInternalDebugOffTests.cpp
test/unittest/logging/log_macros/LogMacrosNoErrorTests.cpp
test/unittest/logging/log_macros/LogMacrosNoInfoTests.cpp
test/unittest/logging/log_macros/LogMacrosNoWarningTests.cpp

Prior to #1679 the default library behavior was:
- if not using **INTERNAL_DEBUG** never queue infos.
- if using **INTERNAL_DEBUG** on Debug config infos are queued but other configs don't queue them.
- if user defines **LOG_NO_INFO** no infos are queued regardless config or cmake options. 
For multiconfig generators like MSVC this was optimal because Release builds never queued infos and Debug builds may do it or not depending on **INTERNAL_DEBUG** or **LOG_NO_INFO** settings.
In order to allow testing to rely on logging regardless of configuration #1679 introduced new CMake options (**LOG_NO_INFO**, **LOG_NO_WARNING**, **LOG_NO_ERROR**). 
In order to enable info logging on debug builds **LOG_NO_INFO** option was set if **CMAKE_BUILD_TYPE** was debug.  Unfortunately this broke …

[10637] Restore smart default logging for multiconfig generators

---

test/performance/latency/LatencyTestSubscriber.cpp
test/performance/latency/main_LatencyTest.cpp

Parameter validation didn't take into account that some flags were not present in non-security sources.

[10645 ] Fixing performance latency test build without security

---

cmake/modules/FindAtomic.cmake
include/fastrtps/config.h.in
src/cpp/CMakeLists.txt

`FindAtomic.cmake` module relies on CMake module `CheckLibraryExists` to check if **libatomic.so** is present in the system.
This module implementation just checks that specific APIs in the given library can be successfully linked in a dummy source file.
If the module build reports any other error unrelated to the linker ability to find the APIs the wrongly module assumes the APIs are not available.
Raspbian buster g++ version arises an error (related with API signature redefinition) that gcc considers a warning. Thus in this OS the checks must be done using the C compiler. Note that in MSVC and Clang conversely the C++ compiler must be used to avoid unrelated errors.
Now if c++20 or c++17 standard is enforced a corresponding preprocessor macro is defined (as in C++14 and C++11 were).
A …

[10646] Fix various CMake issues

---

test/performance/throughput/ThroughputSubscriber.cpp

This PR:
* Makes sure that the reader history is empty when a new test is recycling the same reader
* Considers data-sharing overrides as a lost sample

clean reader history on performance tests 

---

src/cpp/CMakeLists.txt

This will solve #1722
SOVERSION should be bumped on every release that breaks ABI. Although not every minor release breaks ABI, it does in many cases in our product. Therefore, we find less error prone if we automatize the bumping of the SOVERSION, even if that means we end up generating a different library name on some backward compatible releases.

Change SOVERSION to <major>.<minor> [10489]

---

include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
include/fastdds/rtps/attributes/ServerAttributes.h
include/fastdds/rtps/builtin/discovery/participant/PDP.h
include/fastdds/rtps/common/GuidPrefix_t.hpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
test/blackbox/common/BlackboxTestsPubSubBasic.cpp
test/blackbox/common/RTPSBlackboxTestsPersistenceGuid.cpp
test/blackbox/utils/check_guid.py
tools/fds/server.cpp

This PR adds more verbosity to the stdout of the `fastdds discovery` command. Example:
```
Server ID:          0
Server GUID prefix: 44.53.00.5f.45.50.52.4f.53.49.4d.41
Server Address:     UDPv4:[127.0.0.1]:11811
Participant Type    SERVER
```
This way, creating an XML file for CLIENTS connecting to the SERVER is easier, since the prefix is clearly stated. For doing this, a `<<` operator has been added for the `DiscoveryProtocol` enum. Furthermore, the `<<` operator for the `GuidPrefix` has been enhanced, so that the bytes are always showed as two digits, adding a preceding 0 if necessary.
It is important to note the the default GUID prefix for the server has changed. The following schema is applied now:
* `44.53.<server_id>.5f.45.50.52.4f.53.49.4d.41`, which translated into ASCII as …

Add more verbosity to discovery CLI [10611]

---

fastrtps.repos

`BuiltinDataSerializationTests` requires using the latest release for Fast CDR (1.0.20)

Bump to Fast CDR <1.0.20> in Fast DDS <2.1.x> [10711]

---

fastrtps.repos
test/unittest/rtps/builtin/CMakeLists.txt

Building <2.0.x> with the tests enabled failed due to source files being missed. This PR removes these files from the CMakeLists.txt.
Also, it bumps the Fast CDR version to <1.0.20> because `BuiltinDataSerializationTests` only pass with at least this release.

Fix <2.0.x> build and bump Fast CDR to <1.0.20> [10710]

---

include/fastdds/rtps/attributes/ServerAttributes.h
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp

This PR adds the possibility to specify remote servers to a server using the environment variable `ROS_DISCOVERY_SERVER`. This can be used in combination with `fastdds discovery` CLI to create and link servers from command line avoiding XML configuration files.

Add remote servers to server using env variable [10613]

---

include/fastdds/dds/core/UserAllocatedSequence.hpp
include/fastdds/rtps/history/ReaderHistory.h
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.hpp
src/cpp/fastdds/subscriber/DataReaderImpl/DataReaderLoanManager.hpp
src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
src/cpp/rtps/history/ReaderHistory.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
test/blackbox/common/BlackboxTestsLifespanQoS.cpp
test/blackbox/common/DDSBlackboxTestsDataSharing.cpp
test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
test/unittest/dds/subscriber/DataReaderTests.cpp
test/unittest/dds/subscriber/FooType.hpp

This PR adds new checks to `DataReaderTests.read_unread` and fixes the behavior of  `read_next_sample` and `take_next_sample`.
Depends on #1731

Fix read_next_sample and take_next_sample [10480]

---

src/cpp/rtps/DataSharing/DataSharingPayloadPool.hpp
src/cpp/utils/shared_memory/RobustExclusiveLock.hpp
src/cpp/utils/shared_memory/RobustSharedLock.hpp
src/cpp/utils/shared_memory/SharedDir.hpp

This is a port of #1776 to 2.2.x

Provide an alternative path for robustlock files under QNX <2.2.x>

---

CMakeLists.txt
include/fastrtps/config.h.in
versions.md

New Statistics tool requires a CMake option that enables the building of the specific code implemented for this tool to prevent taxing the performance.
Here the [related documentation PR](https://github.com/eProsima/Fast-DDS-docs/pull/241).

[10700] Add FASTDDS_STATISTICS CMake option

---

test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp

eProsima/Fast-DDS#1732 introduced a regression on fastrtps API compilation. This PR corrects the compilation with `-DFASTRTPS_API_TESTS=ON`

Fix fastrtps API test compilation [10480]

---

include/fastdds/dds/subscriber/DataReader.hpp
src/cpp/fastdds/subscriber/DataReader.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.hpp
test/mock/rtps/RTPSReader/fastdds/rtps/reader/RTPSReader.h
test/unittest/dds/subscriber/DataReaderTests.cpp
versions.md

The old `Subscriber` API has a `get_unread_count` method. This PR adds the equivalent on DataReader along with checks for it on the DataReader unit tests.

Expose get_unread_count on DataReader [10756]

---

include/fastdds/statistics/types.idl
src/cpp/statistics/types/types.cxx
src/cpp/statistics/types/types.h
src/cpp/statistics/types/typesPubSubTypes.cxx
src/cpp/statistics/types/typesPubSubTypes.h

Include a new topic with it's corresponding type:
```idl
struct PhysicalData
{
@Key detail::GUID_s participant_guid;
string host;
string user;
string process;
};
```

[10715] Update idl to include the Physical Data topic and type

---

package.xml

It appears that libasio-dev is pulling in this dependency at build time, but it is actually directly needed to build Fast-DDS with SECURITY=ON.

Add an explicit build dependency on libssl-dev

---

include/fastdds/statistics/types.idl
src/cpp/statistics/types/types.h

GCC issues a warning due to this case that does not have any data type associated.

[10715] Hotfix: remove case NONE from IDL

---

include/fastrtps/types/TypesBase.h
src/cpp/dynamic-types/TypesBase.cpp
versions.md

`types::ReturnCode_t` error codes could not be used in *case* statements of a `switch` control sentence.
This refactor solves the issue. The following is now valid:
```C++
ReturnCode_t res =
reader->take_next_sample(...);
switch ( res() )
{
case ReturnCode_t::RETCODE_OK:
...
break;
case ReturnCode_t::RETCODE_NO_DATA:
...
break;
}
```

[10879] Refactor `types::ReturnCode_t` to make it switch friendly

---

include/fastdds/dds/domain/DomainParticipant.hpp
include/fastdds/dds/publisher/DataWriter.hpp
include/fastdds/dds/subscriber/DataReader.hpp
include/fastdds/rtps/participant/RTPSParticipant.h
src/cpp/fastdds/publisher/DataWriterImpl.hpp

When building the doxygen documentation several warnings were issued due to current additions to the DataReader and DataWriter APIs. This PR solves those warnings with the following exception:
Doxygen issues this warning:
```
[workspace]/build/code/external/eprosima/src/fastdds/include/fastdds/rtps/attributes/ServerAttributes.h:74: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
```
This warning is caused by the `FASTDDS_DEPRECATED_UNTIL` macro and no easy solution have been found.
Labelled as `skip-ci` because this PR only modifies comments.

[10787] Fix doxygen documentation

---

include/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.h
src/cpp/rtps/network/ReceiverResource.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/reader/StatefulReader.cpp
test/blackbox/common/BlackboxTestsPubSubBasic.cpp

This PR fixes two issues:
* Too many piggyback heartbeats were being sent when a SHM transport is registered
* ACKs were not correctly delivered on certain corner cases

Fix heartbeat and ACKs issues [11003]

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp

The current mechanism detected the absence of WAN address in a profile provided locator as a mutation.

[10964] Fix participant's port mutation detection mechanism 

---

src/cpp/rtps/network/ReceiverResource.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
test/blackbox/BlackboxTestsPubSubBasic.cpp

Fix heartbeat and ACKs issues <1.8.x> [11007]

---

include/fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.h
src/cpp/rtps/network/ReceiverResource.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/reader/StatefulReader.cpp
test/blackbox/BlackboxTestsPubSubBasic.cpp

Fix heartbeat and ACKs issues <2.0.x> [11006]

---

src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastrtps_deprecated/participant/ParticipantImpl.cpp
test/blackbox/common/DDSBlackboxTestsPersistence.cpp

Right now when a persistent writer with lifespan is initialized, the lifespan is not set for loaded samples. This PR fix this and after load the samples, initialize lifespan timer.
This PR depends on #1837.

Lifespan support in Persistent DataWriters [10997]

---

src/cpp/statistics/types/types.cxx
test/unittest/statistics/dds/CMakeLists.txt
test/unittest/statistics/rtps/RTPSStatisticsTests.cpp

This PR fixes warnings and errors that appear when building with the CMake option `FASTDDS_STATISTICS` in Windows.
* Fix warning C4127 `conditional expression is constant` in `src/cpp/statistics/types/types.cxx`.
* Fix MOCK_METHOD macro call in `RTPSStatisticsTests`.
* Fix error LNK2019 building `StatisticsDomainParticipantTests`.

[11056] Fix building errors in Windows when `FASTDDS_STATISTICS` CMake option is enabled

---

include/fastdds/dds/core/policy/QosPolicies.hpp
include/fastdds/rtps/common/SerializedPayload.h
src/cpp/CMakeLists.txt
src/cpp/fastdds/core/policy/QosPolicyUtils.cpp
src/cpp/fastdds/core/policy/QosPolicyUtils.hpp
src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/publisher/qos/DataWriterQos.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/qos/DataReaderQos.cpp
test/unittest/dds/status/CMakeLists.txt

Fix two error reported by AddressSanitizer and UndefinedBehaviorSanitizer.
The AddressSanitizer error is trivial.
For the UndefinedBehaviorSanitizer error, left shifting a uint64 by 64 bits is considered undefined behavior. See this article for reference.
This is take 2 of an earlier PR: https://github.com/eProsima/Fast-DDS/pull/1834

Fix asan and undefined behavior error [10916]

---

include/fastdds/dds/core/policy/QosPolicies.hpp
include/fastdds/rtps/common/SerializedPayload.h
src/cpp/CMakeLists.txt
src/cpp/fastdds/core/policy/QosPolicyUtils.cpp
src/cpp/fastdds/core/policy/QosPolicyUtils.hpp
src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/publisher/qos/DataWriterQos.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/qos/DataReaderQos.cpp
test/unittest/dds/status/CMakeLists.txt

This is a port of #1845 from <master> to <2.2.x>

Fix asan and undefined behavior error <2.2.x> [11123]

---

test/unittest/dds/publisher/DataWriterTests.cpp

`DataWriterTests.ForcedDataSharing` consistently fails in the [nightlies without Security](http://jenkins.eprosima.com:8080/view/Nightly%20Fast%20DDS/job/nightly_fastdds_no-sec_master_linux/test_results_analyzer/).

[11166] Fix DataWriterTests.ForcedDataSharing

---

include/fastdds/statistics/dds/domain/DomainParticipant.hpp
src/cpp/fastdds/domain/DomainParticipantFactory.cpp
src/cpp/statistics/fastdds/domain/DomainParticipant.cpp
test/blackbox/CMakeLists.txt
test/blackbox/StatisticsDomainParticipant.xml
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/common/DDSBlackboxTestsStatisticsDomainParticipant.cpp
test/unittest/dds/status/CMakeLists.txt
test/unittest/statistics/dds/CMakeLists.txt
test/unittest/statistics/dds/StatisticsDomainParticipantTests.cpp

This PR includes:
* Auxiliary methods to create and enable builtin statistics entities.
* Auxiliary methods to delete builtin statistics entities.
* Additional blackbox tests that checks creation and destruction of statistics domain participant
* Additional unit test that checks statistics participant creation with invalid topic name.
* Add FASTDDS_STATISTICS environment variable

[10714] Create and delete domainParticipant implementation

---

include/fastdds/dds/topic/TypeSupport.hpp

This should fix build problems on old compilers when assigning a `TypeSupport`

Add missing operators to TypeSupport [11194]

---

src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
test/blackbox/CMakeLists.txt
test/blackbox/api/dds-pim/PubSubParticipant.hpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/api/dds-pim/PubSubWriterReader.hpp
test/blackbox/api/dds-pim/ReqRepHelloWorldReplier.cpp
test/blackbox/api/dds-pim/ReqRepHelloWorldRequester.cpp
test/blackbox/common/BlackboxTests.cpp
test/blackbox/common/BlackboxTests.hpp
test/blackbox/common/BlackboxTestsDiscovery.cpp
test/blackbox/common/BlackboxTestsPubSubBasic.cpp
test/unittest/dds/publisher/DataWriterTests.cpp

This PR fixes the logic on StatefulWriter when `m_pushMode` is false and exposes it through property `fastdds.push_mode`
Documentation PR on eProsima/Fast-DDS-docs#256

Fix and expose pull mode

---

test/performance/latency/LatencyTestPublisher.cpp
test/performance/latency/LatencyTestSubscriber.cpp

Fixes https://github.com/eProsima/Fast-DDS/issues/1898

Disable data sharing in LatencyTest by default

---

include/fastrtps/utils/collections/foonathan_memory_helpers.hpp
src/cpp/utils/collections/node_size_helpers.hpp

When building on debug mode, `foonathan_memory` uses a different implementation for the `free_list` for which the `fence_size` equals the `node_size`.
The helper function `min_pool_size` was not taking that into account.
Should fix #1917

Fix min_pool_size() calculation on debug builds [11213]

---

include/fastdds/dds/core/UserAllocatedSequence.hpp
include/fastdds/rtps/history/ReaderHistory.h
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.hpp
src/cpp/fastdds/subscriber/DataReaderImpl/DataReaderLoanManager.hpp
src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
src/cpp/rtps/history/ReaderHistory.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
test/blackbox/common/BlackboxTestsLifespanQoS.cpp
test/blackbox/common/DDSBlackboxTestsDataSharing.cpp
test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
test/unittest/dds/subscriber/DataReaderTests.cpp
test/unittest/dds/subscriber/FooType.hpp

This is a port of #1732 from <master> to <2.2.x>

Fix read_next_sample and take_next_sample <2.2.x> [11145]

---

include/fastdds/rtps/attributes/RTPSParticipantAttributes.h
include/fastdds/rtps/attributes/ServerAttributes.h
include/fastdds/rtps/builtin/discovery/participant/PDP.h
include/fastdds/rtps/common/GuidPrefix_t.hpp
include/fastrtps/xmlparser/XMLParserCommon.h
resources/xsd/fastRTPS_profiles.xsd
src/cpp/rtps/builtin/BuiltinProtocols.cpp
src/cpp/rtps/builtin/discovery/database/DiscoveryParticipantChangeData.hpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.h
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/xmlparser/XMLElementParser.cpp
src/cpp/rtps/xmlparser/XMLParserCommon.cpp
test/blackbox/common/RTPSBlackboxTestsPersistenceGuid.cpp
test/unittest/xmlparser/XMLElementParserTests.cpp
tools/fds/server.cpp

This PR backports:
* Discovery CLI verbosity: #1764 (partially) and #1799
* Super Client feature: #1763

[10778] <2.2.x> Backport discovery service fixes

---

test/performance/latency/CMakeLists.txt
test/performance/latency/latency_tests.py
test/performance/throughput/CMakeLists.txt
test/performance/throughput/throughput_tests.py

<2.2.x> Explicitly set reliability [10777]

---

src/cpp/rtps/transport/shared_mem/SharedMemChannelResource.hpp
src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
test/communication/CMakeLists.txt
test/communication/PubSubMain.cpp
test/communication/Subscriber.cpp
test/communication/Subscriber.hpp
test/communication/SubscriberMain.cpp
test/communication/shm_communication_subscriber_dies_while_processing_message.py
test/communication/shm_communication_subscriber_dies_while_processing_message.xml

This is a port of #1856 from <master> to <2.1.x>

Free used buffers in SHM on zombie ports <2.1.x> [11126]

---

src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
test/blackbox/common/BlackboxTestsPubSubHistory.cpp

This PR fixes an assertion on writers with bounded types and `PREALLOCATED_WITH_REALLOC` policy, and also sets `PREALLOCATED` on readers with bounded types and `PREALLOCATED_WITH_REALLOC`

Correctly update memory policy on writers and readers [11348]

---

include/fastdds/rtps/writer/StatefulWriter.h
include/fastdds/statistics/rtps/StatisticsCommon.hpp
include/fastdds/statistics/rtps/StatisticsCommonEmpty.hpp
src/cpp/statistics/rtps/StatisticsBase.cpp
src/cpp/statistics/rtps/StatisticsBase.hpp
src/cpp/statistics/rtps/reader/StatisticsReaderImpl.cpp
src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
test/unittest/statistics/rtps/RTPSStatisticsTests.cpp

Writers with an associated statistics listener now generate callbacks on `HEARTBEAT` submessage composition.
Mock testing has been updated to split the single `on_statistics_data()` callback into specific mock calls.
This must be merged after https://github.com/eProsima/Fast-DDS/pull/1884

[10797] HEARTBEAT_COUNT callback implementation

---

include/fastdds/rtps/reader/RTPSReader.h
include/fastdds/statistics/rtps/StatisticsCommon.hpp
include/fastdds/statistics/rtps/StatisticsCommonEmpty.hpp
src/cpp/rtps/messages/RTPSMessageGroup.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/statistics/rtps/reader/StatisticsReaderImpl.cpp
test/unittest/statistics/rtps/CMakeLists.txt
test/unittest/statistics/rtps/RTPSStatisticsTests.cpp

In order to test the callback the test fixture was updated to use a special transport with leaks.
An ABBA deadlock was detected and solved.
This pull request must be merged after https://github.com/eProsima/Fast-DDS/pull/1911

[10799] NACKFRAG_COUNT callback implementation

---

include/fastdds/rtps/participant/RTPSParticipant.h
include/fastdds/statistics/rtps/StatisticsCommon.hpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/participant/RTPSParticipant.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/statistics/rtps/StatisticsBase.cpp
src/cpp/statistics/rtps/StatisticsBase.hpp
src/cpp/statistics/rtps/reader/StatisticsReaderImpl.cpp
src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
test/unittest/statistics/rtps/RTPSStatisticsTests.cpp

Merge after https://github.com/eProsima/Fast-DDS/pull/1919

[10804 ] Collection of data and notification to listeners DISCOVERED_ENTITY

---

.github/workflows/statistics_coverage.yml
include/fastdds/rtps/writer/ReaderProxy.h
include/fastdds/statistics/rtps/StatisticsCommon.hpp
include/fastdds/statistics/rtps/StatisticsCommonEmpty.hpp
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/statistics/rtps/StatisticsBase.hpp
src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
test/unittest/statistics/rtps/RTPSStatisticsTests.cpp

There is a piggyback now Statistics' `for_each_listener` methods use temporary lists to prevent collection traversal with the mutex locked.

[10796] RESENT_DATAS tests & implementation

---

include/fastdds/rtps/common/EntityId_t.hpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/statistics/rtps/StatisticsBase.cpp
src/cpp/statistics/rtps/StatisticsBase.hpp
test/unittest/statistics/rtps/RTPSStatisticsTests.cpp

It must be merged after https://github.com/eProsima/Fast-DDS/pull/1946

[10803] Collection of data and notification to listeners EDP_PACKETS

---

include/fastdds/rtps/writer/RTPSWriter.h
include/fastdds/rtps/writer/StatefulWriter.h
include/fastdds/statistics/rtps/StatisticsCommon.hpp
include/fastdds/statistics/rtps/StatisticsCommonEmpty.hpp
src/cpp/rtps/messages/RTPSMessageGroup.cpp
src/cpp/rtps/writer/RTPSWriter.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp

This PR builds on top of #1945 and fixes the way DATA_COUNT collect samples, in order to make it more accurate and also improve performance by calling the listener fewer times (once per `send_any_unsent_changes` / `unsent_change_added_to_history` call)

Fix DATA_COUNT to account for number of destinations [11446]

---

src/cpp/rtps/transport/UDPv6Transport.cpp

Looks like uncrustify made some other changes into the IPLocator file. 
Solves #1928
Signed-off-by: Ryan Friedman <ryan_friedman@trimble.com>

Set a default ipv6 address for multicast

---

src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
src/cpp/rtps/transport/TCPChannelResourceBasic.h
src/cpp/rtps/transport/TCPTransportInterface.cpp
src/cpp/rtps/transport/tcp/RTCPHeader.h
test/unittest/transport/TCPv4Tests.cpp

This PR should fix issue #1268 by always waiting for the RTCP header, consuming bytes if they come unordered.

Synchronize TCP reception to wait for RTCP header. [11562]

---

include/fastdds/statistics/rtps/StatisticsCommon.hpp
include/fastdds/statistics/rtps/StatisticsCommonEmpty.hpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
src/cpp/statistics/rtps/StatisticsBase.hpp
src/cpp/statistics/rtps/writer/StatisticsWriterImpl.cpp
test/unittest/statistics/rtps/RTPSStatisticsTests.cpp

It was decided to retake the concept of reporting rate instead of the number of bytes. The change simplifies things and if in the future the amount of bytes is necessary we can extend the **idl**.
The callback will return bytes/second ( payload size / time span since the last callback). We only need to keep the
timestamp of the last callback and initialize it on construction (creation is the first callback).

[10792] Collection of data and notification to listeners PUBLICATION_THROUGHPUT

---

include/fastdds/statistics/rtps/StatisticsCommon.hpp
include/fastdds/statistics/rtps/StatisticsCommonEmpty.hpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp
src/cpp/statistics/rtps/StatisticsBase.hpp
src/cpp/statistics/rtps/reader/StatisticsReaderImpl.cpp
test/unittest/statistics/rtps/RTPSStatisticsTests.cpp

Merge after https://github.com/eProsima/Fast-DDS/pull/1955

[10793] Collection of data and notification to listeners SUBSCRIPTION_THROUGHPUT

---

include/fastdds/rtps/RTPSDomain.h
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/participant/RTPSParticipant.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/reader/StatefulReader.cpp

This PR prevents accessing to an already deleted `RTPSParticipant`. This case may arise when an application does:
1. Create an RTPSParticipant an save the pointer
2. Call to `RTPSDomain::stopAll()`
3. Call to `RTPSDomain::removeRTPSParticipant()` with the saved pointer.
`stopAll()` already deleted all the created `RTPSParticipant`s, so accessing to the memory segment using the pointer obtained on creation is dangerous at best. We can not prevent applications to manipulate the pointer after calling `stopAll()` (thus breaking the contract), but we definitely should not do so within Fast DDS.

Document and assert RTPS entity pointers lifetime [11579]

---

fastrtps.repos

This PR modifies the name of the folders where `fastddsgen` is going to be downloaded from the `.repos` file.
This PR is needed for eProsima/Fast-DDS-docs#266

Update from fastrtpsgen to fastddsgen

---

include/fastdds/dds/core/policy/ParameterTypes.hpp
src/cpp/rtps/DataSharing/DataSharingListener.cpp
src/cpp/rtps/DataSharing/DataSharingNotification.hpp
src/cpp/rtps/DataSharing/DataSharingPayloadPool.hpp
src/cpp/rtps/builtin/data/ParticipantProxyData.cpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp

Fix warnings and segfaults on Win32 builds

---

include/fastdds/dds/core/condition/Condition.hpp
include/fastdds/dds/core/condition/GuardCondition.hpp
src/cpp/CMakeLists.txt
src/cpp/fastdds/core/condition/ConditionNotifier.cpp
src/cpp/fastdds/core/condition/ConditionNotifier.hpp
src/cpp/fastdds/core/condition/WaitSetImpl.cpp
src/cpp/fastdds/core/condition/WaitSetImpl.hpp
src/cpp/utils/collections/unordered_vector.hpp
test/unittest/dds/core/condition/CMakeLists.txt
test/unittest/dds/core/condition/ConditionNotifierTests.cpp
test/unittest/dds/core/condition/ConditionNotifierTests/fastdds/core/condition/WaitSetImpl.hpp
test/unittest/dds/core/condition/WaitSetImplTests.cpp
test/unittest/dds/core/condition/WaitSetImplTests/fastdds/core/condition/ConditionNotifier.hpp

This PR includes implementation detail classes, along with their unit tests, required to build `Condition` and `WaitSet`

WaitSet detail classes [11656]

---

src/cpp/rtps/transport/TCPTransportInterface.h

RedHat-based systems don't have asio/steady_timer.hpp included through asio.hpp

include asio/steady_timer.hpp

---

src/cpp/rtps/transport/UDPv4Transport.cpp
src/cpp/rtps/transport/UDPv6Transport.cpp
src/cpp/rtps/transport/UDPv6Transport.h
src/cpp/statistics/rtps/messages/RTPSStatisticsMessages.hpp
test/blackbox/api/dds-pim/PubSubParticipant.hpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/api/fastrtps_deprecated/PubSubParticipant.hpp
test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
test/blackbox/common/BlackboxTests.cpp
test/blackbox/common/BlackboxTests.hpp
test/blackbox/common/BlackboxTestsNetworkConf.cpp
test/blackbox/common/BlackboxTestsTransportUDP.cpp
test/unittest/transport/UDPv4Tests.cpp
test/unittest/transport/UDPv6Tests.cpp

This PR updates UDPv6 and includes several tests to check this feature. This PR fixes the whitelist interface feature for UDPv6 (fixes #1923).
There was a bug when comparing IPv6. IPv6 address has an scope that is included after the address separated by `%`. There is a new method that allows the comparison of IPv6 addresses without taking into account the scope. This way the user can simply whitelist using the IPv6 address without having to include the name of the interface so Asio can infer the scope of the given address. It also works if the scope is given.
IPv6 feature is not completely tested so this PR is going to be a draft while some tests are included to ensure that the feature is stable and working in the most usual cases.

[11278] UDPv6 refactor and tests

---

cmake/packaging/Config.cmake.in
cmake/packaging/windows/InstallRedistributables.nsh
cmake/packaging/windows/fastrtps.manifest
cmake/packaging/windows/fastrtps.manifest.in
fastrtps.repos
src/cpp/CMakeLists.txt

The windows installer binaries require OpenSSL dependency despite of not been build with security.
Now both static and dynamic OpenSSL libraries are distributed. If the user sets *FASTDDS_STATIC=ON* the deployed static libs will be used avoiding any abi break issues.
The **dll hell** on OpenSSL dlls (an independent OpenSSL installation broke Fast-DDS operation) is now solved using a private assembly.
Generated installer available [here](http://jenkins.eprosima.com:8080/job/FastRTPS%20Installer%20Windows/243/)

[11561] Fixing static linking when SECURITY=OFF but SSL is needed

---

include/fastrtps/types/TypeDescriptor.h
src/cpp/dynamic-types/TypeDescriptor.cpp
test/unittest/xtypes/XTypesTests.cpp

According to the DDS-XTypes spec 7.5.2.4.10, the name of TypeDescriptor
should be the fully qualified name, which is the concatenation of
module names with the name of a type inside of those modules.
This change will allow an object of DynamicTypeBuilder to set a type
name that contains colon in it. Sometimes it's necessary to use a fully
qualified name in dynamic types to communicate to some existing
ros2 topic directly.
Related issue: https://gitmemory.com/issue/eProsima/Fast-RTPS-Gen/21/603785610

Allow fully qualified name in TypeDescriptor [11063]

---

src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp

Change log severity in DiscoveryServer first announcement [11777]

---

include/fastdds/rtps/common/SequenceNumber.h
include/fastdds/rtps/common/Time_t.h
include/fastdds/rtps/common/Types.h

With this change we can upgrade the sphinx version for documentation.

Change constants initialization [11867]

---

src/cpp/statistics/rtps/StatisticsBase.cpp

As receiving the same datagram twice may be forced by a malicious party, we shouldn't assert on code that is part of the processing of a received datagram.
This PR changes one of such assertions into a harmless conditional check

Remove assert on network statistics processing code

---

include/fastdds/rtps/common/SequenceNumber.h
include/fastdds/rtps/messages/CDRMessage.hpp
include/fastrtps/utils/fixed_size_bitmap.hpp
src/cpp/rtps/messages/MessageReceiver.cpp

This PR limits the maximum number of bits on the deserialization of SequenceNumberSet (i.e. ACKNACK and GAP submessages) to avoid a signed integer overflow on the high part of the sequence number.
As a bonus, it also drops messages with a protocol major version number lower than 2.

Limit SequenceNumberSet number of bits on deserialization [11875]

---

src/cpp/rtps/builtin/discovery/participant/timedevent/DSClientEvent.cpp

`DSClientEvent` accesses the information of `PDPSimple` without locking its mutex. When this event is running and a new Participant is discovered, a segmentation fault occurs. This PR adds the locking of `PDPSimple`'s mutex.

Fix segmentation fault on discovery server [11922]

---

src/cpp/rtps/security/SecurityManager.cpp
src/cpp/rtps/security/SecurityManager.h

This PR fixes a deadlock between the `SecurityManager`'s mutex and the `DiscoveredParticipantInfo`'s event. The destruction of the `DiscoveryParticipantInfo` have to happen without the `SecurityManager`'s mutex locked.

Fix deadlock with security and timers. [11923]

---

test/blackbox/api/dds-pim/PubSubWriterReader.hpp

Fixes a bug in a test with multiple threads accessing a `std::vector` without protection.

Fix bug using not protected code in a test [11924]

---

include/fastdds/dds/core/Entity.hpp
include/fastdds/dds/core/condition/StatusCondition.hpp
src/cpp/CMakeLists.txt
src/cpp/fastdds/core/Entity.cpp
src/cpp/fastdds/core/condition/StatusConditionImpl.hpp
src/cpp/fastdds/publisher/DataWriter.cpp
src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/publisher/DataWriterImpl.hpp
src/cpp/fastdds/subscriber/DataReader.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.hpp
test/unittest/dds/core/condition/StatusConditionImplTests.cpp
test/unittest/dds/core/entity/CMakeLists.txt
test/unittest/dds/publisher/DataWriterTests.cpp
test/unittest/dds/status/CMakeLists.txt
test/unittest/dds/subscriber/DataReaderTests.cpp
test/unittest/statistics/dds/CMakeLists.txt

This PR:
* Performs notification of status changes using the `StatusCondition`
* Fixes listener calls for deadline statuses
* Implements `DataReader::get_subscription_matched_status`
* Implements `DataWriter::get_publication_matched_status`
* Changes the implementation of `Entity::get_status_changes` to use the raw status on `StatusConditionImpl`

Notify status changes [11835]

---

src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp

Fixes a deadlock when asserting liveliness of a writer (due to a sample was received from it).

Fix deadlock with LivelinessManager [11925]

---

src/cpp/rtps/DataSharing/DataSharingListener.cpp
src/cpp/rtps/DataSharing/DataSharingListener.hpp
src/cpp/rtps/DataSharing/DataSharingPayloadPool.hpp
src/cpp/rtps/DataSharing/IDataSharingListener.hpp
src/cpp/rtps/reader/RTPSReader.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp
test/blackbox/api/dds-pim/PubSubWriterReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubWriterReader.hpp
test/blackbox/common/BlackboxTestsDiscovery.cpp

There is a limitation about Datareader's HistoryQos and Datasharing. In case it is detected, a warning is shown to the user.

Add warning about Datasharing limitation with Datareader's history size [11926]

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp
test/blackbox/common/BlackboxTestsLivelinessQos.cpp

If main metadata multicast port cannot be opened, warning to the user because discovery can fail with other applications.

Warning if cannot open multicast port [11928]

---

src/cpp/rtps/resources/ResourceEvent.cpp

When the interval of an event is too low, the `ResourceEvent` thread can enter in to a loop.

Fix interval loop on events [11929]

---

include/fastdds/rtps/messages/CDRMessage.hpp

As a follow-up of #2027, this PR adds a validation check to avoid overflowing the high part of the sequence number.

Validate sequence range on CDRMessage::readSequenceNumberSet [11920]

---

test/performance/latency/LatencyTestTypes.cpp
test/performance/latency/LatencyTestTypes.hpp
test/performance/throughput/ThroughputTypes.cpp
test/performance/throughput/ThroughputTypes.hpp

Dataloans uses more size that allocated by Payload

Fix wrong size calculation [11963]

---

include/fastrtps/types/TypeDescriptor.h
src/cpp/dynamic-types/TypeDescriptor.cpp

Just what the title says.
Related to #2014

Move TypeDescriptor::stateTable from header to implementation. [11841]

---

src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
test/unittest/dds/subscriber/CMakeLists.txt
test/unittest/dds/subscriber/DataReaderTests.cpp

`ReadTakeCommand` breaks the search of new changes if it found a future change of a writer although there is unread changes from other writers.

Read/Take return NO_DATA if a future change is found [12134]

---

src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
test/blackbox/types/Data1mbType.cpp
test/blackbox/types/Data64kbType.cpp
test/blackbox/types/HelloWorldType.cpp
test/blackbox/types/StringType.cpp
test/unittest/dds/subscriber/DataReaderTests.cpp

The bug was reproduced when reader's history is 1 depth and while read_sample()/take_sample() operation is deserializing the data, the data  is overwritten by the datawriter. The `ReadTakeCommand` returned OK and the code tries to access a 0 length vector.
Also the code was changed to return NO_DATA if the operation will return no data.

Fix error in read_sample()/take_sample() operations with Datasharing [12130]

---

include/fastdds/rtps/history/ReaderHistory.h
include/fastrtps/subscriber/SubscriberHistory.h
src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
test/unittest/dds/subscriber/DataReaderTests.cpp

This PR solves the issue https://github.com/eProsima/Fast-DDS/issues/2044 and workarounds the abi break introduced in https://github.com/eProsima/Fast-DDS/pull/2053.

[11993] Assuring proper history clean up when a reader unmatches a writer keeping abi compatibility

---

src/cpp/fastdds/publisher/DataWriterImpl.cpp
test/blackbox/common/DDSBlackboxTestsDataSharing.cpp

`loan_sample()` and `discard_loan()` are unprotected code. Added `RTPSWriter`'s mutex lock.

Unprotected code loaning samples [12211]

---

examples/C++/DDS/LateJoiners/latejoiners.cpp

Fix late joiners example

---

include/fastdds/rtps/participant/RTPSParticipant.h
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
src/cpp/rtps/participant/RTPSParticipant.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h

This PR adds the API necessary to propagate the `DomainParticipantQos` updates to the RTPS layer.
* `set_attributes` method to `RTPSParticipant` and `RTPSParticipantImpl`
* `upload_remote_servers_list` method to `PDPServer`

[12196] Add empty api

---

src/cpp/fastdds/publisher/DataWriterImpl.cpp
test/blackbox/common/BlackboxTestsDeadlineQos.cpp

Deadline error when no Reliable DataReaders in VOLATILE DataWriters [12321]

---

include/fastdds/dds/core/policy/QosPolicies.hpp
src/cpp/fastdds/subscriber/SubscriberImpl.cpp
src/cpp/fastdds/subscriber/qos/ReaderQos.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
test/blackbox/common/BlackboxTestsDiscovery.cpp
test/unittest/dds/subscriber/SubscriberTests.cpp

Apply setting subscriber's partition to empty set [12317]

---

include/fastdds/dds/core/policy/QosPolicies.hpp
include/fastdds/rtps/participant/RTPSParticipant.h
src/cpp/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/fastdds/domain/DomainParticipantImpl.hpp
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/builtin/BuiltinProtocols.cpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
src/cpp/rtps/participant/RTPSParticipant.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h

This PR implements the link between the DDS and the RTPS layer to propagate the updates to the `DomainParticipantQos`.
It also includes the access protection of the remote servers list with the `PDP` mutex.

[12196] DomainParticipantQos propagation to the RTPS layer implementation

---

src/cpp/fastdds/domain/DomainParticipantImpl.cpp
test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
test/unittest/dds/participant/ParticipantTests.cpp

This PR enables updating `WireProtocolConfigQos` iff the only modified field is the list of remote discovery servers.
**IMPORTANT**: Merge after #2113

WireProtocolConfigQos update through DomainParticipant::set_qos [12197]

---

include/fastdds/rtps/writer/RTPSWriter.h
include/fastdds/rtps/writer/ReaderProxy.h
include/fastdds/rtps/writer/StatefulWriter.h
include/fastdds/rtps/writer/StatelessWriter.h
include/fastdds/statistics/rtps/StatisticsCommon.hpp

Since the merge of #1996, the Fast DDS docs nightly job has been failing. This PR fixes the doxygen warning issued by this PR and some previous ones (Statistics Module)

[12357] Fix doxygen documentation

---

test/blackbox/api/dds-pim/PubSubParticipant.hpp
test/blackbox/common/DDSBlackboxTestsUserDataQos.cpp

This PR should be merged after #2113 (review from commit "Modify blackbox PubSubParticipant API to include UserDataQosPolicy").
The PR add a DDS API blackbox test that checks that the update of the `UserDataQos` is correctly updated and sent to other participants. In order to implement the test the DDS API `PubSubParticipant` has been completed to have participant discovery callbacks available.

[12196] Add UserDataQoS blackbox test

---

include/fastdds/rtps/common/Locator.h
include/fastrtps/utils/IPLocator.h
src/cpp/utils/IPLocator.cpp
test/unittest/rtps/builtin/CMakeLists.txt
test/unittest/rtps/common/CMakeLists.txt
test/unittest/rtps/discovery/CMakeLists.txt
test/unittest/utils/CMakeLists.txt
test/unittest/utils/LocatorTests.cpp
test/unittest/xmlparser/CMakeLists.txt

Resolve IP by DNS on locators.

Resolve ip name [11726]

---

src/cpp/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.h
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
test/blackbox/CMakeLists.txt
test/blackbox/api/dds-pim/PubSubParticipant.hpp
test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
test/unittest/dds/participant/ParticipantTests.cpp

This PR brings the following functionality:
1. `DomainParticipantQos::wire_protocol().builtin.discovery_config.m_DiscoveryServers` can only be modified to add servers, but not to remove them.
2. Propagate new servers to `PDPServer` and `PDPClient` so that discovery can take place
3. Add simple discovery test using discovery server to check that servers added both to a SERVER and a CLIENT have the expected effect.

Propagate servers list updates to PDPServer and PDPClient [12278]

---

include/fastdds/dds/core/policy/QosPolicies.hpp
include/fastdds/rtps/participant/RTPSParticipant.h
src/cpp/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/fastdds/domain/DomainParticipantImpl.hpp
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/builtin/BuiltinProtocols.cpp
src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.h
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.hpp
src/cpp/rtps/participant/RTPSParticipant.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
test/blackbox/CMakeLists.txt
test/blackbox/api/dds-pim/PubSubParticipant.hpp
test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
test/blackbox/common/DDSBlackboxTestsUserDataQos.cpp
test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
test/mock/rtps/RTPSParticipant/fastdds/rtps/participant/RTPSParticipant.h
test/unittest/dds/participant/ParticipantTests.cpp

This PR includes:
* Fix the DDS and RTPS layer link to propagate the DomainParticipantQos updates
* Implementation to allow updates of `user_data`.
* Implementation to allow adding new servers to the remote servers list.
* Blackbox tests that checks both functionalities
* Corresponding unit test when possible

Allow DomainParticipantQos updates for UserDataQosPolicy and adding new servers to the remote server list

---

src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
src/cpp/rtps/xmlparser/XMLElementParser.cpp
test/blackbox/common/BlackboxTestsDiscovery.cpp
tools/fds/README.txt
tools/fds/server.cpp
tools/fds/server.h

This PR allows configuring both Discovery Servers and Clients specifying names instead of IPv4 addresses (port is still required). If a name is specified, the DNS is queried for IPv4 addresses, which are in turn used to configure the Server and Client.

Configure Discovery Server using names [12349]

---

src/cpp/rtps/writer/LivelinessManager.cpp

Fix wrong iterator after vector reallocation ln LivelinessManager [12362]

---

include/fastdds/dds/log/Log.hpp

As it is right now, `logInfo` only produces messages under the following conditions:
1. `HAVE_LOG_NO_INFO` is false AND
2. Either `FASTDDS_ENFORCE_LOG_INFO` is defined OR
3. `__INTERNALDEBUG` or `_INTERNALDEBUG` is defined AND `_DEBUG` or `__DEBUG` is defined.
* `HAVE_LOG_NO_INFO` can be set by users with `-DLOG_NO_INFO`, which defaults to OFF in debug and ON in every other configuration.
* `FASTDDS_ENFORCE_LOG_INFO` can be defined by the user and defaults to OFF
* `__INTERNALDEBUG` is defined when compiling Fast DDS with `-DINTERNAL_DEBUG`, which defaults to OFF
* `_INTERNALDEBUG` can be defined by the user. Fast DDS does not define it, nor Fast DDS CMakeLists
* `_DEBUG` is defined when using Windows config generators in build type is debug
* `__DEBUG` is defined iff `CMAKE_BUILD_TYPE` …

Check for NDEBUG in logInfo [12218]

---

test/blackbox/common/DDSBlackboxTestsDiscovery.cpp

This should solve http://jenkins.eprosima.com:8080/job/nightly_fastdds_sec_master_windows/786/label=windows-secure,platform=Win32,toolset=v141/testReport/junit/projectroot.test/blackbox/BlackboxTests_DDS_PIM_DDSDiscovery_AddDiscoveryServerToList/

Initialize char* to nullptr [12367]

---

src/cpp/utils/SystemInfo.cpp
src/cpp/utils/SystemInfo.hpp
test/unittest/utils/CMakeLists.txt
test/unittest/utils/SystemInfoTests.cpp
test/unittest/utils/environment_test_file.json

This PR should be merged after #2155. It implements `SystemInfo::load_environment_file` and tests its functionality.

[12199] Load environment file

---

include/fastdds/rtps/attributes/ServerAttributes.h
src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
test/blackbox/CMakeLists.txt
test/blackbox/common/BlackboxTestsDiscovery.cpp
test/blackbox/environment_file.json

This PR is built over #2157. It refactors `load_environment_server_info` to check first if the environment file exists and if so, read the environment info from there. It also adds some test cases that checks this new feature.

[12199] Refactor load environment server info to take into account environment file

---

include/fastdds/rtps/history/ReaderHistory.h
src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
src/cpp/rtps/history/ReaderHistory.cpp
src/cpp/utils/collections/sorted_vector_insert.hpp
test/blackbox/common/BlackboxTestsPubSubHistory.cpp
test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h

On a reliable reader, when using a topic with keys, and changes arrive unordered, they are returned in the received order instead of the sequence number order.
This PR fixes this misbehavior, and also adds a generic utility function to keep changes on a vector sorted.

Keep changes inside instances sorted by source timestamp [12421]

---

src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp

I merged #2177 without applying the changes on #2182 to DataReaderHistory.
This PR fixes that mistake.

Fixed DataReaderHistory [12471]

---

include/fastdds/rtps/messages/RTPSMessageGroup.h
include/fastdds/rtps/messages/RTPSMessageSenderInterface.hpp
include/fastdds/rtps/reader/RTPSReader.h
include/fastdds/rtps/reader/StatefulReader.h
include/fastdds/rtps/reader/StatelessReader.h
include/fastdds/rtps/writer/LocatorSelectorSender.hpp
include/fastdds/rtps/writer/ReaderLocator.h
include/fastdds/rtps/writer/ReaderProxy.h
src/cpp/rtps/builtin/discovery/participant/DirectMessageSender.hpp
src/cpp/rtps/flowcontrol/FlowControllerImpl.hpp
src/cpp/rtps/messages/RTPSMessageGroup.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp
src/cpp/rtps/reader/WriterProxy.cpp
src/cpp/rtps/reader/WriterProxy.h
src/cpp/rtps/writer/LocatorSelectorSender.cpp
src/cpp/rtps/writer/StatefulWriter.cpp
src/cpp/rtps/writer/StatelessWriter.cpp
test/mock/rtps/RTPSWriter/fastdds/rtps/writer/RTPSWriter.h
test/mock/rtps/ReaderLocator/fastdds/rtps/writer/ReaderLocator.h

`RTPSMessageGroup` used by the flow controller could lead in a ABBA deadlock when the sender is changed. This PR fixes this. Instead of use the writer's mutex, the LocatorSelectorSender has its own mutex.

Fix ABBA deadlock in flow controller core [12394]

---

src/cpp/security/authentication/PKIDH.cpp

Fix the const correctness of DH and EC_KEY, so the codebase will compile
against OpenSSL 3. However, there are a number of warnings due to
deprecated functions, which are not touched by this commit and will need
to get fixed separately.

Fix compilation errors with OpenSSL 3.0

---

include/fastdds/dds/core/policy/QosPolicies.hpp
include/fastdds/dds/domain/qos/DomainParticipantQos.hpp
include/fastdds/rtps/flowcontrol/FlowControllerDescriptor.hpp

Flow controllers made their way to master, but doxygen was not updated accordingly.

Remove not implemented warning on doxygen [12358]

---

include/fastdds/dds/domain/qos/DomainParticipantQos.hpp

Hotfix: add DomainParticipantQos::flow_controllers doxygen documentation

---

include/fastdds/rtps/flowcontrol/FlowControllerConsts.hpp
src/cpp/rtps/flowcontrol/FlowControllerConsts.cpp
src/cpp/rtps/flowcontrol/FlowControllerFactory.cpp
src/cpp/statistics/fastdds/publisher/qos/DataWriterQos.cpp

From a call of a user's writer `write()` function, internally is a call of a statistics's writer `write()` function. Using asynchronous publication mode, this second call will call again the FlowController's mutex leading into a deadlock. This PR creates another asynchronous thread specially for statistics writers.

Fix deadlock using asynchronous publication and statistics [12396]

---

src/cpp/statistics/fastdds/publisher/qos/DataWriterQos.cpp

Communications are improved decreasing the history's depth.

Improve statistics communication performance [12415]

---

include/fastdds/rtps/RTPSDomain.h
include/fastdds/rtps/attributes/ServerAttributes.h
include/fastdds/rtps/participant/RTPSParticipant.h
src/cpp/fastdds/domain/DomainParticipantFactory.cpp
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/RTPSDomainImpl.hpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
src/cpp/rtps/participant/RTPSParticipant.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/utils/SystemInfo.cpp
src/cpp/utils/SystemInfo.hpp
test/CMakeLists.txt
test/blackbox/common/BlackboxTestsDiscovery.cpp
test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
test/dds/discovery/CMakeLists.txt
test/dds/discovery/ParticipantMain.cpp
test/dds/discovery/ParticipantModule.cpp
test/dds/discovery/ParticipantModule.hpp
test/dds/discovery/client_server_dynamic_discovery.py
test/unittest/utils/SystemInfoTests.cpp

This PR implements the final functionality. Monitoring the environment file and applying the changes when the watcher triggers.
It also includes the refactor of `SystemInfo::get_env` to use `std::string` instead of `char*`.

[12199] Reload environment file information

---

examples/C++/DDS/LateJoiners/latejoiners.cpp

DDS Lata Joiners example was calling non implemented API `DataReader::get_matched_publications` which is always returning `ReturnCode_t::RETCODE_UNSUPPORTED`. Thus the previous implementation blocks in a `do-while` block waiting for this API to return a non-empty vector. This PR introduces a sleep that ensures that most times the discovery phase will finish and the example is going to work as expected.

Fix DDS Late Joiners example

---

test/unittest/logging/log_macros/LogMacrosDefaultTests.cpp

The test referenced in the title has been failing consistently on Windows since #2089 was merged.
On that PR, the following assumption was made:
> HAVE_LOG_NO_INFO can be set by users with -DLOG_NO_INFO, which defaults to OFF in debug and ON in every other configuration.
But the default behavior is different for Visual Studio since #1775, as `LOG_NO_INFO` is always OFF on multiconfig CMake generators (i.e. Visual Studio).
This PR adds a build check on the default values for NDEBUG and LOG_NO_INFO, and adapts the way the expected result is calculated.

Fixed LogMacrosTests.default_macros_test [12575]

---

src/cpp/utils/collections/impl/node-sizes/custom/tree_node_size_impl.hpp

When foonathan/memory is cross-compiled, and the `node_size_dbg` tool cannot be executed with an emulator, some custom node types are used to calculate the size of the nodes being requested to the allocator.
After some reports of a `bad_node_size` exception being thrown, I investigated this deeply, and found the custom type was not compliant with certain std implementations (libstdc++).

Avoid bad_node_size exception when cross building [12583]

---

src/cpp/rtps/flowcontrol/FlowControllerFactory.cpp

This should fix #2174 and fix #2219 by using std::pair, as explained [here](https://stackoverflow.com/a/53197779).

Fix build on old compilers [12546]

---

src/cpp/rtps/writer/StatefulWriter.cpp

Currently, when there is a hole in the history a GAP message is sent for each reader. This PR improves this behavior by sending a single GAP for everyone (useful when readers are configured in multicast).

Communication improvement sending only one GAP for all readers [12576]

---

src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/rtps/reader/RTPSReader.cpp
src/cpp/rtps/reader/StatefulReader.cpp

Persistence guid hotfixes [12680]

---

include/fastrtps/types/DynamicTypeBuilderFactory.h
include/fastrtps/types/TypesBase.h
src/cpp/dynamic-types/DynamicData.cpp
src/cpp/dynamic-types/DynamicType.cpp
src/cpp/dynamic-types/TypeDescriptor.cpp
test/unittest/dynamic_types/DynamicTypesTests.cpp

In order to remove the dependency on `#include <dds/core/LengthUnlimited.hpp>`, this PR changes references to `::dds::core::LENGTH_UNLIMITED` into `eprosima::fastrtps::types::BOUND_UNLIMITED`

Use BOUND_UNLIMITED on Dynamic Types

---

src/cpp/fastrtps_deprecated/Domain.cpp

Currently this feature is not working with ROS 2 Foxy because the RMW implementation is still using the deprecated API.
No tests have been added because this API is already deprecated.

[12819] Fully support dynamic addition od remote servers in deprecated API

---

include/fastrtps/xmlparser/XMLParserCommon.h

As discussed in issue #1997 this macro was clashing with function from the Gtk3 UI library. As it is not needed it was proposed by MiguelCompany to remove it.

Removing unused macro to avoid naming clashes

---

src/cpp/rtps/RTPSDomain.cpp
test/unittest/dds/participant/ParticipantTests.cpp

If the `FASTDDS_ENVIRONMENT_FILE` environment variable is set but the file does not exist, Fast DDS breaks. This PR fixes this issue and adds also a test to check different Discovery Server configurations.

[12529] Fix file watch initialization

---

src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/SubscriberImpl.cpp
src/cpp/rtps/reader/RTPSReader.cpp

This PR disables the `DataReader` on destruction. This is because, as reported in #2307 , it could be the case that a data sample is received while deleting a `DataReader`, which before could end up in a situation in which the underlying `RTPSReader` was accessed when it had been already deleted. To avoid this case, the first thing done on the destruction of the `DataReader` is to disable it, which sets the `DataReader` and `RTPSReader` listeners to `nullptr`, thus preventing receiving a data sample on upper layers.
Closes #2307

Disable DataReader on destruction [12870]

---

src/cpp/fastdds/core/policy/QosPoliciesSerializer.hpp

Serialization of X-Types Qos policies in the Data(p) parameter list is not contemplating correctly the alignment. This PR fixes this.

Fix wrong serialization of X-Types QoS policies [12686]

---

include/fastdds/rtps/writer/ReaderProxy.h
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp

Using new flow controllers for low bandwidth communications I've realized periodic HEARTBEATS stop begin sent. This is caused my history's depth is low, and when the periodic heartbeat is triggered, all samples in the `ReaderProxy` are in UNSENT state.
This PR adds periodic HEARTBEAT also dependes in the low_mark. I f the low_mark is less than the minimun sequence number in the history, the HEARTBEAT is sent.

Periodic heartbeat also depending on ReaderProxy's low_mark [12642]

---

include/fastdds/rtps/writer/ReaderProxy.h
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp

Current mechanism could send GAP about missing samples but they are not currently a hole in the history. This information already will be in the HEARTBEAT message.
This PR avoid to send GAP of this kind of samples which their sequence number is less than minimum sequence number in the history.

Avoid sending GAP for no current history holes [12643]

---

src/cpp/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/fastdds/domain/DomainParticipantImpl.hpp
src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
test/blackbox/common/DDSBlackboxTestsStatistics.cpp
test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp

This can lead to an error. If the user's publisher is configured with a partition, there will no matching with statistics_backend

Fix statistics writers sometimes uses the user's publisher [12391]

---

src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.cpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.h
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServerListener.cpp

Merge after https://github.com/eProsima/Fast-DDS/pull/2244

Discovery Server fix reconnection [12522]

---

src/cpp/rtps/writer/ReaderProxy.cpp

This is a follow-up of #2254, and should fix [this](http://jenkins.eprosima.com:8080/view/Nightly%20Fast%20DDS/job/nightly_fastdds_sec_master_mac/860/testReport/junit/projectroot.test/blackbox/BlackboxTests_DDS_PIM_DDSDataReader_LivelinessChangedStatusGet_Intraprocess/)

Convert ReaderProxy assertion into condition [13005]

---

src/cpp/fastdds/core/policy/ParameterList.hpp
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/rtps/persistence/sqlite3.h
src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp
src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
src/cpp/utils/shared_memory/SharedMemSegment.hpp

When trying to build Fast-DDS on Ubuntu 22.04 with gcc 11, there were a number of new warnings.  This PR fixes all of those warnings in various different ways.
For the most part, I think these are correct.  The change that I'm most worried about is the last one, that changes a memset to use `std::fill_n` instead.  That seems more correct to me, but I didn't have a good way to test it out.  That one should be reviewed and tested more fully before this is merged.
Also, please note that I targeted this change at the 2.3.x branch, as that is what ROS 2 is currently targeting.  I can target another branch if needed, though we'll eventually want this change on whatever branch ROS 2 is using.
Reviews or thoughts are welcome.

Fix various gcc11 warnings [12970]

---

CMakeLists.txt
Public_API_foonathan_memory.md
Quality_Declaration_foonathan_memory.md
README.md
package.xml

Bumping version and updating QD for foonathan memory.

Bump version to 2.4.1 [13029]

---

include/fastdds/rtps/common/InstanceHandle.h
test/unittest/dds/subscriber/DataReaderTests.cpp
versions.md

This should fix #2306 by adding a specific validity field to `InstanceHandle_t`. This means the solution is not ABI compatible with the current code. That's why I added this to v2.5.0 milestone.

Allow zero-valued InstanceHandle_t [12942]

---

include/fastdds/dds/core/policy/ParameterTypes.hpp
include/fastdds/rtps/common/InstanceHandle.h
src/cpp/rtps/builtin/data/ReaderProxyData.cpp
src/cpp/rtps/builtin/data/WriterProxyData.cpp
src/cpp/rtps/builtin/liveliness/WLP.cpp
src/cpp/rtps/history/CacheChangePool.cpp
test/unittest/rtps/history/BasicPoolsTests.cpp
test/unittest/rtps/history/CacheChangePoolTests.cpp

This is a follow-up to #2316, that should fix the build errors on [Win32](http://jenkins.eprosima.com:8080/job/nightly_fastdds_sec_master_windows/896/label=windows-secure,platform=Win32,toolset=v142/)

Fix InstanceHandle_t issues [13111]

---

src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp

This should fix #2333, and also improve readability and maintainability with a small refactor.

Fix and refactor EDPSimple destructor [13117]

---

include/fastdds/rtps/history/ReaderHistory.h
include/fastdds/rtps/reader/StatefulReader.h
include/fastrtps/subscriber/SubscriberHistory.h
src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
src/cpp/rtps/history/ReaderHistory.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp
test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h

This PR adds a mechanism on ReaderHistory to check if a new change will be accepted into it. This allows the code on `processDataMsg` to avoid copying the change information (and, possibly, its payload) for a sample that is going to be rejected

Avoid payload reservation and copy when change is going to be rejected by history [13120]

---

include/fastrtps/types/AnnotationParameterValue.h

When generate source code with TypeObjects, on Windows the user application doesn't compile because some needed functions are not exported. This PR fixes this.

Exported some function on Windows [12673]

---

include/fastdds/dds/topic/IContentFilterFactory.hpp
include/fastdds/dds/topic/TopicDataType.hpp
include/fastdds/dds/topic/TypeSupport.hpp
include/fastrtps/types/DynamicPubSubType.h
src/cpp/dynamic-types/DynamicPubSubType.cpp
src/cpp/fastdds/domain/DomainParticipantImpl.cpp

After some internal discussions about the design, this PR updates the following interfaces:
**IContentFilterFactory**
* Method `create_content_filter` receives `TopicDataType` instead of `TopicDescriptor`
* Removed `type_descriptor` getter from `TopicDataType`

Updating content filter interfaces [13272]

---

versions.md

#2103 included a new feature which was not documented in `versions.md`.

[13283] Add chaining transports feature to versions.md

---

src/cpp/fastdds/domain/DomainParticipantFactory.cpp
test/unittest/dds/status/CMakeLists.txt

The first time an interprocess synchronization object is created by boost, a singleton is instantiated and its destructor is registered with std::atexit(&atexit_work).
This PR ensures that singleton is created before the DomainParticipantFactory instance so that it is destroyed after all the participants have been deleted.

Ensure correct boost singleton destruction order [13288]

---

include/fastdds/dds/log/Log.hpp
include/fastdds/rtps/writer/LocatorSelectorSender.hpp
src/cpp/fastdds/log/Log.cpp
test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
test/unittest/logging/mock/MockConsumer.h

`Log.hpp` header file is used everywhere. It's include `<condition_variable>` and `<mutex>`. This is incompatible with making a C# wrapper. This PR moves these included headers to `Log.cpp`.

Remove `#include <condition_variable>` from `Log.hpp` [12720]

---

src/cpp/dynamic-types/BuiltinAnnotationsTypeObject.cpp
src/cpp/dynamic-types/TypeObjectFactory.cpp
test/unittest/dynamic_types/DynamicComplexTypesTests.cpp

`TypeObjectFactory` currently only supports `@key`, but not `@Key`. This PR fixes this.

Add support for Key annotation in TypeObjectFactory [12674]

---

src/cpp/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/rtps/transport/test_UDPv4Transport.cpp
src/cpp/rtps/transport/test_UDPv4Transport.h
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
test/blackbox/api/fastrtps_deprecated/PubSubWriter.hpp
test/blackbox/common/DDSBlackboxTestsDiscovery.cpp
test/blackbox/common/RTPSBlackboxTestsBasic.cpp
test/blackbox/common/RTPSWithRegistrationReader.hpp
test/blackbox/common/RTPSWithRegistrationWriter.hpp

Currently only network interfaces found when launching Fast DDS are taken into account. This PR adds new participant locators if new network interfaces are detected. In order to trigger the check, the user must call `DomainParticipant::set_qos`. If some user is using the RTPS layer directly, the feature can also be triggered by calling `RTPSParticipant::update_attributes`.
This PR includes both the implementation and the Blackbox tests at RTPS and DDS level. It also completes test API, both in the Entities as in the Transport layer.
Related PRs:
* eProsima/Fast-DDS-docs#301

Add participant locators if new network interfaces are found [12753]

---

include/fastdds/dds/subscriber/SampleInfo.hpp
include/fastdds/rtps/common/CacheChange.h
include/fastdds/rtps/history/ReaderHistory.h
include/fastrtps/subscriber/SubscriberHistory.h
include/fastrtps/utils/collections/ResourceLimitedVector.hpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
src/cpp/fastdds/subscriber/history/DataReaderCacheChange.hpp
src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp
src/cpp/fastdds/subscriber/history/DataReaderInstance.hpp
src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
src/cpp/rtps/history/ReaderHistory.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp
src/cpp/utils/SystemInfo.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
test/unittest/dds/subscriber/DataReaderTests.cpp

Implementing figure 2.11 (Statechart of the instance_state and view_state for a single instance) of the DDS standard.

Adding implementation for instance_state and view_state [12758]

---

include/fastdds/dds/publisher/DataWriter.hpp
include/fastrtps/publisher/PublisherHistory.h
src/cpp/fastdds/publisher/DataWriter.cpp
src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/publisher/DataWriterImpl.hpp
src/cpp/fastrtps_deprecated/publisher/PublisherHistory.cpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/common/DDSBlackboxTestsDataWriter.cpp
test/mock/rtps/PublisherHistory/fastrtps/publisher/PublisherHistory.h
test/unittest/dds/publisher/CMakeLists.txt
test/unittest/dds/publisher/DataWriterTests.cpp
test/unittest/statistics/dds/CMakeLists.txt
versions.md

Add API to DataWriter: overload `wait_for_acknowledgments` for a specific instance.
Depends on #2356

Add writer wait for acknowledgements for a specific instance [13252]

---

include/fastdds/rtps/RTPSDomain.h
include/fastdds/rtps/attributes/EndpointAttributes.h
include/fastdds/rtps/participant/RTPSParticipant.h
src/cpp/fastdds/domain/DomainParticipantImpl.hpp
src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/publisher/DataWriterImpl.hpp
src/cpp/fastdds/publisher/PublisherImpl.hpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.hpp
src/cpp/fastdds/subscriber/SubscriberImpl.hpp
src/cpp/rtps/RTPSDomain.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/statistics/fastdds/publisher/DataWriterImpl.hpp
test/mock/dds/DomainParticipantImpl/fastdds/domain/DomainParticipantImpl.hpp
test/mock/rtps/RTPSDomain/fastdds/rtps/RTPSDomain.h
test/mock/rtps/RTPSParticipantImpl/rtps/participant/RTPSParticipantImpl.h
test/unittest/dds/publisher/DataWriterTests.cpp
test/unittest/dds/subscriber/DataReaderTests.cpp

Currently when the user creates a Datawriter or Datareader not enabled, the `get_guid()` functions return `GUID_t::unknown()`.
This PR fixes this and improve DDS API generating the GUID in the entity creation instead of in the enabling.

Reservation of EntityId in DDS layer [12669]

---

include/fastdds/dds/subscriber/SampleInfo.hpp
include/fastdds/rtps/common/CacheChange.h
include/fastdds/rtps/history/ReaderHistory.h
include/fastrtps/subscriber/SubscriberHistory.h
include/fastrtps/utils/collections/ResourceLimitedVector.hpp
src/cpp/CMakeLists.txt
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.hpp
src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp
src/cpp/fastdds/subscriber/history/DataReaderCacheChange.hpp
src/cpp/fastdds/subscriber/history/DataReaderHistory.cpp
src/cpp/fastdds/subscriber/history/DataReaderHistory.hpp
src/cpp/fastdds/subscriber/history/DataReaderInstance.hpp
src/cpp/fastrtps_deprecated/subscriber/SubscriberHistory.cpp
src/cpp/rtps/history/ReaderHistory.cpp
src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp
src/cpp/utils/SystemInfo.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/mock/rtps/ReaderHistory/fastdds/rtps/history/ReaderHistory.h
test/unittest/dds/publisher/CMakeLists.txt
test/unittest/dds/status/CMakeLists.txt
test/unittest/dds/subscriber/DataReaderTests.cpp
test/unittest/statistics/dds/CMakeLists.txt
test/unittest/utils/ResourceLimitedVectorTests.cpp
versions.md

This PR makes the DataReader use a new `DataReaderHistory` class with a correct implementation of instance_state and view_state.

DataReaderHistory [12400]

---

src/cpp/rtps/RTPSDomain.cpp
test/blackbox/common/BlackboxTestsPubSubBasic.cpp
test/blackbox/common/mock/BlackboxMockConsumer.h

This PR avoids a `logWarning` that was issued whenever `DomainParticipantFactory::load_profiles()` was called for the first time without setting `FASTDDS_ENVIRONMENT_FILE` environment variable or setting it to `""`. It also adds a regression test and a test that checks that the `logWarning` is indeed issued if `FASTDDS_ENVIRONMENT_FILE` is set to an non-existing file.

Avoid logWarning when environment file filename is empty [13302]

---

src/cpp/fastdds/subscriber/DataReaderImpl/ReadTakeCommand.hpp

Method `ReadTakeCommand::check_datasharing_validity` could receive 'nullptr' on `wp`.
As that parameter was only used on the `logWarning` call to obtain the GUID of the writer, and it could be obtained from the cache change, I just removed that parameter completely

Avoid null dereference on log message

---

include/fastdds/rtps/attributes/ServerAttributes.h

This PR adds `DOXYGEN_SHOULD_SKIP_THIS` to deprecated API in ServerAttributes.h

Doxygen skip deprecated functions [13408]

---

src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
test/unittest/xmlparser/CMakeLists.txt
test/unittest/xmlparser/XMLParserTests.cpp
test/unittest/xmlparser/regressions/13418.xml

Fixed a null-dereference on XML parser

Fix oss-fuzz 42193 [13449]

---

include/fastdds/rtps/common/Time_t.h

The Time_t nanosec() method requires a uint32_t to be passed in.
But the previous code was using an int32_t for the nanoseconds,
which was causing a warning in some compilers.  Fix this by
using a uint32_t for the nano variable.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
Note that I targeted this at the 2.3.x branch, which is where I noticed it (using ROS 2 Rolling).  I'm happy to retarget it to master if preferred (though I'll then ask for a backport to 2.3.x).

Fix warning when converting string to Time_t.

---

src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
test/unittest/xmlparser/XMLParserTests.cpp
test/unittest/xmlparser/regressions/13454.xml

XMLDynamicParser uses `stoi()` without a try/catch statement. With a wrong XML attribute value a exception is launched without being caught.
This will fix oss-fuzz 43525

Fix not caught exception in XMLDynamicParser [13462]

---

examples/C++/DDS/ZeroCopyExample/LoanableHelloWorldSubscriber.cxx
src/cpp/rtps/reader/RTPSReader.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/common/DDSBlackboxTestsDataSharing.cpp

Hotfix of the user API for sample validation which was broken.
Include a new test to prevent this issue from been unnoticed in the future.
Associated to [issue 2369](https://github.com/eProsima/Fast-DDS/issues/2369).

[13357] Fix DataSharing sample validation

---

src/cpp/rtps/transport/TCPv4Transport.cpp
src/cpp/rtps/transport/TCPv6Transport.cpp
src/cpp/rtps/transport/UDPv4Transport.cpp
src/cpp/rtps/transport/UDPv6Transport.cpp
test/blackbox/common/BlackboxTests.cpp
test/blackbox/common/BlackboxTests.hpp
test/blackbox/common/BlackboxTestsTransportTCP.cpp
test/blackbox/common/TCPReqRepHelloWorldReplier.cpp
test/blackbox/common/TCPReqRepHelloWorldRequester.cpp

This PR fix the fill local IP functions defining the IP kind before filling the locator with the given IP.

Fix fill local IP [13390]

---

examples/C++/DDS/HelloWorldExampleSharedMem/HelloWorldPublisher.cpp
examples/C++/DDS/HelloWorldExampleSharedMem/HelloWorldSubscriber.cpp

The shared memory example is adding 2 transport layers, shared memory + UDP.
The UDP will not be used if a shared memory transport layer conditions are met and this is a unique shared memory example.
I find it confusing as a user that the shared memory example also configure UDP, it looks like a mandatory step for shared memory and it's not.
Consider using this PR to remove it and make the example clearer.

Remove UDP transport from the shared memory example

---

test/blackbox/common/RTPSBlackboxTestsPersistenceNonIntraprocess.cpp
test/blackbox/common/mock/BlackboxMockConsumer.h

In a blackbock tests a condition_variable is being notified locking a mutex but for waiting process another mutex is used.

Fixing wrong usage of condition_variable [13542]

---

test/unittest/logging/mock/MockConsumer.h
test/unittest/statistics/dds/StatisticsDomainParticipantMockTests.cpp
test/unittest/statistics/dds/StatisticsDomainParticipantTests.cpp
test/unittest/xmlparser/XMLElementParserTests.cpp
test/unittest/xmlparser/XMLEndpointParserTests.cpp
test/unittest/xmlparser/XMLParserTests.hpp

The class used on unit tests for checking behavior regarding the log messages is wrongly used.
A reference to its condition_variable is obtained and then used with a different mutex.
This PR fixes this by adding a generic `wait` method receiving a predicate, as long as a `wait_for_at_least_entries` method, which is the most common use in the unit tests.
The `cv()` getter and `ConsumedEntriesSize_nts()` methods are removed, to ensure we don't have incorrect behaviour.

Fix locks used in MockConsumer [13303]

---

cmake/modules/FindLibP11.cmake
test/blackbox/CMakeLists.txt

There is also a fix in the blackbox testing.

Update pkcs11 module for red hat distros [13616]

---

src/cpp/rtps/writer/ReaderProxy.cpp
test/mock/rtps/ReaderLocator/fastdds/rtps/writer/ReaderLocator.h
test/mock/rtps/StatefulWriter/fastdds/rtps/writer/StatefulWriter.h
test/unittest/rtps/writer/CMakeLists.txt
test/unittest/rtps/writer/ReaderProxyTests.cpp

This PR fixes a bug which occurs when the `CacheChange_t` with minimum sequence number in the Writer's history is irrelevant for a new reader (for example because reader is volatile). This change is not added in the GAP message because of a `>` instead of a `>=`.

Fix inserting minimum CacheChange_t in GAP message [13671]

---

test/unittest/statistics/dds/CMakeLists.txt

Fixes compilation of Statistics tests

Add Pkcs11Provider.cpp to Statistics unit test CMakelists.txt [13808]

---

examples/C++/DDS/ZeroCopyExample/LoanableHelloWorldSubscriber.cxx
include/fastdds/dds/core/LoanableSequence.hpp
include/fastdds/dds/core/LoanableTypedCollection.hpp
src/cpp/rtps/DataSharing/ReaderPool.hpp
src/cpp/utils/shared_memory/SharedMemSegment.hpp

This PR adds several safety protection mechanisms on DataReader entities using data-sharing.
First, the readers will open the shared history on read-only mode.
Second, a new FASTDDS_CONST_SEQUENCE macro to define a sequence that only has the `const` version of the `[]` operator.
Should fix #2385

Enable memory protection on DataSharing readers [13457]

---

src/cpp/rtps/security/SecurityManager.cpp
test/blackbox/api/fastrtps_deprecated/PubSubReader.hpp
test/blackbox/common/BlackboxTestsSecurity.cpp
test/unittest/rtps/security/SecurityHandshakeProcessTests.cpp
test/unittest/rtps/security/SecurityTests.cpp
test/unittest/rtps/security/SecurityTests.hpp
test/unittest/rtps/security/SecurityValidationRemoteTests.cpp

[13295] Fix memory leak in SecurityManager

---

src/cpp/security/authentication/PKIDH.cpp

This is a temporary fix until the code can be refactored to
use real OpenSSL 3.0 APIs.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
Note that this should also be forward-ported to the master branch, as the same warning is there.

Suppress OpenSSL 3.0 warnings.

---

test/blackbox/api/dds-pim/PubSubReader.hpp

Sometimes the `DDSStatus.IncompatibleQosConditions` test fails due to `PubSubReader::incompatible_qos()` not taking into account `total_count_changes`, and instead only increasing the variable `times_incompatible_qos_` by one each time the Waitset returns. This PR corrects `PubSubReader::incompatible_qos()` so it uses `times_incompatible_qos_`.

Fix flaky test: incompatible qos conditions [13582]

---

src/cpp/utils/StringMatching.cpp
src/cpp/utils/SystemInfo.cpp

Select the right windows API functions independently of the `_UNICODE` preprocessor definition.
This addresses the issue https://github.com/eProsima/Fast-DDS/issues/2501

Refs 13882. Fixes for _UNICODE macro on Visual Studio

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.h
src/cpp/rtps/writer/StatefulWriter.cpp

This PR closes #1819. It also replaces #1823.
I have tried the regression test proposed in that PR but it does not seem to provoke the data race condition and the segmentation fault. However, the test is prone to failure due to discovery issues. Thus, I have not introduced it in this PR (if the reviewer considers it is of interest I can update this PR). There is no regression test because forcing the failure is not straight forward nor easy. However, the benefits of correctly protecting the access to the collections are too great compare to a regression test. My opinion is that this fix should be merged.

[10843] Correctly protect endpoints collections

---

include/fastdds/dds/core/policy/QosPolicies.hpp
include/fastdds/dds/domain/qos/DomainParticipantQos.hpp
include/fastdds/rtps/common/Time_t.h
include/fastrtps/utils/collections/ResourceLimitedContainerConfig.hpp
src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
src/cpp/rtps/common/Time_t.cpp
test/unittest/dds/publisher/PublisherTests.cpp
test/unittest/dds/subscriber/SubscriberTests.cpp

There are missing things which not make work well setting a default qos for DataWriters and DataReaders. This PR fixes this and also add/extend a regression test.
Also comes with minor changes to make work Swig when generating Python bindings.

Fix incomplete `set_qos` making not working set a default entity qos [13836]

---

src/cpp/fastdds/publisher/DataWriterImpl.cpp
src/cpp/fastdds/subscriber/DataReaderImpl.cpp
test/blackbox/api/dds-pim/PubSubReader.hpp
test/blackbox/api/dds-pim/PubSubWriter.hpp
test/blackbox/common/DDSBlackboxTestsDiscovery.cpp

Prior to this PR, `SubscriptionMatchedStatus::last_publication_handle` and `PublicationMatchedStatus::last_subscription_handle` where only updated when a new matched occurred, but not when a remote `DataWriter`|`DataReader` was unmatched. According to the DDS specification, the `last_*_handle` should contain the `InstanceHandle` to the last entity that modified the status, which includes modifications by unmatching. This PR:
1. Adds a regression test for the correct behaviour
2. Correctly updates the `last_*_handle` both for `DataReaders` and `DataWriters`
@Mergifyio backport 2.5.x 2.4.x

Correct reporting of MatchedStatus last_*_handle [13786]

---

src/cpp/statistics/fastdds/subscriber/qos/DataReaderQos.cpp

This PR sets the recommend Statistics DataReaderQos history memory policy to `PREALLOCATED_WITH_REALLOC_MEMORY_MODE` to allow future statistics data type extensions,
@Mergifyio backport 2.3.x 2.4.x 2.5.x

Set recommended DataReaderQos to PREALLOCATED_WITH_REALLOC [14006]

---

src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterGrammar.hpp
test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp

This PR improves DDSSQLFilter by including lowercase `and`, `or`, `not`, `between`, `not between`, `true`, and `false`.
Apart from updating the unit tests to include checks for the lowercase keywords, t has an improvement on `test_compound_or` to check for 'not between' operator, for which no test was present.
@mergifyio backport 2.5.x

[14018] Support lowercase keywords on SQL filter

---

include/fastdds/rtps/builtin/BuiltinProtocols.h
include/fastdds/rtps/builtin/discovery/participant/PDP.h
src/cpp/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/rtps/builtin/BuiltinProtocols.cpp
src/cpp/rtps/builtin/discovery/endpoint/EDPStatic.cpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
src/cpp/rtps/builtin/discovery/participant/PDPListener.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp

The goal is to improve bandwidth network when using Static Discovery. Currently when the `RTPSParticipant` is created, BuiltinProtocols are initialized and enabled at same time. Using Static Discovery provokes each time a DDS entity is enabled a new DATA(p) is sent adding this entity into the property list.
With this PR the enabling of BuiltinProtocols is done after the enabling of DDS entities. Using Static Discovery only one DATA(p) is sent with all entities information.

Separate initialization and enabling of BuiltinProtocols [12388]

---

include/fastdds/dds/core/Entity.hpp
include/fastdds/dds/domain/DomainParticipant.hpp
include/fastdds/dds/publisher/DataWriter.hpp
include/fastdds/dds/publisher/Publisher.hpp
include/fastdds/dds/subscriber/DataReader.hpp
include/fastdds/dds/subscriber/Subscriber.hpp
include/fastdds/dds/topic/Topic.hpp
versions.md

Added missing exports required by the SWIG wrapper used in the python bindings.

Remove constructor exports for factory created entities [13947]

---

include/fastdds/dds/core/status/IncompatibleQosStatus.hpp
include/fastdds/dds/publisher/DataWriter.hpp
include/fastdds/dds/subscriber/DataReader.hpp
src/cpp/fastdds/publisher/DataWriter.cpp
src/cpp/fastdds/subscriber/DataReader.cpp
test/unittest/dds/publisher/DataWriterTests.cpp
versions.md

DataWriter API should use `fastrtps::Time_t` instead of `fastrtps::rtps::Time_t`.

Cleanup on several APIs [14031]

---

include/fastrtps/xmlparser/XMLParser.h
resources/xsd/fastRTPS_profiles.xsd
src/cpp/rtps/xmlparser/XMLElementParser.cpp
src/cpp/rtps/xmlparser/XMLParser.cpp
test/unittest/xmlparser/XMLElementParserTests.cpp
test/unittest/xmlparser/XMLParserTests.cpp
test/unittest/xmlparser/test_xml_profiles.xml

Add support of parsing octet vector with XML parser, as `user_data`, `topic_data` and `group_data`.

Add support for octet vectors on XML parser [14011]

---

include/fastrtps/xmlparser/XMLParserCommon.h
src/cpp/rtps/xmlparser/XMLParserCommon.cpp
src/cpp/rtps/xmlparser/XMLProfileManager.cpp
test/system/tools/fds/CMakeLists.txt
test/system/tools/fds/test_wrong_xml_discovery_server.xml
test/system/tools/fds/test_xml_discovery_server.xml
test/system/tools/fds/tests.py
tools/fds/server.cpp
tools/fds/server.h

Documentation PR: eProsima/Fast-DDS-docs#351
Signed-off-by: Victor M Maroto <victormaroto@eprosima.com>

Support XML config for fastdds-discovery-server [13783]

---

include/fastdds/rtps/builtin/discovery/participant/PDP.h
src/cpp/rtps/builtin/BuiltinProtocols.cpp
src/cpp/rtps/builtin/discovery/participant/PDP.cpp
src/cpp/rtps/builtin/discovery/participant/PDPClient.cpp
src/cpp/rtps/builtin/discovery/participant/PDPServer.cpp
src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp
src/cpp/statistics/fastdds/domain/DomainParticipantImpl.cpp
src/cpp/statistics/rtps/StatisticsBase.cpp
test/blackbox/common/DDSBlackboxTestsBasic.cpp
test/blackbox/common/RTPSBlackboxTestsBasic.cpp

#2171 introduced a separation between initialization and enabling of `BuiltinProtocols`.
This had the side effect of the statistics' physical data not to be published, since the data was generated and added to the writer history only once on the creation of the corresponding `DataWriter`, which was performed prior to enabling the `DomainParticipantImpl`.
This lead to the `RTPSWriter` not to being created, as there was not `RTPSParticipant` (created when enabling the `DomainParticipantImpl`).
This PR fixes this behaviour by always enabling the `DomainParticipantImpl` before creating the statistics `DataWriter`s.
Furthermore, #2171 also introduced a regression in which removing a not enabled `RTPSParticipant` results in accessing a `nullptr` and therefore into a segmentation fault. This PR …

Fix publishing on physical data topic [14124]

---

src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpressionParser.cpp
src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpressionParserImpl/literal_values.hpp
src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterGrammar.hpp
test/unittest/dds/topic/DDSSQLFilter/DDSSQLFilterTests.cpp

Just what the title says. Extend DDSSQLFilter unit tests, and add support for hexadecimal constant values.
@mergifyio backport 2.5.x
Related documentation PR: eProsima/Fast-DDS-docs#361

[14234] Add support for hexadecimal values to DDSSQLFilter

---

include/fastdds/dds/subscriber/DataReader.hpp
src/cpp/fastdds/subscriber/DataReader.cpp

Adding `const` to `guid()` method in DataReader
**Not sure about ABI/API compat**

Refs #9977. Add const to DataReader::guid()

---

src/cpp/rtps/writer/ReaderProxy.cpp
test/blackbox/common/BlackboxTestsPubSubBasic.cpp

When adding samples to a full history on a reliable DataWriter, just after a new transient-local reader has been discovered, the ReaderProxy of the newly discovered reader ends up in an inconsistent state, where all the samples are marked as ACKNOWLEDGED, but the low_mark stays on the sequence number of the first historical change.
@Mergifyio backport 2.5.x 2.3.x 2.1.x

[14349] Fix inconsistent ReaderProxy state on intra-process

---

src/cpp/rtps/participant/RTPSParticipantImpl.cpp

If Fast DDS is compile with Statistics (`-DFASTDDS_STATISTICS=ON`) and in Debug, when updating the remote server locator and assertion in `OutputTrafficManager::set_statistics_message_data` fails. This is due to the new locator not being added to the `collection_` member of this class. New locators are added when calling to the specific transport `OpenOutputChannel`. This PR ensures that it is called before announcing the new Participant state, preventing the assertion to fail.
This feature is tested with the tests included in eProsima/Discovery-Server#52. Running these tests with Fast DDS …

[14091] Fix update remote server locators when enabling statistics

---

test/unittest/dds/participant/ParticipantTests.cpp

#2521 added ContentFilteredTopics into Fast DDS. Some DomainParticipant unit tests were not updated taking into account this new feature. This PR improves two of these tests:
* DeleteTopicInUse: check that even if no endpoints are created in the Topic, Topic deletion fails if there is a ContentFilteredTopic created using this specific Topic.
* DeleteContainedEntities: check that `DomainParticipant::delete_contained_entities` also takes charge of gracefully deleting the ContentFilteredTopic allowing the Topic to be deleted as well.
@Mergifyio backport 2.5.x
* **N/A** New feature has been added to the `versions.md` file (if applicable).
* **N/A** New …

[14361] Improve ParticipantTests with ContentFilteredTopic 

---

src/cpp/rtps/xmlparser/XMLDynamicParser.cpp
test/unittest/xmlparser/XMLParserTests.cpp
test/unittest/xmlparser/regressions/13513.xml

Fixed a null-dereference on XML parser
@Mergifyio backport 2.5.x 2.3.x 2.1.x

[14386] Fix oss-fuzz 43650

---

src/cpp/rtps/transport/TCPChannelResourceBasic.cpp
src/cpp/rtps/transport/UDPChannelResource.cpp

This PR moves the close operation over the UDP socket from `UDPChannelResource::release` to the destructor of `UDPChannelResource`.
As the destructor is called after calling `UDPChannelResource::clear`, the receiving thread would have been already joined, so the thread sanitizer should not complain.
As a bonus, I introduced a small change on `TCPChannelResourceBasic::disconnect` that I think is responsible for leaving TCP sockets on a FIN_2 state sometimes.
@Mergifyio backport 2.5.x 2.3.x 2.1.x
- **N/A** New feature has been documented/Current behavior is correctly described …

[14385] Avoid data race on UDPChannelResource

---

src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp
test/unittest/rtps/discovery/EdpTests.cpp

It was discovered that an endpoint with an empty partition list was not correctly matching with an endpoint having an empty string on its partition list.
This PR adds a test for that case and fixes the issue.
@Mergifyio backport 2.5.x 2.4.x 2.3.x 2.1.x

[14139] Fix partition validation checks on EDP

---

CMakeLists.txt
src/cpp/CMakeLists.txt

Google removed support for functions used by android-ifaddrs library
in API30. This means that FastDDS compiled for Android API level 30+
does not work. Fortunately native ifaddrs.h is available since API 24
so android-ifaddrs is not needed anymore. Therefore, we use
android-ifaddrs only for APIs < 24.

Don't use android-ifaddrs with Android APIs >= 24

---

include/fastdds/rtps/common/Locator.h
include/fastdds/rtps/common/LocatorList.hpp
include/fastdds/rtps/common/LocatorListComparisons.hpp
include/fastdds/rtps/common/LocatorsIterator.hpp

This PR improves doxygen documentation related to Locator classes improving thus the API reference.
* **N/A** New feature has been added to the `versions.md` file (if applicable).
Related documentation PR: eProsima/Fast-DDS-docs#367

[14470] Improve doxygen documentation related to Locator classes.

---

include/fastdds/rtps/writer/ReaderProxy.h
src/cpp/rtps/transport/shared_mem/SharedMemManager.hpp
src/cpp/rtps/writer/ReaderProxy.cpp
src/cpp/rtps/writer/StatefulWriter.cpp

* Port small SHM segment warning message
* Fix bug with gap not being sent with heartbeat message
This PR fixes a problem with my service test: https://github.com/ros2/rmw_fastrtps/issues/559
That test will eventually fail cuz of client won't receive response from service. Right now gaps will be sent after reader-writer match, but there could be a kind of race:
* Writer matches a reader in the service
* Writer sends heartbeat and gap messages
* Reader matches a writer in the client
In that case initial gap message will be lost and reader will be asking for sequence set from heartbeat forever.
Seems like that issue is already fixed in master branch.

[foxy] Fix: gap not being sent [14675]

---

include/fastdds/rtps/writer/ChangeForReader.h
test/blackbox/common/BlackboxTestsPubSubFragments.cpp
test/unittest/rtps/writer/ReaderProxyTests.cpp

Signed-off-by: Igor Abdrakhimov <abdrahimov@arrival.com>
When sending large files (>16 MB), the transfer may hang on the RTPS level. This happens because of how `ChangeForReader_t` handles fragments.
The issue appears when on `ChangeForReader_t::markFragmentsAsUnsent` call, if `unsentFragments` contains only one fragment and this fragment is less than `unsent_fragments_.base_` by >255 fragments.
Then on a `ChangeForReader_t::markFragmentsAsSent` call, `unsent_fragments_` becomes empty. So, `base_update` and `add_range` won't be called for `unsent_fragments_`.
Which leads to `ChangeForReader_t::get_next_unsent_fragment` reporting that all fragments are sent.
Now, a hang will happen if a Reader request for an unsent change which is greater than the previously requested fragment by >255 …

[14430] Fix freezes in the RTPS level when transferring large files

---

src/cpp/rtps/writer/StatefulWriter.cpp

Signed-off-by: Artem Shumov <agshumov@sberautotech.ru>
This PR changes the order of destruction of StatefulWriter members. 
We need to disable all timed events before calling function deinit(), because deinit() [releases all cache changes](https://github.com/shumov-ag/Fast-DDS/blob/6b55651b6edfaf0a201fce26e1861ceef84696a4/src/cpp/rtps/writer/RTPSWriter.cpp#L158-L161) but callbacks of the timed events still use them.
- *N/A*: New feature has been documented/Current behavior is correctly described in the …

Change the order of destruction to prevent use of released objects [14737]

---

.github/workflows/thread-sanitizer.yaml
include/fastdds/rtps/messages/MessageReceiver.h
include/fastrtps/utils/shared_mutex.hpp
src/cpp/rtps/messages/MessageReceiver.cpp

For sanitizer CI see https://github.com/eProsima/Fast-DDS/pull/2565
This refactor promotes the mutex to shared mutex in order to prevent deadlocks due to interaction with participant mutexes.
A) std::mutex MessageReceives::mtx_
B) std::recursive_mutex* RTPSParticipantImpl::mp_mutex 
C) std::mutex RTPSParticipantImpl::m_receiverResourcelistMutex
`MessageReceiver::associateEndpoint(C > A)` takes A while C is taken at `RTPSParticipantImpl::assignEndpoint2LocatorList()`
`EDP::pairing_writer_proxy_with_any_local_reader(A > B)` takes B while A is taken in `MessageReceiver::process_data_message_without_security()`
`RTPSParticipantImpl::deleteUserEndpoint(B > C)` takes C while B is taken in `RTPSParticipantImpl::disable()`
This is the first use of `shared_mutex` in Fast-DDS. Because it's a C++17 …

MessageReceiver refactor to fix deadlocks [14069] <master>

---

include/fastdds/rtps/messages/MessageReceiver.h
include/fastrtps/utils/shared_mutex.hpp
src/cpp/rtps/messages/MessageReceiver.cpp

This refactor promotes the mutex to shared mutex in order to prevent deadlocks due to interaction with participant mutexes.
A) std::mutex MessageReceives::mtx_
B) std::recursive_mutex* RTPSParticipantImpl::mp_mutex 
C) std::mutex RTPSParticipantImpl::m_receiverResourcelistMutex
`MessageReceiver::associateEndpoint(C > A)` takes A while C is taken at `RTPSParticipantImpl::assignEndpoint2LocatorList()`
`EDP::pairing_writer_proxy_with_any_local_reader(A > B)` takes B while A is taken in `MessageReceiver::process_data_message_without_security()`
`RTPSParticipantImpl::deleteUserEndpoint(B > C)` takes C while B is taken in `RTPSParticipantImpl::disable()`
This is the first use of `shared_mutex` in Fast-DDS. Because it's a C++17 feature a public domain implementation is included in our utils …

MessageReceiver refactor to fix deadlocks [14069] <feature/tsan/fixes>

---

src/cpp/rtps/builtin/BuiltinProtocols.cpp
src/cpp/rtps/flowcontrol/FlowControllerImpl.hpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp

This addresses the most common deadlock TSan report in Fast-DDS test suite (reported 317 times).
Now all `DataWriters` use a default asynchronous flow controller.
The associated asynchronous thread traverses the collection of pending changes to send.
For each change the `RTPSMessageSenderInterface` associated with the `DataWriter` is set into the `FlowController` auxiliary `RTPSMessageGroup`.
+ Before calling the `RTPSMessageGroup` setter the new `RTPSMessageSenderInterface` is locked (A).
+ The `RTPSMessageGroup` setter flushes pending messages before change the `RTPSMessageSenderInterface` locking the former `RTPSMessageSenderInterface` (B).
TSan reports that if the next change in the collection is delivered to A then we will lock B &rarr; A.
Note that this is not an issue because, …

 [14237] Fixing flow controller TSan lock-order-inversion reports <feature/tsan/fixes>

---

CMakeLists.txt

CMake option `BUILD_DOCUMENTATION` downloads using `wget` the Readthedocs ZIP file from an URL that does not have the latest documentation. Changing to this other URL solves the problem: https://fast-dds.docs.eprosima.com/_/downloads/en/v2.6.0/htmlzip/, though instead of using `wget`, `curl` must be used.
I have tested it in Ubuntu 20.04. I suggest the reviewer to check that it also works as expected in Windows. To test this PR run:
```
colcon build --packages-select fastrtps --cmake-args -DBUILD_DOCUMENTATION=ON
```
In case of using a `colcon.meta` file, ensure that CMake option `CHECK_DOCUMENTATION` is disabled (by default CMake option `EPROSIMA_BUILD` sets the later to `ON`).
* *N/A* The code follows the style guidelines …

[14147] Fix documentation installation

---

.github/workflows/thread-sanitizer.yaml
include/fastdds/rtps/messages/MessageReceiver.h
include/fastrtps/utils/shared_mutex.hpp
src/cpp/rtps/builtin/BuiltinProtocols.cpp
src/cpp/rtps/flowcontrol/FlowControllerImpl.hpp
src/cpp/rtps/messages/MessageReceiver.cpp
src/cpp/rtps/participant/RTPSParticipantImpl.cpp

For sanitizer CI see https://github.com/eProsima/Fast-DDS/pull/2600
This addresses the most common deadlock TSan report in Fast-DDS test suite (reported 317 times).
Now all `DataWriters` use a default asynchronous flow controller.
The associated asynchronous thread traverses the collection of pending changes to send.
For each change the `RTPSMessageSenderInterface` associated with the `DataWriter` is set into the `FlowController` auxiliary `RTPSMessageGroup`.
+ Before calling the `RTPSMessageGroup` setter the new `RTPSMessageSenderInterface` is locked (A).
+ The `RTPSMessageGroup` setter flushes pending messages before change the `RTPSMessageSenderInterface` locking the former `RTPSMessageSenderInterface` (B).
TSan reports that if the next change in the collection is delivered to A then …

[14237] Fixing flow controller TSan lock-order-inversion reports <master>

---

include/fastdds/rtps/resources/ResourceEvent.h
src/cpp/rtps/participant/RTPSParticipantImpl.cpp
src/cpp/rtps/resources/ResourceEvent.cpp

Closing participant's event thread sooner on participant removal to prevent data races.

[14467] Fixing event thread shutdown <feature/tsan/fixes>

---

src/cpp/rtps/reader/StatefulReader.cpp
src/cpp/rtps/reader/StatelessReader.cpp
src/cpp/rtps/transport/UDPTransportInterface.cpp
src/cpp/rtps/transport/UDPTransportInterface.h
src/cpp/rtps/transport/UDPv4Transport.cpp
src/cpp/rtps/transport/UDPv6Transport.cpp

Deadlock fix already directed to master (https://github.com/eProsima/Fast-DDS/pull/2712).
The basic idea is modifying the RTPSReader subclasses matching code to avoid taking simultaneously the reader endpoint mutex and the participant & PDP mutexes required for WLP calls.
This PR aim is to simplify integration with tsan deadlock fixes by creating a commit in the intermediate branch.
Note both PR use the same branch, thus if one can merge so does the other.

Fix WLP deadlock and EDP discovery performance improvement [14450][14457] <feature/tsan/fixes>

---

include/fastdds/rtps/writer/LivelinessManager.h
include/fastrtps/utils/collections/ResourceLimitedVector.hpp
src/cpp/rtps/writer/LivelinessManager.cpp

For sanitizer CI see https://github.com/eProsima/Fast-DDS/pull/2679
LivelinessManager should be refactored in order to solve lock inversion issues reported in several issues like 4139.
The class has now a
```
std::mutex mutex_;
```
devoted to safeguarding the class data (including member collection contents). And a
```
shared_mutex col_mutex_;
```
devoted to protecting member collections and allowing their safe traversal without taking any *writer lock* that will lead to lock inversion.
The code was reordered in order to prevent any callbacks (potencial deadlock sources) with any `lock` taken (only `shared_lock` or none is allowed.

[14749] Solving sanitizer issue 4139 <master>

---

include/fastdds/rtps/common/GuidPrefix_t.hpp

Fix GuidPrefix fail case in >>operator
`GuidPrefix_t` class has a deserialization method `>> operator` that does not fail in case an incorrect string format is passed.
This is fixed by returning an `unknown` (invalid) GuidPrefix.

Refs #13972: Fix GuidPrefix fail case in >>operator [13972]
